import type { JapaneseWord } from '../../types';

export const sakura_12: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Friends will come to my house.',
        pl: 'Przyjaciele przyjdą do mojego domu.',
        jp: 'ともだちがわたしのうちにきます。',
    },
    {
        type: 'noun',
        en: 'When',
        pl: 'Kiedy',
        jp: 'いつ',
    },
    {
        type: 'verb',
        en: 'Use',
        pl: 'Używać',
        jp: 'つかいます',
    },
    {
        type: 'verb',
        en: 'Meet',
        pl: 'Spotykać',
        jp: 'あいます',
    },
    {
        type: 'phrase',
        en: 'With whom do you meet?',
        pl: 'Z kim się spotykasz?',
        jp: 'だれとあいますか？',
    },
    {
        type: 'verb',
        en: 'Make / Create',
        pl: 'Robić / Tworzyć',
        jp: 'つくります',
    },
    {
        type: 'phrase',
        en: 'I use a phone.',
        pl: 'Używam telefonu.',
        jp: 'でんわをつかいます。',
    },
    {
        type: 'phrase',
        en: 'Take pictures',
        pl: 'Robić zdjęcia',
        jp: 'しゃしんをとります',
    },
    {
        type: 'phrase',
        en: 'Send a letter',
        pl: 'Wysyłać list',
        jp: 'てがみをおくります',
    },
    {
        type: 'noun',
        en: 'Package',
        pl: 'Paczka',
        jp: 'にもつ',
    },
    {
        type: 'phrase',
        en: 'Play by yourself',
        pl: 'Bawić się samemu',
        jp: 'ひとりであそびます',
    },
    {
        type: 'verb',
        en: 'Play / Have fun / Hang out',
        pl: 'Bawić się / Miło spędzać czas',
        jp: 'あそびます',
    },
    {
        type: 'noun',
        en: 'Musical instrument',
        pl: 'Instrument muzyczny',
        jp: 'がっき',
    },
    {
        type: 'verb',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: 'ひきます',
    },
    {
        type: 'phrase',
        en: 'Play an instrument',
        pl: 'Grać na instrumencie',
        jp: 'がっきをひきます',
    },
    {
        type: 'verb',
        en: 'Rest',
        pl: 'Odpoczywać',
        jp: 'やすみます',
    },
    {
        type: 'verb',
        en: 'Swim',
        pl: 'Pływać',
        jp: 'およぎます',
    },
    {
        type: 'verb',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: 'はなします',
    },
    {
        type: 'phrase',
        en: 'Who are you talking with?',
        pl: 'Z kim rozmawiasz?',
        jp: 'だれとはなしますか？',
    },
    {
        type: 'verb',
        en: 'Teach',
        pl: 'Uczyć (kogoś)',
        jp: 'おしえます',
    },
    {
        type: 'phrase',
        en: 'I teach my children math.',
        pl: 'Uczę moje dzieci matematyki.',
        jp: 'わたしはこどもにすうがくをおしえます。',
    },
    {
        type: 'verb',
        en: 'Put on (clothes)',
        pl: 'Zakładać (ubrania)',
        jp: 'きます',
    },
    {
        type: 'phrase',
        en: 'Put on a jacket',
        pl: 'Zakładać kurtkę',
        jp: 'ジャケットをきます',
    },
    {
        type: 'noun',
        en: 'All day',
        pl: 'Cały dzień',
        jp: 'いちにちじゅう',
    },
    {
        type: 'phrase',
        en: 'Cook',
        pl: 'Gotować',
        jp: 'りょうりをします',
    },
    {
        type: 'phrase',
        en: 'Do sports',
        pl: 'Uprawiać sport',
        jp: 'スポーツをします',
    },
    {
        type: 'phrase',
        en: 'I shop twice every week.',
        pl: 'Robię zakupy dwa razy w każdy tydzień.',
        jp: 'まいしゅうににかいかいものをします。',
    },
    {
        type: 'phrase',
        en: 'Cook pierogi',
        pl: 'Gotować pierogi',
        jp: 'ピエロギをつくります',
    },
    {
        type: 'phrase',
        en: 'Cook Japanese food',
        pl: 'Gotować japońskie jedzenie',
        jp: 'にほんのりょうりをつくります',
    },
    {
        type: 'noun',
        en: 'Copy (noun)',
        pl: 'Kopia',
        jp: 'コピー',
    },
    {
        type: 'phrase',
        en: 'Make a copy',
        pl: 'Robić kopię',
        jp: 'コピーをします',
    },
    {
        type: 'noun',
        en: 'Piano',
        pl: 'Pianino',
        jp: 'ピアノ',
    },
    {
        type: 'noun',
        en: 'Guitar',
        pl: 'Gitara',
        jp: 'ギター',
    },
    {
        type: 'adjective',
        en: 'Yellow',
        pl: 'Żółty',
        jp: 'きいろい',
    },
    {
        type: 'noun',
        en: 'Street',
        pl: 'Ulica',
        jp: 'とおり',
    },
    {
        type: 'noun',
        en: 'Air',
        pl: 'Powietrze',
        jp: 'くうき',
    },
    {
        type: 'adjective',
        en: 'Big',
        pl: 'Duży',
        jp: 'おおきい',
    },
    {
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: 'おおかみ',
    },
    {
        type: 'adjective',
        en: 'Small',
        pl: 'Mały',
        jp: 'ちいさい',
    },
    {
        type: 'adjective',
        en: 'Far',
        pl: 'Daleko',
        jp: 'とおい',
    },
    {
        type: 'noun',
        en: 'Fridge',
        pl: 'Lodówka',
        jp: 'れいぞうこ',
    },
];
