import type { JapaneseWord } from '../../types';

export const sakura_2: JapaneseWord[] = [
    {
        type: 'adjective',
        en: 'Red',
        pl: 'Czerwony',
        jp: 'あかい',
    },
    {
        type: 'noun',
        en: 'Train station',
        pl: 'Dworzec kolejowy',
        jp: 'えき',
    },
    {
        type: 'noun',
        en: 'Up / Above',
        pl: 'Nad / Na górze',
        jp: 'うえ',
    },
    {
        type: 'adjective',
        en: 'Blue',
        pl: 'Niebieski',
        jp: 'あおい',
    },
    {
        type: 'noun',
        en: 'Here',
        pl: 'Tutaj',
        jp: 'ここ',
    },
    {
        type: 'noun',
        en: 'Umbrella',
        pl: 'Parasol',
        jp: 'かさ',
    },
    {
        type: 'noun',
        en: 'Sweets / Candy',
        pl: 'Słodycze / Cukierki',
        jp: 'おかし',
    },
    {
        type: 'noun',
        en: 'Chair',
        pl: 'Krzesło',
        jp: 'いす',
    },
    {
        type: 'noun',
        en: 'Leg / Foot',
        pl: 'Noga / Stopa',
        jp: 'あし',
    },
    {
        type: 'noun',
        en: 'House',
        pl: 'Dom',
        jp: 'うち',
    },
    {
        type: 'noun',
        en: 'Hand',
        pl: 'Ręka',
        jp: 'て',
    },
    {
        type: 'noun',
        en: 'Physical Education',
        pl: 'Wychowanie fizyczne',
        jp: 'たいいく',
    },
    {
        type: 'noun',
        en: 'Japan',
        pl: 'Japonia',
        jp: 'にほん',
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: 'ドイツ',
    },
    {
        type: 'noun',
        en: 'China',
        pl: 'Chiny',
        jp: 'ちゅうごく',
    },
    {
        type: 'noun',
        en: 'Egypt',
        pl: 'Egipt',
        jp: 'エジプト',
    },
    {
        type: 'noun',
        en: 'South Korea',
        pl: 'Korea Południowa',
        jp: 'かんこく',
    },
    {
        type: 'noun',
        en: 'Australia',
        pl: 'Australia',
        jp: 'オーストラリア',
    },
    {
        type: 'noun',
        en: 'Language',
        pl: 'Język',
        jp: 'ご',
    },
    {
        type: 'noun',
        en: 'English',
        pl: 'Angielski',
        jp: 'えいご',
    },
    {
        type: 'noun',
        en: 'Spanish',
        pl: 'Hiszpański',
        jp: 'スペインご',
    },
    {
        type: 'noun',
        en: 'Arabic',
        pl: 'Arabski',
        jp: 'アラビアご',
    },
    {
        type: 'noun',
        en: 'Country',
        pl: 'Kraj',
        jp: 'くに',
    },
    {
        type: 'noun',
        en: 'Hindu',
        pl: 'Hindi',
        jp: 'ヒンディーご',
    },
    {
        type: 'phrase',
        en: 'What is your country?',
        pl: 'Jaki jest twój kraj?',
        jp: 'おくには',
    },
    {
        type: 'phrase',
        en: 'What languages do you know?',
        pl: 'Jakimi językami potrafisz mówić?',
        jp: 'なにごができますか',
    },
    {
        type: 'phrase',
        en: 'What is your nationality?',
        pl: 'Jakiej jesteś narodowości?',
        jp: 'なにじんですか',
    },
    {
        type: 'phrase',
        en: 'I speak Japanese and English.',
        pl: 'Mówię po japońsku i angielsku.',
        jp: 'にほんごとえいごができます。',
    },
    {
        type: 'phrase',
        en: "I can't speak Chinese.",
        pl: 'Nie potrafię mówić po chińsku.',
        jp: 'ちゅうごくごはできません。',
    },
    {
        type: 'phrase',
        en: 'Where are you from?',
        pl: 'Skąd jesteś?',
        jp: 'どちらからきましたか',
    },
    {
        type: 'phrase',
        en: 'I am from Poland.',
        pl: 'Jestem z Polski.',
        jp: 'ポーランドからきました',
    },
    {
        type: 'noun',
        en: 'While studying',
        pl: 'Uczę się',
        jp: 'べんきょうちゅう',
    },
    {
        type: 'phrase',
        en: "I'm learning Japanese.",
        pl: 'Uczę się japońskiego.',
        jp: 'にほんごをべんきょうちゅうです。',
    },
    {
        type: 'verb',
        en: 'Come (from)',
        pl: 'Pochodzić (z)',
        jp: 'きます',
    },
    {
        type: 'noun',
        en: 'Citizen',
        pl: 'Obywatel',
        jp: 'じん',
    },
    {
        type: 'noun',
        en: 'Poland',
        pl: 'Polska',
        jp: 'ポーランド',
    },
    {
        type: 'noun',
        en: 'Great Britain',
        pl: 'Wielka Brytania',
        jp: 'イギリス',
    },
    {
        type: 'noun',
        en: 'France',
        pl: 'Francja',
        jp: 'フランス',
    },
    {
        type: 'noun',
        en: 'Russia',
        pl: 'Rosja',
        jp: 'ロシア',
    },
    {
        type: 'noun',
        en: 'Ukraine',
        pl: 'Ukraina',
        jp: 'ウクライナ',
    },
    {
        type: 'noun',
        en: 'Spain',
        pl: 'Hiszpania',
        jp: 'スペイン',
    },
    {
        type: 'noun',
        en: 'Portugal',
        pl: 'Portugalia',
        jp: 'ポルトガル',
    },
    {
        type: 'noun',
        en: 'India',
        pl: 'Indie',
        jp: 'インド',
    },
    {
        type: 'noun',
        en: 'USA',
        pl: 'USA',
        jp: 'アメリカ',
    },
    {
        type: 'noun',
        en: 'Canada',
        pl: 'Kanada',
        jp: 'カナダ',
    },
    {
        type: 'noun',
        en: 'New Zealand',
        pl: 'Nowa Zelandia',
        jp: 'ニュージーランド',
    },
    {
        type: 'noun',
        en: 'Brazil',
        pl: 'Brazylia',
        jp: 'ブラジル',
    },
    {
        type: 'noun',
        en: 'Mexico',
        pl: 'Meksyk',
        jp: 'メキシコ',
    },
    {
        type: 'verb',
        en: 'Can',
        pl: 'Potrafić',
        jp: 'できます',
    },
    {
        type: 'other',
        en: 'A little',
        pl: 'Trochę',
        jp: 'すこし / ちょっと',
    },
    {
        type: 'phrase',
        en: 'Not enough',
        pl: 'Niewystarczająco',
        jp: 'まだまだです',
    },
    {
        type: 'other',
        en: 'Very',
        pl: 'Bardzo',
        jp: 'とても',
    },
];
