import type { JapaneseWord } from '../../types';

export const sakura_10: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Breakfast',
        pl: 'Śniadanie',
        jp: 'あさごはん',
    },
    {
        type: 'noun',
        en: 'Lunch',
        pl: 'Obiad',
        jp: 'ひるごはん',
    },
    {
        type: 'noun',
        en: 'Dinner',
        pl: 'Kolacja',
        jp: 'ばんごはん',
    },
    {
        type: 'noun',
        en: 'Picture / Drawing',
        pl: 'Obrazek / Rysunek',
        jp: 'え',
    },
    {
        type: 'noun',
        en: 'Music',
        pl: 'Muzyka',
        jp: 'おんがく',
    },
    {
        type: 'verb',
        en: 'Listen',
        pl: 'Słuchać',
        jp: 'ききます',
    },
    {
        type: 'noun',
        en: 'Radio',
        pl: 'Radio',
        jp: 'ラジオ',
    },
    {
        type: 'noun',
        en: 'News',
        pl: 'Wiadomości',
        jp: 'ニュース',
    },
    {
        type: 'noun',
        en: 'Hiragana',
        pl: 'Hiragana',
        jp: 'ひらがな',
    },
    {
        type: 'noun',
        en: 'Katakana',
        pl: 'Katakana',
        jp: 'カタカナ',
    },
    {
        type: 'noun',
        en: 'Kanji',
        pl: 'Kanji',
        jp: 'かんじ',
    },
    {
        type: 'verb',
        en: 'Draw',
        pl: 'Rysować',
        jp: 'かきます',
    },
    {
        type: 'verb',
        en: 'Write',
        pl: 'Pisać',
        jp: 'かきます',
    },
    {
        type: 'verb',
        en: 'Not listen',
        pl: 'Nie słuchać',
        jp: 'ききません',
    },
    {
        type: 'verb',
        en: 'Not write',
        pl: 'Nie pisać',
        jp: 'かきません',
    },
    {
        type: 'verb',
        en: 'Buy',
        pl: 'Kupować',
        jp: 'かいます',
    },
    {
        type: 'verb',
        en: 'Not buy',
        pl: 'Nie kupować',
        jp: 'かいません',
    },
    {
        type: 'noun',
        en: 'Smartphone',
        pl: 'Smartfon',
        jp: 'スマホ',
    },
    {
        type: 'verb',
        en: 'Do / Play',
        pl: 'Robić / Grać',
        jp: 'します',
    },
    {
        type: 'verb',
        en: 'Not do / play',
        pl: 'Nie robić / grać',
        jp: 'しません',
    },
    {
        type: 'phrase',
        en: 'Learn',
        pl: 'Uczyć się',
        jp: 'べんきょうをします',
    },
    {
        type: 'phrase',
        en: 'Do judo',
        pl: 'Uprawiać judo',
        jp: 'じゅうどうをします',
    },
    {
        type: 'phrase',
        en: 'Play games',
        pl: 'Grać w gry',
        jp: 'ゲームをします',
    },
    {
        type: 'phrase',
        en: 'Do shopping',
        pl: 'Robić zakupy',
        jp: 'かいものをします',
    },
    {
        type: 'phrase',
        en: 'Do homework',
        pl: 'Robić pracę domową',
        jp: 'しゅくだいをします',
    },
    {
        type: 'noun',
        en: 'Email',
        pl: 'Email',
        jp: 'メール',
    },
];
