import type { JapaneseWord } from '../../types';

export const sakura_12: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Friends will come to my house.',
        pl: 'Przyjaciele przyjdą do mojego domu.',
        jp: 'ともだちがわたしのうちにきます。',
    },
    {
        en: 'When',
        pl: 'Kiedy',
        jp: 'いつ',
    },
    {
        type: 'verb',
        en: 'Use',
        pl: 'Używać',
        jp: 'つかう [u]',
        jp_description: ['つかいます', 'つかいません'],
    },
    {
        type: 'verb',
        en: 'Meet',
        pl: 'Spotykać',
        jp: 'あう [u]',
        jp_description: ['あいます', 'あいません'],
    },
    {
        type: 'phrase',
        en: 'With whom do you meet?',
        pl: 'Z kim się spotykasz?',
        jp: 'だれとあいますか？',
    },
    {
        type: 'verb',
        en: 'Make / Create',
        pl: 'Robić / Tworzyć',
        jp: 'つくる [u]',
        jp_description: ['つくります', 'つくりません'],
    },
    {
        type: 'phrase',
        en: 'I use a phone.',
        pl: 'Używam telefonu.',
        jp: 'でんわをつかいます。',
    },
    {
        type: 'verb',
        en: 'Take (an object or picture)',
        pl: 'Brać (przedmiot) lub robić (zdjęcie)',
        jp: 'とる [u]',
        jp_description: ['とります', 'とりません'],
    },
    {
        type: 'phrase',
        en: 'Take pictures',
        pl: 'Robić zdjęcia',
        jp: 'しゃしんをとる',
    },
    {
        type: 'verb',
        en: 'Send',
        pl: 'Wysyłać',
        jp: 'おくる [ru]',
        jp_description: ['おくります', 'おくりません'],
    },
    {
        type: 'phrase',
        en: 'Send a letter',
        pl: 'Wysyłać list',
        jp: 'てがみをおくります',
    },
    {
        type: 'noun',
        en: 'Package',
        pl: 'Paczka',
        jp: 'にもつ',
    },
    {
        type: 'phrase',
        en: 'Play by yourself',
        pl: 'Bawić się samemu',
        jp: 'ひとりであそぶ',
    },
    {
        type: 'verb',
        en: 'Play / Have fun / Hang out',
        pl: 'Bawić się / Miło spędzać czas',
        jp: 'あそぶ [u]',
        jp_description: ['あそびます', 'あそびません'],
    },
    {
        type: 'noun',
        en: 'Musical instrument',
        pl: 'Instrument muzyczny',
        jp: 'がっき',
    },
    {
        type: 'verb',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: 'ひく [u]',
        jp_description: ['ひきます', 'ひきません'],
    },
    {
        type: 'phrase',
        en: 'Play an instrument',
        pl: 'Grać na instrumencie',
        jp: 'がっきをひく',
    },
    {
        type: 'verb',
        en: 'Rest',
        pl: 'Odpoczywać',
        jp: 'やすむ [u]',
        jp_description: ['やすみます', 'やすみません'],
    },
    {
        type: 'verb',
        en: 'Swim',
        pl: 'Pływać',
        jp: 'およぐ [u]',
        jp_description: ['およぎます', 'およぎません'],
    },
    {
        type: 'verb',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: 'はなす [u]',
        jp_description: ['はなします', 'はなしません'],
    },
    {
        type: 'phrase',
        en: 'Who are you talking with?',
        pl: 'Z kim rozmawiasz?',
        jp: 'だれとはなしますか？',
    },
    {
        type: 'verb',
        en: 'Teach',
        pl: 'Uczyć (kogoś)',
        jp: 'おしえる [ru]',
        jp_description: ['おしえます', 'おしえません'],
    },
    {
        type: 'phrase',
        en: 'I teach my children math.',
        pl: 'Uczę moje dzieci matematyki.',
        jp: 'わたしはこどもにすうがくをおしえます。',
    },
    {
        type: 'verb',
        en: 'Put on (clothes)',
        pl: 'Zakładać (ubrania)',
        jp: 'きる [ru]',
        jp_description: ['きます', 'きません'],
    },
    {
        type: 'phrase',
        en: 'Put on a jacket',
        pl: 'Zakładać kurtkę',
        jp: 'ジャケットをきる',
    },
    {
        en: 'All day',
        pl: 'Cały dzień',
        jp: 'いちにちじゅう',
    },
    {
        type: 'phrase',
        en: 'Cook',
        pl: 'Gotować',
        jp: 'りょうりをする',
    },
    {
        type: 'phrase',
        en: 'Do sports',
        pl: 'Uprawiać sport',
        jp: 'スポーツをする',
    },
    {
        type: 'phrase',
        en: 'I shop twice every week.',
        pl: 'Robię zakupy dwa razy w każdy tydzień.',
        jp: 'まいしゅうににかいかいものをします。',
    },
    {
        type: 'phrase',
        en: 'Cook pierogi',
        pl: 'Gotować pierogi',
        jp: 'ピエロギをつくります',
    },
    {
        type: 'phrase',
        en: 'Cook Japanese food',
        pl: 'Gotować japońskie jedzenie',
        jp: 'にほんのりょうりをつk',
    },
    {
        type: 'noun',
        en: 'Copy',
        pl: 'Kopia',
        jp: 'コピー',
    },
    {
        type: 'phrase',
        en: 'Make a copy',
        pl: 'Robić kopię',
        jp: 'コピーをする',
    },
    {
        type: 'noun',
        en: 'Piano',
        pl: 'Pianino',
        jp: 'ピアノ',
    },
    {
        type: 'noun',
        en: 'Guitar',
        pl: 'Gitara',
        jp: 'ギター',
    },
    {
        type: 'noun',
        en: 'Yellow',
        pl: 'Żółty',
        jp: 'きいろい',
    },
    {
        type: 'noun',
        en: 'Street',
        pl: 'Ulica',
        jp: 'とおり',
    },
    {
        type: 'noun',
        en: 'Air',
        pl: 'Powietrze',
        jp: 'くうき',
    },
    {
        type: 'adjective',
        en: 'Big',
        pl: 'Duży',
        jp: 'おおきい',
    },
    {
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: 'おおかみ',
    },
    {
        type: 'adjective',
        en: 'Small',
        pl: 'Mały',
        jp: 'ちいさい',
    },
    {
        type: 'adjective',
        en: 'Far',
        pl: 'Daleko',
        jp: 'とおい',
    },
    {
        type: 'noun',
        en: 'Fridge',
        pl: 'Lodówka',
        jp: 'れいぞうこ',
    },
];
