import type { JapaneseWord } from '../../types';

export const sakura_11: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'You (polite)',
        pl: 'Ty (grzecznie)',
        jp: 'あなた',
    },
    {
        type: 'noun',
        en: 'You (casual)',
        pl: 'Ty (potocznie)',
        jp: 'きみ',
    },
    {
        type: 'noun',
        en: 'Hospital',
        pl: 'Szpital',
        jp: 'びょういん',
    },
    {
        type: 'noun',
        en: 'New year',
        pl: 'Nowy rok',
        jp: 'おしょうがつ',
    },
    {
        type: 'noun',
        en: 'Birthday',
        pl: 'Urodziny',
        jp: 'たんじょうび',
    },
    {
        type: 'noun',
        en: 'Time',
        pl: 'Czas',
        jp: 'じかん',
    },
    {
        type: 'noun',
        en: 'Now',
        pl: 'Teraz',
        jp: 'いま',
    },
    {
        type: 'phrase',
        en: 'What time is it now?',
        pl: 'Która jest teraz godzina?',
        jp: 'いまなんじですか',
    },
    {
        type: 'noun',
        en: 'AM',
        pl: 'Przed południem',
        jp: 'ごぜん',
    },
    {
        type: 'noun',
        en: 'PM',
        pl: 'Po południu',
        jp: 'ごご',
    },
    {
        type: 'noun',
        en: 'Morning',
        pl: 'Rano',
        jp: 'あさ',
    },
    {
        type: 'noun',
        en: 'Noon',
        pl: 'Południe',
        jp: 'ひる',
    },
    {
        type: 'noun',
        en: 'Night',
        pl: 'Noc',
        jp: 'よる',
    },
    {
        type: 'other',
        en: 'Around',
        pl: 'Około',
        jp: 'ごろ',
    },
    {
        type: 'phrase',
        en: 'Work',
        pl: 'Pracować',
        jp: 'しごとをします',
    },
    {
        type: 'verb',
        en: 'Go back',
        pl: 'Wracać',
        jp: 'かえります',
    },
    {
        type: 'phrase',
        en: 'Go back home',
        pl: 'Wracać do domu',
        jp: 'うちにかえります',
    },
    {
        type: 'verb',
        en: 'Wake up',
        pl: 'Budzić się',
        jp: 'おきます',
    },
    {
        type: 'verb',
        en: 'Go',
        pl: 'Iść',
        jp: 'いきます',
    },
    {
        type: 'phrase',
        en: 'Go to work',
        pl: 'Iść do pracy',
        jp: 'かいしゃにいきます',
    },
    {
        type: 'phrase',
        en: "It's 7 AM now.",
        pl: 'Jest teraz siódma rano.',
        jp: 'いまごぜんしちじです。',
    },
    {
        type: 'phrase',
        en: 'When do you take a shower?',
        pl: 'O której bierzesz prysznic?',
        jp: 'なんじにシャワーをあびますか。',
    },
    {
        type: 'phrase',
        en: 'What time is it now in Tokyo?',
        pl: 'Która jest teraz godzina w Tokio?',
        jp: 'とうきょうはいまなんじですか。',
    },
    {
        type: 'noun',
        en: 'Diary',
        pl: 'Pamiętnik',
        jp: 'にっき',
    },
    {
        type: 'noun',
        en: 'Blog',
        pl: 'Blog',
        jp: 'ブログ',
    },
    {
        type: 'phrase',
        en: 'Take a shower',
        pl: 'Brać prysznic',
        jp: 'シャワーをあびます',
    },
    {
        type: 'phrase',
        en: 'Take a bath',
        pl: 'Brać kąpiel',
        jp: 'おふろにはいります',
    },
    {
        type: 'verb',
        en: 'Sleep',
        pl: 'Spać',
        jp: 'ねます',
    },
    {
        type: 'adjective',
        en: 'I am busy',
        pl: 'Jestem zajęty',
        jp: 'いそがしいです',
    },
    {
        type: 'phrase',
        en: 'Work out',
        pl: 'Ćwiczyć',
        jp: 'うんどうをします',
    },
    {
        type: 'phrase',
        en: 'Do housework',
        pl: 'Robić prace domowe',
        jp: 'かじをします',
    },
    {
        type: 'phrase',
        en: 'Read newspaper at home',
        pl: 'Czytać gazetę w domu',
        jp: 'うちでしんぶんをよみます',
    },
    {
        type: 'phrase',
        en: 'Go to work by train',
        pl: 'Jechać do pracy pociągiem',
        jp: 'でんしゃでしごとにいきます',
    },
    {
        type: 'phrase',
        en: 'Walk',
        pl: 'Spacerować',
        jp: 'さんぽをします',
    },
    {
        type: 'verb',
        en: 'Enter',
        pl: 'Wchodzić',
        jp: 'はいります',
    },
    {
        type: 'phrase',
        en: 'Enter the school',
        pl: 'Wchodzić do szkoły',
        jp: 'がっこうにはいります',
    },
];
