import type { TranslatedJapaneseText, WordBag } from '../../types';

const dual_2026: TranslatedJapaneseText[] = [
    {
        id: 'dc336152-3dcb-4a4f-9c0f-6da83b83377f',
        type: 'noun',
        en: 'Question / Problem',
        pl: 'Pytanie / Problem',
        jp: { text: '問題', pronunciation: 'もんだい' },
    },
    {
        id: '53de28d6-98a8-4c08-8980-e9a451b85b66',
        type: 'noun',
        en: "Master's course",
        pl: 'Studia magisterskie',
        jp: { text: '修士課程', pronunciation: 'しゅうしかてい' },
    },
    {
        id: '6da60055-f32f-4387-9ba5-965e1ebd5a12',
        type: 'noun',
        en: 'Technological university',
        pl: 'Politechnika',
        jp: { text: '工科大学', pronunciation: 'こうかだいがく' },
    },
    {
        id: '8d22599f-0603-475c-be5e-dd9ee60bbf83',
        type: 'phrase',
        formality: 'formal',
        en: 'When I was a child, I played outside.',
        pl: 'Kiedy byłem dzieckiem, bawiłem się na zewnątrz.',
        jp: { text: '子供の時、外で遊びました。', pronunciation: 'こどものとき、そとであそびました。' },
    },
    {
        id: 'b0dce3fe-0a2d-4a4e-85b7-a0853c5a3564',
        type: 'phrase',
        formality: 'informal',
        en: 'Yes',
        pl: 'Tak',
        jp: { text: 'うん' },
    },
    {
        id: 'c0c0a1c7-93cc-4d09-82e8-86d463d45f6a',
        type: 'phrase',
        formality: 'informal',
        en: 'No',
        pl: 'Nie',
        jp: { text: 'ううん' },
    },
    {
        id: 'bc29a363-5c63-425b-b7a9-cc9719e5573d',
        type: 'phrase',
        formality: 'informal',
        en: "I don't have time.",
        pl: 'Nie mam czasu.',
        jp: { text: '時間がない。', pronunciation: 'じかんがない。' },
    },
    {
        id: '4508bc49-7237-400d-a9e6-c4001f086588',
        type: 'phrase',
        formality: 'formal',
        en: "I don't have time.",
        pl: 'Nie mam czasu.',
        jp: { text: '時間はありません。', pronunciation: 'じかんはありません。' },
    },
    {
        id: '8b0e4c57-24cd-47b3-9efd-2a4a4285fabf',
        type: 'noun',
        en: 'Normal',
        pl: 'Normalny',
        jp: { text: '普通', pronunciation: 'ふつう' },
    },
    {
        id: '71fec940-82e9-4a75-aabd-1b7def7c82b3',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Admirable / Distinguished',
        pl: 'Godny podziwu / Wybitny',
        jp: { text: '偉い', pronunciation: 'えらい' },
    },
    {
        id: '98042efd-37f3-4493-af6f-8b94235e1439',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Envious / Jealous',
        pl: 'Zazdrosny',
        jp: { text: '羨ましい', pronunciation: 'うらやましい' },
    },
    {
        id: '73b558cd-42ae-4e80-9f2c-e673f1e74bed',
        type: 'noun',
        en: 'Leaning Tower of Pisa',
        pl: 'Krzywa Wieża w Pizie',
        jp: { text: 'ピサの斜塔', pronunciation: 'ピサのしゃとう' },
    },
    {
        id: '44dc4f87-ca6a-42c2-99eb-b5736a64f8b7',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tired',
        pl: 'Zmęczony',
        jp: { text: 'しんどい' },
    },
    {
        id: 'd694ac19-d5d9-4dbe-a79c-4e7868498a6a',
        type: 'noun',
        en: 'Future',
        pl: 'Przyszłość',
        jp: { text: '将来', pronunciation: 'しょうらい' },
    },
    {
        id: 'addc8429-e4bc-4708-b314-d50d295cedf1',
        type: 'adverb',
        en: 'Almost',
        pl: 'Prawie',
        jp: { text: 'ほとんど' },
    },
    {
        id: '0e9d71bf-04ae-4d63-ba54-d9744885f3fc',
        type: 'noun',
        en: 'Microwave oven',
        pl: 'Mikrofalówka',
        jp: { text: '電子レンジ', pronunciation: 'でんしレンジ' },
    },
    {
        id: '8bd9438f-4fa7-4afe-ae26-9534db268c52',
        type: 'noun',
        en: 'Oven',
        pl: 'Piekarnik',
        jp: { text: 'オーブン' },
    },
    {
        id: '25722f24-909c-4133-bd32-f551692c226d',
        type: 'noun',
        en: 'Light blue',
        pl: 'Jasnoniebieski',
        jp: { text: '水色', pronunciation: 'みずいろ' },
    },
    {
        id: '61390da4-03f3-4f93-be1c-e9e255e090ea',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Take out / Remove',
        pl: 'Wyciągnąć',
        jp: { text: '出す', pronunciation: 'だす' },
    },
    {
        id: '33e4ab96-e3e1-4790-82ad-89b68e6982f2',
        type: 'noun',
        en: 'Entrance',
        pl: 'Wejście',
        jp: { text: '入口', pronunciation: 'いりぐち' },
    },
    {
        id: '187b4a11-645e-4beb-a5b9-15ebd4902541',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'transitive',
        en: 'Put into',
        pl: 'Włożyć',
        jp: { text: '入れる', pronunciation: 'いれる' },
    },
    {
        id: 'c9a52907-92d2-4cd6-bd1a-50219db3afc6',
        type: 'noun',
        en: 'The western world',
        pl: 'Świat zachodni',
        jp: { text: '西洋', pronunciation: 'せいよう' },
    },
    {
        id: '9ed4b766-32d6-43b4-b10e-4a2474d562f4',
        type: 'noun',
        en: 'Conversation',
        pl: 'Rozmowa',
        jp: { text: '会話', pronunciation: 'かいわ' },
    },
    {
        id: '16b64567-3ff5-46b9-90dd-f56c041f809f',
        type: 'noun',
        en: 'Talk / Discussion',
        pl: 'Rozmowa / Dyskusja',
        jp: { text: '話', pronunciation: 'はなし' },
    },
    {
        id: '7b979608-edc8-4d6e-9a92-5b79a5d5d5ff',
        type: 'noun',
        en: 'Factory',
        pl: 'Fabryka',
        jp: { text: '工場', pronunciation: ['こうじょう', 'こうば'] },
    },
    {
        id: '9333cf56-84c8-4cfe-a42e-00d286827fc7',
        type: 'noun',
        en: 'Inspection / Study by observation',
        pl: 'Zwiedzanie / Wizyta studyjna',
        jp: { text: '見学', pronunciation: 'けんがく' },
    },
    {
        id: 'ddb82dd6-df33-4c1f-ace8-920072dc9abe',
        type: 'noun',
        en: 'Voice',
        pl: 'Głos',
        jp: { text: '声', pronunciation: 'こえ' },
    },
    {
        id: '80e4090f-d118-4472-9d84-e7cf7e84c8d2',
        type: 'noun',
        en: 'Traffic light',
        pl: 'Sygnalizacja świetlna',
        jp: { text: '信号', pronunciation: 'しんごう' },
    },
    {
        id: '907746a2-8844-4067-a080-12f4b3d08a6f',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Turn',
        pl: 'Skręcić',
        jp: { text: '曲がる', pronunciation: 'まがる' },
    },
    {
        id: '1b5aa59b-1c31-44eb-b97a-c9d2b97480c3',
        type: 'noun',
        en: 'Direction / Way',
        pl: 'Kierunek / Droga',
        jp: { text: '方', pronunciation: 'ほう' },
    },
    {
        id: '66516d32-1a45-4297-bbf5-6193503ed6e7',
        type: 'noun',
        en: 'Outside',
        pl: 'Na zewnątrz',
        jp: { text: '外', pronunciation: 'そと' },
    },
    {
        id: '8df1efcb-84f7-48bd-9c98-2fb820a73184',
        type: 'noun',
        en: 'Area / Region',
        pl: 'Obszar / Region',
        jp: { text: '辺', pronunciation: 'へん' },
    },
    {
        id: '4fafec0d-e98e-40f3-a195-3088c1f5eeee',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Few / Little',
        pl: 'Mało / Niewielki',
        jp: { text: '少ない', pronunciation: 'すくない' },
    },
];

export const dual2026Bag: WordBag = {
    id: 'a7333f6a-3dec-4b51-a59d-5f27866c1fe0',
    name: 'Dual 2026',
    category: 'dual',
    words: dual_2026,
};
