import type { JapaneseWord } from '../../types';

export const genki_3: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Movie',
        pl: 'Film',
        jp: '映画',
        jp_pronunciation: 'えいが',
    },
    {
        type: 'noun',
        en: 'Music',
        pl: 'Muzyka',
        jp: '音楽',
        jp_pronunciation: 'おんがく',
    },
    {
        type: 'noun',
        en: 'Magazine',
        pl: 'Magazyn',
        jp: '雑誌',
        jp_pronunciation: 'ざっし',
    },
    {
        type: 'noun',
        en: 'Sport',
        pl: 'Sport',
        jp: 'スポーツ',
    },
    {
        type: 'noun',
        en: 'Date (romantic outing)',
        pl: 'Randka',
        jp: 'デート',
    },
    {
        type: 'noun',
        en: 'Tennis',
        pl: 'Tenis',
        jp: 'テニス',
    },
    {
        type: 'noun',
        en: 'Television',
        pl: 'Telewizja',
        jp: 'テレビ',
    },
    {
        type: 'noun',
        en: 'Ice cream',
        pl: 'Lody',
        jp: 'アイスクリーム',
    },
    {
        type: 'noun',
        en: 'Hamburger',
        pl: 'Hamburger',
        jp: 'ハンバーガー',
    },
    {
        type: 'noun',
        en: 'Alcoholic drink',
        pl: 'Alkohol',
        jp: 'お酒',
        jp_pronunciation: 'おさけ',
    },
    {
        type: 'noun',
        en: 'Green tea',
        pl: 'Zielona herbata',
        jp: 'お茶',
        jp_pronunciation: 'おちゃ',
    },
    {
        type: 'noun',
        en: 'Coffee',
        pl: 'Kawa',
        jp: 'コーヒー',
    },
    {
        type: 'noun',
        en: 'Water',
        pl: 'Woda',
        jp: '水',
        jp_pronunciation: 'みず',
    },
    {
        type: 'noun',
        en: 'Breakfast',
        pl: 'Śniadanie',
        jp: '朝ご飯',
        jp_pronunciation: 'あさごはん',
    },
    {
        type: 'noun',
        en: 'Lunch',
        pl: 'Obiad',
        jp: '昼ご飯',
        jp_pronunciation: 'ひるごはん',
    },
    {
        type: 'noun',
        en: 'Dinner',
        pl: 'Kolacja',
        jp: '晩ご飯',
        jp_pronunciation: 'ばんごはん',
    },
    {
        type: 'noun',
        en: 'House',
        pl: 'Dom (budynek)',
        jp: '家',
        jp_pronunciation: 'いえ',
    },
    {
        type: 'noun',
        en: 'Home',
        pl: 'Dom (miejsce zamieszkania)',
        jp: 'うち',
    },
    {
        type: 'noun',
        en: 'Morning',
        pl: 'Rano',
        jp: '朝',
        jp_pronunciation: 'あさ',
    },
    {
        type: 'noun',
        en: 'This evening',
        pl: 'Dziś wieczorem',
        jp: '今晩',
        jp_pronunciation: 'こんばん',
    },
    {
        type: 'noun',
        en: 'Every day',
        pl: 'Codziennie',
        jp: '毎日',
        jp_pronunciation: 'まいにち',
    },
    {
        type: 'noun',
        en: 'Every night',
        pl: 'Co noc',
        jp: '毎晩',
        jp_pronunciation: 'まいばん',
    },
    {
        type: 'noun',
        en: 'Weekend',
        pl: 'Weekend',
        jp: '週末',
        jp_pronunciation: 'しゅうまつ',
    },
    {
        type: 'noun',
        en: 'When',
        pl: 'Kiedy',
        jp: 'いつ',
    },
    {
        type: 'suffix',
        en: 'Around (time)',
        pl: 'Około (czas)',
        jp: 'ごろ',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Go',
        pl: 'Iść',
        jp: '行く',
        jp_pronunciation: 'いく',
        masu_form: '行きます',
        masen_form: '行きません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Return',
        pl: 'Wracać',
        jp: '帰る',
        jp_pronunciation: 'かえる',
        masu_form: '帰ります',
        masen_form: '帰りません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Listen / Hear',
        pl: 'Słuchać / Słyszeć',
        jp: '聞く',
        jp_pronunciation: 'きく',
        masu_form: '聞きます',
        masen_form: '聞きません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Drink',
        pl: 'Pić',
        jp: '飲む',
        jp_pronunciation: 'のむ',
        masu_form: '飲みます',
        masen_form: '飲みません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Speak / Talk',
        pl: 'Mówić',
        jp: '話す',
        jp_pronunciation: 'はなす',
        masu_form: '話します',
        masen_form: '話しません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Read',
        pl: 'Czytać',
        jp: '読む',
        jp_pronunciation: 'よむ',
        masu_form: '読みます',
        masen_form: '読みません',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get up',
        pl: 'Wstawać',
        jp: '起きる',
        jp_pronunciation: 'おきる',
        masu_form: '起きます',
        masen_form: '起きません',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Eat',
        pl: 'Jeść',
        jp: '食べる',
        jp_pronunciation: 'たべる',
        masu_form: '食べます',
        masen_form: '食べません',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Sleep / Go to bed',
        pl: 'Spać / Iść spać',
        jp: '寝る',
        jp_pronunciation: 'ねる',
        masu_form: '寝ます',
        masen_form: '寝ません',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'See / Watch / Look at',
        pl: 'Widzieć / Oglądać / Patrzeć na',
        jp: '見る',
        jp_pronunciation: 'みる',
        masu_form: '見ます',
        masen_form: '見ません',
    },
    {
        type: 'verb',
        verb_type: 'irregular',
        en: 'Do',
        pl: 'Robić',
        jp: 'する',
        masu_form: 'します',
        masen_form: 'しません',
    },
    {
        type: 'verb',
        verb_type: 'irregular',
        en: 'Come',
        pl: 'Przybywać',
        jp: '来る',
        jp_pronunciation: 'くる',
        masu_form: '来ます',
        masen_form: '来ません',
    },
    {
        type: 'phrase',
        en: 'Study',
        pl: 'Uczyć się',
        jp: '勉強する',
        jp_pronunciation: 'べんきょうする',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Good',
        pl: 'Dobry',
        jp: 'いい',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Early',
        pl: 'Wcześnie',
        jp: '早い',
        jp_pronunciation: 'はやい',
    },
    {
        type: 'adverb',
        en: 'Rarely',
        pl: 'Rzadko',
        jp: 'あまり',
    },
    {
        type: 'adverb',
        en: 'Never',
        pl: 'Nigdy',
        jp: '全然',
        jp_description: 'ぜんぜん',
    },
    {
        type: 'adverb',
        en: 'Usually',
        pl: 'Zazwyczaj',
        jp: 'たいてい',
    },
    {
        type: 'adverb',
        en: 'A little',
        pl: 'Trochę',
        jp: 'ちょっと',
    },
    {
        type: 'adverb',
        en: 'Sometimes',
        pl: 'Czasami',
        jp: '時々',
        jp_pronunciation: 'ときどき',
    },
    {
        type: 'adverb',
        en: 'Often',
        pl: 'Często',
        jp: 'よく',
    },
    {
        type: 'phrase',
        en: "That's right",
        pl: 'Zgadza się',
        jp: 'そうですね',
    },
    {
        type: 'phrase',
        en: 'But',
        pl: 'Ale',
        jp: 'でも',
    },
    {
        type: 'phrase',
        en: 'How about ...?',
        pl: 'A co z ...?',
        jp: '・・・はどうですか',
    },
    {
        type: 'phrase',
        en: 'Yes (less formal)',
        pl: 'Tak (mniej formalne)',
        jp: 'ええ',
    },
];
