import type { JapaneseWord } from '../../types';

// Even though there were some countries in Genki 1, I decided to put all of them in dedicated countries file.
// Also, the same applied for family members - they are in family.ts file.
export const genki_1: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'University',
        pl: 'Uniwersytet',
        jp: 'だいがく',
    },
    {
        type: 'unknown',
        en: 'High school',
        pl: 'Liceum',
        jp: 'こうこう',
    },
    {
        type: 'unknown',
        en: 'Student',
        pl: 'Uczeń / Student',
        jp: 'がくせい',
    },
    {
        type: 'unknown',
        en: 'College student',
        pl: 'Student (wyższa uczelnia)',
        jp: 'だいがくせい',
    },
    {
        type: 'unknown',
        en: 'International student',
        pl: 'Student zagraniczny',
        jp: 'りゅうがくせい',
    },
    {
        type: 'unknown',
        en: 'Teacher / Professor',
        pl: 'Nauczyciel / Profesor',
        jp: 'せんせい',
    },
    {
        type: 'unknown',
        en: '... year student',
        pl: 'Student ... roku',
        jp: '...ねんせい',
    },
    {
        type: 'unknown',
        en: 'First year student',
        pl: 'Student pierwszego roku',
        jp: 'いちねんせい',
    },
    {
        type: 'unknown',
        en: 'I',
        pl: 'Ja',
        jp: '私',
        jp_pronunciation: 'わたし',
    },
    {
        type: 'unknown',
        en: 'Friend',
        pl: 'Przyjaciel / Przyjaciółka',
        jp: 'ともだち',
    },
    {
        type: 'unknown',
        en: 'Mr. / Ms. ...',
        pl: 'Pan / Pani ...',
        jp: '... さん',
    },
    {
        type: 'unknown',
        en: 'Citizen of ...',
        pl: 'Obywatel ...',
        jp: '... じん',
    },
    {
        type: 'unknown',
        en: 'Now',
        pl: 'Teraz',
        jp: 'いま',
    },
    {
        type: 'unknown',
        en: 'A.M. (morning)',
        pl: 'Rano',
        jp: 'ごぜん',
    },
    {
        type: 'unknown',
        en: 'P.M. (afternoon)',
        pl: 'Po południu',
        jp: 'ごご',
    },
    {
        type: 'unknown',
        en: "O'clock",
        pl: 'Godzina',
        jp: '... じ',
    },
    {
        type: 'unknown',
        en: 'Half past ...',
        pl: 'Pół godziny po ...',
        jp: '... はん',
    },
    {
        type: 'unknown',
        en: 'Language (suffix)',
        pl: 'Język (sufiks)',
        jp: '... ご',
    },
    {
        type: 'unknown',
        en: '... years old',
        pl: '... lat',
        jp: '... さい',
    },
    {
        type: 'unknown',
        en: 'Phone',
        pl: 'Telefon',
        jp: 'でんわ',
    },
    {
        type: 'unknown',
        en: 'Number (phone / bank account etc.)',
        pl: 'Numer (telefonu / konta bankowego itd.)',
        jp: 'ばんごう',
    },
    {
        type: 'unknown',
        en: 'Name',
        pl: 'Imię',
        jp: 'なまえ',
    },
    {
        type: 'unknown',
        en: 'What',
        pl: 'Co / Jaki',
        jp: 'なん / なに',
    },
    {
        type: 'unknown',
        en: 'Um...',
        pl: 'Yyy...',
        jp: 'あのう',
    },
    {
        type: 'unknown',
        en: 'Yes',
        pl: 'Tak',
        jp: 'はい',
    },
    {
        type: 'unknown',
        en: "That's right",
        pl: 'Zgadza się',
        jp: 'そうです',
    },
    {
        type: 'unknown',
        en: 'Is that so?',
        pl: 'Czy tak? / Naprawdę?',
        jp: 'そうですか',
    },
    {
        type: 'unknown',
        en: 'Country',
        pl: 'Kraj',
        jp: 'くに',
    },
    {
        type: 'unknown',
        en: 'Major (university subject)',
        pl: 'Kierunek (studiów)',
        jp: 'せんこう',
    },
    {
        type: 'unknown',
        en: 'Occupation / Job',
        pl: 'Zawód',
        jp: 'しごと',
    },
    {
        type: 'unknown',
        en: 'Doctor',
        pl: 'Lekarz',
        jp: 'いしゃ',
    },
    {
        type: 'unknown',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: 'かいしゃいん',
    },
    {
        type: 'unknown',
        en: 'Nurse',
        pl: 'Pielęgniarka',
        jp: 'かんごし',
    },
    {
        type: 'unknown',
        en: 'High school student',
        pl: 'Uczeń liceum',
        jp: 'こうこうせい',
    },
    {
        type: 'unknown',
        en: 'Housewife',
        pl: 'Gospodyni domowa',
        jp: 'しゅふ',
    },
    {
        type: 'unknown',
        en: 'Graduate student',
        pl: 'Student studiów magisterskich / doktoranckich',
        jp: 'だいがくいんせい',
    },
    {
        type: 'unknown',
        en: 'Lawyer',
        pl: 'Prawnik',
        jp: 'べんごし',
    },
];
