import type { TranslatedJapaneseText, WordBag } from '../../types';

const genki_5_adjectives: TranslatedJapaneseText[] = [
    {
        id: 'b2952560-9b65-4dbd-b058-1fdaeeb3f616',
        type: 'phrase',
        en: 'This is an interesting book.',
        pl: 'To jest interesująca książka.',
        jp: { text: 'これはおもしろい本です。', pronunciation: 'これはおもしろいほんです。' },
    },
    {
        id: '4f65978d-34fb-4fbe-8a50-1d39ebcf287a',
        type: 'phrase',
        en: "It's extremely hot today.",
        pl: 'Dzisiaj jest niesamowicie gorąco.',
        jp: { text: '今日はすごく暑いです。', pronunciation: 'きょうはすごくあついです。' },
    },
    {
        id: 'ebda4d5c-bc24-40cd-aafa-95d8ef0c918f',
        type: 'phrase',
        en: 'The sea in Osaka is very beautiful.',
        pl: 'Morze w Osace jest bardzo piękne.',
        jp: { text: '大阪の海はとてもきれいです。', pronunciation: 'おおさかのうみはとてもきれいです。' },
    },
    {
        id: 'b927af93-2127-4ac0-a100-c0c0b2d981be',
        type: 'phrase',
        en: "It's a bit sunny today.",
        pl: 'Dzisiaj jest trochę słonecznie.',
        jp: { text: '今日はちょっと晴れです。', pronunciation: 'きょうはちょっとはれです。' },
    },
    {
        id: '427b1336-f8f2-47ba-a21b-e836de9d5f5b',
        type: 'phrase',
        en: "I'm fine.",
        pl: 'Czuję się dobrze.',
        jp: { text: '私は元気です。', pronunciation: 'わたしはげんきです。' },
    },
    {
        id: 'a8bb2d01-7900-492a-81e8-99b189453ebf',
        type: 'phrase',
        en: "I'm not fine.",
        pl: 'Nie czuję się dobrze.',
        jp: { text: '私は元気じゃないです。', pronunciation: 'わたしはげんきじゃないです。' },
    },
    {
        id: 'cce0d667-82a2-4e43-87d8-67bb4ca2fd26',
        type: 'phrase',
        en: "It's cold.",
        pl: 'Jest zimno.',
        jp: { text: 'さむいです。' },
    },
    {
        id: 'a1f05e17-d60c-4ec7-9c8f-728cbccba380',
        type: 'phrase',
        en: "It's not cold.",
        pl: 'Nie jest zimno.',
        jp: { text: 'さむくないです。' },
    },
    {
        id: 'c4b81587-f723-434a-bd1c-1c965e132d52',
        type: 'phrase',
        en: 'It was big.',
        pl: 'Było duże.',
        jp: { text: '大きかったです。', pronunciation: 'おおきかったです。' },
    },
    {
        id: '87154e20-7b59-4294-9847-46a955313417',
        type: 'phrase',
        en: 'It was not big.',
        pl: 'Nie było duże.',
        jp: { text: '大きくなかったです。', pronunciation: 'おおきくなかったです。' },
    },
    {
        id: '612aebc0-d627-4b7e-a7a6-9a1748f8698a',
        type: 'phrase',
        en: 'The movie was scary.',
        pl: 'Film był straszny.',
        jp: { text: '映画はこわかったです。', pronunciation: 'えいがはこわかったです。' },
    },
    {
        id: 'd27c1153-2eae-4793-b25c-37d8c484a984',
        type: 'phrase',
        en: 'The movie was not scary.',
        pl: 'Film nie był straszny.',
        jp: { text: '映画はこわくなかったです。', pronunciation: 'えいがはこわくなかったです。' },
    },
    {
        id: 'afaea7de-b429-4312-8c7a-5f99ee2d3e6c',
        type: 'phrase',
        en: 'The mountain was small.',
        pl: 'Góra była mała.',
        jp: { text: '山は小さかったです。', pronunciation: 'やまはちいさかったです。' },
    },
    {
        id: 'f3e92a1e-b41f-443f-b46d-38c0b8de2d29',
        type: 'phrase',
        en: 'The mountain was not small.',
        pl: 'Góra nie była mała.',
        jp: { text: '山は小さくなかったです。', pronunciation: 'やまはちいさくなかったです。' },
    },
    {
        id: '889f6986-0985-4c67-826c-59611d4cbaed',
        type: 'phrase',
        en: "The trip wasn't fun.",
        pl: 'Wycieczka nie była fajna.',
        jp: { text: '旅行は楽しくなかったです。', pronunciation: 'りょこうはたのしくなかったです。' },
    },
    {
        id: '2decbc3c-af62-4ef3-841f-7b5b3af14d4a',
        type: 'phrase',
        en: 'It was quiet.',
        pl: 'Było cicho.',
        jp: { text: '静かでした。', pronunciation: 'しずかでした。' },
    },
    {
        id: '3456e667-bc0c-4217-bd95-3841c3821a1c',
        type: 'phrase',
        en: "It wasn't quiet.",
        pl: 'Nie było cicho.',
        jp: { text: '静かじゃなかったです。', pronunciation: 'しずかじゃなかったです。' },
    },
    {
        id: '691d0d6f-784e-42c1-a64e-e1ea6fa9c25a',
        type: 'phrase',
        en: 'This is my favorite restaurant.',
        pl: 'To jest moja ulubiona restauracja.',
        jp: { text: 'これは私の好きなレストランです。', pronunciation: 'これはわたしのすきなレストランです。' },
    },
    {
        id: '518bdb01-2623-4cf7-8df0-d742d9b0a4db',
        type: 'phrase',
        en: 'This is my least favorite shop.',
        pl: 'To jest mój najmniej lubiony sklep.',
        jp: { text: 'これは私の嫌いな店です。', pronunciation: 'これはわたしのきらいなみせです。' },
    },
];

export const genki5AdjectivesBag: WordBag = {
    id: 'e13c568d-1c22-441d-a426-cfd6775959dc',
    name: 'Genki #5 Adjectives',
    category: 'genki',
    words: genki_5_adjectives,
};
