import type { JapaneseWord } from '../../types';

export const genki_2: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Which one (of three or more)',
        pl: 'Który (z trzech lub więcej)',
        jp: 'どれ',
    },
    {
        type: 'unknown',
        en: 'Which (of two)',
        pl: 'Który (z dwóch)',
        jp: 'どちら',
    },
    {
        type: 'unknown',
        en: 'Who',
        pl: 'Kto',
        jp: 'だれ',
    },
    {
        type: 'unknown',
        en: 'Delicious',
        pl: 'Pyszny',
        jp: 'おいしい',
    },
    {
        type: 'unknown',
        en: 'Fish',
        pl: 'Ryba',
        jp: 'さかな',
    },
    {
        type: 'unknown',
        en: 'Pork cutlet',
        pl: 'Kotlet schabowy',
        jp: 'とんかつ',
    },
    {
        type: 'unknown',
        en: 'Meat',
        pl: 'Mięso',
        jp: 'にく',
    },
    {
        type: 'unknown',
        en: 'Menu',
        pl: 'Menu',
        jp: 'メニュー',
    },
    {
        type: 'unknown',
        en: 'Vegetables',
        pl: 'Warzywa',
        jp: 'やさい',
    },
    {
        type: 'unknown',
        en: 'Umbrella',
        pl: 'Parasol',
        jp: 'かさ',
    },
    {
        type: 'unknown',
        en: 'Bag',
        pl: 'Torba',
        jp: 'かばん',
    },
    {
        type: 'unknown',
        en: 'Shoe',
        pl: 'But',
        jp: 'くつ',
    },
    {
        type: 'unknown',
        en: 'Wallet',
        pl: 'Portfel',
        jp: 'さいふ',
    },
    {
        type: 'unknown',
        en: 'Jeans',
        pl: 'Dżinsy',
        jp: 'ジーンズ',
    },
    {
        type: 'unknown',
        en: 'Bicycle',
        pl: 'Rower',
        jp: 'じてんしゃ',
    },
    {
        type: 'unknown',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: 'しんぶん',
    },
    {
        type: 'unknown',
        en: 'Smartphone',
        pl: 'Smartfon',
        jp: 'スマホ',
    },
    {
        type: 'unknown',
        en: 'T-shirt',
        pl: 'Koszulka',
        jp: 'Tシャツ',
    },
    {
        type: 'unknown',
        en: 'Watch / Clock',
        pl: 'Zegarek / Zegar',
        jp: 'とけい',
    },
    {
        type: 'unknown',
        en: 'Notebook',
        pl: 'Notatnik',
        jp: 'ノート',
    },
    {
        type: 'unknown',
        en: 'Pen',
        pl: 'Długopis',
        jp: 'ペン',
    },
    {
        type: 'unknown',
        en: 'Hat / Cap',
        pl: 'Kapelusz / Czapka',
        jp: 'ぼうし',
    },
    {
        type: 'unknown',
        en: 'Book',
        pl: 'Książka',
        jp: 'ほん',
    },
    {
        type: 'unknown',
        en: 'Bank',
        pl: 'Bank',
        jp: 'ぎんこう',
    },
    {
        type: 'unknown',
        en: 'Convenience store',
        pl: 'Sklep całodobowy',
        jp: 'コンビニ',
    },
    {
        type: 'unknown',
        en: 'Toilet',
        pl: 'Toaleta',
        jp: 'トイレ',
    },
    {
        type: 'unknown',
        en: 'Library',
        pl: 'Biblioteka',
        jp: 'としょかん',
    },
    {
        type: 'unknown',
        en: 'Post office',
        pl: 'Poczta',
        jp: 'ゆうびんきょく',
    },
    {
        type: 'unknown',
        en: 'Britain',
        pl: 'Wielka Brytania',
        jp: 'イギリス',
    },
    {
        type: 'unknown',
        en: 'Korea',
        pl: 'Korea',
        jp: 'かんこく',
    },
    {
        type: 'unknown',
        en: 'China',
        pl: 'Chiny',
        jp: 'ちゅうごく',
    },
    {
        type: 'unknown',
        en: 'English',
        pl: 'Język angielski',
        jp: 'えいご',
    },
    {
        type: 'unknown',
        en: 'Economics',
        pl: 'Ekonomia',
        jp: 'けいざい',
    },
    {
        type: 'unknown',
        en: 'How much',
        pl: 'Ile (kosztuje)?',
        jp: 'いくら',
    },
    {
        type: 'unknown',
        en: 'Yen',
        pl: 'Jen',
        jp: 'えん',
    },
    {
        type: 'unknown',
        en: 'Welcome (said to customers)',
        pl: 'Witamy (mówione do klientów)',
        jp: 'いらっしゃいませ',
    },
    {
        type: 'unknown',
        en: 'Please / Here you are (when giving something)',
        pl: 'Proszę / Proszę bardzo (gdy coś dajemy)',
        jp: 'どうぞ',
    },
    {
        type: 'unknown',
        en: 'Thanks (casual)',
        pl: 'Dziękuję (pot.)',
        jp: 'どうも',
    },
];

