import type { TranslatedJapaneseText, WordBag } from '../../types';

// Family related vocabulary was skipped because it is already present in its own bag.
const genki_7: TranslatedJapaneseText[] = [
    {
        id: '0f06a1ff-f87e-47a0-a24f-d36f883d198d',
        type: 'noun',
        en: 'Man',
        pl: 'Mężczyzna',
        jp: { text: '男の人', pronunciation: 'おとこのひと' },
    },
    {
        id: '0ad97342-7cdb-474d-8e08-362aff120205',
        type: 'noun',
        en: 'Woman',
        pl: 'Kobieta',
        jp: { text: '女の人', pronunciation: 'おんなのひと' },
    },
    {
        id: 'db20c896-90d3-4627-bfe8-9311e6b49834',
        type: 'noun',
        en: 'Company',
        pl: 'Firma',
        jp: { text: '会社', pronunciation: 'かいしゃ' },
    },
    {
        id: '99245424-ace9-44d6-907c-d8adfe6a937f',
        type: 'noun',
        en: 'Cafeteria / Dining commons',
        pl: 'Stołówka',
        jp: { text: '食堂', pronunciation: 'しょくどう' },
    },
    {
        id: '1b65f602-0056-4a1f-b5b6-af9ccbe0ff94',
        type: 'noun',
        en: 'Department store',
        pl: 'Dom towarowy',
        jp: { text: 'デパート' },
    },
    {
        id: 'f708f2b7-8d98-4d29-9265-854782a5c21e',
        type: 'noun',
        en: 'Hair',
        pl: 'Włosy',
        jp: { text: '髪', pronunciation: 'かみ' },
    },
    {
        id: '9749faa9-a256-46c0-88c2-7f95b42ebea3',
        type: 'noun',
        en: 'Mouth',
        pl: 'Usta',
        jp: { text: '口', pronunciation: 'くち' },
    },
    {
        id: 'a9b2e6a6-5a30-4dbb-83b7-70eebed79974',
        type: 'noun',
        en: 'Eye',
        pl: 'Oko',
        jp: { text: '目', pronunciation: 'め' },
    },
    {
        id: '1a4a0654-f4d1-478d-9970-c8953c370647',
        type: 'noun',
        en: 'Glasses',
        pl: 'Okulary',
        jp: { text: '眼鏡', pronunciation: 'めがね' },
    },
    {
        id: 'ddb9c7a5-a293-438e-a274-a6c16d9f042b',
        type: 'noun',
        en: 'Song',
        pl: 'Piosenka',
        jp: { text: '歌', pronunciation: 'うた' },
    },
    {
        id: '2c9d7b51-833b-4900-a7ba-1fdb8706d65d',
        type: 'noun',
        en: 'Club activity / Group with common interest',
        pl: 'Koło zainteresowań / Zajęcia pozalekcyjne',
        jp: { text: 'サークル' },
    },
    {
        id: '699d718c-566e-451f-8283-f19d51894e30',
        type: 'noun',
        en: 'Car',
        pl: 'Samochód',
        jp: { text: '車', pronunciation: 'くるま' },
    },
    {
        id: '1b3e87fd-0f8a-431d-bb32-e116e3c9ef28',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Long',
        pl: 'Długi',
        jp: { text: '長い', pronunciation: 'ながい' },
    },
    {
        id: '360cf2f2-c6fc-4b3d-91a9-7cd437b76842',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short (length)',
        pl: 'Krótki',
        jp: { text: '短い', pronunciation: 'みじかい' },
    },
    {
        id: '5fade6ee-b9f0-4bdc-adfc-7eedfbd6d6a2',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fast',
        pl: 'Szybki',
        jp: { text: '速い', pronunciation: 'はやい' },
    },
    {
        id: '6be25a82-a4b4-4501-9949-7995b55bc9ce',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tall (stature)',
        pl: 'Wysoki (wzrost)',
        jp: { text: '背が高い', pronunciation: 'せがたかい' },
    },
    {
        id: 'f0613ae2-0c8b-49ee-ba8a-aa0a0efc6553',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short (stature)',
        pl: 'Niski (wzrost)',
        jp: { text: '背が低い', pronunciation: 'せがひくい' },
    },
    {
        id: 'd6dfe9da-f4e9-4e93-a57e-1ead22352d55',
        type: 'adjective',
        adjective_type: 'i-adjective-irregular',
        en: 'Smart / Clever',
        pl: 'Mądry / Sprytny',
        jp: { text: '頭がいい', pronunciation: 'あたまがいい' },
        negative: { text: '頭がよくない', pronunciation: 'あたまがよくない' },
    },
    {
        id: '2c559d56-ad05-4a81-ba17-c06e887deb94',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cute',
        pl: 'Słodki / Uroczy',
        jp: { text: 'かわいい' },
    },
    {
        id: 'b637a9cb-a6cd-48ad-b36a-1e9b0e1d9fa5',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Nice / Kind (can only be used for not close people)',
        pl: 'Miły / Uprzejmy (może być używane tylko do osób, z którymi nie jesteśmy blisko)',
        jp: { text: '親切', pronunciation: 'しんせつ' },
    },
    {
        id: 'ac8e3db1-072b-46f8-b023-50d47634ca4d',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient',
        pl: 'Wygodny',
        jp: { text: '便利', pronunciation: 'べんり' },
    },
    {
        id: '6cc1b1b0-2d9f-4dcb-bca2-f970f6af8cfe',
        type: 'verb',
        verb_type: 'godan',
        en: 'Sing',
        pl: 'Śpiewać',
        jp: { text: '歌う', pronunciation: 'うたう' },
    },
    {
        id: '7b19bb92-fec4-49d8-bb70-1782c8fa6c0b',
        type: 'phrase',
        en: 'To sing a song',
        pl: 'Śpiewać piosenkę',
        jp: { text: '歌を歌う', pronunciation: 'うたをうたう' },
    },
    {
        id: 'd38a67b1-150d-415f-b572-8c6bcf37244a',
        type: 'verb',
        verb_type: 'godan',
        en: 'Put on (hat)',
        pl: 'Zakładać (kapelusz)',
        jp: { text: 'かぶる' },
    },
    {
        id: 'b65889b1-3ee2-4533-a71c-d20a734a4cc1',
        type: 'phrase',
        en: 'To put on a hat',
        pl: 'Zakładać kapelusz',
        jp: { text: '帽子をかぶる', pronunciation: 'ぼうしをかぶる' },
    },
    {
        id: '502bdda9-da6a-4066-9c21-4b0208630805',
        type: 'verb',
        verb_type: 'godan',
        en: 'Put on (item below your waist)',
        pl: 'Zakładać (ubranie poniżej pasa)',
        jp: { text: 'はく' },
    },
    {
        id: 'ddc79caf-50bb-46de-a92d-a08cf941d19c',
        type: 'phrase',
        en: 'To put on shoes',
        pl: 'Zakładać buty',
        jp: { text: '靴をはく', pronunciation: 'くつをはく' },
    },
    {
        id: '7160a23a-6829-49d3-a994-2c06a88f372c',
        type: 'verb',
        verb_type: 'godan',
        en: 'Know / Be aware of',
        pl: 'Wiedzieć / Znać',
        jp: { text: '知る', pronunciation: 'しる' },
    },
    {
        id: '66815647-e89d-4a53-943e-9fba611ac74b',
        type: 'verb',
        verb_type: 'godan',
        en: 'Live / Reside',
        pl: 'Mieszkać',
        jp: { text: '住む', pronunciation: 'すむ' },
    },
    {
        id: 'e454b408-e6bc-461d-b4bc-ed4ab6ea6e3e',
        type: 'verb',
        verb_type: 'godan',
        en: 'Work',
        pl: 'Pracować',
        jp: { text: '働く', pronunciation: 'はたらく' },
    },
    {
        id: 'e08b458e-9931-4bac-9586-85a5e890690b',
        type: 'verb',
        verb_type: 'godan',
        en: 'Gain weight',
        pl: 'Przytyć',
        jp: { text: '太る', pronunciation: 'ふとる' },
    },
    {
        id: 'bdcb0057-8027-4baf-9d8e-b4c83576af5d',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Put on (glasses)',
        pl: 'Zakładać (okulary)',
        jp: { text: 'かける' },
    },
    {
        id: '4fd69195-399f-4b0d-9748-988842d64bc5',
        type: 'phrase',
        en: 'To put on glasses',
        pl: 'Zakładać okulary',
        jp: { text: '眼鏡をかける', pronunciation: 'めがねをかける' },
    },
    {
        id: 'ba35c7f8-73f0-4339-afa4-8bc9d30feaec',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Lose weight',
        pl: 'Schudnąć',
        jp: { text: '痩せる', pronunciation: 'やせる' },
    },
    {
        id: '9e65a898-0707-450c-bcf0-4585aa628f3b',
        type: 'verb',
        verb_type: 'suru',
        en: 'Get married',
        pl: 'Wziąć ślub',
        jp: { text: '結婚する', pronunciation: 'けっこんする' },
    },
    {
        id: '4a62a4a8-4e99-4ca4-be9a-dd0378ab41d4',
        type: 'phrase',
        en: 'Nothing',
        pl: 'Nic',
        jp: { text: '何も', pronunciation: 'なにも' },
    },
    {
        id: '4c0a478a-76bf-4c80-858a-4d6880f9a4a3',
        type: 'adverb',
        en: 'Nothing in particular / Not especially',
        pl: 'Nic szczególnego / Nic specjalnego',
        jp: { text: '別に', pronunciation: 'べつに' },
    },
    {
        id: '19d32f61-b498-447d-ac8a-51c3cad3d670',
        type: 'adverb',
        en: 'Of course / Certainly',
        pl: 'Oczywiście / Z pewnością',
        jp: { text: 'もちろん' },
    },
    {
        id: '4dbcb577-1225-4da2-affd-d9d7860afdb0',
        type: 'phrase',
        en: 'If you like / If you want',
        pl: 'Jeśli chcesz / Jeśli masz ochotę',
        jp: { text: 'よかったら' },
    },
    {
        id: 'f253a0dc-e67c-4ef9-9661-0202fb916ace',
        type: 'phrase',
        en: "I'm not doing anything especially.",
        pl: 'Nie robię nic szczególnego.',
        jp: { text: '別に何もしていません。', pronunciation: 'べつになにもしていません。' },
    },
];

export const genki7Bag: WordBag = {
    id: 'a5ff9208-3cdc-4d53-bb5b-50b697126fdd',
    name: 'Genki #7',
    words: genki_7,
};
