import type { JapaneseWord } from '../../types.ts';

export const genki_0: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: 'おはよう',
    },
    {
        type: 'phrase',
        en: 'Good morning (polite)',
        pl: 'Dzień dobry (rano, grzecznościowe)',
        jp: 'おはようございます',
    },
    {
        type: 'phrase',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: 'こんにちは',
    },
    {
        type: 'phrase',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: 'こんばんは',
    },
    {
        type: 'phrase',
        en: 'Goodbye (long time)',
        pl: 'Do widzenia (na dłuższy czas)',
        jp: 'さようなら',
    },
    {
        type: 'phrase',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: 'おやすみ(なさい)',
        jp_description: 'なさい is a polite ending, can be omitted in casual speech',
    },
    {
        type: 'phrase',
        en: 'Thank you (polite)',
        pl: 'Dziękuję (grzecznościowe)',
        jp: 'ありがとうございます',
    },
    {
        type: 'phrase',
        en: 'Thank you (casual)',
        pl: 'Dziękuję (potoczne)',
        jp: 'ありがとう',
    },
    {
        type: 'phrase',
        en: "Excuse me; I'm sorry",
        pl: 'Przepraszam',
        jp: 'すみません',
    },
    {
        type: 'phrase',
        en: 'No; not at all',
        pl: 'Nie; nie szkodzi',
        jp: 'いいえ',
    },
    {
        type: 'phrase',
        en: "I'll go and come back",
        pl: 'Idę i wrócę',
        jp: 'いってきます',
        jp_description: 'Used when leaving home',
    },
    {
        type: 'phrase',
        en: 'Please go and come back',
        pl: 'Idź i wróć',
        jp: 'いってらっしゃい',
        jp_description: 'Used as a goodbye when someone else is leaving a home',
    },
    {
        type: 'phrase',
        en: "I'm home",
        pl: 'Już jestem w domu',
        jp: 'ただいま',
    },
    {
        type: 'phrase',
        en: 'Welcome home',
        pl: 'Witaj w domu',
        jp: 'おかえり(なさい)',
        jp_description: 'Used to welcome someone home',
    },
    {
        type: 'phrase',
        en: 'Bon appétit',
        pl: 'Smacznego',
        jp: 'いただきます',
        jp_description: 'Said before eating. Literally: Thank you for the meal',
    },
    {
        type: 'phrase',
        en: 'Thank you for the meal',
        pl: 'Dziękuję za posiłek',
        jp: 'ごちそうさまでした',
    },
    {
        type: 'phrase',
        en: 'Nice to meet you (at the beginning of introduction)',
        pl: 'Miło cię poznać (na początku przedstawiania się)',
        jp: 'はじめまして',
    },
    {
        type: 'phrase',
        en: 'Nice to meet you (said after introduction)',
        pl: 'Miło cię poznać (po przedstawieniu się)',
        jp: 'よろしくおねがいします',
        jp_description: 'Used after introduction. Literally: Please treat me well.',
    },
];
