import type { JapaneseWord } from '../../types';

// Even though there were some countries in Genki 1, I decided to put all of them in dedicated countries file.
// Also, the same applied for family members - they are in family.ts file.
export const genki_1: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'University',
        pl: 'Uniwersytet',
        jp: { word: 'だいがく' },
    },
    {
        type: 'noun',
        en: 'High school',
        pl: 'Liceum',
        jp: { word: 'こうこう' },
    },
    {
        type: 'noun',
        en: 'Student',
        pl: 'Uczeń / Student',
        jp: { word: 'がくせい' },
    },
    {
        type: 'noun',
        en: 'College student',
        pl: 'Student (wyższa uczelnia)',
        jp: { word: 'だいがくせい' },
    },
    {
        type: 'noun',
        en: 'International student',
        pl: 'Student zagraniczny',
        jp: { word: 'りゅうがくせい' },
    },
    {
        type: 'noun',
        en: 'Teacher / Professor',
        pl: 'Nauczyciel / Profesor',
        jp: { word: 'せんせい' },
    },
    {
        type: 'suffix',
        en: '... year student',
        pl: 'Student ... roku',
        jp: { word: 'ねんせい' },
    },
    {
        type: 'noun',
        en: 'First year student',
        pl: 'Student pierwszego roku',
        jp: { word: 'いちねんせい' },
    },
    {
        type: 'pronoun',
        en: 'I',
        pl: 'Ja',
        jp: { word: '私', pronunciation: 'わたし' },
    },
    {
        type: 'noun',
        en: 'Friend',
        pl: 'Przyjaciel / Przyjaciółka',
        jp: { word: 'ともだち' },
    },
    {
        type: 'suffix',
        en: 'Mr. / Ms.',
        pl: 'Pan / Pani',
        jp: { word: 'さん' },
    },
    {
        type: 'suffix',
        en: 'Citizen of',
        pl: 'Obywatel',
        jp: { word: 'じん' },
    },
    {
        type: 'noun',
        en: 'Now',
        pl: 'Teraz',
        jp: { word: 'いま' },
    },
    {
        type: 'noun',
        en: 'A.M. (morning)',
        pl: 'Przed południem',
        jp: { word: 'ごぜん' },
    },
    {
        type: 'noun',
        en: 'P.M. (afternoon)',
        pl: 'Po południu',
        jp: { word: 'ごご' },
    },
    {
        type: 'suffix',
        en: "O'clock",
        pl: 'Godzina',
        jp: { word: 'じ' },
    },
    {
        type: 'noun',
        en: 'Half past',
        pl: 'Pół godziny po',
        jp: { word: 'はん' },
    },
    {
        type: 'suffix',
        en: 'Language',
        pl: 'Język',
        jp: { word: 'ご' },
    },
    {
        type: 'suffix',
        en: 'Years old',
        pl: 'Lat',
        jp: { word: 'さい' },
    },
    {
        type: 'noun',
        en: 'Phone',
        pl: 'Telefon',
        jp: { word: 'でんわ' },
    },
    {
        type: 'noun',
        en: 'Number (phone / bank account etc.)',
        pl: 'Numer (telefonu / konta bankowego itd.)',
        jp: { word: 'ばんごう' },
    },
    {
        type: 'noun',
        en: 'Name',
        pl: 'Imię',
        jp: { word: 'なまえ' },
    },
    {
        type: 'pronoun',
        en: 'What',
        pl: 'Co / Jaki',
        jp: { word: 'なん / なに' },
    },
    {
        type: 'phrase',
        en: 'Um...',
        pl: 'Yyy...',
        jp: { word: 'あのう' },
    },
    {
        type: 'phrase',
        en: 'Yes',
        pl: 'Tak',
        jp: { word: 'はい' },
    },
    {
        type: 'phrase',
        en: "That's right.",
        pl: 'Zgadza się.',
        jp: { word: 'そうです。' },
    },
    {
        type: 'phrase',
        en: 'Is that so?',
        pl: 'Czy tak? / Naprawdę?',
        jp: { word: 'そうですか。' },
    },
    {
        type: 'noun',
        en: 'Country',
        pl: 'Kraj',
        jp: { word: 'くに' },
    },
    {
        type: 'noun',
        en: 'Major (university subject)',
        pl: 'Kierunek (studiów)',
        jp: { word: 'せんこう' },
    },
    {
        type: 'noun',
        en: 'Occupation / Job',
        pl: 'Zawód',
        jp: { word: 'しごと' },
    },
    {
        type: 'noun',
        en: 'Doctor',
        pl: 'Lekarz',
        jp: { word: 'いしゃ' },
    },
    {
        type: 'noun',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: { word: 'かいしゃいん' },
    },
    {
        type: 'noun',
        en: 'Nurse',
        pl: 'Pielęgniarka',
        jp: { word: 'かんごし' },
    },
    {
        type: 'noun',
        en: 'High school student',
        pl: 'Uczeń liceum',
        jp: { word: 'こうこうせい' },
    },
    {
        type: 'noun',
        en: 'Housewife',
        pl: 'Gospodyni domowa',
        jp: { word: 'しゅふ' },
    },
    {
        type: 'noun',
        en: 'Graduate student',
        pl: 'Student studiów magisterskich / doktoranckich',
        jp: { word: 'だいがくいんせい' },
    },
    {
        type: 'noun',
        en: 'Lawyer',
        pl: 'Prawnik',
        jp: { word: 'べんごし' },
    },
];
