import type { JapaneseWord } from '../../types.ts';

export const genki_0: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: { word: 'おはよう' },
    },
    {
        type: 'unknown',
        en: 'Good morning (polite)',
        pl: 'Dzień dobry (rano, grzecznościowe)',
        jp: { word: 'おはようございます' },
    },
    {
        type: 'unknown',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: { word: 'こんにちは' },
    },
    {
        type: 'unknown',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: { word: 'こんばんは' },
    },
    {
        type: 'unknown',
        en: 'Goodbye (long time)',
        pl: 'Do widzenia (na dłuższy czas)',
        jp: { word: 'さようなら' },
    },
    {
        type: 'unknown',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: { word: 'おやすみ(なさい)' },
        description: 'なさい is a polite ending, can be omitted in casual speech.',
    },
    {
        type: 'unknown',
        en: 'Thank you (polite)',
        pl: 'Dziękuję (grzecznościowe)',
        jp: { word: 'ありがとうございます' },
    },
    {
        type: 'unknown',
        en: 'Thank you (casual)',
        pl: 'Dziękuję (potoczne)',
        jp: { word: 'ありがとう' },
    },
    {
        type: 'unknown',
        en: "Excuse me; I'm sorry",
        pl: 'Przepraszam',
        jp: { word: 'すみません' },
    },
    {
        type: 'unknown',
        en: 'No; not at all',
        pl: 'Nie; nie szkodzi',
        jp: { word: 'いいえ' },
    },
    {
        type: 'unknown',
        en: "I'll go and come back",
        pl: 'Idę i wrócę',
        jp: { word: 'いってきます' },
        description: 'Used when leaving home',
    },
    {
        type: 'unknown',
        en: 'Please go and come back',
        pl: 'Idź i wróć',
        jp: { word: 'いってらっしゃい' },
        description: 'Used as a goodbye when someone else is leaving a home.',
    },
    {
        type: 'unknown',
        en: "I'm home",
        pl: 'Już jestem w domu',
        jp: { word: 'ただいま' },
    },
    {
        type: 'unknown',
        en: 'Welcome home',
        pl: 'Witaj w domu',
        jp: { word: 'おかえり(なさい)' },
        description: 'Used to welcome someone home.',
    },
    {
        type: 'unknown',
        en: 'Bon appétit',
        pl: 'Smacznego',
        jp: { word: 'いただきます' },
        description: 'Said before eating. Literally: Thank you for the meal',
    },
    {
        type: 'unknown',
        en: 'Thank you for the meal',
        pl: 'Dziękuję za posiłek',
        jp: { word: 'ごちそうさまでした' },
    },
    {
        type: 'unknown',
        en: 'Nice to meet you (at the beginning of introduction)',
        pl: 'Miło cię poznać (na początku przedstawiania się)',
        jp: { word: 'はじめまして' },
    },
    {
        type: 'unknown',
        en: 'Nice to meet you (said after introduction)',
        pl: 'Miło cię poznać (po przedstawieniu się)',
        jp: { word: 'よろしくおねがいします' },
        description: 'Used after introduction. Literally: Please treat me well.',
    },
];
