import type { JapaneseWord } from '../../types';

export const genki_4: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Game',
        pl: 'Gra',
        jp: 'ゲーム',
    },
    {
        type: 'noun',
        en: 'Part time job',
        pl: 'Praca na część etatu',
        jp: 'アルバイト',
    },
    {
        type: 'noun',
        en: 'Shopping',
        pl: 'Zakupy',
        jp: '買い物',
        jp_pronunciation: 'かいもの',
    },
    {
        type: 'noun',
        en: 'Class',
        pl: 'Klasa',
        jp: 'クラス',
    },
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: '犬',
        jp_pronunciation: 'いぬ',
    },
    {
        type: 'noun',
        en: 'Cat',
        pl: 'Kot',
        jp: '猫',
        jp_pronunciation: 'ねこ',
    },
    {
        type: 'noun',
        en: 'Person',
        pl: 'Osoba',
        jp: '人',
        jp_pronunciation: 'ひと',
    },
    {
        type: 'pronoun',
        en: 'You (polite)',
        pl: 'Ty (grzecznie)',
        jp: 'あなた',
    },
    {
        type: 'noun',
        en: 'Chair',
        pl: 'Krzesło',
        jp: 'いす',
    },
    {
        type: 'noun',
        en: 'Desk',
        pl: 'Biurko',
        jp: '机',
        jp_pronunciation: 'つくえ',
    },
    {
        type: 'noun',
        en: 'Picture / Photograph',
        pl: 'Obraz / Zdjęcie',
        jp: '写真',
        jp_pronunciation: 'しゃしん',
    },
    {
        type: 'noun',
        en: 'Flower',
        pl: 'Kwiat',
        jp: '花',
        jp_pronunciation: 'はな',
    },
    {
        type: 'noun',
        en: 'Report / Paper',
        pl: 'Raport / Praca pisemna',
        jp: 'レポート',
    },
    {
        type: 'noun',
        en: 'Rice / Meal',
        pl: 'Ryż / Posiłek',
        jp: 'ご飯',
        jp_pronunciation: 'ごはん',
    },
    {
        type: 'noun',
        en: 'Bread',
        pl: 'Chleb',
        jp: 'パン',
    },
    {
        type: 'noun',
        en: 'Temple',
        pl: 'Świątynia',
        jp: 'お寺',
        jp_pronunciation: 'おてら',
    },
    {
        type: 'noun',
        en: 'Park',
        pl: 'Park',
        jp: '公園',
        jp_pronunciation: 'こうえん',
    },
    {
        type: 'noun',
        en: 'Supermarket',
        pl: 'Supermarket',
        jp: 'スーパー',
    },
    {
        type: 'noun',
        en: 'Bus stop',
        pl: 'Przystanek autobusowy',
        jp: 'バス停',
        jp_pronunciation: 'バスてい',
    },
    {
        type: 'noun',
        en: 'Hospital',
        pl: 'Szpital',
        jp: '病院',
        jp_pronunciation: 'びょういん',
    },
    {
        type: 'noun',
        en: 'Hotel',
        pl: 'Hotel',
        jp: 'ホテル',
    },
    {
        type: 'noun',
        en: 'Bookstore',
        pl: 'Księgarnia',
        jp: '本屋',
        jp_pronunciation: 'ほんや',
    },
    {
        type: 'noun',
        en: 'Town',
        pl: 'Miasteczko',
        jp: '町',
        jp_pronunciation: 'まち',
    },
    {
        type: 'noun',
        en: 'Restaurant',
        pl: 'Restauracja',
        jp: 'レストラン',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Meet',
        pl: 'Spotykać',
        jp: '会う',
        jp_pronunciation: 'あう',
        masu_form: '会います (あいます)',
        masen_form: '会いません (あいません)',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'There is / There are (inanimate)',
        pl: 'Jest / Są (nieożywione)',
        jp: 'あります',
        masu_form: 'あります',
        masen_form: 'ありません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Buy',
        pl: 'Kupować',
        jp: '買う',
        jp_pronunciation: 'かう',
        masu_form: '買います (かいます)',
        masen_form: '買いません (かいません)',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Write',
        pl: 'Pisać',
        jp: '書く',
        jp_pronunciation: 'かく',
        masu_form: '書きます (かきます)',
        masen_form: '書きません (かきません)',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Take (a picture)',
        pl: 'Robić (zdjęcie)',
        jp: '撮る',
        jp_pronunciation: 'とる',
        masu_form: '撮ります (とります)',
        masen_form: '撮りません (とりません)',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Wait',
        pl: 'Czekać',
        jp: '待つ',
        jp_pronunciation: 'まつ',
        masu_form: '待ちます (まちます)',
        masen_form: '待ちません (まちません)',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Understand',
        pl: 'Rozumieć',
        jp: '分かる',
        jp_pronunciation: 'わかる',
        masu_form: '分かります (わかります)',
        masen_form: '分かりません (わかりません)',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'There is / There are (animate)',
        pl: 'Jest / Są (ożywione)',
        jp: 'いる',
        masu_form: 'います',
        masen_form: 'いません',
    },
    {
        type: 'suffix',
        en: 'Around / About (time period)',
        pl: 'Około (okres czasu)',
        jp: 'ぐらい',
    },
    {
        type: 'phrase',
        en: "I'm sorry",
        pl: 'Przepraszam',
        jp: 'ごめんなさい',
    },
    {
        type: 'phrase',
        en: 'And then / After that',
        pl: 'A potem / Po tym',
        jp: 'それから',
    },
    {
        type: 'phrase',
        en: 'So / Therefore',
        pl: 'Więc / Dlatego',
        jp: 'だから',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'A lot / Many / Much',
        pl: 'Dużo / Wielu / Wiele',
        jp: 'たくさん',
    },
    {
        type: 'adverb',
        en: 'Why / How',
        pl: 'Dlaczego / Jak',
        jp: 'どうして',
    },
    {
        type: 'phrase',
        en: 'Alone',
        pl: 'Samemu',
        jp: '一人で',
        jp_pronunciation: 'ひとりで',
    },
    {
        type: 'phrase',
        en: 'Hello (on the phone)',
        pl: 'Halo',
        jp: 'もしもし',
    },
];
