import type { TranslatedJapaneseText, WordBag } from '../../types';

// Words that were skipped because they are already in general purpose bags:
// last month - せんげつ
// last year - きょねん
const genki_9: TranslatedJapaneseText[] = [
    {
        id: '829833c3-3032-421f-96bf-08bcff4b2b17',
        type: 'noun',
        en: 'Word / Vocabulary',
        pl: 'Słowo / Słownictwo',
        jp: { text: '単語', pronunciation: 'たんご' },
    },
    {
        id: '8c197c1b-36ed-42df-a7b9-5f84bbdd4e6b',
        type: 'noun',
        en: 'Essay / Composition',
        pl: 'Wypracowanie / Kompozycja',
        jp: { text: '作文', pronunciation: 'さくぶん' },
    },
    {
        id: 'e1a330bb-0257-40f9-9a65-f98b40987feb',
        type: 'noun',
        en: 'Exam',
        pl: 'Egzamin',
        jp: { text: '試験', pronunciation: 'しけん' },
    },
    {
        id: 'b2566a67-0773-4698-94fb-c5c91326751f',
        type: 'noun',
        en: 'E-Mail',
        pl: 'E-Mail',
        jp: { text: 'メール' },
    },
    {
        id: '2c5f984b-70f4-4f4e-addb-2747ae245da7',
        type: 'noun',
        en: 'Guitar',
        pl: 'Gitara',
        jp: { text: 'ギター' },
    },
    {
        id: '474ae8df-8ca3-48ce-a9bd-095da316d8f5',
        type: 'noun',
        en: 'Piano',
        pl: 'Fortepian',
        jp: { text: 'ピアノ' },
    },
    {
        id: 'af579f2e-e8a2-4289-87e9-b2d8b37c8f49',
        type: 'noun',
        en: 'Concert',
        pl: 'Koncert',
        jp: { text: 'コンサート' },
    },
    {
        id: '721b57a2-b528-4f77-8799-30f2d7f76a7d',
        type: 'noun',
        en: 'Ticket (for plane, concert, etc.)',
        pl: 'Bilet (na samolot, koncert, itp.)',
        jp: { text: 'チケット' },
    },
    {
        id: '3d9a0ba4-e269-4c70-a9e9-1ea88079ad39',
        type: 'noun',
        en: 'Traditional form of drama and music',
        pl: 'Tradycyjna forma dramatu i muzyki',
        jp: { text: '歌舞伎', pronunciation: 'かぶき' },
    },
    {
        id: '235682e5-6f03-4bc3-b4e4-37e0540bfc8c',
        type: 'noun',
        en: 'Skiing',
        pl: 'Narciarstwo',
        jp: { text: 'スキー' },
    },
    {
        id: '833270b2-757c-4ffe-bfcd-2f67ebcc4690',
        type: 'noun',
        en: 'Boxed lunch',
        pl: 'Pudełkowy lunch',
        jp: { text: 'お弁当', pronunciation: 'おべんとう' },
    },
    {
        id: 'f3c4cbfa-0634-415b-b819-70e90666f941',
        type: 'noun',
        en: 'Pizza',
        pl: 'Pizza',
        jp: { text: 'ピザ' },
    },
    {
        id: '64f61cf9-5efe-4413-93c9-806d06ee4183',
        type: 'noun',
        en: 'Sickness / Illness',
        pl: 'Choroba',
        jp: { text: '病気', pronunciation: 'びょうき' },
    },
    {
        id: 'a0482998-83af-4bdc-a908-86cdb7bdd04e',
        type: 'noun',
        en: 'Good child',
        pl: 'Dobre dziecko',
        jp: { text: 'いい子', pronunciation: 'いいこ' },
    },
    {
        id: '03c45fbb-1970-47c2-a1ac-69624807a94c',
        type: 'noun',
        en: 'Color',
        pl: 'Kolor',
        jp: { text: '色', pronunciation: 'いろ' },
    },
    {
        id: '40c5ffd6-eaa3-4eec-98bb-212ab869702d',
        type: 'noun',
        en: 'Next time / Near future',
        pl: 'Następnym razem / W najbliższej przyszłości',
        jp: { text: '今度', pronunciation: 'こんど' },
    },
    {
        id: '938ad7a6-a84b-484f-9729-f7f2dc14a345',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Blue',
        pl: 'Niebieski',
        jp: { text: '青い', pronunciation: 'あおい' },
    },
    {
        id: '4d1354d8-0d0f-4933-93bf-5eeb08df883b',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Red',
        pl: 'Czerwony',
        jp: { text: '赤い', pronunciation: 'あかい' },
    },
    {
        id: 'e8390389-940e-44ab-a38a-08ae937cbbe3',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Black',
        pl: 'Czarny',
        jp: { text: '黒い', pronunciation: 'くろい' },
    },
    {
        id: 'fd25505c-efc3-47da-8abd-789ec7f3da08',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'White',
        pl: 'Biały',
        jp: { text: '白い', pronunciation: 'しろい' },
    },
    {
        id: 'cfe96980-3451-4f08-a505-d9f4ee0f39a9',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Lonely',
        pl: 'Samotny',
        jp: { text: '寂しい', pronunciation: ['さびしい', 'さみしい'] },
    },
    {
        id: '1cec6ef7-fa51-454b-822f-4436bc57e688',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Young',
        pl: 'Młody',
        jp: { text: '若い', pronunciation: 'わかい' },
    },
    {
        id: 'c76bf946-4992-4962-8832-cdcc65b3d372',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Malicious / Mean',
        pl: 'Złośliwy / Zły',
        jp: { text: '意地悪', pronunciation: 'いじわる' },
    },
    {
        id: '5396ace7-35cc-476b-9a6e-408a61a249ea',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Dance',
        pl: 'Tańczyć',
        jp: { text: '踊る', pronunciation: 'おどる' },
    },
    {
        id: '67948762-ae98-43d2-b9f6-a4a8b79fbccb',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'ambitransitive',
        en: 'End',
        pl: 'Kończyć / Kończyć się',
        jp: { text: '終わる', pronunciation: 'おわる' },
    },
    {
        id: 'b475771a-bceb-4629-93d8-8620a55ca97a',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Take a medicine',
        pl: 'Brać lekarstwo',
        jp: { text: '薬を飲む', pronunciation: 'くすりをのむ' },
    },
    {
        id: '4f3a1aef-8143-4f86-90e2-2eb9d84f03c3',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Be popular',
        pl: 'Być popularnym',
        jp: { text: '人気がある', pronunciation: 'にんきがある' },
    },
    {
        id: 'f56ad89e-fbff-4083-b9f2-026e13cf4369',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: { text: '弾く', pronunciation: 'ひく' },
    },
    {
        id: '12eed8c9-823e-4d95-904b-5d2fb6230fd4',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Receive',
        pl: 'Otrzymywać',
        jp: { text: 'もらう' },
    },
    {
        id: '67372d8e-df5a-40b0-add6-e28fa4b3878b',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'transitive',
        en: 'Memorize',
        pl: 'Zapamiętywać',
        jp: { text: '覚える', pronunciation: 'おぼえる' },
    },
    {
        id: 'ce810491-6e9e-47de-8086-d69eafcbb8c1',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'intransitive',
        en: 'Appear / Attend / Exit',
        pl: 'Pojawiać się / Uczestniczyć / Wychodzić',
        jp: { text: '出る', pronunciation: 'でる' },
    },
    {
        id: 'a8a6541c-d4d2-407b-84da-ba0f72ee131c',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'intransitive',
        en: 'Exercise',
        pl: 'Ćwiczyć',
        jp: { text: '運動する', pronunciation: 'うんどうする' },
    },
    {
        id: '56b5480c-1c5d-4c79-b231-d170b3871fae',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'intransitive',
        en: 'Take a walk',
        pl: 'Spacerować',
        jp: { text: '散歩する', pronunciation: 'さんぽする' },
    },
    {
        id: '5bbf9488-3c2e-4567-ba1a-3e9548086be8',
        type: 'particle',
        en: 'From (a time)',
        pl: 'Od (czasu)',
        jp: { text: 'から' },
    },
    {
        id: '51089b54-5fd0-4565-9f26-e10b2b9ddc67',
        type: 'particle',
        en: 'Until (a time)',
        pl: 'Do (czasu)',
        jp: { text: 'まで' },
    },
    {
        id: 'a69871c9-fce6-456b-a10e-980dbfef8982',
        type: 'adverb',
        en: 'By all means',
        pl: 'Koniecznie / Wszelkimi sposobami',
        jp: { text: '是非', pronunciation: 'ぜひ' },
    },
    {
        id: 'c1ce7148-ea28-4762-8f5e-aae0da8a6b83',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'By the way',
        pl: 'A propos',
        jp: { text: 'ところで' },
    },
    {
        id: 'a55a880f-276d-4999-92c5-549c3a109ce3',
        type: 'pronoun',
        en: 'All',
        pl: 'Wszyscy',
        jp: { text: 'みんな' },
    },
    {
        id: '6f66b8a6-1e4e-41d7-9385-4b8aaba3b473',
        type: 'adverb',
        en: 'Already',
        pl: 'Już',
        jp: { text: 'もう' },
    },
];

export const genki9Bag: WordBag = {
    id: '55086b7d-9ce1-43d5-989a-04aa76082227',
    name: 'Genki #9',
    category: 'genki',
    words: genki_9,
};
