import type { TranslatedJapaneseText, WordBag } from '../../types';

const genki_6_phrases: TranslatedJapaneseText[] = [
    {
        id: '61d32021-7f36-4d27-b314-10bf5a9b7826',
        type: 'phrase',
        en: 'Ken, hurry up please!',
        pl: 'Ken, pośpiesz się proszę!',
        jp: { text: 'ケンさん、急いでください！', pronunciation: 'けんさん、いそいでください！' },
    },
    {
        id: '6f31d370-9979-4cac-8ecf-93ded95d3f5d',
        type: 'phrase',
        en: 'I will return books to the library.',
        pl: 'Oddam książki do biblioteki.',
        jp: { text: '図書館に本を返します。', pronunciation: 'としょかんにほんをかえします。' },
    },
    {
        id: '80e7e551-d113-4e7f-808c-8e7e52756918',
        type: 'phrase',
        en: 'I will turn off the light.',
        pl: 'Wyłączę światło.',
        jp: { text: '電気を消します。', pronunciation: 'でんきをけします。' },
    },
    {
        id: 'd3575b5a-4ff5-494d-91a3-eee9607292d6',
        type: 'phrase',
        en: 'Sit down on the chair, please.',
        pl: 'Usiądź na krześle, proszę.',
        jp: { text: 'いすに座ってください。', pronunciation: 'いすにすわってください。' },
    },
    {
        id: '01bee4f9-6a98-4fc8-b668-679724748848',
        type: 'phrase',
        en: 'I often use the dictionary.',
        pl: 'Często używam słownika.',
        jp: { text: 'よく辞書を使います。', pronunciation: 'よくじしょをつかいます。' },
    },
    {
        id: 'ddafc739-35ba-479f-afb5-a06829c5de2e',
        type: 'phrase',
        en: 'I will help my older sister with house chores.',
        pl: 'Pomogę starszej siostrze w obowiązkach domowych.',
        jp: { text: '姉の家事を手伝います。', pronunciation: 'あねのかじをてつだいます。' },
    },
    {
        id: '424e5cf7-c020-4fd4-981b-b2940aba8d88',
        type: 'phrase',
        en: 'I entered the room.',
        pl: 'Wszedłem do pokoju.',
        jp: { text: '部屋に入りました。', pronunciation: 'へやにはいりました。' },
    },
    {
        id: '9cc92bf2-6bd3-4ef7-834e-b5a1003b0b1a',
        type: 'phrase',
        en: 'Shall I hold the bag for you?',
        pl: 'Potrzymać ci torbę?',
        jp: { text: 'かばんを持ちましょうか。', pronunciation: 'かばんをもちましょうか。' },
    },
    {
        id: 'a7f6f021-0702-4264-9517-f7f81bba0eeb',
        type: 'phrase',
        en: 'Yesterday I was absent from class.',
        pl: 'Wczoraj nie było mnie na lekcji.',
        jp: { text: '昨日授業を休みました。', pronunciation: 'きのうじゅぎょうをやすみました。' },
    },
    {
        id: 'a4320fec-2a5f-46bf-b402-5ef0e852e171',
        type: 'phrase',
        en: 'Open the window, please.',
        pl: 'Otwórz okno, proszę.',
        jp: { text: '窓を開けてください。', pronunciation: 'まどをあけてください。' },
    },
    {
        id: '5c52ddf7-445c-4979-b46a-3a63c104b49b',
        type: 'phrase',
        en: 'I teach kanji to my wife.',
        pl: 'Uczę moją żonę kanji.',
        jp: { text: '妻に漢字を教えます。', pronunciation: 'つまにかんじをおしえます。' },
    },
    {
        id: '414bf407-c4be-4394-beaa-295346805786',
        type: 'phrase',
        en: 'I closed the door.',
        pl: 'Zamknąłem drzwi.',
        jp: { text: 'ドアを閉めました。', pronunciation: 'どあをしめました。' },
    },
    {
        id: 'a9e2a4fc-59b6-43af-a5e8-b8fde98f9d5c',
        type: 'phrase',
        en: 'I forgot the umbrella.',
        pl: 'Zapomniałem parasolki.',
        jp: { text: '傘を忘れました。', pronunciation: 'かさをわすれました。' },
    },
    {
        id: 'cb4c2b4d-992e-4935-a859-c7a6f8a9a146',
        type: 'phrase',
        en: "Let's get off the train.",
        pl: 'Wysiądźmy z pociągu.',
        jp: { text: '電車を降りましょう。', pronunciation: 'でんしゃをおりましょう。' },
    },
    {
        id: 'bb86d25e-12a2-4bb3-a35b-f38dc3b07175',
        type: 'phrase',
        en: 'I borrowed a book from Mark.',
        pl: 'Pożyczyłem książkę od Marka.',
        jp: { text: 'マークさんに本を借りました。', pronunciation: 'マークさんにほんをかりました。' },
    },
    {
        id: '9ea9f234-4c0e-4dd1-b874-1018705cf791',
        type: 'phrase',
        en: 'I turned on the electric kettle.',
        pl: 'Włączyłem czajnik elektryczny.',
        jp: { text: '電気ケトルをつけました。', pronunciation: 'でんきケトルをつけました。' },
    },
    {
        id: '0b84bea5-264f-432e-b0eb-bb7fe3a2131c',
        type: 'phrase',
        en: 'I called my cousin yesterday.',
        pl: 'Wczoraj zadzwoniłem do kuzyna.',
        jp: { text: '昨日いとこに電話しました。', pronunciation: 'きのういとこにでんわしました。' },
    },
    {
        id: '5f144ff1-dedd-4255-a741-809495932a10',
        type: 'phrase',
        en: 'I brought my camera on the trip.',
        pl: 'Zabrałem aparat na wycieczkę.',
        jp: { text: '旅行にカメラを持ってきました。', pronunciation: 'りょこうにカメラをもってきました。' },
    },
    {
        id: '25eb19e3-03e8-4abf-bd29-cb2e4db58cae',
        type: 'phrase',
        en: 'I will bring my grandmother to the party.',
        pl: 'Zabiorę moją babcię na przyjęcie.',
        jp: { text: 'パーティーに祖母を連れて行きます。', pronunciation: 'パーティーにそぼをつれていきます。' },
    },
];

export const genki6PhrasesBag: WordBag = {
    id: 'bcaa27b2-5cf0-4aab-858c-25d64f5684a8',
    name: 'Genki #6 Phrases',
    words: genki_6_phrases,
};
