import type { TranslatedJapaneseText, WordBag } from '../../types';

// Words that were skipped because they are already in general purpose bags:
// the day after tomorrow - あさって
// every week - まいしゅう
// this month - こんげつ
// next month - らいげつ
// Spain - スペイン
const genki_8: TranslatedJapaneseText[] = [
    {
        id: 'aac0a038-c975-4a37-b711-eb17edf8a298',
        type: 'noun',
        en: 'Sunny weather',
        pl: 'Słoneczna pogoda',
        jp: { text: '晴れ', pronunciation: 'はれ' },
    },
    {
        id: 'c6b2ec35-04e2-4fd4-8af9-189dc77dd861',
        type: 'noun',
        en: 'Rain',
        pl: 'Deszcz',
        jp: { text: '雨', pronunciation: 'あめ' },
    },
    {
        id: '1523c1f7-aeaa-48ff-b31d-baebe6ac4458',
        type: 'noun',
        en: 'Cloudy weather',
        pl: 'Pochmurna pogoda',
        jp: { text: '曇り', pronunciation: 'くもり' },
    },
    {
        id: '7f479969-5d51-4077-89e7-64858e6e7911',
        type: 'noun',
        en: 'Snow',
        pl: 'Śnieg',
        jp: { text: '雪', pronunciation: 'ゆき' },
    },
    {
        id: '38d150ff-deba-4af5-9281-3aa54f323cb1',
        type: 'noun',
        en: 'Weather forecast',
        pl: 'Prognoza pogody',
        jp: { text: '天気予報', pronunciation: 'てんきよほう' },
    },
    {
        id: 'f009f02d-8202-4164-9e6b-2fa6b03631f8',
        type: 'noun',
        en: 'Temperature (weather)',
        pl: 'Temperatura (w kontekście pogody)',
        jp: { text: '気温', pronunciation: 'きおん' },
        description: 'This word is used only in the context of weather, not for temperature of objects.',
    },
    {
        id: '15d89d98-af34-4d38-9ffc-de8b694d0d37',
        type: 'noun',
        en: 'Summer',
        pl: 'Lato',
        jp: { text: '夏', pronunciation: 'なつ' },
    },
    {
        id: 'c8d8ad99-a682-452e-bcb7-1d3bd4d0b6fe',
        type: 'noun',
        en: 'Winter',
        pl: 'Zima',
        jp: { text: '冬', pronunciation: 'ふゆ' },
    },
    {
        id: 'a7c4dc42-5b5d-4a6f-aa38-23db4c60798c',
        type: 'noun',
        en: 'This morning',
        pl: 'Dziś rano',
        jp: { text: '今朝', pronunciation: 'けさ' },
    },
    {
        id: 'd8a95bac-30d5-42b4-80a3-df53b2f810a7',
        type: 'noun',
        en: 'Office worker',
        pl: 'Pracownik biurowy',
        jp: { text: '会社員', pronunciation: 'かいしゃいん' },
    },
    {
        id: 'e1b6a009-59b9-4c6d-abe4-9bf72d02d413',
        type: 'noun',
        en: 'Job / Work',
        pl: 'Praca',
        jp: { text: '仕事', pronunciation: 'しごと' },
    },
    {
        id: 'dabf85c2-ccfd-4bf2-af97-d5517b80ab28',
        type: 'noun',
        en: 'Camera',
        pl: 'Aparat fotograficzny',
        jp: { text: 'カメラ' },
    },
    {
        id: 'fa603baf-4ea5-4868-8111-b4c569fff89a',
        type: 'noun',
        en: 'Karaoke',
        pl: 'Karaoke',
        jp: { text: 'カラオケ' },
    },
    {
        id: '8011aa40-df40-4c0e-8a55-dec2e13ab645',
        type: 'noun',
        en: 'Place (abstract)',
        pl: 'Miejsce (w sensie abstrakcyjnym)',
        jp: { text: '所', pronunciation: 'ところ' },
    },
    {
        id: 'ba8ffc21-1f3f-4759-9569-58a599043392',
        type: 'noun',
        en: 'Tomato',
        pl: 'Pomidor',
        jp: { text: 'トマト' },
    },
    {
        id: '3839f0d0-23b1-46a6-aecc-d02f2f3bf4f6',
        type: 'noun',
        en: 'Chopsticks',
        pl: 'Pałeczki',
        jp: { text: '箸', pronunciation: 'はし' },
    },
    {
        id: '20735c88-9676-4cde-b26e-f987f32f60b2',
        type: 'noun',
        en: 'Party',
        pl: 'Przyjęcie',
        jp: { text: 'パーティー' },
    },
    {
        id: '2d06ad00-b34d-4e29-be5d-dc9bade0f812',
        type: 'noun',
        en: 'Barbecue',
        pl: 'Grill',
        jp: { text: 'バーベキュー' },
    },
    {
        id: 'de8940c9-4b4f-4fbb-8e70-1bf1dc2c3382',
        type: 'noun',
        en: 'Homestay',
        pl: 'Pobyt u rodziny goszczącej',
        jp: { text: 'ホームステイ' },
    },
    {
        id: 'ba751d4d-4352-4af7-8e87-70ca22293b92',
        type: 'noun',
        en: 'Bathroom',
        pl: 'Łazienka',
        jp: { text: 'お風呂', pronunciation: 'おふろ' },
    },
    {
        id: '505c42da-a1a7-4034-9216-025640e1c991',
        type: 'noun',
        en: 'Something',
        pl: 'Coś',
        jp: { text: '何か', pronunciation: ['なにか', 'なんか'] },
    },
    {
        id: 'c38816c6-3b0f-45e1-a2a3-88cbca7eca33',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Skilled / Good at (objective)',
        pl: 'Zręczny / Dobry w (obiektywnie)',
        jp: { text: '上手', pronunciation: 'じょうず' },
    },
    {
        id: '7d5d598a-0200-409b-b862-8dd0f32cce1a',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Unskilled / Poor at (objective)',
        pl: 'Niezręczny / Słaby w (obiektywnie)',
        jp: { text: '下手', pronunciation: 'へた' },
    },
    {
        id: 'b8a6690e-e105-4a7d-83df-3cdba60499e9',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Famous',
        pl: 'Sławny',
        jp: { text: '有名', pronunciation: 'ゆうめい' },
    },
    {
        id: 'd195fb8a-829c-4fd4-9123-c127b5b4648c',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Wash',
        pl: 'Myć',
        jp: { text: '洗う', pronunciation: 'あらう' },
    },
    {
        id: 'f8c135da-10ed-4e82-aa80-7365e682814d',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Say',
        pl: 'Mówić',
        jp: { text: '言う', pronunciation: 'いう' },
    },
    {
        id: '95c09970-c7c2-4d60-b9aa-62bc1dace5dc',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Be needed',
        pl: 'Być potrzebnym',
        jp: { text: '要る', pronunciation: 'いる' },
    },
    {
        id: 'cf456f76-a4ae-42a7-9459-31f894c7b7fa',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Become',
        pl: 'Stawać się',
        jp: { text: 'なる' },
    },
    {
        id: 'e7287e89-a23c-4efc-a34d-418ae8af9c79',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Be late',
        pl: 'Spóźniać się',
        jp: { text: '遅くなる', pronunciation: 'おそくなる' },
    },
    {
        id: '02316e5a-4780-4d2f-a790-bd175a25ba6e',
        type: 'phrase',
        en: 'Take a bath',
        pl: 'Brać kąpiel',
        jp: { text: 'お風呂に入る', pronunciation: 'おふろにはいる' },
    },
    {
        id: '6e01ecd2-fda0-4d7c-a37d-2cdce3c247c6',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Think',
        pl: 'Myśleć',
        jp: { text: '思う', pronunciation: 'おもう' },
    },
    {
        id: '05c39b8f-3c47-4693-bb11-6903ee553776',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Cut',
        pl: 'Ciąć',
        jp: { text: '切る', pronunciation: 'きる' },
    },
    {
        id: '843b27b4-36d5-44ed-9b18-f89103d46f4f',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Make',
        pl: 'Robić',
        jp: { text: '作る', pronunciation: 'つくる' },
    },
    {
        id: 'f1075445-8141-4f41-9e5d-89f7296b9f06',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'intransitive',
        en: 'Fall (rain, snow, ash)',
        pl: 'Padać (o deszczu/śniegu) / Spadać lub opadać (o popiele)',
        jp: { text: '降る', pronunciation: 'ふる' },
    },
    {
        id: '0c456271-8232-41a6-97b9-8003287b31d5',
        type: 'phrase',
        en: "It's raining",
        pl: 'Pada deszcz',
        jp: { text: '雨が降っている', pronunciation: 'あめがふっている' },
    },
    {
        id: 'c37ee90c-77e9-4b08-9f33-2711cfcf6a60',
        type: 'phrase',
        en: 'Take something along',
        pl: 'Brać coś ze sobą',
        jp: { text: '持っていく', pronunciation: 'もっていく' },
    },
    {
        id: 'd2250787-a792-4ea1-ae01-4e3b0830510d',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'transitive',
        en: 'Throw away',
        pl: 'Wyrzucać',
        jp: { text: '捨てる', pronunciation: 'すてる' },
    },
    {
        id: '68ee44c7-502a-4690-ab60-acdccbb505ac',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'transitive',
        en: 'Begin',
        pl: 'Zaczynać',
        jp: { text: '始める', pronunciation: 'はじめる' },
    },
    {
        id: 'e8fdc198-790c-469b-a271-52e71dba1587',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Drive',
        pl: 'Prowadzić',
        jp: { text: '運転する', pronunciation: 'うんてんする' },
    },
    {
        id: 'ae097307-a63e-4c45-980d-cc5dd49ced4a',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Do laundry',
        pl: 'Robić pranie',
        jp: { text: '洗濯する', pronunciation: 'せんたくする' },
    },
    {
        id: '3e6dad0a-59da-436e-a333-b633c38df18d',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Clean',
        pl: 'Sprzątać',
        jp: { text: '掃除する', pronunciation: 'そうじする' },
    },
    {
        id: '6c42e0bb-f65d-41e3-a563-f852aee5a7c3',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Cook',
        pl: 'Gotować',
        jp: { text: '料理する', pronunciation: 'りょうりする' },
    },
    {
        id: '66fe26d1-dec5-4cf8-bfb8-f1f4edd6ddfd',
        type: 'adverb',
        en: 'Always',
        pl: 'Zawsze',
        jp: { text: 'いつも' },
    },
    {
        id: '48c6e3e5-9e6e-4dbd-be4b-cd92954d8eb2',
        type: 'adverb',
        en: 'Late',
        pl: 'Późno',
        jp: { text: '遅く', pronunciation: 'おそく' },
    },
    {
        id: 'f0053b2a-0492-4e52-95aa-e3c8e2a574f0',
        type: 'phrase',
        en: 'Cheers!',
        pl: 'Na zdrowie!',
        jp: { text: '乾杯', pronunciation: 'かんぱい' },
    },
    {
        id: '6b57f877-ea95-437d-b8a4-44070970e267',
        type: 'noun',
        en: 'Everybody',
        pl: 'Wszyscy',
        jp: { text: 'みんな' },
    },
    {
        id: '8f31cb58-57a6-4a6c-bb46-75b395800f42',
        type: 'noun',
        en: 'Degree (angle, temperature)',
        pl: 'Stopień (kąt, temperatura)',
        jp: { text: '度', pronunciation: 'ど' },
    },
    {
        id: 'e725be0b-367c-43d2-9170-eb83e672adad',
        type: 'adverb',
        en: 'How / In what way / How about',
        pl: 'Jak / W jaki sposób / A co z',
        jp: { text: 'どう' },
    },
];

export const genki8Bag: WordBag = {
    id: '51a50aa0-c2b5-42d7-8133-cbc6b7083809',
    name: 'Genki #8',
    category: 'genki',
    words: genki_8,
};
