import type { TranslatedJapaneseText, WordBag } from '../../types';

const genki_6: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Kanji / Chinese character',
        pl: 'Kanji / Chiński znak',
        jp: { text: '漢字', pronunciation: 'かんじ' },
    },
    {
        type: 'noun',
        en: 'Textbook',
        pl: 'Podręcznik',
        jp: { text: '教科書', pronunciation: 'きょうかしょ' },
    },
    {
        type: 'noun',
        en: 'Page',
        pl: 'Strona',
        jp: { text: 'ページ' },
    },
    {
        type: 'noun',
        en: 'Next',
        pl: 'Następny',
        jp: { text: '次', pronunciation: 'つぎ' },
    },
    {
        type: 'noun',
        en: 'Money',
        pl: 'Pieniądze',
        jp: { text: 'お金', pronunciation: 'おかね' },
    },
    {
        type: 'noun',
        en: 'Baggage',
        pl: 'Bagaż',
        jp: { text: '荷物', pronunciation: 'にもつ' },
    },
    {
        type: 'noun',
        en: 'Personal computer',
        pl: 'Komputer osobisty',
        jp: { text: 'パソコン' },
    },
    {
        type: 'noun',
        en: 'Shower',
        pl: 'Prysznic',
        jp: { text: 'シャワー' },
    },
    {
        type: 'noun',
        en: 'Air conditioner',
        pl: 'Klimatyzacja',
        jp: { text: 'エアコン' },
    },
    {
        type: 'noun',
        en: 'Electricity / Electric light',
        pl: 'Elektryczność / Światło elektryczne',
        jp: { text: '電気', pronunciation: 'でんき' },
    },
    {
        type: 'noun',
        en: 'Window',
        pl: 'Okno',
        jp: { text: '窓', pronunciation: 'まど' },
    },
    {
        type: 'noun',
        en: 'Train',
        pl: 'Pociąg',
        jp: { text: '電車', pronunciation: 'でんしゃ' },
    },
    {
        type: 'noun',
        en: 'Country',
        pl: 'Kraj',
        jp: { text: '国', pronunciation: 'くに' },
    },
    {
        type: 'noun',
        en: 'This week',
        pl: 'Ten tydzień',
        jp: { text: '今週', pronunciation: 'こんしゅう' },
    },
    {
        type: 'noun',
        en: 'Next week',
        pl: 'Następny tydzień',
        jp: { text: '来週', pronunciation: 'らいしゅう' },
    },
    {
        type: 'noun',
        en: 'Next year',
        pl: 'Następny rok',
        jp: { text: '来年', pronunciation: 'らいねん' },
    },
    {
        type: 'noun',
        en: 'Night',
        pl: 'Noc',
        jp: { text: '夜', pronunciation: 'よる' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Tough (situation)',
        pl: 'Trudny (sytuacja)',
        jp: { text: '大変', pronunciation: 'たいへん' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Play / Hang out',
        pl: 'Bawić się / Spędzać czas',
        jp: { text: '遊ぶ', pronunciation: 'あそぶ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Hurry',
        pl: 'Spieszyć się',
        jp: { text: '急ぐ', pronunciation: 'いそぐ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Return (a thing)',
        pl: 'Zwracać (rzecz)',
        jp: { text: '返す', pronunciation: 'かえす' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Turn off / Erase',
        pl: 'Wyłączać / Wymazywać',
        jp: { text: '消す', pronunciation: 'けす' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Die',
        pl: 'Umrzeć',
        jp: { text: '死ぬ', pronunciation: 'しぬ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Sit down',
        pl: 'Usiąść',
        jp: { text: '座る', pronunciation: 'すわる' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Stand up',
        pl: 'Wstać',
        jp: { text: '立つ', pronunciation: 'たつ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Smoke',
        pl: 'Palić',
        jp: { text: 'たばこを吸う', pronunciation: 'たばこをすう' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Use',
        pl: 'Używać',
        jp: { text: '使う', pronunciation: 'つかう' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Help',
        pl: 'Pomagać',
        jp: { text: '手伝う', pronunciation: 'てつだう' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Enter',
        pl: 'Wchodzić',
        jp: { text: '入る', pronunciation: 'はいる' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Carry / Hold',
        pl: 'Nosić / Trzymać',
        jp: { text: '持つ', pronunciation: 'もつ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Be absent / Rest',
        pl: 'Być nieobecnym / Odpoczywać',
        jp: { text: '休む', pronunciation: 'やすむ' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Open',
        pl: 'Otwierać',
        jp: { text: '開ける', pronunciation: 'あける' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Close',
        pl: 'Zamykać',
        jp: { text: '閉める', pronunciation: 'しめる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Teach / Instruct',
        pl: 'Uczyć (kogoś)',
        jp: { text: '教える', pronunciation: 'おしえる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Forget / Leave behind',
        pl: 'Zapominać / Zostawiać',
        jp: { text: '忘れる', pronunciation: 'わすれる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get off',
        pl: 'Wysiadać',
        jp: { text: '降りる', pronunciation: 'おりる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Borrow',
        pl: 'Pożyczać (od kogoś)',
        jp: { text: '借りる', pronunciation: 'かりる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Turn on',
        pl: 'Włączać',
        jp: { text: 'つける' },
    },
    {
        type: 'phrase',
        en: 'Take a shower',
        pl: 'Brać prysznic',
        jp: { text: 'シャワーを浴びる', pronunciation: 'シャワーをあびる' },
    },
    {
        type: 'verb',
        verb_type: 'suru',
        en: 'Call',
        pl: 'Dzwonić',
        jp: { text: '電話する', pronunciation: 'でんわする' },
    },
    {
        type: 'adverb',
        en: 'Later / Afterwards',
        pl: 'Później',
        jp: { text: '後で', pronunciation: 'あとで' },
    },
    {
        type: 'adverb',
        en: 'Immediately',
        pl: 'Natychmiast',
        jp: { text: 'すぐ' },
    },
    {
        type: 'adverb',
        en: 'Slowly',
        pl: 'Powoli',
        jp: { text: 'ゆっくり' },
    },
    {
        type: 'phrase',
        en: 'No, thank you.',
        pl: 'Nie, dziękuję.',
        jp: { text: 'いいえ、結構です。', pronunciation: 'いいえ、けっこうです。' },
    },
    {
        type: 'phrase',
        en: 'Really? / Is that so?',
        pl: 'Naprawdę? / Czy tak jest?',
        jp: { text: '本当ですか。', pronunciation: 'ほんとうですか。' },
    },
];

export const genki6Bag: WordBag = {
    id: '25f49248-1f93-46b5-ab53-fc9ee6ef1480',
    name: 'Genki #6',
    words: genki_6,
};
