import type { TranslatedJapaneseText } from '../../types';

export const genki_5: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Food',
        pl: 'Jedzenie',
        jp: { text: '食べ物', pronunciation: 'たべもの' },
    },
    {
        type: 'noun',
        en: 'Drink',
        pl: 'Napój',
        jp: { text: '飲み物', pronunciation: 'のみもの' },
    },
    {
        type: 'noun',
        en: 'Fruit',
        pl: 'Owoc',
        jp: { text: '果物', pronunciation: 'くだもの' },
    },
    {
        type: 'noun',
        en: 'Holiday / Day off / Absence',
        pl: 'Święto / Dzień wolny / Nieobecność',
        jp: { text: '休み', pronunciation: 'やすみ' },
    },
    {
        type: 'noun',
        en: 'Travel',
        pl: 'Podróż',
        jp: { text: '旅行', pronunciation: 'りょこう' },
    },
    {
        type: 'noun',
        en: 'Sea',
        pl: 'Morze',
        jp: { text: '海', pronunciation: 'うみ' },
    },
    {
        type: 'noun',
        en: 'Surfing',
        pl: 'Surfing',
        jp: { text: 'サーフィン' },
    },
    {
        type: 'noun',
        en: 'Souvenir',
        pl: 'Pamiątka',
        jp: { text: 'お土産', pronunciation: 'おみやげ' },
    },
    {
        type: 'noun',
        en: 'Bus',
        pl: 'Autobus',
        jp: { text: 'バス' },
    },
    {
        type: 'noun',
        en: 'Weather',
        pl: 'Pogoda',
        jp: { text: '天気', pronunciation: 'てんき' },
    },
    {
        type: 'noun',
        en: 'Homework',
        pl: 'Praca domowa',
        jp: { text: '宿題', pronunciation: 'しゅくだい' },
    },
    {
        type: 'noun',
        en: 'Test',
        pl: 'Test',
        jp: { text: 'テスト' },
    },
    {
        type: 'noun',
        en: 'Birthday',
        pl: 'Urodziny',
        jp: { text: '誕生日', pronunciation: 'たんじょうび' },
    },
    {
        type: 'noun',
        en: 'Room',
        pl: 'Pokój',
        jp: { text: '部屋', pronunciation: 'へや' },
    },
    {
        type: 'noun',
        en: 'I (used by man)',
        pl: 'Ja (używane przez mężczyznę)',
        jp: { text: '僕', pronunciation: 'ぼく' },
    },
    {
        type: 'noun',
        en: 'Size L',
        pl: 'Rozmiar L',
        jp: { text: 'Lサイズ', pronunciation: 'エルサイズ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'New',
        pl: 'Nowy',
        jp: { text: '新しい', pronunciation: 'あたらしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Old (thing)',
        pl: 'Stary (rzecz)',
        jp: { text: '古い', pronunciation: 'ふるい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Hot (weather)',
        pl: 'Gorący (pogoda)',
        jp: { text: '暑い', pronunciation: 'あつい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cold (weather)',
        pl: 'Zimny (pogoda)',
        jp: { text: '寒い', pronunciation: 'さむい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Hot (thing)',
        pl: 'Gorący (rzecz)',
        jp: { text: '熱い', pronunciation: 'あつい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Busy (people/day)',
        pl: 'Zajęty (ludzie/dzień)',
        jp: { text: '忙しい', pronunciation: 'いそがしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Large',
        pl: 'Duży',
        jp: { text: '大きい', pronunciation: 'おおきい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Small',
        pl: 'Mały',
        jp: { text: '小さい', pronunciation: 'ちいさい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Interesting / Funny',
        pl: 'Interesujący / Zabawny',
        jp: { text: '面白い', pronunciation: 'おもしろい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Boring',
        pl: 'Nudny',
        jp: { text: 'つまらない' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Easy (problem) / Kind (person)',
        pl: 'Łatwy (problem) / Uprzejmy (osoba)',
        jp: { text: 'やさしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Difficult',
        pl: 'Trudny',
        jp: { text: '難しい', pronunciation: 'むずかしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Good-looking / Cool / Stylish',
        pl: 'Przystojny / Fajny / Stylowy',
        jp: { text: 'かっこいい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Scary / Frightening',
        pl: 'Straszny',
        jp: { text: 'こわい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fun / Enjoyable / Happy',
        pl: 'Fajny / Przyjemny / Wesoły',
        jp: { text: '楽しい', pronunciation: 'たのしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cheap',
        pl: 'Tani',
        jp: { text: '安い', pronunciation: 'やすい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Fond of / Liked',
        pl: 'Lubiany',
        jp: { text: '好き', pronunciation: 'すき' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Disliked',
        pl: 'Nielubiany',
        jp: { text: '嫌い', pronunciation: 'きらい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Very fond of / Beloved',
        pl: 'Bardzo lubiany / Ukochany',
        jp: { text: '大好き', pronunciation: 'だいすき' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Hated',
        pl: 'Znienawidzony',
        jp: { text: '大嫌い', pronunciation: 'だいきらい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Beautiful / Clean',
        pl: 'Piękny / Czysty',
        jp: { text: 'きれい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Healthy / Energetic',
        pl: 'Zdrowy / Energiczny',
        jp: { text: '元気', pronunciation: 'げんき' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Quiet',
        pl: 'Cichy',
        jp: { text: '静か', pronunciation: 'しずか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Lively',
        pl: 'Pełen życia / Gwarny',
        jp: { text: '賑やか', pronunciation: 'にぎやか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Not busy / Free (time)',
        pl: 'Nie zajęty / Wolny (czas)',
        jp: { text: '暇', pronunciation: 'ひま' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Swim',
        pl: 'Pływać',
        jp: { text: '泳ぐ', pronunciation: 'およぐ' },
        present: {
            masu: {
                affirmative: { text: '泳ぎます', pronunciation: 'およぎます' },
                negative: { text: '泳ぎません', pronunciation: 'およぎません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Listen / Ask',
        pl: 'Słuchać / Pytać',
        jp: { text: '聞く', pronunciation: 'きく' },
        present: {
            masu: {
                affirmative: { text: '聞きます', pronunciation: 'ききます' },
                negative: { text: '聞きません', pronunciation: 'ききません' },
            },
        },
        description:
            'When using this verb in the meaning of "ask", it is usually followed by に (e.g. 先生に聞きます - I ask the teacher). In the meaning of "listen", it is usually followed by を (e.g. 音楽を聞きます - I listen to music).',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Ride / Board',
        pl: 'Jeździć / Wsiadać',
        jp: { text: '乗る', pronunciation: 'のる' },
        present: {
            masu: {
                affirmative: { text: '乗ります', pronunciation: 'のります' },
                negative: { text: '乗りません', pronunciation: 'のりません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'To do / Perform',
        pl: 'Robić / Wykonywać',
        jp: { text: 'やる' },
        present: {
            masu: {
                affirmative: { text: 'やります' },
                negative: { text: 'やりません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Go out',
        pl: 'Wyjść',
        jp: { text: '出かける', pronunciation: 'でかける' },
        present: {
            masu: {
                affirmative: { text: '出かけます', pronunciation: 'でかけます' },
                negative: { text: '出かけません', pronunciation: 'でかけません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Together',
        pl: 'Razem',
        jp: { text: '一緒', pronunciation: 'いっしょ' },
    },
    {
        type: 'phrase',
        en: 'To go together',
        pl: 'Iść razem',
        jp: { text: '一緒に行く', pronunciation: 'いっしょにいく' },
    },
    {
        type: 'adverb',
        en: 'Extremely (casual)',
        pl: 'Bardzo (nieformalnie)',
        jp: { text: 'すごく' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Fine / OK / Alright',
        pl: 'W porządku / OK / Dobrze',
        jp: { text: '大丈夫', pronunciation: 'だいじょうぶ' },
    },
    {
        type: 'adverb',
        en: 'Very (neutral)',
        pl: 'Bardzo (neutralnie)',
        jp: { text: 'とても' },
    },
    {
        type: 'pre-noun-adjective',
        en: 'What kind of',
        pl: 'Jaki rodzaj',
        jp: { text: 'どんな' },
    },
];
