import type { JapaneseWord } from '../../types.ts';

export const duolingo_7: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Tomorrow',
        pl: 'Jutro',
        jp: { word: 'あした' },
    },
    {
        type: 'unknown',
        en: 'Always',
        pl: 'Zawsze',
        jp: { word: 'いつも' },
    },
    {
        type: 'unknown',
        en: 'Sleep',
        pl: 'Spać',
        jp: { word: 'ねます' },
    },
    {
        type: 'unknown',
        en: 'E-mail',
        pl: 'E-mail',
        jp: { word: 'メール' },
    },
    {
        type: 'unknown',
        en: 'Take a shower',
        pl: 'Wziąć prysznic',
        jp: { word: 'シャワーをあびます' },
    },
    {
        type: 'unknown',
        en: 'Pasta',
        pl: 'Makaron',
        jp: { word: 'パスタ' },
    },
    {
        type: 'unknown',
        en: 'Run',
        pl: 'Biegać',
        jp: { word: 'はしります' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Drink',
        pl: 'Pić',
        jp: { word: '飲む', pronunciation: 'のむ' },
        present: {
            masu: {
                affirmative: { word: '飲みます', pronunciation: 'のみます' },
                negative: { word: '飲みません', pronunciation: 'のみません' },
            },
        },
    },
    {
        type: 'unknown',
        en: 'I will drink green tea next week with my older sister.',
        pl: 'W przyszłym tygodniu wypiję zieloną herbatę z moją starszą siostrą.',
        jp: { word: 'らいしゅう、あねとおちゃを飲みます。', pronunciation: 'らいしゅう、あねとおちゃをのみます。' },
    },
    {
        type: 'unknown',
        en: 'Where do you live?',
        pl: 'Gdzie mieszkasz?',
        jp: { word: 'どこにすんでいますか。' },
    },
    {
        type: 'unknown',
        en: 'I always do yoga at 7:30 AM.',
        pl: 'Zawsze ćwiczę jogę o 7:30 rano.',
        jp: { word: 'いつもごぜんしちじはんにヨガをします。' },
    },
    {
        type: 'unknown',
        en: 'I will eat dinner with my mom tomorrow.',
        pl: 'Jutro zjem obiad z moją mamą.',
        jp: { word: 'あしたははとばんごはんをたべます。' },
    },
    {
        type: 'unknown',
        en: 'Hang out',
        pl: 'Spędzać czas',
        jp: { word: 'あそびます' },
    },
    {
        type: 'unknown',
        en: 'I go to sleep around 22:30 every night.',
        pl: 'Każdej nocy kładę się spać około 22:30.',
        jp: { word: 'まいばんじゅうじはんごろねます。' },
    },
    {
        type: 'unknown',
        en: 'Will you go out next week?',
        pl: 'Czy wyjdziesz w przyszłym tygodniu?',
        jp: { word: 'らいしゅうでかけますか。' },
    },
    {
        type: 'unknown',
        en: 'To go out',
        pl: 'Wyjść',
        jp: { word: 'でかけます' },
    },
    {
        type: 'unknown',
        en: 'Boyfriend',
        pl: 'Chłopak',
        jp: { word: 'かれし' },
    },
    {
        type: 'unknown',
        en: 'My name is John.',
        pl: 'Nazywam się John.',
        jp: { word: 'ジョンと言います。', pronunciation: 'ジョンといいます。' },
    },
    {
        type: 'unknown',
        en: 'Girlfriend',
        pl: 'Dziewczyna',
        jp: { word: 'かのじょ' },
    },
    {
        type: 'unknown',
        en: 'Hobby',
        pl: 'Hobby',
        jp: { word: 'しゅみ' },
    },
    {
        type: 'unknown',
        en: 'Do you have a hobby?',
        pl: 'Czy masz jakieś hobby?',
        jp: { word: 'しゅみがありますか。' },
    },
    {
        type: 'unknown',
        en: 'KPop',
        pl: 'KPop',
        jp: { word: 'Kポップ' },
    },
    {
        type: 'unknown',
        en: 'I like Japanese music.',
        pl: 'Lubię japońską muzykę.',
        jp: { word: 'にほんのおんがくがすきです。' },
    },
    {
        type: 'unknown',
        en: 'Mystery (genre)',
        pl: 'Kryminał (gatunek)',
        jp: { word: 'ミステリー' },
    },
    {
        type: 'unknown',
        en: 'Horror (genre)',
        pl: 'Horror (gatunek)',
        jp: { word: 'ホラー' },
    },
    {
        type: 'unknown',
        en: 'Fantasy (genre)',
        pl: 'Fantastyka (gatunek)',
        jp: { word: 'ファンタジー' },
    },
    {
        type: 'unknown',
        en: 'What kind of pizza do you like?',
        pl: 'Jaki rodzaj pizzy lubisz?',
        jp: { word: 'どんなピザがすきですか。' },
    },
    {
        type: 'unknown',
        en: 'Comedy (genre)',
        pl: 'Komedia (gatunek)',
        jp: { word: 'コメディー' },
    },
    {
        type: 'unknown',
        en: 'Romance (genre)',
        pl: 'Romans (gatunek)',
        jp: { word: 'れんあい' },
    },
    {
        type: 'unknown',
        en: 'Korean drama',
        pl: 'Koreański dramat',
        jp: { word: 'かんこくのドラマ' },
    },
    {
        type: 'unknown',
        en: 'Action (genre)',
        pl: 'Akcja (gatunek)',
        jp: { word: 'アクション' },
    },
    {
        type: 'unknown',
        en: 'Really',
        pl: 'Naprawdę',
        jp: { word: 'ほんとうに' },
    },
    {
        type: 'unknown',
        en: 'This is my boyfriend.',
        pl: 'To jest mój chłopak.',
        jp: { word: 'こちらはわたしのかれしです。' },
    },
    {
        type: 'unknown',
        en: 'House',
        pl: 'Dom',
        jp: { word: 'いえ' },
    },
    {
        type: 'unknown',
        en: "This house is old, isn't it?",
        pl: 'Ten dom jest stary, prawda?',
        jp: { word: 'このいえはふるいですね。' },
    },
    {
        type: 'unknown',
        en: 'Move (to a new house)',
        pl: 'Przeprowadzić się (do nowego domu)',
        jp: { word: 'ひっこします' },
    },
    {
        type: 'unknown',
        en: 'Still',
        pl: 'Wciąż',
        jp: { word: 'まだ' },
    },
    {
        type: 'unknown',
        en: 'Spacious',
        pl: 'Przestronny',
        jp: { word: 'ひろい' },
    },
    {
        type: 'unknown',
        en: 'Kitchen',
        pl: 'Kuchnia',
        jp: { word: 'キッチン' },
    },
    {
        type: 'unknown',
        en: 'Narrow / tight',
        pl: 'Wąski / ciasny',
        jp: { word: 'せまい' },
    },
    {
        type: 'unknown',
        en: 'Living room',
        pl: 'Salon',
        jp: { word: 'リビング' },
    },
    {
        type: 'unknown',
        en: 'Bed',
        pl: 'Łóżko',
        jp: { word: 'ベッド' },
    },
    {
        type: 'unknown',
        en: 'Shower',
        pl: 'Prysznic',
        jp: { word: 'シャワー' },
    },
    {
        type: 'unknown',
        en: 'Bookshelf',
        pl: 'Regał na książki',
        jp: { word: 'ほんだな' },
    },
];
