import type { TranslatedJapaneseText, WordBag } from '../../types.ts';

const duolingo_2: TranslatedJapaneseText[] = [
    {
        type: 'unknown',
        en: 'Here',
        pl: 'Tutaj',
        jp: { text: 'ここ' },
    },
    {
        type: 'unknown',
        en: 'Where',
        pl: 'Gdzie',
        jp: { text: 'どこ' },
    },
    {
        type: 'unknown',
        en: 'Hotel',
        pl: 'Hotel',
        jp: { text: 'ホテル' },
    },
    {
        type: 'unknown',
        en: 'Convenience store',
        pl: 'Sklep spożywczy (mały)',
        jp: { text: 'コンビニ' },
    },
    {
        type: 'unknown',
        en: 'Department store',
        pl: 'Dom towarowy',
        jp: { text: 'デパート' },
    },
    {
        type: 'unknown',
        en: 'Bus stop',
        pl: 'Przystanek autobusowy',
        jp: { text: 'バスてい' },
    },
    {
        type: 'unknown',
        en: 'There',
        pl: 'Tam',
        jp: { text: 'そこ' },
    },
    {
        type: 'unknown',
        en: 'Train station',
        pl: 'Dworzec kolejowy',
        jp: { text: 'えき' },
    },
    {
        type: 'unknown',
        en: 'University',
        pl: 'Uniwersytet',
        jp: { text: 'だいがく' },
    },
    {
        type: 'unknown',
        en: 'I',
        pl: 'Ja',
        jp: { text: '私', pronunciation: 'わたし' },
    },
    {
        type: 'unknown',
        en: 'Hat',
        pl: 'Kapelusz / Czapka',
        jp: { text: 'ぼうし' },
    },
    {
        type: 'unknown',
        en: 'Umbrella',
        pl: 'Parasol',
        jp: { text: 'かさ' },
    },
    {
        type: 'unknown',
        en: 'Shoe',
        pl: 'But',
        jp: { text: 'くつ' },
    },
    {
        type: 'unknown',
        en: 'Coat',
        pl: 'Płaszcz',
        jp: { text: 'コート' },
    },
    {
        type: 'unknown',
        en: 'Red',
        pl: 'Czerwony',
        jp: { text: 'あかい' },
    },
    {
        type: 'unknown',
        en: 'White',
        pl: 'Biały',
        jp: { text: 'しろい' },
    },
    {
        type: 'unknown',
        en: 'Cheerful',
        pl: 'Radosny',
        jp: { text: 'あかるい' },
    },
    {
        type: 'unknown',
        en: 'Funny',
        pl: 'Zabawny',
        jp: { text: 'おもしろい' },
    },
    {
        type: 'unknown',
        en: 'Apple',
        pl: 'Jabłko',
        jp: { text: 'りんご' },
    },
    {
        type: 'unknown',
        en: 'Cute',
        pl: 'Słodki / Uroczy',
        jp: { text: 'かわいい' },
    },
    {
        type: 'unknown',
        en: 'Thank you',
        pl: 'Dziękuję',
        jp: { text: 'ありがとう' },
    },
    {
        type: 'unknown',
        en: 'Thanks',
        pl: 'Dzięki',
        jp: { text: 'どうも' },
    },
    {
        type: 'unknown',
        en: 'Thank you very much',
        pl: 'Bardzo dziękuję',
        jp: { text: 'ありがとうございます' },
    },
    {
        type: 'unknown',
        en: 'Map',
        pl: 'Mapa',
        jp: { text: 'ちず' },
    },
    {
        type: 'unknown',
        en: 'Ticket',
        pl: 'Bilet',
        jp: { text: 'きっぷ' },
    },
    {
        type: 'unknown',
        en: 'Subway',
        pl: 'Metro',
        jp: { text: 'ちかてつ' },
    },
    {
        type: 'unknown',
        en: 'Airport',
        pl: 'Lotnisko',
        jp: { text: 'くうこう' },
    },
    {
        type: 'unknown',
        en: "Isn't",
        pl: 'Nie jest',
        jp: { text: 'じゃないです' },
    },
    {
        type: 'unknown',
        en: 'Is',
        pl: 'Jest',
        jp: { text: 'です' },
    },
    {
        type: 'unknown',
        en: 'Passport',
        pl: 'Paszport',
        jp: { text: 'パスポート' },
    },
    {
        type: 'unknown',
        en: 'Smartphone',
        pl: 'Smartfon',
        jp: { text: 'スマホ' },
    },
    {
        type: 'unknown',
        en: 'Bag',
        pl: 'Torba',
        jp: { text: 'かばん' },
    },
    {
        type: 'unknown',
        en: 'Welcome',
        pl: 'Witam',
        jp: { text: 'ようこそ' },
    },
    {
        type: 'unknown',
        en: 'Comes from ...',
        pl: 'Pochodzi z ...',
        jp: { text: '...しゅっしん' },
    },
    {
        type: 'unknown',
        en: 'What is your origin?',
        pl: 'Skąd pochodzisz?',
        jp: { text: 'しゅっしんはどこですか？' },
    },
    {
        type: 'unknown',
        en: 'Also',
        pl: 'Też',
        jp: { text: 'も' },
    },
    {
        type: 'unknown',
        en: 'Tokyo',
        pl: 'Tokio',
        jp: { text: '東京', pronunciation: 'とうきょう' },
    },
    {
        type: 'unknown',
        en: 'Kyoto',
        pl: 'Kioto',
        jp: { text: '京都', pronunciation: 'きょうと' },
    },
];

export const duolingo2Bag: WordBag = {
    id: '38e00aa9-dc82-4a80-ba40-eb14ddea1a86',
    name: 'Duolingo #2',
    words: duolingo_2,
};
