import type { JapaneseWord } from '../../types.ts';

export const duolingo_7: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Tomorrow',
        pl: 'Jutro',
        jp: 'あした',
    },
    {
        type: 'unknown',
        en: 'Always',
        pl: 'Zawsze',
        jp: 'いつも',
    },
    {
        type: 'unknown',
        en: 'Sleep',
        pl: 'Spać',
        jp: 'ねます',
    },
    {
        type: 'unknown',
        en: 'E-mail',
        pl: 'E-mail',
        jp: 'メール',
    },
    {
        type: 'unknown',
        en: 'Take a shower',
        pl: 'Wziąć prysznic',
        jp: 'シャワーをあびます',
    },
    {
        type: 'unknown',
        en: 'Pasta',
        pl: 'Makaron',
        jp: 'パスタ',
    },
    {
        type: 'unknown',
        en: 'Run',
        pl: 'Biegać',
        jp: 'はしります',
    },
    {
        type: 'unknown',
        en: 'Drink',
        pl: 'Pić',
        jp: '飲みます',
        jp_pronunciation: 'のみます',
    },
    {
        type: 'unknown',
        en: 'I will drink green tea next week with my older sister.',
        pl: 'W przyszłym tygodniu wypiję zieloną herbatę z moją starszą siostrą.',
        jp: 'らいしゅう、あねとおちゃを飲みます。',
        jp_pronunciation: 'らいしゅう、あねとおちゃをのみます。',
    },
    {
        type: 'unknown',
        en: 'Where do you live?',
        pl: 'Gdzie mieszkasz?',
        jp: 'どこにすんでいますか。',
    },
    {
        type: 'unknown',
        en: 'I always do yoga at 7:30 AM.',
        pl: 'Zawsze ćwiczę jogę o 7:30 rano.',
        jp: 'いつもごぜんしちじはんにヨガをします。',
    },
    {
        type: 'unknown',
        en: 'I will eat dinner with my mom tomorrow.',
        pl: 'Jutro zjem obiad z moją mamą.',
        jp: 'あしたははとばんごはんをたべます。',
    },
    {
        type: 'unknown',
        en: 'Hang out',
        pl: 'Spędzać czas',
        jp: 'あそびます',
    },
    {
        type: 'unknown',
        en: 'I go to sleep around 22:30 every night.',
        pl: 'Każdej nocy kładę się spać około 22:30.',
        jp: 'まいばんじゅうじはんごろねます。',
    },
    {
        type: 'unknown',
        en: 'Will you go out next week?',
        pl: 'Czy wyjdziesz w przyszłym tygodniu?',
        jp: 'らいしゅうでかけますか。',
    },
    {
        type: 'unknown',
        en: 'To go out',
        pl: 'Wyjść',
        jp: 'でかけます',
    },
    {
        type: 'unknown',
        en: 'Boyfriend',
        pl: 'Chłopak',
        jp: 'かれし',
    },
    {
        type: 'unknown',
        en: 'My name is John.',
        pl: 'Nazywam się John.',
        jp: 'ジョンと言います。',
        jp_pronunciation: 'ジョンといいます。',
    },
    {
        type: 'unknown',
        en: 'Girlfriend',
        pl: 'Dziewczyna',
        jp: 'かのじょ',
    },
    {
        type: 'unknown',
        en: 'Hobby',
        pl: 'Hobby',
        jp: 'しゅみ',
    },
    {
        type: 'unknown',
        en: 'Do you have a hobby?',
        pl: 'Czy masz jakieś hobby?',
        jp: 'しゅみがありますか。',
    },
    {
        type: 'unknown',
        en: 'KPop',
        pl: 'KPop',
        jp: 'Kポップ',
    },
    {
        type: 'unknown',
        en: 'I like Japanese music.',
        pl: 'Lubię japońską muzykę.',
        jp: 'にほんのおんがくがすきです。',
    },
    {
        type: 'unknown',
        en: 'Mystery (genre)',
        pl: 'Kryminał (gatunek)',
        jp: 'ミステリー',
    },
    {
        type: 'unknown',
        en: 'Horror (genre)',
        pl: 'Horror (gatunek)',
        jp: 'ホラー',
    },
    {
        type: 'unknown',
        en: 'Fantasy (genre)',
        pl: 'Fantastyka (gatunek)',
        jp: 'ファンタジー',
    },
    {
        type: 'unknown',
        en: 'What kind of pizza do you like?',
        pl: 'Jaki rodzaj pizzy lubisz?',
        jp: 'どんなピザがすきですか。',
    },
    {
        type: 'unknown',
        en: 'Comedy (genre)',
        pl: 'Komedia (gatunek)',
        jp: 'コメディー',
    },
    {
        type: 'unknown',
        en: 'Romance (genre)',
        pl: 'Romans (gatunek)',
        jp: 'れんあい',
    },
    {
        type: 'unknown',
        en: 'Korean drama',
        pl: 'Koreański dramat',
        jp: 'かんこくのドラマ',
    },
    {
        type: 'unknown',
        en: 'Action (genre)',
        pl: 'Akcja (gatunek)',
        jp: 'アクション',
    },
    {
        type: 'unknown',
        en: 'Really',
        pl: 'Naprawdę',
        jp: 'ほんとうに',
    },
    {
        type: 'unknown',
        en: 'This is my boyfriend.',
        pl: 'To jest mój chłopak.',
        jp: 'こちらはわたしのかれしです。',
    },
    {
        type: 'unknown',
        en: 'House',
        pl: 'Dom',
        jp: 'いえ',
    },
    {
        type: 'unknown',
        en: "This house is old, isn't it?",
        pl: 'Ten dom jest stary, prawda?',
        jp: 'このいえはふるいですね。',
    },
    {
        type: 'unknown',
        en: 'Move (to a new house)',
        pl: 'Przeprowadzić się (do nowego domu)',
        jp: 'ひっこします',
    },
    {
        type: 'unknown',
        en: 'Still',
        pl: 'Wciąż',
        jp: 'まだ',
    },
    {
        type: 'unknown',
        en: 'Spacious',
        pl: 'Przestronny',
        jp: 'ひろい',
    },
    {
        type: 'unknown',
        en: 'Kitchen',
        pl: 'Kuchnia',
        jp: 'キッチン',
    },
    {
        type: 'unknown',
        en: 'Narrow / tight',
        pl: 'Wąski / ciasny',
        jp: 'せまい',
    },
    {
        type: 'unknown',
        en: 'Living room',
        pl: 'Salon',
        jp: 'リビング',
    },
    {
        type: 'unknown',
        en: 'Bed',
        pl: 'Łóżko',
        jp: 'ベッド',
    },
    {
        type: 'unknown',
        en: 'Shower',
        pl: 'Prysznic',
        jp: 'シャワー',
    },
    {
        type: 'unknown',
        en: 'Bookshelf',
        pl: 'Regał na książki',
        jp: 'ほんだな',
    },
];
