import type { JapaneseWord } from '../../types.ts';

export const duolingo_10: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Seoul',
        pl: 'Seul',
        jp: 'ソウル',
    },
    {
        type: 'noun',
        en: 'After',
        pl: 'Po',
        jp: 'あと',
    },
    {
        type: 'phrase',
        en: 'After rain it is sunny.',
        pl: 'Po deszczu jest słonecznie.',
        jp: 'あめのあとははれです。',
    },
    {
        type: 'phrase',
        en: 'After work I go home.',
        pl: 'Po pracy idę do domu.',
        jp: 'しごとのあとうちにかえります。',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Help',
        pl: 'Pomagać',
        jp: 'てつだう',
        masu_form: 'てつだいます',
        masen_form: 'てつだいません',
    },
    {
        type: 'noun',
        en: 'Cleaning',
        pl: 'Sprzątanie',
        jp: 'そうじ',
    },
    {
        type: 'phrase',
        en: 'To clean',
        pl: 'Sprzątać',
        jp: 'そうじをする',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Various',
        pl: 'Różnorodny',
        jp: 'いろいろ',
    },
    {
        type: 'noun',
        en: 'Laundry',
        pl: 'Pranie',
        jp: 'せんたく',
    },
    {
        type: 'phrase',
        en: 'To do laundry',
        pl: 'Robić pranie',
        jp: 'せんたくをする',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Easy / Simple',
        pl: 'Prosty',
        jp: 'やさしい',
    },
    {
        type: 'noun',
        en: 'Meal / Rice',
        pl: 'Posiłek / Ryż',
        jp: 'ごはん',
    },
    {
        type: 'noun',
        en: 'Bathtub',
        pl: 'Wanna',
        jp: 'おふろ',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Hard / Challenging',
        pl: 'Trudny / Wymagający',
        jp: 'たいへん',
    },
    {
        type: 'phrase',
        en: 'And then / After that (as a result)',
        pl: 'A potem / Następnie (jako rezultat)',
        jp: 'そして',
    },
    {
        type: 'phrase',
        en: "I played games. As a result I didn't do my homework.",
        pl: 'Grałem w gry. W rezultacie nie zrobiłem pracy domowej.',
        jp: 'ゲームをしました。そして、しゅくだいはしませんでした。',
    },
    {
        type: 'noun',
        en: 'Stretching',
        pl: 'Rozciąganie',
        jp: 'ストレッチ',
    },
    {
        type: 'phrase',
        en: 'To stretch',
        pl: 'Rozciągać się',
        jp: 'ストレッチをする',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fun',
        pl: 'Zabawny / Przyjemny',
        jp: 'たのしい',
    },
    {
        type: 'phrase',
        en: 'Day off',
        pl: 'Dzień wolny',
        jp: 'やすみのひ',
    },
    {
        type: 'noun',
        en: 'Gardening',
        pl: 'Ogrodnictwo',
        jp: 'ガーデニング',
    },
    {
        type: 'phrase',
        en: 'To do gardening',
        pl: 'Uprawiać ogród',
        jp: 'ガーデニングをする',
    },
    {
        type: 'phrase',
        en: "Let's go!",
        pl: 'Chodźmy!',
        jp: 'いきましょう！',
    },
    {
        type: 'suffix',
        en: "We should / Let's",
        pl: 'Powinniśmy / Chodźmy',
        jp: 'ましょう',
    },
    {
        type: 'phrase',
        en: 'What should we do?',
        pl: 'Co powinniśmy zrobić?',
        jp: 'なにをしましょうか？',
    },
    {
        type: 'noun',
        en: 'Suitcase',
        pl: 'Walizka',
        jp: 'スーツケース',
    },
    {
        type: 'noun',
        en: 'Plane',
        pl: 'Samolot',
        jp: 'ひこうき',
    },
    {
        type: 'noun',
        en: 'Ticket (plane, concert, etc.)',
        pl: 'Bilet (samolot, koncert, itp.)',
        jp: 'チケット',
    },
    {
        type: 'noun',
        en: 'Art museum',
        pl: 'Muzeum sztuki',
        jp: 'びじゅつかん',
    },
    {
        type: 'noun',
        en: 'Zoo',
        pl: 'Zoo',
        jp: 'どうぶつえん',
    },
    {
        type: 'noun',
        en: 'Plaza',
        pl: 'Rynek',
        jp: 'ひろば',
    },
    {
        type: 'phrase',
        en: 'French kitchen',
        pl: 'Francuska kuchnia',
        jp: 'フランスりょうり',
    },
    {
        type: 'noun',
        en: 'Lobby',
        pl: 'Hol',
        jp: 'ロビー',
    },
    {
        type: 'phrase',
        en: 'Airport lobby',
        pl: 'Hol lotniska',
        jp: 'くうこうのロビー',
    },
    {
        type: 'noun',
        en: 'Sushi restaurant',
        pl: 'Restauracja sushi',
        jp: 'すしや',
    },
    {
        type: 'noun',
        en: 'Seat',
        pl: 'Miejsce siedzące',
        jp: 'せき',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient',
        pl: 'Wygodny / Dogodny',
        jp: 'べんり',
    },
    {
        type: 'noun',
        en: 'Shinkansen',
        pl: 'Shinkansen',
        jp: 'しんかんせん',
    },
    {
        type: 'noun',
        en: 'Castle',
        pl: 'Zamek',
        jp: 'しろ',
    },
    {
        type: 'noun',
        en: 'Garden',
        pl: 'Ogród',
        jp: 'にわ',
    },
    {
        type: 'noun',
        en: 'Tourism / Sightseeing',
        pl: 'Turystyka / Zwiedzanie',
        jp: 'かんこう',
    },
    {
        type: 'phrase',
        en: 'To do sightseeing',
        pl: 'Zwiedzać',
        jp: 'かんこうをする',
    },
    {
        type: 'noun',
        en: 'Pork cutlet in miso sauce',
        pl: 'Kotlet schabowy w sosie miso',
        jp: 'みそかつ',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short',
        pl: 'Krótki',
        jp: 'みじかい',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Wait',
        pl: 'Czekać',
        jp: 'まつ',
        masu_form: 'まちます',
        masen_form: 'まちません',
    },
    {
        type: 'noun',
        en: 'Stuff / Thing',
        pl: 'Rzecz / Przedmiot',
        jp: 'もの',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Sweet',
        pl: 'Słodki',
        jp: 'あまい',
    },
    {
        type: 'noun',
        en: 'Cake shop',
        pl: 'Tortownia',
        jp: 'ケーキや',
    },
    {
        type: 'noun',
        en: 'Pastry shop',
        pl: 'Cukiernia',
        jp: 'おかしや',
    },
    {
        type: 'noun',
        en: 'Cheesecake',
        pl: 'Sernik',
        jp: 'チーズケーキ',
    },
    {
        type: 'noun',
        en: 'Green',
        pl: 'Zielony',
        jp: 'みどり',
        jp_description: 'Japanese does not have an adjective form for "green".',
    },
    {
        type: 'phrase',
        en: 'Green fridge',
        pl: 'Zielona lodówka',
        jp: 'みどりのれいぞうこ',
    },
    {
        type: 'noun',
        en: 'Cupcake',
        pl: 'Babeczka',
        jp: 'カップケーキ',
    },
    {
        type: 'phrase',
        en: 'What kind of place is Kyoto?',
        pl: 'Jaki rodzaj miejsca to Kioto?',
        jp: 'きょうとはどんなところですか。',
    },
    {
        type: 'noun',
        en: 'Cooking / Cuisine / Dish',
        pl: 'Gotowanie / Kuchnia / Danie',
        jp: 'りょうり',
    },
];
