import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_16: TranslatedJapaneseText[] = [
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'A lot of / Many',
        pl: 'Dużo',
        jp: { text: '多い', pronunciation: 'おおい' },
    },
    {
        type: 'phrase',
        en: 'Welcome, how many people is your party?',
        pl: 'Witamy, stolik dla ilu osób?',
        jp: { text: 'いらっしゃいませ、何名様ですか？', pronunciation: 'いらっしゃいませ、なんめいさまですか？' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Stay at',
        pl: 'Zatrzymać się w',
        jp: { text: '泊まる', pronunciation: 'とまる' },
    },
    {
        type: 'phrase',
        en: 'I stayed at a hotel last week.',
        pl: 'Zatrzymałem się w hotelu w zeszłym tygodniu.',
        jp: { text: '先週ホテルに泊まりました。', pronunciation: 'せんしゅうホテルにとまりました。' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Look for / Search for',
        pl: 'Szukać',
        jp: { text: '探す', pronunciation: 'さがす' },
    },
    {
        type: 'phrase',
        en: 'I looked for a place in which to sleep.',
        pl: 'Szukałem miejsca, w którym mógłbym spać.',
        jp: { text: '寝る場所を探しました。', pronunciation: 'ねるばしょをさがしました。' },
    },
    {
        type: 'noun',
        en: 'Number',
        pl: 'Numer',
        jp: { text: '番号', pronunciation: 'ばんごう' },
    },
    {
        type: 'noun',
        en: 'Ice',
        pl: 'Lód',
        jp: { text: '氷', pronunciation: 'こおり' },
    },
    {
        type: 'noun',
        en: 'Room service',
        pl: 'Obsługa hotelowa',
        jp: { text: 'ルームサービス' },
    },
    {
        type: 'noun',
        en: 'Password',
        pl: 'Hasło',
        jp: { text: 'パスワード' },
    },
    {
        type: 'noun',
        en: 'Towel',
        pl: 'Ręcznik',
        jp: { text: 'タオル' },
    },
    {
        type: 'noun',
        en: 'Spa',
        pl: 'Spa',
        jp: { text: 'スパ' },
    },
    {
        type: 'noun',
        en: 'Free',
        pl: 'Darmowy',
        jp: { text: '無料', pronunciation: 'むりょう' },
    },
    {
        type: 'noun',
        en: 'Milk',
        pl: 'Mleko',
        jp: { text: '牛乳', pronunciation: 'ぎゅうにゅう' },
    },
    {
        type: 'noun',
        en: 'Toast',
        pl: 'Tost',
        jp: { text: 'トースト' },
    },
    {
        type: 'noun',
        en: 'Check-out',
        pl: 'Wymeldowanie',
        jp: { text: 'チェックアウト' },
    },
    {
        type: 'particle',
        en: 'Until',
        pl: 'Do',
        jp: { text: 'まで' },
    },
    {
        type: 'noun',
        en: 'Coffee maker',
        pl: 'Ekspres do kawy',
        jp: { text: 'コーヒーメーカー' },
    },
    {
        type: 'noun',
        en: 'Pants',
        pl: 'Spodnie',
        jp: { text: 'ズボン' },
    },
    {
        type: 'noun',
        en: 'Part-time job',
        pl: 'Praca na część etatu',
        jp: { text: 'アルバイト' },
    },
    {
        type: 'noun',
        en: 'Elementary school backpack',
        pl: 'Tornister',
        jp: { text: 'ランドセル' },
    },
    {
        type: 'noun',
        en: 'Green bell pepper',
        pl: 'Zielona papryka',
        jp: { text: 'ピーマン' },
    },
    {
        type: 'noun',
        en: 'Apartment in a block of flats',
        pl: 'Mieszkanie w bloku',
        jp: { text: 'マンション' },
    },
    {
        type: 'noun',
        en: 'Culture',
        pl: 'Kultura',
        jp: { text: '文化', pronunciation: 'ぶんか' },
    },
    {
        type: 'noun',
        en: 'Traditional Japanese theater',
        pl: 'Tradycyjny japoński teatr',
        jp: { text: '歌舞伎', pronunciation: 'かぶき' },
    },
    {
        type: 'noun',
        en: 'Crepe',
        pl: 'Naleśnik',
        jp: { text: 'クレープ' },
    },
    {
        type: 'noun',
        en: 'Start / First',
        pl: 'Początek / Pierwszy',
        jp: { text: '初め', pronunciation: 'はじめ' },
    },
    {
        type: 'phrase',
        en: 'I sang a song for the first time.',
        pl: 'Zaśpiewałem piosenkę po raz pierwszy.',
        jp: { text: '初めて歌を歌いました。', pronunciation: 'はじめてうたをうたいました。' },
    },
    {
        type: 'noun',
        en: 'Peanut',
        pl: 'Orzech ziemny',
        jp: { text: 'ピーナッツ' },
    },
    {
        type: 'noun',
        en: 'Aquarium',
        pl: 'Akwarium',
        jp: { text: '水族館', pronunciation: 'すいぞくかん' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Find / Discover',
        pl: 'Znajdować / Odkrywać',
        jp: { text: '見つける', pronunciation: 'みつける' },
    },
    {
        type: 'noun',
        en: 'Elephant',
        pl: 'Słoń',
        jp: { text: '象', pronunciation: 'ぞう' },
    },
    {
        type: 'noun',
        en: 'Thai language',
        pl: 'Język tajski',
        jp: { text: 'タイ語', pronunciation: 'タイご' },
    },
    {
        type: 'verb',
        verb_type: 'suru',
        en: 'Practice / Exercise',
        pl: 'Ćwiczyć / Trenować',
        jp: { text: '練習をする', pronunciation: 'れんしゅうをする' },
    },
    {
        type: 'noun',
        en: 'Fried chicken',
        pl: 'Smażony kurczak',
        jp: { text: 'フライドチキン' },
    },
    {
        type: 'noun',
        en: 'Road / Path / Street',
        pl: 'Droga / Ścieżka / Ulica',
        jp: { text: '道', pronunciation: 'みち' },
    },
    {
        type: 'noun',
        en: 'Fork',
        pl: 'Widelec',
        jp: { text: 'フォーク' },
    },
    {
        type: 'noun',
        en: 'Knife',
        pl: 'Nóż',
        jp: { text: 'ナイフ' },
    },
    {
        type: 'noun',
        en: 'Cup',
        pl: 'Kubek',
        jp: { text: 'カップ' },
    },
    {
        type: 'noun',
        en: 'Hundred yen shop',
        pl: 'Sklep z rzeczami za 100 jenów',
        jp: { text: '百円ショップ', pronunciation: 'ひゃくえんショップ' },
    },
    {
        type: 'particle',
        en: 'From',
        pl: 'Od',
        jp: { text: 'から' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Cross over / Go across',
        pl: 'Przekroczyć / Przejść przez',
        jp: { text: '渡る', pronunciation: 'わたる' },
    },
    {
        type: 'phrase',
        en: 'How / In what way',
        pl: 'Jak / W jaki sposób',
        jp: { text: 'どうやって' },
    },
    {
        type: 'noun',
        en: 'On the way',
        pl: 'Po drodze',
        jp: { text: '途中', pronunciation: 'とちゅう' },
    },
    {
        type: 'phrase',
        en: 'I will buy milk on the way.',
        pl: 'Kupię mleko po drodze.',
        jp: { text: '途中で牛乳を買います。', pronunciation: 'とちゅうでぎゅうにゅうをかいます。' },
    },
    {
        type: 'noun',
        en: 'Toy',
        pl: 'Zabawka',
        jp: { text: 'おもちゃ' },
    },
    {
        type: 'noun',
        en: 'Headphones',
        pl: 'Słuchawki',
        jp: { text: 'ヘッドホン' },
    },
    {
        type: 'noun',
        en: 'Electric appliance store',
        pl: 'Sklep z elektroniką',
        jp: { text: '電気屋', pronunciation: 'でんきや' },
    },
    {
        type: 'noun',
        en: 'Plate',
        pl: 'Talerz',
        jp: { text: 'お皿', pronunciation: 'おさら' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Walk',
        pl: 'Chodzić',
        jp: { text: '歩く', pronunciation: 'あるく' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Cut',
        pl: 'Kroić / Ciąć',
        jp: { text: '切る', pronunciation: 'きる' },
    },
    {
        type: 'adverb',
        en: 'More',
        pl: 'Bardziej / Więcej',
        jp: { text: 'もっと' },
    },
    {
        type: 'noun',
        en: 'Battery',
        pl: 'Bateria',
        jp: { text: '電池', pronunciation: 'でんち' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Heavy',
        pl: 'Ciężki',
        jp: { text: '重い', pronunciation: 'おもい' },
    },
];

export const duolingo16Bag: WordBag = {
    id: '94dfcccd-aa6d-4bff-a907-8e63ff18a81b',
    name: 'Duolingo #16',
    words: duolingo_16,
};
