import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_6: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Friend',
        pl: 'Przyjaciel',
        jp: { text: 'ともだち' },
    },
    {
        type: 'noun',
        en: 'Family',
        pl: 'Rodzina',
        jp: { text: 'かぞく' },
    },
    {
        type: 'noun',
        en: 'Sports',
        pl: 'Sport',
        jp: { text: 'スポーツ' },
    },
    {
        type: 'phrase',
        en: 'I do sports with my dad.',
        pl: 'Uprawiam sport z moim tatą.',
        jp: { text: '父とスポーツをします。', pronunciation: 'ちちとスポーツをします。' },
    },
    {
        type: 'noun',
        en: 'Karate',
        pl: 'Karate',
        jp: { text: 'からて' },
    },
    {
        type: 'phrase',
        en: 'I play baseball on Saturdays.',
        pl: 'Gram w baseball w soboty.',
        jp: { text: '土曜日にやきゅうをします。', pronunciation: 'どようびにやきゅうをします。' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'To buy',
        pl: 'Kupić',
        jp: { text: '買う', pronunciation: 'かう' },
    },
    {
        type: 'noun',
        en: 'Game',
        pl: 'Gra',
        jp: { text: 'ゲーム' },
    },
    {
        type: 'noun',
        en: 'Tennis',
        pl: 'Tenis',
        jp: { text: 'テニス' },
    },
    {
        type: 'noun',
        en: 'Judo',
        pl: 'Judo',
        jp: { text: 'じゅうどう' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: { text: '話す', pronunciation: 'はなす' },
        te_form: { text: '話して', pronunciation: 'はなして' },
    },
    {
        type: 'noun',
        en: 'Video / Film',
        pl: 'Wideo / Film',
        jp: { text: 'どうが' },
    },
    {
        type: 'pronoun',
        en: 'These',
        pl: 'Te',
        jp: { text: 'これら' },
        description: 'Plural form of これ (this).',
    },
    {
        type: 'phrase',
        en: 'I watch funny videos.',
        pl: 'Oglądam zabawne filmy.',
        jp: { text: 'おもしろいどうがを見ます。', pronunciation: 'おもしろいどうがをみます。' },
    },
    {
        type: 'phrase',
        en: 'I listen to music by myself.',
        pl: 'Słucham muzyki sam.',
        jp: { text: 'ひとりでおんがくをききます。' },
    },
    {
        type: 'noun',
        en: 'Ticket gate',
        pl: 'Brama biletowa',
        jp: { text: 'かいさつ' },
    },
    {
        type: 'pronoun',
        en: 'Over there',
        pl: 'Tam',
        jp: { text: 'あそこ' },
    },
    {
        type: 'noun',
        en: 'ATM',
        pl: 'Bankomat',
        jp: { text: 'ATM', pronunciation: 'エーティーエム' },
    },
    {
        type: 'noun',
        en: 'Second floor',
        pl: 'Drugie piętro',
        jp: { text: 'にかい' },
    },
    {
        type: 'noun',
        en: 'Elevator',
        pl: 'Winda',
        jp: { text: 'エレベーター' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'To have (inanimate)',
        pl: 'Mieć (nieożywione)',
        jp: { text: 'ある' },
    },
    {
        type: 'noun',
        en: 'Platform',
        pl: 'Peron',
        jp: { text: 'ホーム' },
    },
    {
        type: 'noun',
        en: 'First floor',
        pl: 'Pierwsze piętro',
        jp: { text: 'いっかい' },
    },
    {
        type: 'noun',
        en: 'Trash can',
        pl: 'Kosz na śmieci',
        jp: { text: 'ゴミばこ' },
    },
    {
        type: 'noun',
        en: 'Transfer',
        pl: 'Przesiadka',
        jp: { text: 'のりかえ' },
    },
    {
        type: 'noun',
        en: 'Taxi',
        pl: 'Taksówka',
        jp: { text: 'タクシー' },
    },
    {
        type: 'noun',
        en: 'Restroom',
        pl: 'Toaleta (publiczna)',
        jp: { text: 'おてあらい' },
    },
    {
        type: 'noun',
        en: 'Underground',
        pl: 'Podziemny / Poziom podziemny',
        jp: { text: 'ちか' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Far',
        pl: 'Daleki',
        jp: { text: 'とおい' },
    },
    {
        type: 'noun',
        en: 'Phone',
        pl: 'Telefon',
        jp: { text: 'でんわ' },
    },
    {
        type: 'noun',
        en: 'Stairs',
        pl: 'Schody',
        jp: { text: 'かいだん' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Close',
        pl: 'Bliski',
        jp: { text: 'ちかい' },
    },
    {
        type: 'noun',
        en: 'Cafe',
        pl: 'Kawiarnia',
        jp: { text: 'カフェ' },
    },
    {
        type: 'noun',
        en: 'Exit',
        pl: 'Wyjście',
        jp: { text: 'でぐち' },
    },
    {
        type: 'noun',
        en: 'Vending machine',
        pl: 'Automat z napojami',
        jp: { text: 'じはんき' },
    },
    {
        type: 'noun',
        en: 'Coin locker',
        pl: 'Szafka na monety',
        jp: { text: 'コインロッカー' },
    },
    {
        type: 'noun',
        en: 'Radio',
        pl: 'Radio',
        jp: { text: 'ラジオ' },
    },
    {
        type: 'noun',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: { text: '新聞', pronunciation: 'しんぶん' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get up',
        pl: 'Wstać',
        jp: { text: '起きる', pronunciation: 'おきる' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Eat',
        pl: 'Jeść',
        jp: { text: '食べる', pronunciation: 'たべる' },
    },
    {
        type: 'adverb',
        en: 'Always',
        pl: 'Zawsze',
        jp: { text: 'いつも' },
    },
    {
        type: 'noun',
        en: 'Volleyball',
        pl: 'Siatkówka',
        jp: { text: 'バレーボール' },
    },
    {
        type: 'noun',
        en: 'Every week',
        pl: 'Co tydzień',
        jp: { text: 'まいしゅう' },
    },
    {
        type: 'suffix',
        en: 'Around',
        pl: 'Około',
        jp: { text: 'ごろ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Make',
        pl: 'Robić',
        jp: { text: '作る', pronunciation: 'つくる' },
    },
    {
        type: 'noun',
        en: 'Next week',
        pl: 'W przyszłym tygodniu',
        jp: { text: 'らいしゅう' },
    },
];

export const duolingo6Bag: WordBag = {
    id: '7202e479-2fd1-4df3-9d73-47704f77919d',
    name: 'Duolingo #6',
    words: duolingo_6,
};
