import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_15: TranslatedJapaneseText[] = [
    {
        type: 'conjunction',
        en: 'And then / After that',
        pl: 'A potem / Po tym',
        jp: { text: 'それから' },
    },
    {
        type: 'noun',
        en: 'Hamster',
        pl: 'Chomik',
        jp: { text: 'ハムスター' },
    },
    {
        type: 'noun',
        en: 'Pancake',
        pl: 'Pankejk',
        jp: { text: 'パンケーキ' },
    },
    {
        type: 'phrase',
        en: 'There is one white cat.',
        pl: 'Tam jest jeden biały kot.',
        jp: { text: '白い猫が一匹います。', pronunciation: 'しろいねこがいっぴきいます。' },
    },
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: { text: '犬', pronunciation: 'いぬ' },
    },
    {
        type: 'noun',
        en: 'Ear',
        pl: 'Ucho',
        jp: { text: '耳', pronunciation: 'みみ' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Play / Have fun / Enjoy',
        pl: 'Bawić się / Cieszyć się',
        jp: { text: '遊ぶ', pronunciation: 'あそぶ' },
    },
    {
        type: 'noun',
        en: 'Tomato',
        pl: 'Pomidor',
        jp: { text: 'トマト' },
    },
    {
        type: 'noun',
        en: 'Mouth',
        pl: 'Usta',
        jp: { text: '口', pronunciation: 'くち' },
    },
    {
        type: 'noun',
        en: 'Room',
        pl: 'Pokój',
        jp: { text: '部屋', pronunciation: 'へや' },
    },
    {
        type: 'noun',
        en: 'Nose',
        pl: 'Nos',
        jp: { text: '鼻', pronunciation: 'はな' },
    },
    {
        type: 'noun',
        en: 'Chameleon',
        pl: 'Kameleon',
        jp: { text: 'カメレオン' },
    },
    {
        type: 'phrase',
        en: 'There are two colorful chameleons.',
        pl: 'Tam są dwa kolorowe kameleony.',
        jp: { text: 'カラフルなカメレオンが二匹います。', pronunciation: 'カラフルなカメレオンがにひきいます。' },
    },
    {
        type: 'noun',
        en: 'Corner',
        pl: 'Narożnik / Kąt',
        jp: { text: '隅', pronunciation: 'すみ' },
    },
    {
        type: 'noun',
        en: 'Tomato salad',
        pl: 'Sałatka pomidorowa',
        jp: { text: 'トマトサラダ' },
    },
    {
        type: 'noun',
        en: 'Cat cafe',
        pl: 'Kocia kawiarnia',
        jp: { text: '猫カフェ', pronunciation: 'ねこカフェ' },
    },
    {
        type: 'noun',
        en: 'Backpack',
        pl: 'Plecak',
        jp: { text: 'バックパック' },
    },
    {
        type: 'noun',
        en: 'Hiking',
        pl: 'Wędrówka',
        jp: { text: 'ハイキング' },
    },
    {
        type: 'noun',
        en: 'Camping',
        pl: 'Kemping',
        jp: { text: 'キャンプ' },
    },
    {
        type: 'phrase',
        en: 'When is good for you?',
        pl: 'Kiedy ci pasuje?',
        jp: { text: 'いつがいいですか。' },
    },
    {
        type: 'phrase',
        en: 'Which day of the week is good for you?',
        pl: 'Który dzień tygodnia ci pasuje?',
        jp: { text: '何曜日がいいですか。', pronunciation: 'なんようびがいいですか。' },
    },
    {
        type: 'noun',
        en: 'Picnic',
        pl: 'Piknik',
        jp: { text: 'ピクニック' },
    },
    {
        type: 'noun',
        en: 'Barbecue',
        pl: 'Grill',
        jp: { text: 'バーベキュー' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Early',
        pl: 'Wczesny',
        jp: { text: '早い', pronunciation: 'はやい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dark',
        pl: 'Ciemny',
        jp: { text: '暗い', pronunciation: 'くらい' },
    },
    {
        type: 'noun',
        en: 'River',
        pl: 'Rzeka',
        jp: { text: '川', pronunciation: 'かわ' },
    },
    {
        type: 'noun',
        en: 'Views/ Scenery / Landscape',
        pl: 'Widoki / Krajobraz',
        jp: { text: '景色', pronunciation: 'けしき' },
    },
    {
        type: 'noun',
        en: 'Outdoor / Outside',
        pl: 'Na zewnątrz',
        jp: { text: '外', pronunciation: 'そと' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Enjoy / Take pleasure in',
        pl: 'Cieszyć się',
        jp: { text: '楽しむ', pronunciation: 'たのしむ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cool / Refreshing',
        pl: 'Chłodny / Rześki',
        jp: { text: 'すずしい' },
    },
    {
        type: 'noun',
        en: 'Beef',
        pl: 'Wołowina',
        jp: { text: '牛肉', pronunciation: 'ぎゅうにく' },
    },
    {
        type: 'noun',
        en: 'Pepper',
        pl: 'Pieprz',
        jp: { text: 'こしょう' },
    },
    {
        type: 'noun',
        en: 'Sea food',
        pl: 'Owoce morza',
        jp: { text: 'シーフード' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Grill',
        pl: 'Grillować',
        jp: { text: '焼く', pronunciation: 'やく' },
    },
    {
        type: 'phrase',
        en: 'It will probably rain tomorrow.',
        pl: 'Prawdopodobnie jutro będzie padać.',
        jp: { text: '明日は多分雨です。', pronunciation: 'あしたはたぶんあめです。' },
    },
    {
        type: 'verb',
        verb_type: 'suru',
        en: 'Have a picnic',
        pl: 'Mieć piknik',
        jp: { text: 'ピクニックをする' },
    },
    {
        type: 'verb',
        verb_type: 'suru',
        en: 'Have a barbecue',
        pl: 'Mieć grilla',
        jp: { text: 'バーベキューをする' },
    },
    {
        type: 'noun',
        en: 'Chinatown',
        pl: 'Chinatown',
        jp: { text: '中華街', pronunciation: 'ちゅうかがい' },
    },
    {
        type: 'noun',
        en: 'Chinese food',
        pl: 'Chińszczyzna (jedzenie)',
        jp: { text: '中華料理', pronunciation: 'ちゅうかりょうり' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Open (doors, business)',
        pl: 'Otwierać się (drzwi, biznes)',
        jp: { text: '開く', pronunciation: 'あく' },
    },
    {
        type: 'noun',
        en: 'Bubble tea',
        pl: 'Bubble tea',
        jp: { text: 'タピオカティー' },
    },
    {
        type: 'noun',
        en: 'Menu',
        pl: 'Menu',
        jp: { text: 'メニュー' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cold (thing)',
        pl: 'Zimny (rzecz)',
        jp: { text: '冷たい', pronunciation: 'つめたい' },
    },
    {
        type: 'phrase',
        en: 'Welcome!',
        pl: 'Witamy!',
        jp: { text: 'いらっしゃいませ' },
    },
    {
        type: 'noun',
        en: 'Oolong tea',
        pl: 'Herbata oolong',
        jp: { text: 'ウーロン茶', pronunciation: 'ウーロンちゃ' },
    },
    {
        type: 'noun',
        en: 'Sichuan mapo tofu',
        pl: 'Syczuańskie mapo tofu',
        jp: { text: 'マーボー豆腐', pronunciation: 'マーボーどうふ' },
    },
    {
        type: 'noun',
        en: 'Soup',
        pl: 'Zupa',
        jp: { text: 'スープ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Spicy',
        pl: 'Ostry',
        jp: { text: '辛い', pronunciation: 'からい' },
    },
    {
        type: 'noun',
        en: 'Napkin',
        pl: 'Serwetka',
        jp: { text: 'ナプキン' },
    },
    {
        type: 'noun',
        en: 'Chopsticks',
        pl: 'Pałeczki',
        jp: { text: '箸', pronunciation: 'はし' },
    },
    {
        type: 'noun',
        en: 'Waiter / Employee of a store',
        pl: 'Kelner / Obsługa sklepu',
        jp: { text: '店員', pronunciation: 'てんいん' },
    },
    {
        type: 'noun',
        en: 'Fried rice with shrimp',
        pl: 'Smażony ryż z krewetkami',
        jp: { text: 'えびチャーハン' },
    },
    {
        type: 'noun',
        en: 'Shrimp',
        pl: 'Krewetka',
        jp: { text: 'えび' },
    },
    {
        type: 'noun',
        en: 'Fried dumplings',
        pl: 'Smażone pierożki',
        jp: { text: '餃子', pronunciation: 'ぎょうざ' },
    },
    {
        type: 'noun',
        en: 'Change',
        pl: 'Reszta',
        jp: { text: 'お釣り', pronunciation: 'おつり' },
    },
    {
        type: 'noun',
        en: 'All / Entire / Whole',
        pl: 'Całość / Wszystko',
        jp: { text: '全部', pronunciation: 'ぜんぶ' },
    },
    {
        type: 'phrase',
        en: 'It will be 10 yen in total.',
        pl: 'To będzie 10 jenów razem.',
        jp: { text: '全部で十円です。', pronunciation: 'ぜんぶでじゅうえんです。' },
    },
    {
        type: 'noun',
        en: 'Bill / Check',
        pl: 'Rachunek',
        jp: { text: '会計', pronunciation: 'かいけい' },
    },
];

export const duolingo15Bag: WordBag = {
    id: '42bab80c-fbce-481a-8eb9-e4184d3db13c',
    name: 'Duolingo #15',
    words: duolingo_15,
};
