import type { JapaneseWord } from '../../types.ts';

export const duolingo_12: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Entrance',
        pl: 'Wejście',
        jp: '入口',
        jp_pronunciation: 'いりぐち',
    },
    {
        type: 'noun',
        en: 'Entrance fee',
        pl: 'Opłata za wstęp',
        jp: '入場料',
        jp_pronunciation: 'にゅうじょうりょう',
    },
    {
        type: 'noun',
        en: 'Kid ticket',
        pl: 'Bilet dla dziecka',
        jp: 'こどものチケット',
    },
    {
        type: 'noun',
        en: 'Adult',
        pl: 'Dorosły',
        jp: '大人',
        jp_pronunciation: 'おとな',
    },
    {
        type: 'noun',
        en: 'Adult ticket',
        pl: 'Bilet dla dorosłego',
        jp: '大人のチケット',
        jp_pronunciation: 'おとなのチケット',
    },
    {
        type: 'noun',
        en: 'Tonight / This evening',
        pl: 'Dziś w nocy / Dziś wieczorem',
        jp: '今晩',
        jp_pronunciation: 'こんばん',
    },
    {
        type: 'noun',
        en: 'Go-karts',
        pl: 'Gokarty',
        jp: 'ゴーカート',
    },
    {
        type: 'noun',
        en: 'Attraction',
        pl: 'Atrakcja',
        jp: 'アトラクション',
    },
    {
        type: 'noun',
        en: 'Rollercoaster',
        pl: 'Rollercoaster',
        jp: 'ジェットコースター',
    },
    {
        type: 'phrase',
        en: 'Ride the rollercoaster',
        pl: 'Jechać na rollercoasterze',
        jp: 'ジェットコースターにのる',
    },
    {
        type: 'phrase',
        en: 'Ride the go-karts',
        pl: 'Jechać na gokartach',
        jp: 'ゴーカートにのる',
    },
    {
        type: 'phrase',
        en: 'What are you looking forward to?',
        pl: 'Czego nie możesz się doczekać?',
        jp: '何がたのしみですか。',
        jp_pronunciation: 'なにがたのしみですか。',
    },
    {
        type: 'noun',
        en: 'Bookstore',
        pl: 'Księgarnia',
        jp: '本屋',
        jp_pronunciation: 'ほんや',
    },
    {
        type: 'noun',
        en: 'Sale',
        pl: 'Wyprzedaż',
        jp: 'セール',
    },
    {
        type: 'noun',
        en: 'CD',
        pl: 'Płyta CD',
        jp: 'CD',
        jp_pronunciation: 'シーディー',
    },
    {
        type: 'noun',
        en: 'DVD',
        pl: 'Płyta DVD',
        jp: 'DVD',
        jp_pronunciation: 'ディーブイディー',
    },
    {
        type: 'noun',
        en: 'Section (in a store)',
        pl: 'Sekcja (w sklepie)',
        jp: 'コーナー',
    },
    {
        type: 'noun',
        en: 'Fiction (genre)',
        pl: 'Fikcja (gatunek)',
        jp: 'フィクション',
    },
    {
        type: 'noun',
        en: 'Nonfiction (genre)',
        pl: 'Literatura faktu (gatunek)',
        jp: 'ノンフィクション',
    },
    {
        type: 'noun',
        en: 'Story',
        pl: 'Opowieść',
        jp: '話',
        jp_pronunciation: 'はなし',
    },
    {
        type: 'noun',
        en: 'Album',
        pl: 'Album',
        jp: 'アルバム',
    },
    {
        type: 'noun',
        en: 'Band',
        pl: 'Zespół',
        jp: 'バンド',
    },
    {
        type: 'noun',
        en: 'Anime music (genre)',
        pl: 'Muzyka anime (gatunek)',
        jp: 'アニソン',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Difficult',
        pl: 'Trudny',
        jp: 'むずかしい',
    },
    {
        type: 'noun',
        en: 'Pop music (genre)',
        pl: 'Muzyka pop (gatunek)',
        jp: 'ポップス',
    },
    {
        type: 'noun',
        en: 'Card game',
        pl: 'Gra karciana',
        jp: 'カードゲーム',
    },
    {
        type: 'noun',
        en: 'Science fiction',
        pl: 'Fantastyka naukowa',
        jp: 'SF',
        jp_pronunciation: 'エスエフ',
    },
    {
        type: 'noun',
        en: 'Jigsaw puzzle',
        pl: 'Puzzle',
        jp: 'パズル',
    },
    {
        type: 'noun',
        en: 'Actor',
        pl: 'Aktor',
        jp: '俳優',
        jp_pronunciation: 'はいゆう',
    },
    {
        type: 'noun',
        en: 'Poster',
        pl: 'Plakat',
        jp: 'ポスター',
    },
    {
        type: 'noun',
        en: 'Documentary',
        pl: 'Film dokumentalny',
        jp: 'ドキュメンタリー',
    },
    {
        type: 'noun',
        en: 'Floor',
        pl: 'Piętro',
        jp: '階',
        jp_pronunciation: 'かい',
    },
    {
        type: 'noun',
        en: 'Reception',
        pl: 'Recepcja',
        jp: 'うけつけ',
    },
    {
        type: 'noun',
        en: 'Meeting (at work)',
        pl: 'Spotkanie (w pracy)',
        jp: 'ミーティング',
    },
    {
        type: 'noun',
        en: 'Printer',
        pl: 'Drukarka',
        jp: 'プリンター',
    },
    {
        type: 'noun',
        en: 'Training / Practice',
        pl: 'Szkolenie / Ćwiczenia',
        jp: 'トレーニング',
    },
    {
        type: 'noun',
        en: 'Dining room / Cafeteria',
        pl: 'Jadalnia / Stołówka',
        jp: '食堂',
        jp_pronunciation: 'しょくどう',
    },
    {
        type: 'noun',
        en: 'Lunch break',
        pl: 'Przerwa na lunch',
        jp: 'ひる休み',
        jp_pronunciation: 'ひるやすみ',
    },
    {
        type: 'noun',
        en: 'Fried rice',
        pl: 'Smażony ryż',
        jp: 'チャーハン',
    },
    {
        type: 'noun',
        en: 'French fries',
        pl: 'Frytki',
        jp: 'フライドポテト',
    },
    {
        type: 'noun',
        en: 'PC',
        pl: 'PC',
        jp: 'パソコン',
    },
    {
        type: 'noun',
        en: 'Presentation',
        pl: 'Prezentacja',
        jp: 'プレゼン',
    },
    {
        type: 'noun',
        en: 'Client',
        pl: 'Klient',
        jp: 'クライアント',
    },
];
