import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_14: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Present',
        pl: 'Prezent',
        jp: { text: 'プレゼント' },
    },
    {
        type: 'noun',
        en: 'Suit',
        pl: 'Garnitur',
        jp: { text: 'スーツ' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Wear',
        pl: 'Nosić',
        jp: { text: '着る', pronunciation: 'きる' },
        present: {
            masu: {
                affirmative: { text: '着ます', pronunciation: 'きます' },
                negative: { text: '着ません', pronunciation: 'きません' },
            },
        },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'White',
        pl: 'Biały',
        jp: { text: '白い', pronunciation: 'しろい' },
    },
    {
        type: 'noun',
        en: 'Blouse',
        pl: 'Bluzka',
        jp: { text: 'ブラウス' },
    },
    {
        type: 'noun',
        en: 'Movie theater',
        pl: 'Kino',
        jp: { text: '映画館', pronunciation: 'えいがかん' },
    },
    {
        type: 'noun',
        en: 'Director',
        pl: 'Reżyser',
        jp: { text: '監督', pronunciation: 'かんとく' },
    },
    {
        type: 'noun',
        en: 'Hot dog',
        pl: 'Hot dog',
        jp: { text: 'ホットドッグ' },
    },
    {
        type: 'noun',
        en: 'Popcorn',
        pl: 'Popcorn',
        jp: { text: 'ポップコーン' },
    },
    {
        type: 'phrase',
        en: 'Reserve',
        pl: 'Rezerwować',
        jp: { text: '予約する', pronunciation: 'よやくする' },
    },
    {
        type: 'phrase',
        en: 'I will reserve a movie ticket.',
        pl: 'Zarezerwuję bilet na film.',
        jp: { text: '映画のチケットを予約します。', pronunciation: 'えいがのチケットをよやくします。' },
    },
    {
        type: 'noun',
        en: 'Wine',
        pl: 'Wino',
        jp: { text: 'ワイン' },
    },
    {
        type: 'noun',
        en: 'Steak',
        pl: 'Stek',
        jp: { text: 'ステーキ' },
    },
    {
        type: 'noun',
        en: 'Song',
        pl: 'Piosenka',
        jp: { text: '歌', pronunciation: 'うた' },
    },
    {
        type: 'phrase',
        en: 'I will sing a birthday song.',
        pl: 'Zaśpiewam piosenkę urodzinową.',
        jp: { text: '誕生日の歌を歌います。', pronunciation: 'たんじょうびのうたをうたいます。' },
    },
    {
        type: 'noun',
        en: 'Ticket window / Box office',
        pl: 'Okienko biletowe / Kasa biletowa',
        jp: { text: '切符売り場', pronunciation: 'きっぷうりば' },
    },
    {
        type: 'noun',
        en: 'Monorail',
        pl: 'Kolejka jednoszynowa',
        jp: { text: 'モノレール' },
    },
    {
        type: 'noun',
        en: 'Platform number one',
        pl: 'Peron numer jeden',
        jp: { text: '一番ホーム', pronunciation: 'いちばんホーム' },
    },
    {
        type: 'noun',
        en: 'Orange',
        pl: 'Pomarańcza',
        jp: { text: 'オレンジ' },
    },
    {
        type: 'noun',
        en: 'High speed / Rapid',
        pl: 'Wysoka prędkość / Pospieszny',
        jp: { text: '快速', pronunciation: 'かいそく' },
    },
    {
        type: 'noun',
        en: 'Rapid train',
        pl: 'Szybki pociąg',
        jp: { text: '快速電車', pronunciation: 'かいそくでんしゃ' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get off',
        pl: 'Wysiadać',
        jp: { text: '降りる', pronunciation: 'おりる' },
        present: {
            masu: {
                affirmative: { text: '降ります', pronunciation: 'おります' },
                negative: { text: '降りません', pronunciation: 'おりません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I will get off at the next station.',
        pl: 'Wysiądę na następnym przystanku.',
        jp: { text: '次の駅で降ります。', pronunciation: 'つぎのえきでおります。' },
    },
    {
        type: 'phrase',
        en: 'I will get off the train.',
        pl: 'Wysiądę z pociągu.',
        jp: { text: '電車を降ります。', pronunciation: 'でんしゃをおります。' },
    },
    {
        type: 'noun',
        en: 'North exit',
        pl: 'Wyjście północne',
        jp: { text: '北口', pronunciation: 'きたぐち' },
    },
    {
        type: 'noun',
        en: 'Escalator',
        pl: 'Schody ruchome',
        jp: { text: 'エスカレーター' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Transfer',
        pl: 'Przesiadać się',
        jp: { text: '乗り換える', pronunciation: 'のりかえる' },
        present: {
            masu: {
                affirmative: { text: '乗り換えます', pronunciation: 'のりかえます' },
                negative: { text: '乗り換えません', pronunciation: 'のりかえません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Tour',
        pl: 'Wycieczka',
        jp: { text: 'ツアー' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Pay',
        pl: 'Płacić',
        jp: { text: '払う', pronunciation: 'はらう' },
        present: {
            masu: {
                affirmative: { text: '払います', pronunciation: 'はらいます' },
                negative: { text: '払いません', pronunciation: 'はらいません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Information desk',
        pl: 'Punkt informacyjny',
        jp: { text: 'インフォメーション' },
    },
    {
        type: 'noun',
        en: 'Drink',
        pl: 'Napój',
        jp: { text: '飲み物', pronunciation: 'のみもの' },
    },
    {
        type: 'noun',
        en: 'South exit',
        pl: 'Wyjście południowe',
        jp: { text: '南口', pronunciation: 'みなみぐち' },
    },
    {
        type: 'phrase',
        en: 'Relax',
        pl: 'Relaksować się',
        jp: { text: 'ゆっくりする' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Call / Invite / Summon',
        pl: 'Wołać / Zapraszać / Przywoływać',
        jp: { text: '呼ぶ', pronunciation: 'よぶ' },
        present: {
            masu: {
                affirmative: { text: '呼びます', pronunciation: 'よびます' },
                negative: { text: '呼びません', pronunciation: 'よびません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I will call a taxi at the north exit.',
        pl: 'Zadzwonię po taksówkę przy wyjściu północnym.',
        jp: { text: '北口でタクシーを呼びます。', pronunciation: 'きたぐちでタクシーをよびます。' },
    },
    {
        type: 'phrase',
        en: 'Which bus do I take?',
        pl: 'Którym autobusem mam jechać?',
        jp: { text: 'どのバスに乗りますか。', pronunciation: 'どのバスにのりますか。' },
    },
    {
        type: 'noun',
        en: 'First year student',
        pl: 'Student pierwszego roku',
        jp: { text: '一年生', pronunciation: 'いちねんせい' },
    },
    {
        type: 'noun',
        en: 'Second year student',
        pl: 'Student drugiego roku',
        jp: { text: '二年生', pronunciation: 'にねんせい' },
    },
    {
        type: 'noun',
        en: 'Third year student',
        pl: 'Student trzeciego roku',
        jp: { text: '三年生', pronunciation: 'さんねんせい' },
    },
    {
        type: 'noun',
        en: 'Fourth year student',
        pl: 'Student czwartego roku',
        jp: { text: '四年生', pronunciation: 'よねんせい' },
    },
    {
        type: 'phrase',
        en: 'Which year student are you?',
        pl: 'Studentem którego roku jesteś?',
        jp: { text: '何年生ですか。', pronunciation: 'なんねんせいですか。' },
    },
    {
        type: 'noun',
        en: 'University major',
        pl: 'Kierunek studiów',
        jp: { text: '専攻', pronunciation: 'せんこう' },
    },
    {
        type: 'noun',
        en: 'Mathematics',
        pl: 'Matematyka',
        jp: { text: '数学', pronunciation: 'すうがく' },
    },
    {
        type: 'noun',
        en: 'Business',
        pl: 'Biznes',
        jp: { text: 'ビジネス' },
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: { text: 'ドイツ' },
    },
    {
        type: 'noun',
        en: 'Language',
        pl: 'Język',
        jp: { text: '言語', pronunciation: 'げんご' },
    },
    {
        type: 'noun',
        en: 'Philippines',
        pl: 'Filipiny',
        jp: { text: 'フィリピン' },
    },
    {
        type: 'phrase',
        en: 'Which languages do you know?',
        pl: 'Jakie języki znasz?',
        jp: { text: 'どの言語ができますか。', pronunciation: 'どのげんごができますか。' },
    },
    {
        type: 'noun',
        en: 'Dormitory',
        pl: 'Akademik',
        jp: { text: '寮', pronunciation: 'りょう' },
    },
    {
        type: 'noun',
        en: 'Campus',
        pl: 'Kampus',
        jp: { text: 'キャンパス' },
    },
    {
        type: 'phrase',
        en: 'Tokyo station is near my dormitory.',
        pl: 'Stacja Tokyo jest blisko mojego akademika.',
        jp: { text: '東京駅は私の寮の近くです。', pronunciation: 'とうきょうえきはわたしのりょうのちかくです。' },
    },
    {
        type: 'noun',
        en: 'Roommate',
        pl: 'Współlokator / Współlokatorka',
        jp: { text: 'ルームメート' },
    },
    {
        type: 'noun',
        pl: 'Koło zainteresowań',
        en: 'Club (university) / Circle of interest',
        jp: { text: 'サークル' },
    },
    {
        type: 'noun',
        en: 'Board game',
        pl: 'Gra planszowa',
        jp: { text: 'ボードゲーム' },
    },
    {
        type: 'noun',
        en: 'Volunteer',
        pl: 'Wolontariusz / Wolontariuszka',
        jp: { text: 'ボランティア' },
    },
    {
        type: 'noun',
        en: 'Chess',
        pl: 'Szachy',
        jp: { text: 'チェス' },
    },
    {
        type: 'verb',
        en: 'Enter / Come in / Join',
        pl: 'Wejść / Dołączyć',
        verb_type: 'godan',
        jp: { text: '入る', pronunciation: 'はいる' },
        present: {
            masu: {
                affirmative: { text: '入ります', pronunciation: 'はいります' },
                negative: { text: '入りません', pronunciation: 'はいりません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I will join the chess club.',
        pl: 'Dołączę do klubu szachowego.',
        jp: { text: 'チェスサークルに入ります。', pronunciation: 'チェスサークルにはいります。' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Speak / Talk',
        pl: 'Mówić / Rozmawiać',
        jp: { text: '話す', pronunciation: 'はなす' },
        present: {
            masu: {
                affirmative: { text: '話します', pronunciation: 'はなします' },
                negative: { text: '話しません', pronunciation: 'はなしません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I speak German with my roommate.',
        pl: 'Mówię po niemiecku z moim współlokatorem.',
        jp: { text: 'ルームメートとドイツ語を話します。', pronunciation: 'ルームメートとドイツごをはなします。' },
    },
    {
        type: 'noun',
        en: 'Animal',
        pl: 'Zwierzę',
        jp: { text: '動物', pronunciation: 'どうぶつ' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Popular',
        pl: 'Popularny',
        jp: { text: '人気', pronunciation: 'にんき' },
    },
    {
        type: 'noun',
        en: 'Cappuccino',
        pl: 'Cappuccino',
        jp: { text: 'カプチーノ' },
    },
    {
        type: 'noun',
        en: 'Brown color',
        pl: 'Brąz / Kolor brązowy',
        jp: { text: '茶色', pronunciation: 'ちゃいろ' },
    },
    {
        type: 'noun',
        en: 'Eyes',
        pl: 'Oczy',
        jp: { text: '目', pronunciation: 'め' },
    },
];

export const duolingo14Bag: WordBag = {
    id: '74409eaa-ba40-4c46-a889-05e2b3ad3194',
    name: 'Duolingo #14',
    words: duolingo_14,
};
