import type { TranslatedJapaneseText, WordBag } from '../../types.ts';

const duolingo_1: TranslatedJapaneseText[] = [
    {
        type: 'unknown',
        en: 'Rice',
        pl: 'Ryż',
        jp: { text: 'ごはん' },
    },
    {
        type: 'unknown',
        en: 'Water',
        pl: 'Woda',
        jp: { text: 'みず' },
    },
    {
        type: 'unknown',
        en: 'Sushi',
        pl: 'Sushi',
        jp: { text: 'すし' },
    },
    {
        type: 'unknown',
        en: 'Please',
        pl: 'Proszę',
        jp: { text: 'ください' },
    },
    {
        type: 'unknown',
        en: 'And',
        pl: 'I / Oraz',
        jp: { text: 'と' },
    },
    {
        type: 'unknown',
        en: 'Tea',
        pl: 'Herbata',
        jp: { text: 'おちゃ' },
    },
    {
        type: 'unknown',
        en: 'Is',
        pl: 'Jest',
        jp: { text: 'です' },
    },
    {
        type: 'unknown',
        en: 'Doctor',
        pl: 'Lekarz',
        jp: { text: 'いしゃ' },
    },
    {
        type: 'unknown',
        en: 'Teacher',
        pl: 'Nauczyciel',
        jp: { text: 'せんせい' },
    },
    {
        type: 'unknown',
        en: 'Cool',
        pl: 'Fajny',
        jp: { text: 'かっこいい' },
    },
    {
        type: 'unknown',
        en: 'Lawyer',
        pl: 'Prawnik',
        jp: { text: 'べんごし' },
    },
    {
        type: 'unknown',
        en: 'Nice',
        pl: 'Miły',
        jp: { text: 'やさしい' },
    },
    {
        type: 'unknown',
        en: 'Person',
        pl: 'Osoba',
        jp: { text: 'ひと' },
    },
    {
        type: 'unknown',
        en: 'Student',
        pl: 'Uczeń',
        jp: { text: 'がくせい' },
    },
    {
        type: 'unknown',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: { text: 'こんにちは' },
    },
    {
        type: 'unknown',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: { text: 'おはようございます' },
        description: "Polite form of 'Good morning'. Casual form is just おはよう.",
    },
    {
        type: 'unknown',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: { text: 'こんばんは' },
    },
    {
        type: 'unknown',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: { text: 'おやすみなさい' },
        description: "Polite form of 'Good night'. Casual form is just おやすみ.",
    },
    {
        type: 'unknown',
        en: 'Goodbye',
        pl: 'Do widzenia',
        jp: { text: 'さようなら' },
    },
    {
        type: 'unknown',
        en: 'Mr. / Ms.',
        pl: 'Pan / Pani',
        jp: { text: 'さん' },
        description: 'Polite suffix added to names.',
    },
    {
        type: 'unknown',
        en: 'Nice to get to know you',
        pl: 'Miło cię poznać',
        jp: { text: 'どうぞよろしく' },
        description:
            "Used when meeting someone for the first time or at the end of a self-introduction. Literally means 'Please treat me well'.",
    },
    {
        type: 'unknown',
        en: 'See you tomorrow',
        pl: 'Do zobaczenia jutro',
        jp: { text: 'またあした' },
    },
    {
        type: 'unknown',
        en: 'This (close to speaker)',
        pl: 'To (blisko mówiącego)',
        jp: { text: 'これ' },
    },
    {
        type: 'unknown',
        en: 'That (close to listener)',
        pl: 'To (blisko słuchającego)',
        jp: { text: 'それ' },
    },
    {
        type: 'unknown',
        en: 'Ramen',
        pl: 'Ramen',
        jp: { text: 'ラーメン' },
    },
    {
        type: 'unknown',
        en: 'Curry',
        pl: 'Curry',
        jp: { text: 'カレー' },
    },
    {
        type: 'unknown',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: { text: 'おいしい' },
    },
    {
        type: 'unknown',
        en: 'Pizza',
        pl: 'Pizza',
        jp: { text: 'ピザ' },
    },
    {
        type: 'unknown',
        en: 'Cake',
        pl: 'Ciasto',
        jp: { text: 'ケーキ' },
    },
    {
        type: 'unknown',
        en: 'Yes',
        pl: 'Tak',
        jp: { text: 'はい' },
    },
    {
        type: 'unknown',
        en: 'No',
        pl: 'Nie',
        jp: { text: 'いいえ' },
    },
    {
        type: 'unknown',
        en: 'Citizen (suffix)',
        pl: 'Obywatel (przyrostek)',
        jp: { text: 'じん' },
        description: 'Suffix added to country names to indicate citizenship.',
    },
    {
        type: 'unknown',
        en: 'Small',
        pl: 'Mały',
        jp: { text: 'ちいさい' },
    },
    {
        type: 'unknown',
        en: 'Sorry',
        pl: 'Przepraszam',
        jp: { text: 'すみません' },
    },
];

export const duolingo1Bag: WordBag = {
    id: '72d4f2a1-6963-497e-85a6-b6c2458da116',
    name: 'Duolingo #1',
    words: duolingo_1,
};
