import type { TranslatedJapaneseText, WordBag } from '../../types.ts';

const duolingo_13: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Chocolate Mint',
        pl: 'Czekolada miętowa',
        jp: { text: 'チョコミント' },
    },
    {
        type: 'noun',
        en: 'Bar',
        pl: 'Bar',
        jp: { text: 'バー' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Sing',
        pl: 'Śpiewać',
        jp: { text: '歌う', pronunciation: 'うたう' },
        present: {
            masu: {
                affirmative: { text: '歌います', pronunciation: 'うたいます' },
                negative: { text: '歌いません', pronunciation: 'うたいません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Karaoke',
        pl: 'Karaoke',
        jp: { text: 'カラオケ' },
    },
    {
        type: 'noun',
        en: 'After this',
        pl: 'Po tym',
        jp: { text: 'この後', pronunciation: 'このあと' },
    },
    {
        type: 'pre-noun-adjective',
        en: 'Which one',
        pl: 'Który',
        jp: { text: 'どの' },
    },
    {
        type: 'noun',
        en: 'Last',
        pl: 'Ostatni',
        jp: { text: '最後', pronunciation: 'さいご' },
    },
    {
        type: 'phrase',
        en: 'Last presentation',
        pl: 'Ostatnia prezentacja',
        jp: { text: '最後のプレゼン', pronunciation: 'さいごのプレゼン' },
    },
    {
        type: 'phrase',
        en: "Tomorrow's training",
        pl: 'Jutrzejszy trening',
        jp: { text: '明日のトレーニング', pronunciation: 'あしたのトレーニング' },
    },
    {
        type: 'phrase',
        en: 'Sing at karaoke',
        pl: 'Śpiewać w karaoke',
        jp: { text: 'カラオケで歌う', pronunciation: 'カラオケでうたう' },
    },
    {
        type: 'noun',
        en: 'Badminton',
        pl: 'Badminton',
        jp: { text: 'バドミントン' },
    },
    {
        type: 'noun',
        en: 'Match / Game',
        pl: 'Mecz',
        jp: { text: '試合', pronunciation: 'しあい' },
    },
    {
        type: 'noun',
        en: 'Practice',
        pl: 'Trening',
        jp: { text: '練習', pronunciation: 'れんしゅう' },
    },
    {
        type: 'noun',
        en: 'Piano',
        pl: 'Pianino',
        jp: { text: 'ピアノ' },
    },
    {
        type: 'noun',
        en: 'Musical instrument',
        pl: 'Instrument muzyczny',
        jp: { text: '楽器', pronunciation: 'がっき' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: { text: '弾く', pronunciation: 'ひく' },
        present: {
            masu: {
                affirmative: { text: '弾きます', pronunciation: 'ひきます' },
                negative: { text: '弾きません', pronunciation: 'ひきません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Kanji',
        pl: 'Kanji',
        jp: { text: '漢字', pronunciation: 'かんじ' },
    },
    {
        type: 'noun',
        en: 'Tonight',
        pl: 'Dziś w nocy',
        jp: { text: '今夜', pronunciation: 'こんや' },
    },
    {
        type: 'noun',
        en: 'Ballet',
        pl: 'Balet',
        jp: { text: 'バレエ' },
    },
    {
        type: 'noun',
        en: 'Performance',
        pl: 'Występ',
        jp: { text: 'パフォーマンス' },
    },
    {
        type: 'noun',
        en: 'Lesson',
        pl: 'Lekcja',
        jp: { text: 'レッスン' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Dance',
        pl: 'Tańczyć',
        jp: { text: '踊る', pronunciation: 'おどる' },
        present: {
            masu: {
                affirmative: { text: '踊ります', pronunciation: 'おどります' },
                negative: { text: '踊りません', pronunciation: 'おどりません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Begin',
        pl: 'Zaczynać się',
        jp: { text: '始まる', pronunciation: 'はじまる' },
        present: {
            masu: {
                affirmative: { text: '始まります', pronunciation: 'はじまります' },
                negative: { text: '始まりません', pronunciation: 'はじまりません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Write',
        pl: 'Pisać',
        jp: { text: '書く', pronunciation: 'かく' },
        present: {
            masu: {
                affirmative: { text: '書きます', pronunciation: 'かきます' },
                negative: { text: '書きません', pronunciation: 'かきません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Make',
        pl: 'Robić',
        jp: { text: '作る', pronunciation: 'つくる' },
        present: {
            masu: {
                affirmative: { text: '作ります', pronunciation: 'つくります' },
                negative: { text: '作りません', pronunciation: 'つくりません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Blog',
        pl: 'Blog',
        jp: { text: 'ブログ' },
    },
    {
        type: 'noun',
        en: 'Article',
        pl: 'Artykuł',
        jp: { text: '記事', pronunciation: 'きじ' },
    },
    {
        type: 'noun',
        en: 'Fashion',
        pl: 'Moda',
        jp: { text: 'ファッション' },
    },
    {
        type: 'phrase',
        en: 'Speak English',
        pl: 'Mówić po angielsku',
        jp: { text: '英語を話す', pronunciation: 'えいごをはなす' },
    },
    {
        type: 'noun',
        en: 'Fireworks display',
        pl: 'Pokaz fajerwerków',
        jp: { text: '花火大会', pronunciation: 'はなびたいかい' },
    },
    {
        type: 'phrase',
        en: 'There is a fireworks display tonight.',
        pl: 'Dziś w nocy jest pokaz fajerwerków.',
        jp: { text: '今夜花火大会があります。', pronunciation: 'こんやはなびたいかいがあります。' },
    },
    {
        type: 'noun',
        en: 'Food',
        pl: 'Jedzenie',
        jp: { text: '食べ物', pronunciation: 'たべもの' },
    },
    {
        type: 'noun',
        en: 'Festival / Celebration',
        pl: 'Festiwal / Święto',
        jp: { text: 'お祭り', pronunciation: 'おまつり' },
    },
    {
        type: 'noun',
        en: 'Chocolate banana',
        pl: 'Banan w czekoladzie',
        jp: { text: 'チョコバナナ' },
    },
    {
        type: 'noun',
        en: 'Dance',
        pl: 'Taniec',
        jp: { text: 'ダンス' },
    },
    {
        type: 'noun',
        en: 'Contest',
        pl: 'Konkurs',
        jp: { text: 'コンテスト' },
    },
    {
        type: 'noun',
        en: 'Community center',
        pl: 'Dom kultury',
        jp: { text: 'コミュニティセンター' },
    },
    {
        type: 'noun',
        en: 'Nearby',
        pl: 'W pobliżu',
        jp: { text: '近く', pronunciation: 'ちかく' },
    },
    {
        type: 'noun',
        en: 'Taiko drums',
        pl: 'Bębny taiko',
        jp: { text: '太鼓', pronunciation: 'たいこ' },
    },
    {
        type: 'noun',
        en: 'Party',
        pl: 'Impreza',
        jp: { text: 'パーティー' },
    },
    {
        type: 'noun',
        en: 'Halloween',
        pl: 'Halloween',
        jp: { text: 'ハロウィン' },
    },
    {
        type: 'noun',
        en: 'Parade',
        pl: 'Parada',
        jp: { text: 'パレード' },
    },
    {
        type: 'noun',
        en: "New Year's Eve",
        pl: 'Sylwester',
        jp: { text: '大晦日', pronunciation: 'おおみそか' },
    },
    {
        type: 'noun',
        en: 'Countdown',
        pl: 'Odliczanie',
        jp: { text: 'カウントダウン' },
    },
    {
        type: 'noun',
        en: 'Illumination',
        pl: 'Iluminacja',
        jp: { text: 'イルミネーション' },
    },
    {
        type: 'phrase',
        en: 'Would you like to go to a party on Christmas?',
        pl: 'Czy chciałbyś pójść na imprezę w święta?',
        jp: { text: 'クリスマスにパーティーに行きませんか。', pronunciation: 'クリスマスにパーティーにいきませんか。' },
    },
    {
        type: 'noun',
        en: 'Person',
        pl: 'Osoba',
        jp: { text: '人', pronunciation: 'ひと' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Full of energy',
        pl: 'Pełen energii',
        jp: { text: '元気', pronunciation: 'げんき' },
    },
    {
        type: 'noun',
        en: 'Birthday',
        pl: 'Urodziny',
        jp: { text: '誕生日', pronunciation: 'たんじょうび' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Nice / Kind',
        pl: 'Miły / Uprzejmy',
        jp: { text: '優しい', pronunciation: 'やさしい' },
    },
    {
        type: 'noun',
        en: 'Date',
        pl: 'Randka',
        jp: { text: 'デート' },
    },
    {
        type: 'noun',
        en: 'Wrist watch',
        pl: 'Zegarek na rękę',
        jp: { text: '腕時計', pronunciation: 'うでどけい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Blue',
        pl: 'Niebieski',
        jp: { text: '青い', pronunciation: 'あおい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Stylish / Fashionable',
        pl: 'Stylowy / Modny',
        jp: { text: 'おしゃれ' },
    },
    {
        type: 'noun',
        en: 'Necklace',
        pl: 'Naszyjnik',
        jp: { text: 'ネックレス' },
    },
];

export const duolingo13Bag: WordBag = {
    id: '73cdffd6-fae2-4ff1-ab71-7f879d73bd16',
    name: 'Duolingo #13',
    words: duolingo_13,
};
