import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_10: TranslatedJapaneseText[] = [
    {
        id: '4bbc524e-571b-449e-80a9-c16b4c0fd5a6',
        type: 'noun',
        en: 'Seoul',
        pl: 'Seul',
        jp: { text: 'ソウル' },
    },
    {
        id: 'a6a9c89c-c8a2-45dd-b1dc-c6bdb7b0a792',
        type: 'noun',
        en: 'After',
        pl: 'Po',
        jp: { text: '後', pronunciation: 'あと' },
    },
    {
        id: 'ac58be7c-bcb9-4ac6-9a0c-307c00232978',
        type: 'phrase',
        formality: 'formal',
        en: 'After rain it is sunny.',
        pl: 'Po deszczu jest słonecznie.',
        jp: { text: '雨の後は晴れです。', pronunciation: 'あめのあとははれです。' },
    },
    {
        id: '1340aa43-94cd-466c-a31e-9bf7ec5337fb',
        type: 'phrase',
        formality: 'formal',
        en: 'After work I return home.',
        pl: 'Po pracy wracam do domu.',
        jp: { text: '仕事の後、家に帰ります。', pronunciation: 'しごとのあと、うちにかえります。' },
    },
    {
        id: '4c07bb5e-e977-47cb-a10c-25f30f4426af',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'transitive',
        en: 'Help',
        pl: 'Pomagać',
        jp: { text: '手伝う', pronunciation: 'てつだう' },
    },
    {
        id: 'c22f1640-0e89-4f0d-8ca6-d273d058e665',
        type: 'noun',
        en: 'Cleaning',
        pl: 'Sprzątanie',
        jp: { text: '掃除', pronunciation: 'そうじ' },
    },
    {
        id: 'd3d6a094-0f7b-4c1b-8060-a4ceaf4ea262',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Clean',
        pl: 'Sprzątać',
        jp: { text: '掃除をする', pronunciation: 'そうじをする' },
    },
    {
        id: 'fd015ae9-0e09-486f-bc3a-5f8e91df02fb',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Various',
        pl: 'Różnorodny',
        jp: { text: '色々', pronunciation: 'いろいろ' },
    },
    {
        id: 'b77e04be-b1b8-4829-82ff-7b1186e9b36c',
        type: 'noun',
        en: 'Laundry',
        pl: 'Pranie',
        jp: { text: '洗濯', pronunciation: 'せんたく' },
    },
    {
        id: '11ba7de1-97a2-4046-84dc-3f828acafb24',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Do laundry',
        pl: 'Robić pranie',
        jp: { text: '洗濯をする', pronunciation: 'せんたくをする' },
    },
    {
        id: '822b0122-e6e3-49c0-8302-0220f791f35f',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Easy / Simple',
        pl: 'Prosty',
        jp: { text: 'やさしい' },
    },
    {
        id: 'b8eddae8-7cbf-48b4-907b-4b8ffe52a4db',
        type: 'noun',
        en: 'Meal / Rice',
        pl: 'Posiłek / Ryż',
        jp: { text: 'ご飯', pronunciation: 'ごはん' },
    },
    {
        id: 'bf750a20-0831-4ba7-b768-f85c0c363020',
        type: 'noun',
        en: 'Bathtub',
        pl: 'Wanna',
        jp: { text: 'お風呂', pronunciation: 'おふろ' },
    },
    {
        id: '1e038ee9-495d-4409-a1c1-6f14e84df1fe',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Hard / Challenging',
        pl: 'Trudny / Wymagający',
        jp: { text: '大変', pronunciation: 'たいへん' },
    },
    {
        id: 'a7910aa0-d466-4a7e-a22e-a3d68986031a',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'And then / After that',
        pl: 'A potem / Następnie',
        jp: { text: 'そして' },
    },
    {
        id: 'b226149a-e311-4f8b-9346-1bc01e6a6230',
        type: 'phrase',
        formality: 'formal',
        en: "I played games. Then I didn't do my homework.",
        pl: 'Grałem w gry. Potem nie zrobiłem pracy domowej.',
        jp: { text: 'ゲームをしました。そして、宿題はしませんでした。', pronunciation: 'ゲームをしました。そして、しゅくだいはしませんでした。' },
    },
    {
        id: '41777389-6941-4df7-bd3b-b68eee3396f7',
        type: 'noun',
        en: 'Stretching',
        pl: 'Rozciąganie',
        jp: { text: 'ストレッチ' },
    },
    {
        id: '12fb4f40-5e9e-481b-8c8e-b5e4d063c173',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'unspecified',
        en: 'Stretch',
        pl: 'Rozciągać się',
        jp: { text: 'ストレッチをする' },
    },
    {
        id: 'b82de295-6862-4f34-8fd5-32baa0f382ff',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fun',
        pl: 'Zabawny / Przyjemny',
        jp: { text: '楽しい', pronunciation: 'たのしい' },
    },
    {
        id: '320edec6-08eb-4dcc-bef9-38835c5836ad',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Day off',
        pl: 'Dzień wolny',
        jp: { text: '休みの日', pronunciation: 'やすみのひ' },
    },
    {
        id: '369212d9-b9dc-48c6-ba85-e62bfbb65b92',
        type: 'noun',
        en: 'Gardening',
        pl: 'Ogrodnictwo',
        jp: { text: 'ガーデニング' },
    },
    {
        id: '6d07c0c7-1eda-4a10-9c70-30604bfdc46a',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'unspecified',
        en: 'Do gardening',
        pl: 'Uprawiać ogród',
        jp: { text: 'ガーデニングをする' },
    },
    {
        id: 'e7da340a-ede7-49f1-8938-165e1df2736b',
        type: 'phrase',
        formality: 'formal',
        en: "Let's go!",
        pl: 'Chodźmy!',
        jp: { text: '行きましょう！', pronunciation: 'いきましょう！' },
    },
    {
        id: 'c9d46212-6002-4879-acef-2b02d8508543',
        type: 'suffix',
        en: "We should / Let's",
        pl: 'Powinniśmy / Chodźmy',
        jp: { text: 'ましょう' },
    },
    {
        id: 'f7566aa8-bedd-43f1-9033-761a385c4447',
        type: 'phrase',
        formality: 'formal',
        en: 'What should we do?',
        pl: 'Co powinniśmy zrobić?',
        jp: { text: '何をしましょうか？', pronunciation: 'なにをしましょうか？' },
    },
    {
        id: 'e03ba2fd-c669-4ff9-a2c1-7bc8690f97a9',
        type: 'noun',
        en: 'Suitcase',
        pl: 'Walizka',
        jp: { text: 'スーツケース' },
    },
    {
        id: '0bca6684-53a6-4483-ab92-d679872be5c8',
        type: 'noun',
        en: 'Plane',
        pl: 'Samolot',
        jp: { text: '飛行機', pronunciation: 'ひこうき' },
    },
    {
        id: '006e6f33-66cb-4d50-bd23-dcd8d309ed37',
        type: 'noun',
        en: 'Ticket (for plane, concert, etc.)',
        pl: 'Bilet (na samolot, koncert, itp.)',
        jp: { text: 'チケット' },
    },
    {
        id: '6238a4a8-dfa7-40af-b0de-5143cd6ce082',
        type: 'noun',
        en: 'Art museum',
        pl: 'Muzeum sztuki',
        jp: { text: '美術館', pronunciation: 'びじゅつかん' },
    },
    {
        id: '5a20babc-31f3-41d5-a435-c46fa3ab406f',
        type: 'noun',
        en: 'Zoo',
        pl: 'Zoo',
        jp: { text: '動物園', pronunciation: 'どうぶつえん' },
    },
    {
        id: 'd25dffbb-3dbb-4091-a720-711810de24ae',
        type: 'noun',
        en: 'Plaza',
        pl: 'Rynek',
        jp: { text: '広場', pronunciation: 'ひろば' },
    },
    {
        id: 'd8032190-ea68-4b6f-8bde-75e58a93526d',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'French cuisine',
        pl: 'Francuska kuchnia',
        jp: { text: 'フランス料理', pronunciation: 'フランスりょうり' },
    },
    {
        id: '43fcfff3-bef5-4560-b809-6db691169aaa',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Italian dish',
        pl: 'Włoskie danie',
        jp: { text: 'イタリアの料理', pronunciation: 'イタリアのりょうり' },
    },
    {
        id: '48b58ec6-61ad-4f17-a9c1-bb2099f0aef2',
        type: 'noun',
        en: 'Lobby',
        pl: 'Hol',
        jp: { text: 'ロビー' },
    },
    {
        id: 'a48f8ffc-0e41-4a0d-bf4d-52df685c11a1',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Airport lobby',
        pl: 'Hol lotniska',
        jp: { text: '空港のロビー', pronunciation: 'くうこうのロビー' },
    },
    {
        id: '23dbe047-91b3-43d6-8665-23a43ee60ab3',
        type: 'noun',
        en: 'Sushi restaurant',
        pl: 'Restauracja sushi',
        jp: { text: '寿司屋', pronunciation: 'すしや' },
    },
    {
        id: '76a1aa5d-e846-4a38-8f54-72314d0d2815',
        type: 'noun',
        en: 'Seat',
        pl: 'Miejsce siedzące',
        jp: { text: '席', pronunciation: 'せき' },
    },
    {
        id: '4164ca56-6740-468b-87ad-a2ebeed93777',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient / Useful',
        pl: 'Wygodny / Dogodny',
        jp: { text: '便利', pronunciation: 'べんり' },
    },
    {
        id: '48d838a0-0a65-4e91-80a7-cbff15b8c03b',
        type: 'noun',
        en: 'Shinkansen',
        pl: 'Shinkansen',
        jp: { text: '新幹線', pronunciation: 'しんかんせん' },
    },
    {
        id: 'b797fd3c-ca30-4090-a219-be669776fab2',
        type: 'noun',
        en: 'Castle',
        pl: 'Zamek',
        jp: { text: '城', pronunciation: 'しろ' },
    },
    {
        id: 'e7a58d7b-dbc2-4f0b-bf13-f83c37f19c34',
        type: 'noun',
        en: 'Garden',
        pl: 'Ogród',
        jp: { text: '庭', pronunciation: 'にわ' },
    },
    {
        id: 'cfc1603a-4dcd-4bac-8998-63c859b1865b',
        type: 'noun',
        en: 'Tourism / Sightseeing',
        pl: 'Turystyka / Zwiedzanie',
        jp: { text: '観光', pronunciation: 'かんこう' },
    },
    {
        id: '3a48d686-2a98-4173-b8cc-b25685cbe70a',
        type: 'verb',
        verb_type: 'suru',
        transitivity: 'transitive',
        en: 'Do sightseeing',
        pl: 'Zwiedzać',
        jp: { text: '観光をする', pronunciation: 'かんこうをする' },
    },
    {
        id: '079b114e-1de3-4e8b-ad79-892020de4a41',
        type: 'noun',
        en: 'Pork cutlet in miso sauce',
        pl: 'Kotlet schabowy w sosie miso',
        jp: { text: 'みそかつ' },
    },
    {
        id: '692d75a2-118c-48f3-ab21-c80630c9bcf8',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short',
        pl: 'Krótki',
        jp: { text: '短い', pronunciation: 'みじかい' },
    },
    {
        id: 'c7bd0896-bb7c-4d57-ae53-d70a5b8ccdac',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'ambitransitive',
        en: 'Wait',
        pl: 'Czekać',
        jp: { text: 'まつ' },
    },
    {
        id: '4cdb52a7-4d11-40af-b3b4-6a90c8c18a3c',
        type: 'noun',
        en: 'Stuff / Thing',
        pl: 'Rzecz / Przedmiot',
        jp: { text: 'もの' },
    },
    {
        id: 'bcf5ab36-e973-4f1c-8e57-d52d432db94b',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Sweet',
        pl: 'Słodki',
        jp: { text: '甘い', pronunciation: 'あまい' },
    },
    {
        id: '8d036cb9-fe07-45a0-8fcf-2215d9762c43',
        type: 'noun',
        en: 'Cake shop',
        pl: 'Tortownia',
        jp: { text: 'ケーキや' },
    },
    {
        id: '2aec633b-cede-482b-8b8a-07f58a026e5f',
        type: 'noun',
        en: 'Pastry shop',
        pl: 'Cukiernia',
        jp: { text: 'お菓子屋', pronunciation: 'おかしや' },
    },
    {
        id: 'dc204627-0663-4bce-be89-69c59ff44103',
        type: 'noun',
        en: 'Cheesecake',
        pl: 'Sernik',
        jp: { text: 'チーズケーキ' },
    },
    {
        id: 'feef9c6d-42ee-4604-ae24-08100b33b236',
        type: 'noun',
        en: 'Green',
        pl: 'Zielony',
        jp: { text: '緑', pronunciation: 'みどり' },
        description: 'Japanese does not have an adjective form for "green".',
    },
    {
        id: '5dc04509-be55-4d4e-8fbc-16e99d4fe93f',
        type: 'phrase',
        formality: 'does-not-apply',
        en: 'Green fridge',
        pl: 'Zielona lodówka',
        jp: { text: '緑の冷蔵庫', pronunciation: 'みどりのれいぞうこ' },
    },
    {
        id: '5f9a4401-b56e-442e-b02a-5b2540731170',
        type: 'noun',
        en: 'Cupcake',
        pl: 'Babeczka',
        jp: { text: 'カップケーキ' },
    },
    {
        id: '42c3b024-d18e-476e-b0af-9e9e3b057eff',
        type: 'phrase',
        formality: 'formal',
        en: 'What kind of place is Kyoto?',
        pl: 'Jaki rodzaj miejsca to Kioto?',
        jp: { text: '京都はどんなところですか。', pronunciation: 'きょうとはどんなところですか。' },
    },
    {
        id: '49bd8a67-3b90-4741-be31-33a0df15a44c',
        type: 'noun',
        en: 'Cooking / Cuisine / Dish',
        pl: 'Gotowanie / Kuchnia / Danie',
        jp: { text: '料理', pronunciation: 'りょうり' },
    },
];

export const duolingo10Bag: WordBag = {
    id: '585cb618-ae76-48b7-ba02-e7aa0b4b206d',
    name: 'Duolingo #10',
    category: 'duolingo',
    words: duolingo_10,
};
