import type { TranslatedJapaneseText, WordBag } from '../../types.ts';

const duolingo_10: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Seoul',
        pl: 'Seul',
        jp: { text: 'ソウル' },
    },
    {
        type: 'noun',
        en: 'After',
        pl: 'Po',
        jp: { text: 'あと' },
    },
    {
        type: 'phrase',
        en: 'After rain it is sunny.',
        pl: 'Po deszczu jest słonecznie.',
        jp: { text: 'あめのあとははれです。' },
    },
    {
        type: 'phrase',
        en: 'After work I return home.',
        pl: 'Po pracy wracam do domu.',
        jp: { text: 'しごとのあとうちにかえります。' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Help',
        pl: 'Pomagać',
        jp: { text: 'てつだう' },
        present: {
            masu: {
                affirmative: { text: 'てつだいます' },
                negative: { text: 'てつだいません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Cleaning',
        pl: 'Sprzątanie',
        jp: { text: 'そうじ' },
    },
    {
        type: 'phrase',
        en: 'To clean',
        pl: 'Sprzątać',
        jp: { text: 'そうじをする' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Various',
        pl: 'Różnorodny',
        jp: { text: 'いろいろ' },
    },
    {
        type: 'noun',
        en: 'Laundry',
        pl: 'Pranie',
        jp: { text: 'せんたく' },
    },
    {
        type: 'phrase',
        en: 'To do laundry',
        pl: 'Robić pranie',
        jp: { text: 'せんたくをする' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Easy / Simple',
        pl: 'Prosty',
        jp: { text: 'やさしい' },
    },
    {
        type: 'noun',
        en: 'Meal / Rice',
        pl: 'Posiłek / Ryż',
        jp: { text: 'ごはん' },
    },
    {
        type: 'noun',
        en: 'Bathtub',
        pl: 'Wanna',
        jp: { text: 'おふろ' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Hard / Challenging',
        pl: 'Trudny / Wymagający',
        jp: { text: 'たいへん' },
    },
    {
        type: 'phrase',
        en: 'And then / After that (as a result)',
        pl: 'A potem / Następnie (jako rezultat)',
        jp: { text: 'そして' },
    },
    {
        type: 'phrase',
        en: "I played games. As a result I didn't do my homework.",
        pl: 'Grałem w gry. W rezultacie nie zrobiłem pracy domowej.',
        jp: { text: 'ゲームをしました。そして、しゅくだいはしませんでした。' },
    },
    {
        type: 'noun',
        en: 'Stretching',
        pl: 'Rozciąganie',
        jp: { text: 'ストレッチ' },
    },
    {
        type: 'phrase',
        en: 'To stretch',
        pl: 'Rozciągać się',
        jp: { text: 'ストレッチをする' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fun',
        pl: 'Zabawny / Przyjemny',
        jp: { text: 'たのしい' },
    },
    {
        type: 'phrase',
        en: 'Day off',
        pl: 'Dzień wolny',
        jp: { text: 'やすみのひ' },
    },
    {
        type: 'noun',
        en: 'Gardening',
        pl: 'Ogrodnictwo',
        jp: { text: 'ガーデニング' },
    },
    {
        type: 'phrase',
        en: 'To do gardening',
        pl: 'Uprawiać ogród',
        jp: { text: 'ガーデニングをする' },
    },
    {
        type: 'phrase',
        en: "Let's go!",
        pl: 'Chodźmy!',
        jp: { text: 'いきましょう！' },
    },
    {
        type: 'suffix',
        en: "We should / Let's",
        pl: 'Powinniśmy / Chodźmy',
        jp: { text: 'ましょう' },
    },
    {
        type: 'phrase',
        en: 'What should we do?',
        pl: 'Co powinniśmy zrobić?',
        jp: { text: 'なにをしましょうか？' },
    },
    {
        type: 'noun',
        en: 'Suitcase',
        pl: 'Walizka',
        jp: { text: 'スーツケース' },
    },
    {
        type: 'noun',
        en: 'Plane',
        pl: 'Samolot',
        jp: { text: 'ひこうき' },
    },
    {
        type: 'noun',
        en: 'Ticket (plane, concert, etc.)',
        pl: 'Bilet (samolot, koncert, itp.)',
        jp: { text: 'チケット' },
    },
    {
        type: 'noun',
        en: 'Art museum',
        pl: 'Muzeum sztuki',
        jp: { text: 'びじゅつかん' },
    },
    {
        type: 'noun',
        en: 'Zoo',
        pl: 'Zoo',
        jp: { text: 'どうぶつえん' },
    },
    {
        type: 'noun',
        en: 'Plaza',
        pl: 'Rynek',
        jp: { text: 'ひろば' },
    },
    {
        type: 'phrase',
        en: 'French cuisine',
        pl: 'Francuska kuchnia',
        jp: { text: 'フランスりょうり' },
    },
    {
        type: 'phrase',
        en: 'Italian dish',
        pl: 'Włoskie danie',
        jp: { text: 'イタリアのりょうり' },
    },
    {
        type: 'noun',
        en: 'Lobby',
        pl: 'Hol',
        jp: { text: 'ロビー' },
    },
    {
        type: 'phrase',
        en: 'Airport lobby',
        pl: 'Hol lotniska',
        jp: { text: 'くうこうのロビー' },
    },
    {
        type: 'noun',
        en: 'Sushi restaurant',
        pl: 'Restauracja sushi',
        jp: { text: 'すしや' },
    },
    {
        type: 'noun',
        en: 'Seat',
        pl: 'Miejsce siedzące',
        jp: { text: 'せき' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient / Useful',
        pl: 'Wygodny / Dogodny',
        jp: { text: 'べんり' },
    },
    {
        type: 'noun',
        en: 'Shinkansen',
        pl: 'Shinkansen',
        jp: { text: 'しんかんせん' },
    },
    {
        type: 'noun',
        en: 'Castle',
        pl: 'Zamek',
        jp: { text: 'しろ' },
    },
    {
        type: 'noun',
        en: 'Garden',
        pl: 'Ogród',
        jp: { text: 'にわ' },
    },
    {
        type: 'noun',
        en: 'Tourism / Sightseeing',
        pl: 'Turystyka / Zwiedzanie',
        jp: { text: 'かんこう' },
    },
    {
        type: 'phrase',
        en: 'To do sightseeing',
        pl: 'Zwiedzać',
        jp: { text: 'かんこうをする' },
    },
    {
        type: 'noun',
        en: 'Pork cutlet in miso sauce',
        pl: 'Kotlet schabowy w sosie miso',
        jp: { text: 'みそかつ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short',
        pl: 'Krótki',
        jp: { text: 'みじかい' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Wait',
        pl: 'Czekać',
        jp: { text: 'まつ' },
        present: {
            masu: {
                affirmative: { text: 'まちます' },
                negative: { text: 'まちません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Stuff / Thing',
        pl: 'Rzecz / Przedmiot',
        jp: { text: 'もの' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Sweet',
        pl: 'Słodki',
        jp: { text: 'あまい' },
    },
    {
        type: 'noun',
        en: 'Cake shop',
        pl: 'Tortownia',
        jp: { text: 'ケーキや' },
    },
    {
        type: 'noun',
        en: 'Pastry shop',
        pl: 'Cukiernia',
        jp: { text: 'おかしや' },
    },
    {
        type: 'noun',
        en: 'Cheesecake',
        pl: 'Sernik',
        jp: { text: 'チーズケーキ' },
    },
    {
        type: 'noun',
        en: 'Green',
        pl: 'Zielony',
        jp: { text: 'みどり' },
        description: 'Japanese does not have an adjective form for "green".',
    },
    {
        type: 'phrase',
        en: 'Green fridge',
        pl: 'Zielona lodówka',
        jp: { text: 'みどりのれいぞうこ' },
    },
    {
        type: 'noun',
        en: 'Cupcake',
        pl: 'Babeczka',
        jp: { text: 'カップケーキ' },
    },
    {
        type: 'phrase',
        en: 'What kind of place is Kyoto?',
        pl: 'Jaki rodzaj miejsca to Kioto?',
        jp: { text: 'きょうとはどんなところですか。' },
    },
    {
        type: 'noun',
        en: 'Cooking / Cuisine / Dish',
        pl: 'Gotowanie / Kuchnia / Danie',
        jp: { text: 'りょうり' },
    },
];

export const duolingo10Bag: WordBag = {
    id: '585cb618-ae76-48b7-ba02-e7aa0b4b206d',
    name: 'Duolingo #10',
    words: duolingo_10,
};
