import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_3: TranslatedJapaneseText[] = [
    {
        type: 'phrase',
        en: 'I live in Tokyo.',
        pl: 'Mieszkam w Tokio.',
        jp: { text: '東京に住んでいます。', pronunciation: 'とうきょうにすんでいます。' },
    },
    {
        type: 'phrase',
        en: "What's your name?",
        pl: 'Jak masz na imię?',
        jp: { text: 'おなまえは？' },
    },
    {
        type: 'noun',
        en: 'City',
        pl: 'Miasto',
        jp: { text: 'とし' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Lively / Energetic / Busy',
        pl: 'Żywy / Energiczny / Ruchliwy',
        jp: { text: 'にぎやか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Quiet / Peaceful',
        pl: 'Cichy / Spokojny',
        jp: { text: 'しずか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Clean / Beautiful',
        pl: 'Czysty / Piękny',
        jp: { text: 'きれい' },
    },
    {
        type: 'noun',
        en: 'Town',
        pl: 'Miasteczko',
        jp: { text: 'まち' },
    },
    {
        type: 'adverb',
        en: 'Very',
        pl: 'Bardzo',
        jp: { text: 'とても' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Loud',
        pl: 'Głośny',
        jp: { text: 'うるさい' },
    },
    {
        type: 'phrase',
        en: 'How is...',
        pl: 'Jakie jest...',
        jp: { text: 'どうですか' },
    },
    {
        type: 'suffix',
        en: 'Years old',
        pl: 'Lat',
        jp: { text: 'さい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Famous',
        pl: 'Sławny',
        jp: { text: 'ゆうめい' },
    },
    {
        type: 'noun',
        en: 'Wife',
        pl: 'Żona',
        jp: { text: 'つま' },
    },
    {
        type: 'noun',
        en: 'Husband',
        pl: 'Mąż',
        jp: { text: 'おっと' },
    },
    {
        type: 'noun',
        en: 'Family',
        pl: 'Rodzina',
        jp: { text: 'かぞく' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Busy',
        pl: 'Zajęty',
        jp: { text: 'いそがしい' },
    },
    {
        type: 'noun',
        en: 'Engineer',
        pl: 'Inżynier',
        jp: { text: 'エンジニア' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Funny',
        pl: 'Zabawny',
        jp: { text: 'おもしろい' },
    },
    {
        type: 'noun',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: { text: 'かいしゃいん' },
    },
    {
        type: 'noun',
        en: 'Nurse',
        pl: 'Pielęgniarka / Pielęgniarz',
        jp: { text: 'かんごし' },
    },
    {
        type: 'noun',
        en: 'Student (university)',
        pl: 'Student (uniwersytet)',
        jp: { text: 'だいがくせい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Fashionable / Trendy',
        pl: 'Modny / Trendy',
        jp: { text: 'おしゃれ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Smart',
        pl: 'Mądry',
        jp: { text: 'あたまがいい' },
    },
    {
        type: 'phrase',
        en: 'Welcome',
        pl: 'Witamy',
        jp: { text: 'ようこそ' },
    },
    {
        type: 'noun',
        en: 'Anime',
        pl: 'Anime',
        jp: { text: 'アニメ' },
    },
];

export const duolingo3Bag: WordBag = {
    id: '1cb3b262-0fb8-4f4c-b222-352c3d082736',
    name: 'Duolingo #3',
    words: duolingo_3,
};
