import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_12: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Entrance',
        pl: 'Wejście',
        jp: { text: '入口', pronunciation: 'いりぐち' },
    },
    {
        type: 'noun',
        en: 'Entrance fee',
        pl: 'Opłata za wstęp',
        jp: { text: '入場料', pronunciation: 'にゅうじょうりょう' },
    },
    {
        type: 'noun',
        en: 'Kid ticket',
        pl: 'Bilet dla dziecka',
        jp: { text: 'こどものチケット' },
    },
    {
        type: 'noun',
        en: 'Adult',
        pl: 'Dorosły',
        jp: { text: '大人', pronunciation: 'おとな' },
    },
    {
        type: 'noun',
        en: 'Adult ticket',
        pl: 'Bilet dla dorosłego',
        jp: { text: '大人のチケット', pronunciation: 'おとなのチケット' },
    },
    {
        type: 'noun',
        en: 'Tonight / This evening',
        pl: 'Dziś w nocy / Dziś wieczorem',
        jp: { text: '今晩', pronunciation: 'こんばん' },
    },
    {
        type: 'noun',
        en: 'Go-karts',
        pl: 'Gokarty',
        jp: { text: 'ゴーカート' },
    },
    {
        type: 'noun',
        en: 'Attraction',
        pl: 'Atrakcja',
        jp: { text: 'アトラクション' },
    },
    {
        type: 'noun',
        en: 'Rollercoaster',
        pl: 'Rollercoaster',
        jp: { text: 'ジェットコースター' },
    },
    {
        type: 'phrase',
        en: 'Ride the rollercoaster',
        pl: 'Jechać na rollercoasterze',
        jp: { text: 'ジェットコースターにのる' },
    },
    {
        type: 'phrase',
        en: 'Ride the go-karts',
        pl: 'Jechać na gokartach',
        jp: { text: 'ゴーカートにのる' },
    },
    {
        type: 'phrase',
        en: 'What are you looking forward to?',
        pl: 'Czego nie możesz się doczekać?',
        jp: { text: '何がたのしみですか。', pronunciation: 'なにがたのしみですか。' },
    },
    {
        type: 'noun',
        en: 'Bookstore',
        pl: 'Księgarnia',
        jp: { text: '本屋', pronunciation: 'ほんや' },
    },
    {
        type: 'noun',
        en: 'Sale',
        pl: 'Wyprzedaż',
        jp: { text: 'セール' },
    },
    {
        type: 'noun',
        en: 'CD',
        pl: 'Płyta CD',
        jp: { text: 'CD', pronunciation: 'シーディー' },
    },
    {
        type: 'noun',
        en: 'DVD',
        pl: 'Płyta DVD',
        jp: { text: 'DVD', pronunciation: 'ディーブイディー' },
    },
    {
        type: 'noun',
        en: 'Section (in a store)',
        pl: 'Sekcja (w sklepie)',
        jp: { text: 'コーナー' },
    },
    {
        type: 'noun',
        en: 'Fiction (genre)',
        pl: 'Fikcja (gatunek)',
        jp: { text: 'フィクション' },
    },
    {
        type: 'noun',
        en: 'Nonfiction (genre)',
        pl: 'Literatura faktu (gatunek)',
        jp: { text: 'ノンフィクション' },
    },
    {
        type: 'noun',
        en: 'Story',
        pl: 'Opowieść',
        jp: { text: '話', pronunciation: 'はなし' },
    },
    {
        type: 'noun',
        en: 'Album',
        pl: 'Album',
        jp: { text: 'アルバム' },
    },
    {
        type: 'noun',
        en: 'Band',
        pl: 'Zespół',
        jp: { text: 'バンド' },
    },
    {
        type: 'noun',
        en: 'Anime music (genre)',
        pl: 'Muzyka anime (gatunek)',
        jp: { text: 'アニソン' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Difficult',
        pl: 'Trudny',
        jp: { text: 'むずかしい' },
    },
    {
        type: 'noun',
        en: 'Pop music (genre)',
        pl: 'Muzyka pop (gatunek)',
        jp: { text: 'ポップス' },
    },
    {
        type: 'noun',
        en: 'Card game',
        pl: 'Gra karciana',
        jp: { text: 'カードゲーム' },
    },
    {
        type: 'noun',
        en: 'Science fiction',
        pl: 'Fantastyka naukowa',
        jp: { text: 'SF', pronunciation: 'エスエフ' },
    },
    {
        type: 'noun',
        en: 'Jigsaw puzzle',
        pl: 'Puzzle',
        jp: { text: 'パズル' },
    },
    {
        type: 'noun',
        en: 'Actor',
        pl: 'Aktor',
        jp: { text: '俳優', pronunciation: 'はいゆう' },
    },
    {
        type: 'noun',
        en: 'Poster',
        pl: 'Plakat',
        jp: { text: 'ポスター' },
    },
    {
        type: 'noun',
        en: 'Documentary',
        pl: 'Film dokumentalny',
        jp: { text: 'ドキュメンタリー' },
    },
    {
        type: 'noun',
        en: 'Floor',
        pl: 'Piętro',
        jp: { text: '階', pronunciation: 'かい' },
    },
    {
        type: 'noun',
        en: 'Reception',
        pl: 'Recepcja',
        jp: { text: 'うけつけ' },
    },
    {
        type: 'noun',
        en: 'Meeting (at work)',
        pl: 'Spotkanie (w pracy)',
        jp: { text: 'ミーティング' },
    },
    {
        type: 'noun',
        en: 'Printer',
        pl: 'Drukarka',
        jp: { text: 'プリンター' },
    },
    {
        type: 'noun',
        en: 'Training / Practice',
        pl: 'Trening / Ćwiczenia',
        jp: { text: 'トレーニング' },
    },
    {
        type: 'noun',
        en: 'Dining room / Cafeteria',
        pl: 'Jadalnia / Stołówka',
        jp: { text: '食堂', pronunciation: 'しょくどう' },
    },
    {
        type: 'noun',
        en: 'Lunch break',
        pl: 'Przerwa na lunch',
        jp: { text: 'ひる休み', pronunciation: 'ひるやすみ' },
    },
    {
        type: 'noun',
        en: 'Fried rice',
        pl: 'Smażony ryż',
        jp: { text: 'チャーハン' },
    },
    {
        type: 'noun',
        en: 'French fries',
        pl: 'Frytki',
        jp: { text: 'フライドポテト' },
    },
    {
        type: 'noun',
        en: 'PC',
        pl: 'PC',
        jp: { text: 'パソコン' },
    },
    {
        type: 'noun',
        en: 'Presentation',
        pl: 'Prezentacja',
        jp: { text: 'プレゼン' },
    },
    {
        type: 'noun',
        en: 'Client',
        pl: 'Klient',
        jp: { text: 'クライアント' },
    },
];

export const duolingo12Bag: WordBag = {
    id: '5dda1abf-a337-4591-8e04-aa5c2f1b20fb',
    name: 'Duolingo #12',
    words: duolingo_12,
};
