import type { JapaneseWord } from '../../types.ts';

export const duolingo_11: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Shopping',
        pl: 'Zakupy',
        jp: { word: '買い物', pronunciation: 'かいもの' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Get on / Ride (transport)',
        pl: 'Wsiadać / Jeździć (transport)',
        jp: { word: 'のる' },
        present: {
            masu: {
                affirmative: { word: 'のります' },
                negative: { word: 'のりません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I get on the bus.',
        pl: 'Wsiadam do autobusu.',
        jp: { word: 'バスにのります。' },
    },
    {
        type: 'phrase',
        en: 'I ride a train.',
        pl: 'Jadę pociągiem.',
        jp: { word: 'でんしゃにのります。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Anticipated',
        pl: 'Oczekiwany',
        jp: { word: 'たのしみ' },
    },
    {
        type: 'phrase',
        en: 'I am looking forward to the trip.',
        pl: 'Nie mogę się doczekać podróży.',
        jp: { word: 'りょこうがたのしみです。' },
    },
    {
        type: 'noun',
        en: 'Matcha',
        pl: 'Matcha',
        jp: { word: 'まっちゃ' },
    },
    {
        type: 'noun',
        en: 'Cookie',
        pl: 'Ciastko',
        jp: { word: 'クッキー' },
    },
    {
        type: 'noun',
        en: 'Chocolate',
        pl: 'Czekolada',
        jp: { word: 'チョコレート' },
    },
    {
        type: 'noun',
        en: 'Donut',
        pl: 'Pączek',
        jp: { word: 'ドーナツ' },
    },
    {
        type: 'noun',
        en: 'Pie',
        pl: 'Ciasto / Placek',
        jp: { word: 'パイ' },
    },
    {
        type: 'noun',
        en: 'Free time',
        pl: 'Czas wolny',
        jp: { word: 'ひま' },
    },
    {
        type: 'phrase',
        en: 'On friday afternoon I will have free time.',
        pl: 'W piątek po południu będę mieć czas wolny.',
        jp: { word: 'きんようびのごごひまです。' },
    },
    {
        type: 'noun',
        en: 'Together',
        pl: 'Razem',
        jp: { word: 'いっしょ' },
    },
    {
        type: 'phrase',
        en: "Let's go together.",
        pl: 'Chodźmy razem.',
        jp: { word: 'いっしょにいきましょう。' },
    },
    {
        type: 'noun',
        en: 'Egg',
        pl: 'Jajko',
        jp: { word: '卵', pronunciation: 'たまご' },
    },
    {
        type: 'noun',
        en: 'Soy sauce',
        pl: 'Sos sojowy',
        jp: { word: 'しょうゆ' },
    },
    {
        type: 'noun',
        en: 'Supermarket',
        pl: 'Supermarket',
        jp: { word: 'スーパー' },
    },
    {
        type: 'adverb',
        en: 'More',
        pl: 'Więcej / Bardziej',
        jp: { word: 'もっと' },
    },
    {
        type: 'noun',
        en: 'Fish',
        pl: 'Ryba',
        jp: { word: '魚', pronunciation: 'さかな' },
    },
    {
        type: 'noun',
        en: 'Tofu',
        pl: 'Tofu',
        jp: { word: 'とうふ' },
    },
    {
        type: 'noun',
        en: 'Beef with rice',
        pl: 'Wołowina z ryżem',
        jp: { word: 'ぎゅうどん' },
    },
    {
        type: 'conjunction',
        en: 'But',
        pl: 'Ale',
        jp: { word: 'でも' },
    },
    {
        type: 'noun',
        en: 'Japanese pork cutlet',
        pl: 'Japoński kotlet schabowy',
        jp: { word: 'とんかつ' },
    },
    {
        type: 'noun',
        en: 'Raw / Uncooked',
        pl: 'Nieugotowany / Surowy',
        jp: { word: 'なま' },
        description: "Note this isn't an adjective, it's a noun.",
    },
    {
        type: 'noun',
        en: 'Salt',
        pl: 'Sól',
        jp: { word: 'しお' },
    },
    {
        type: 'noun',
        en: 'Pork',
        pl: 'Wieprzowina',
        jp: { word: 'ぶたにく' },
    },
    {
        type: 'noun',
        en: 'Cola',
        pl: 'Cola',
        jp: { word: 'コーラ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Salty',
        pl: 'Słony',
        jp: { word: 'しょっぱい' },
    },
    {
        type: 'phrase',
        en: "I don't eat raw fish.",
        pl: 'Nie jem surowej ryby.',
        jp: { word: 'なまのさかなはたべません。' },
    },
    {
        type: 'noun',
        en: 'Lesson / Class',
        pl: 'Lekcja / Zajęcia',
        jp: { word: 'じゅぎょう' },
    },
    {
        type: 'noun',
        en: 'A lot of / Many',
        pl: 'Dużo',
        jp: { word: 'たくさん' },
        description:
            'This should always modify the verb, so it should be used before it. Some people in every-day speech might say "たくさんしゅくだい", but the correct way to say it is "しゅくだいがたくさんあります".',
    },
    {
        type: 'phrase',
        en: 'I have a lot of homework.',
        pl: 'Mam dużo pracy domowej.',
        jp: { word: 'しゅくだいがたくさんあります。' },
    },
    {
        type: 'adverb',
        en: 'Early',
        pl: 'Wcześnie',
        jp: { word: 'はやく' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Interesting',
        pl: 'Interesujący',
        jp: { word: 'おもしろい' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'End',
        pl: 'Kończyć się',
        jp: { word: 'おわる' },
        present: {
            masu: {
                affirmative: { word: 'おわります' },
                negative: { word: 'おわりません' },
            },
        },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Ask',
        pl: 'Pytać',
        jp: { word: 'きく' },
        present: {
            masu: {
                affirmative: { word: 'ききます' },
                negative: { word: 'ききません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'I will ask the teacher.',
        pl: 'Zapytam nauczyciela.',
        jp: { word: 'せんせいにききます。' },
    },
    {
        type: 'noun',
        en: 'Deadline',
        pl: 'Termin',
        jp: { word: 'しめきり' },
    },
    {
        type: 'noun',
        en: 'Coworker',
        pl: 'Współpracownik',
        jp: { word: 'どうりょう' },
    },
    {
        type: 'noun',
        en: 'Manager',
        pl: 'Kierownik',
        jp: { word: 'マネージャー' },
    },
    {
        type: 'noun',
        en: 'Library',
        pl: 'Biblioteka',
        jp: { word: 'としょかん' },
    },
    {
        type: 'phrase',
        en: 'Translate',
        pl: 'Tłumaczyć',
        jp: { word: 'ほんやくをする' },
    },
    {
        type: 'noun',
        en: 'Translator',
        pl: 'Tłumacz',
        jp: { word: 'ほんやくしゃ' },
    },
    {
        type: 'noun',
        en: 'Navigation (GPS)',
        pl: 'Nawigacja (GPS)',
        jp: { word: 'ナビ' },
    },
    {
        type: 'phrase',
        en: 'Drive',
        pl: 'Kierować pojazdem',
        jp: { word: 'うんてんをする' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Wash / Clean',
        pl: 'Myć / Czyścić',
        jp: { word: 'あらう' },
        present: {
            masu: {
                affirmative: { word: 'あらいます' },
                negative: { word: 'あらいません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Driver',
        pl: 'Kierowca',
        jp: { word: 'うんてんしゅ' },
    },
    {
        type: 'noun',
        en: 'Camera',
        pl: 'Aparat fotograficzny',
        jp: { word: 'カメラ' },
    },
    {
        type: 'noun',
        en: 'Player / Athlete',
        pl: 'Gracz / Sportowiec',
        jp: { word: 'せんしゅ' },
    },
    {
        type: 'noun',
        en: 'Team',
        pl: 'Drużyna',
        jp: { word: 'チーム' },
    },
    {
        type: 'noun',
        en: 'Gym',
        pl: 'Siłownia',
        jp: { word: 'ジム' },
    },
    {
        type: 'noun',
        en: 'Professional',
        pl: 'Profesjonalista',
        jp: { word: 'プロ' },
    },
    {
        type: 'noun',
        en: 'Amusement park',
        pl: 'Park rozrywki',
        jp: { word: 'ゆうえんち' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dull / Boring',
        pl: 'Nudny',
        jp: { word: 'つまらない' },
    },
];
