import type { JapaneseWord } from '../../types.ts';

export const duolingo_4: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'To watch',
        pl: 'Oglądać',
        jp: { word: '見ます', pronunciation: 'みます' },
    },
    {
        type: 'unknown',
        en: 'Soccer',
        pl: 'Piłka nożna',
        jp: { word: 'サッカー' },
    },
    {
        type: 'unknown',
        en: 'Do',
        pl: 'Robić',
        jp: { word: 'します' },
    },
    {
        type: 'unknown',
        en: 'Basketball',
        pl: 'Koszykówka',
        jp: { word: 'バスケットボール' },
    },
    {
        type: 'unknown',
        en: 'Often',
        pl: 'Często',
        jp: { word: 'よく' },
    },
    {
        type: 'unknown',
        en: 'JPop',
        pl: 'Japoński pop',
        jp: { word: 'Jポップ' },
    },
    {
        type: 'unknown',
        en: 'To listen / To hear',
        pl: 'Słuchać / Słyszeć',
        jp: { word: 'ききます' },
    },
    {
        type: 'unknown',
        en: 'Rock music',
        pl: 'Muzyka rockowa',
        jp: { word: 'ロック' },
    },
    {
        type: 'unknown',
        en: 'TV',
        pl: 'Telewizja',
        jp: { word: 'テレビ' },
    },
    {
        type: 'unknown',
        en: 'Movie',
        pl: 'Film',
        jp: { word: 'えいが' },
    },
    {
        type: 'unknown',
        en: 'Sometimes',
        pl: 'Czasami',
        jp: { word: 'ときどき' },
    },
    {
        type: 'unknown',
        en: 'Music',
        pl: 'Muzyka',
        jp: { word: 'おんがく' },
    },
    {
        type: 'unknown',
        en: 'Jazz',
        pl: 'Jazz',
        jp: { word: 'ジャズ' },
    },
    {
        type: 'unknown',
        en: 'Book',
        pl: 'Książka',
        jp: { word: '本', pronunciation: 'ほん' },
    },
    {
        type: 'unknown',
        en: 'To read',
        pl: 'Czytać',
        jp: { word: '読みます', pronunciation: 'よみます' },
    },
    {
        type: 'unknown',
        en: 'News',
        pl: 'Wiadomości',
        jp: { word: 'ニュース' },
    },
    {
        type: 'unknown',
        en: 'Magazine',
        pl: 'Czasopismo',
        jp: { word: 'ざっし' },
    },
    {
        type: 'unknown',
        en: 'Manga',
        pl: 'Manga',
        jp: { word: 'まんが' },
    },
    {
        type: 'unknown',
        en: 'Baseball',
        pl: 'Baseball',
        jp: { word: 'やきゅう' },
    },
    {
        type: 'unknown',
        en: 'Eat',
        pl: 'Jeść',
        jp: { word: '食べます', pronunciation: 'たべます' },
    },
    {
        type: 'unknown',
        en: 'Every morning',
        pl: 'Każdego poranka',
        jp: { word: 'まいあさ' },
    },
    {
        type: 'unknown',
        en: 'Drink',
        pl: 'Pić',
        jp: { word: 'のみます' },
    },
    {
        type: 'unknown',
        en: 'Hour',
        pl: 'Godzina',
        jp: { word: '時', pronunciation: 'じ' },
    },
    {
        type: 'unknown',
        en: 'Dinner',
        pl: 'Kolacja',
        jp: { word: 'ばんごはん' },
    },
    {
        type: 'unknown',
        en: 'What',
        pl: 'Co',
        jp: { word: '何', pronunciation: 'なに' },
    },
    {
        type: 'unknown',
        en: 'Bread',
        pl: 'Chleb',
        jp: { word: 'パン' },
    },
    {
        type: 'unknown',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: { word: 'おいしい' },
    },
    {
        type: 'unknown',
        en: 'Sandwich',
        pl: 'Kanapka',
        jp: { word: 'サンドイッチ' },
    },
    {
        type: 'unknown',
        en: 'Every day',
        pl: 'Codziennie',
        jp: { word: 'まいにち' },
    },
    {
        type: 'unknown',
        en: 'Juice',
        pl: 'Sok',
        jp: { word: 'ジュース' },
    },
    {
        type: 'unknown',
        en: 'Coffee',
        pl: 'Kawa',
        jp: { word: 'コーヒー' },
    },
    {
        type: 'unknown',
        en: 'Breakfast',
        pl: 'Śniadanie',
        jp: { word: 'あさごはん' },
    },
    {
        type: 'unknown',
        en: 'Boxed lunch',
        pl: 'Pudełkowy lunch',
        jp: { word: 'べんとう' },
    },
    {
        type: 'unknown',
        en: 'Every night',
        pl: 'Każdej nocy',
        jp: { word: 'まいばん' },
    },
    {
        type: 'unknown',
        en: 'Old (thing)',
        pl: 'Stary (rzecz)',
        jp: { word: '古い', pronunciation: 'ふるい' },
    },
    {
        type: 'unknown',
        en: 'New (thing)',
        pl: 'Nowy (rzecz)',
        jp: { word: '新しい', pronunciation: 'あたらしい' },
    },
    {
        type: 'unknown',
        en: 'Clothes',
        pl: 'Ubrania',
        jp: { word: 'ふく' },
    },
    {
        type: 'unknown',
        en: 'Wallet',
        pl: 'Portfel',
        jp: { word: 'さいふ' },
    },
    {
        type: 'unknown',
        en: 'Unfashionable / Not trendy',
        pl: 'Niemodny / Nietrendy',
        jp: { word: 'ダサい' },
    },
    {
        type: 'unknown',
        en: 'Skirt',
        pl: 'Spódnica',
        jp: { word: 'スカート' },
    },
];
