import type { JapaneseWord } from '../../types.ts';

export const duolingo_6: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Friend',
        pl: 'Przyjaciel',
        jp: 'ともだち',
    },
    {
        type: 'noun',
        en: 'Family',
        pl: 'Rodzina',
        jp: 'かぞく',
    },
    {
        type: 'noun',
        en: 'Sports',
        pl: 'Sport',
        jp: 'スポーツ',
    },
    {
        type: 'phrase',
        en: 'I do sports with my dad.',
        pl: 'Uprawiam sport z moim tatą.',
        jp: '父とスポーツをします。',
    },
    {
        type: 'noun',
        en: 'Karate',
        pl: 'Karate',
        jp: 'からて',
    },
    {
        type: 'phrase',
        en: 'I play baseball on Saturdays.',
        pl: 'Gram w baseball w soboty.',
        jp: '土曜日にやきゅうをします。',
        jp_pronunciation: 'どようびにやきゅうをします。',
    },
    {
        type: 'verb',
        en: 'To buy',
        pl: 'Kupić',
        jp: '買います',
        jp_pronunciation: 'かいます',
    },
    {
        type: 'verb',
        en: 'To go out',
        pl: 'Wyjść',
        jp: 'でかけます',
    },
    {
        type: 'noun',
        en: 'Game',
        pl: 'Gra',
        jp: 'ゲーム',
    },
    {
        type: 'noun',
        en: 'Tennis',
        pl: 'Tenis',
        jp: 'テニス',
    },
    {
        type: 'noun',
        en: 'Judo',
        pl: 'Judo',
        jp: 'じゅうどう',
    },
    {
        type: 'verb',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: '話します',
        jp_pronunciation: 'はなします',
    },
    {
        type: 'noun',
        en: 'Video / Film',
        pl: 'Wideo / Film',
        jp: 'どうが',
    },
    {
        type: 'noun',
        en: 'These',
        pl: 'Te',
        jp: 'これら',
        jp_description: 'Plural form of これ (this).',
    },
    {
        type: 'phrase',
        en: 'I watch funny videos.',
        pl: 'Oglądam zabawne filmy.',
        jp: 'おもしろいどうがを見ます。',
    },
    {
        type: 'phrase',
        en: 'I listen to music by myself.',
        pl: 'Słucham muzyki sam.',
        jp: 'ひとりでおんがくをききます。',
    },
    {
        type: 'noun',
        en: 'Ticket gate',
        pl: 'Brama biletowa',
        jp: 'かいさつ',
    },
    {
        type: 'noun',
        en: 'Over there',
        pl: 'Tam',
        jp: 'あそこ',
    },
    {
        type: 'noun',
        en: 'ATM',
        pl: 'Bankomat',
        jp: 'ATM',
    },
    {
        type: 'noun',
        en: 'Second floor',
        pl: 'Drugie piętro',
        jp: 'にかい',
    },
    {
        type: 'noun',
        en: 'Elevator',
        pl: 'Winda',
        jp: 'エレベーター',
    },
    {
        type: 'verb',
        en: 'To have (inanimate)',
        pl: 'Mieć (nieożywione)',
        jp: 'あります',
    },
    {
        type: 'noun',
        en: 'Platform',
        pl: 'Peron',
        jp: 'ホーム',
    },
    {
        type: 'noun',
        en: 'First floor',
        pl: 'Pierwsze piętro',
        jp: 'いっかい',
    },
    {
        type: 'noun',
        en: 'Trash can',
        pl: 'Kosz na śmieci',
        jp: 'ゴミばこ',
    },
    {
        type: 'noun',
        en: 'Transfer',
        pl: 'Przesiadka',
        jp: 'のりかえ',
    },
    {
        type: 'noun',
        en: 'Taxi',
        pl: 'Taksówka',
        jp: 'タクシー',
    },
    {
        type: 'noun',
        en: 'Restroom',
        pl: 'Toaleta (publiczna)',
        jp: 'おてあらい',
    },
    {
        type: 'noun',
        en: 'Underground',
        pl: 'Podziemny / Poziom podziemny',
        jp: 'ちか',
    },
    {
        type: 'adjective',
        en: 'Far',
        pl: 'Daleko',
        jp: 'とおい',
    },
    {
        type: 'noun',
        en: 'Phone',
        pl: 'Telefon',
        jp: 'でんわ',
    },
    {
        type: 'noun',
        en: 'Stairs',
        pl: 'Schody',
        jp: 'かいだん',
    },
    {
        type: 'adjective',
        en: 'Close',
        pl: 'Blisko',
        jp: 'ちかい',
    },
    {
        type: 'noun',
        en: 'Cafe',
        pl: 'Kawiarnia',
        jp: 'カフェ',
    },
    {
        type: 'noun',
        en: 'Exit',
        pl: 'Wyjście',
        jp: 'でぐち',
    },
    {
        type: 'noun',
        en: 'Vending machine',
        pl: 'Automat z napojami',
        jp: 'じはんき',
    },
    {
        type: 'noun',
        en: 'Coin locker',
        pl: 'Szafka na monety',
        jp: 'コインロッカー',
    },
    {
        type: 'noun',
        en: 'Radio',
        pl: 'Radio',
        jp: 'ラジオ',
    },
    {
        type: 'noun',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: '新聞',
        jp_pronunciation: 'しんぶん',
    },
    {
        type: 'verb',
        en: 'Get up',
        pl: 'Wstać',
        jp: 'おきます',
    },
    {
        type: 'verb',
        en: 'Eat',
        pl: 'Jeść',
        jp: '食べます',
        jp_pronunciation: 'たべます',
    },
    {
        type: 'other',
        en: 'Always',
        pl: 'Zawsze',
        jp: 'いつも',
    },
    {
        type: 'noun',
        en: 'Volleyball',
        pl: 'Siatkówka',
        jp: 'バレーボール',
    },
    {
        type: 'noun',
        en: 'Every week',
        pl: 'Co tydzień',
        jp: 'まいしゅう',
    },
    {
        type: 'other',
        en: 'Around',
        pl: 'Około',
        jp: 'ごろ',
    },
    {
        type: 'verb',
        en: 'Make',
        pl: 'Robić',
        jp: 'つくります',
    },
    {
        type: 'noun',
        en: 'Next week',
        pl: 'W przyszłym tygodniu',
        jp: 'らいしゅう',
    },
];
