import type { JapaneseWord } from '../../types.ts';

export const duolingo_11: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Shopping',
        pl: 'Zakupy',
        jp: '買い物',
        jp_pronunciation: 'かいもの',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Get on / Ride (transport)',
        pl: 'Wsiadać / Jeździć (transport)',
        jp: 'のる',
        masu_form: 'のります',
        masen_form: 'のりません',
    },
    {
        type: 'phrase',
        en: 'I get on the bus.',
        pl: 'Wsiadam do autobusu.',
        jp: 'バスにのります。',
    },
    {
        type: 'phrase',
        en: 'I ride a train.',
        pl: 'Jadę pociągiem.',
        jp: 'でんしゃにのります。',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Anticipated',
        pl: 'Oczekiwany',
        jp: 'たのしみ',
    },
    {
        type: 'phrase',
        en: 'I am looking forward to the trip.',
        pl: 'Nie mogę się doczekać podróży.',
        jp: 'りょこうがたのしみです。',
    },
    {
        type: 'noun',
        en: 'Matcha',
        pl: 'Matcha',
        jp: 'まっちゃ',
    },
    {
        type: 'noun',
        en: 'Cookie',
        pl: 'Ciastko',
        jp: 'クッキー',
    },
    {
        type: 'noun',
        en: 'Chocolate',
        pl: 'Czekolada',
        jp: 'チョコレート',
    },
    {
        type: 'noun',
        en: 'Donut',
        pl: 'Pączek',
        jp: 'ドーナツ',
    },
    {
        type: 'noun',
        en: 'Pie',
        pl: 'Ciasto / Placek',
        jp: 'パイ',
    },
    {
        type: 'noun',
        en: 'Free time',
        pl: 'Czas wolny',
        jp: 'ひま',
    },
    {
        type: 'phrase',
        en: 'On friday afternoon I will have free time.',
        pl: 'W piątek po południu będę mieć czas wolny.',
        jp: 'きんようびのごごはひまです。',
    },
    {
        type: 'noun',
        en: 'Together',
        pl: 'Razem',
        jp: 'いっしょ',
    },
    {
        type: 'phrase',
        en: "Let's go together.",
        pl: 'Chodźmy razem.',
        jp: 'いっしょにいきましょう。',
    },
    {
        type: 'noun',
        en: 'Egg',
        pl: 'Jajko',
        jp: '卵',
        jp_pronunciation: 'たまご',
    },
    {
        type: 'noun',
        en: 'Soy sauce',
        pl: 'Sos sojowy',
        jp: 'しょうゆ',
    },
    {
        type: 'noun',
        en: 'Supermarket',
        pl: 'Supermarket',
        jp: 'スーパー',
    },
    {
        type: 'adverb',
        en: 'More',
        pl: 'Więcej / Bardziej',
        jp: 'もっと',
    },
    {
        type: 'noun',
        en: 'Fish',
        pl: 'Ryba',
        jp: '魚',
        jp_pronunciation: 'さかな',
    },
    {
        type: 'noun',
        en: 'Tofu',
        pl: 'Tofu',
        jp: 'とうふ',
    },
    {
        type: 'noun',
        en: 'Beef with rice',
        pl: 'Wołowina z ryżem',
        jp: 'ぎゅうどん',
    },
    {
        type: 'conjunction',
        en: 'But',
        pl: 'Ale',
        jp: 'でも',
    },
    {
        type: 'noun',
        en: 'Japanese pork cutlet',
        pl: 'Japoński kotlet schabowy',
        jp: 'とんかつ',
    },
    {
        type: 'noun',
        en: 'Raw / Uncooked',
        pl: 'Nieugotowany / Surowy',
        jp: 'なま',
        jp_description: "Note this isn't an adjective, it's a noun.",
    },
    {
        type: 'noun',
        en: 'Salt',
        pl: 'Sól',
        jp: 'しお',
    },
    {
        type: 'noun',
        en: 'Pork',
        pl: 'Wieprzowina',
        jp: 'ぶたにく',
    },
    {
        type: 'noun',
        en: 'Cola',
        pl: 'Cola',
        jp: 'コーラ',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Salty',
        pl: 'Słony',
        jp: 'しょっぱい',
    },
    {
        type: 'phrase',
        en: "I don't eat raw fish.",
        pl: 'Nie jem surowej ryby.',
        jp: 'なまのさかなはたべません。',
    },
    {
        type: 'noun',
        en: 'Lesson / Class',
        pl: 'Lekcja / Zajęcia',
        jp: 'じゅぎょう',
    },
    {
        type: 'noun',
        en: 'A lot of / Many',
        pl: 'Dużo',
        jp: 'たくさん',
    },
    {
        type: 'phrase',
        en: 'I have a lot of homework.',
        pl: 'Mam dużo pracy domowej.',
        jp: 'しゅくだいがたくさんあります。',
    },
    {
        type: 'adverb',
        en: 'Soon',
        pl: 'Wkrótce / Niedługo',
        jp: 'はやく',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Interesting',
        pl: 'Interesujący',
        jp: 'おもしろい',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'End',
        pl: 'Kończyć się',
        jp: 'おわる',
        masu_form: 'おわります',
        masen_form: 'おわりません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Ask',
        pl: 'Pytać',
        jp: 'きく',
        masu_form: 'ききます',
        masen_form: 'ききません',
    },
    {
        type: 'phrase',
        en: 'I will ask the teacher.',
        pl: 'Zapytam nauczyciela.',
        jp: 'せんせいにききます。',
    },
    {
        type: 'noun',
        en: 'Deadline',
        pl: 'Termin',
        jp: 'しめきり',
    },
    {
        type: 'noun',
        en: 'Coworker',
        pl: 'Współpracownik',
        jp: 'どうりょう',
    },
    {
        type: 'noun',
        en: 'Manager',
        pl: 'Kierownik',
        jp: 'マネージャー',
    },
    {
        type: 'noun',
        en: 'Library',
        pl: 'Biblioteka',
        jp: 'としょかん',
    },
    {
        type: 'phrase',
        en: 'Translate',
        pl: 'Tłumaczyć',
        jp: 'ほんやくをする',
    },
    {
        type: 'noun',
        en: 'Translator',
        pl: 'Tłumacz',
        jp: 'ほんやくしゃ',
    },
    {
        type: 'noun',
        en: 'Navigation (GPS)',
        pl: 'Nawigacja (GPS)',
        jp: 'ナビ',
    },
    {
        type: 'phrase',
        en: 'Drive',
        pl: 'Kierować pojazdem',
        jp: 'うんてんをする',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Wash / Clean',
        pl: 'Myć / Czyścić',
        jp: 'あらう',
        masu_form: 'あらいます',
        masen_form: 'あらいません',
    },
    {
        type: 'noun',
        en: 'Driver',
        pl: 'Kierowca',
        jp: 'うんてんしゅ',
    },
    {
        type: 'noun',
        en: 'Camera',
        pl: 'Aparat fotograficzny',
        jp: 'カメラ',
    },
    {
        type: 'noun',
        en: 'Player / Athlete',
        pl: 'Gracz / Sportowiec',
        jp: 'せんしゅ',
    },
    {
        type: 'noun',
        en: 'Team',
        pl: 'Drużyna',
        jp: 'チーム',
    },
    {
        type: 'noun',
        en: 'Gym',
        pl: 'Siłownia',
        jp: 'ジム',
    },
    {
        type: 'noun',
        en: 'Professional',
        pl: 'Profesjonalista',
        jp: 'プロ',
    },
    {
        type: 'noun',
        en: 'Amusement park',
        pl: 'Park rozrywki',
        jp: 'ゆうえんち',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dull / Boring',
        pl: 'Nudny',
        jp: 'つまらない',
    },
];
