import type { JapaneseWord } from '../../types.ts';

export const duolingo_5: JapaneseWord[] = [
    {
        type: 'phrase',
        en: "I don't really like...",
        pl: 'Nie bardzo lubię...',
        jp: 'はちょっと…',
        jp_description: "Used as a subtle way to say you don't like something.",
    },
    {
        type: 'adjective',
        en: 'New',
        pl: 'Nowy',
        jp: '新しい',
        jp_pronunciation: 'あたらしい',
    },
    {
        type: 'noun',
        en: 'Skirt',
        pl: 'Spódnica',
        jp: 'スカート',
    },
    {
        type: 'adjective',
        en: 'Want',
        pl: 'Chcieć',
        jp: 'ほしい',
    },
    {
        type: 'phrase',
        en: 'I want a new skirt.',
        pl: 'Chcę nową spódnicę.',
        jp: 'あたらしいスカートがほしいです。',
    },
    {
        type: 'noun',
        en: 'Jacket',
        pl: 'Kurtka',
        jp: 'ジャケット',
    },
    {
        type: 'adjective',
        en: "Don't want",
        pl: 'Nie chcieć',
        jp: 'ほしくない',
    },
    {
        type: 'phrase',
        en: "I don't want an old jacket.",
        pl: 'Nie chcę starej kurtki.',
        jp: '古いジャケットはほしくないです',
        jp_pronunciation: 'ふるいジャケットはほしくないです',
    },
    {
        type: 'noun',
        en: 'T-shirt',
        pl: 'Koszulka',
        jp: 'Tシャツ',
    },
    {
        type: 'noun',
        en: 'Dress',
        pl: 'Sukienka',
        jp: 'ドレス',
    },
    {
        type: 'adjective',
        en: 'Lovely',
        pl: 'Śliczny',
        jp: 'すてき',
    },
    {
        type: 'adjective',
        en: 'Good',
        pl: 'Dobry',
        jp: 'いい',
    },
    {
        type: 'noun',
        en: 'Necktie',
        pl: 'Krawat',
        jp: 'ネクタイ',
    },
    {
        type: 'adjective',
        en: 'Cheap',
        pl: 'Tani',
        jp: 'やすい',
    },
    {
        type: 'phrase',
        en: 'How much is this?',
        pl: 'Ile to kosztuje?',
        jp: 'これはいくらですか？',
    },
    {
        type: 'noun',
        en: 'Yen',
        pl: 'Jen',
        jp: 'えん',
    },
    {
        type: 'phrase',
        en: 'This umbrella costs 500 yen.',
        pl: 'Ten parasol kosztuje 500 jenów.',
        jp: 'このかさは五百えんです。',
    },
    {
        type: 'adjective',
        en: 'Black',
        pl: 'Czarny',
        jp: 'くろい',
    },
    {
        type: 'noun',
        en: 'Shop',
        pl: 'Sklep',
        jp: 'みせ',
    },
    {
        type: 'adjective',
        en: 'Expensive',
        pl: 'Drogi',
        jp: 'たかい',
    },
    {
        type: 'particle',
        en: "..., isn't it?",
        pl: '..., prawda?',
        jp: 'ね',
    },
    {
        type: 'noun',
        en: 'Udon',
        pl: 'Udon',
        jp: 'うどん',
    },
    {
        type: 'noun',
        en: 'Miso soup',
        pl: 'Zupa miso',
        jp: 'みそしる',
    },
    {
        type: 'noun',
        en: 'Restaurant',
        pl: 'Restauracja',
        jp: 'レストラン',
    },
    {
        type: 'noun',
        en: 'Tempura',
        pl: 'Tempura',
        jp: 'てんぷら',
    },
    {
        type: 'phrase',
        en: 'Black tea please.',
        pl: 'Poproszę czarną herbatę.',
        jp: 'こうちゃをください。',
    },
    {
        type: 'noun',
        en: 'Water',
        pl: 'Woda',
        jp: '水',
        jp_pronunciation: 'みず',
    },
    {
        type: 'other',
        en: 'Well then...',
        pl: 'Cóż, w takim razie ...',
        jp: 'じゃあ…',
    },
    {
        type: 'noun',
        en: 'Onigiri',
        pl: 'Onigiri',
        jp: 'おにぎり',
    },
    {
        type: 'adjective',
        en: 'Big',
        pl: 'Duży',
        jp: '大きい',
        jp_pronunciation: 'おおきい',
    },
    {
        type: 'noun',
        en: 'Salad',
        pl: 'Sałatka',
        jp: 'サラダ',
    },
    {
        type: 'noun',
        en: 'Soba',
        pl: 'Soba',
        jp: 'そば',
        jp_description: 'Buckwheat noodles',
    },
    {
        type: 'phrase',
        en: "How's the miso soup?",
        pl: 'Jak jest zupa miso?',
        jp: 'みそしるはどうですか？',
    },
    {
        type: 'adjective',
        en: 'Small',
        pl: 'Mały',
        jp: '小さい',
        jp_pronunciation: 'ちいさい',
    },
    {
        type: 'noun',
        en: 'Black tea',
        pl: 'Czarna herbata',
        jp: 'こうちゃ',
    },
    {
        type: 'noun',
        en: 'Ice cream',
        pl: 'Lody',
        jp: 'アイスクリーム',
    },
    {
        type: 'noun',
        en: 'Iced coffee',
        pl: 'Kawa mrożona',
        jp: 'アイスコーヒー',
    },
    {
        type: 'other',
        en: 'A little',
        pl: 'Trochę',
        jp: 'すこし',
    },
    {
        type: 'verb',
        en: 'Swim',
        pl: 'Pływać',
        jp: 'およぎます',
    },
    {
        type: 'noun',
        en: 'Yoga',
        pl: 'Joga',
        jp: 'ヨガ',
    },
    {
        type: 'phrase',
        en: 'I do yoga every day.',
        pl: 'Codziennie uprawiam jogę.',
        jp: 'まいにちヨガをします。',
    },
    {
        type: 'phrase',
        en: 'With mr Ken',
        pl: 'Z panem Kenem',
        jp: 'けんさんと',
    },
    {
        type: 'other',
        en: 'By myself',
        pl: 'Samemu',
        jp: 'ひとりで',
    },
    {
        type: 'noun',
        en: 'Weekend',
        pl: 'Weekend',
        jp: 'しゅうまつ',
    },
    {
        type: 'noun',
        en: 'TV drama',
        pl: 'Serial telewizyjny',
        jp: 'ドラマ',
    },
    {
        type: 'verb',
        en: 'Hang out',
        pl: 'Spędzać czas',
        jp: 'あそびます',
    },
];
