import type { JapaneseWord } from '../../types.ts';

export const duolingo_5: JapaneseWord[] = [
    {
        type: 'unknown',
        en: "I don't really like...",
        pl: 'Nie bardzo lubię...',
        jp: { word: 'はちょっと…' },
        description: "Used as a subtle way to say you don't like something.",
    },
    {
        type: 'unknown',
        en: 'New',
        pl: 'Nowy',
        jp: { word: '新しい', pronunciation: 'あたらしい' },
    },
    {
        type: 'unknown',
        en: 'Skirt',
        pl: 'Spódnica',
        jp: { word: 'スカート' },
    },
    {
        type: 'unknown',
        en: 'Want',
        pl: 'Chcieć',
        jp: { word: 'ほしい' },
    },
    {
        type: 'unknown',
        en: 'I want a new skirt.',
        pl: 'Chcę nową spódnicę.',
        jp: { word: 'あたらしいスカートがほしいです。' },
    },
    {
        type: 'unknown',
        en: 'Jacket',
        pl: 'Kurtka',
        jp: { word: 'ジャケット' },
    },
    {
        type: 'unknown',
        en: "Don't want",
        pl: 'Nie chcieć',
        jp: { word: 'ほしくない' },
    },
    {
        type: 'unknown',
        en: "I don't want an old jacket.",
        pl: 'Nie chcę starej kurtki.',
        jp: { word: '古いジャケットはほしくないです', pronunciation: 'ふるいジャケットはほしくないです' },
    },
    {
        type: 'unknown',
        en: 'T-shirt',
        pl: 'Koszulka',
        jp: { word: 'Tシャツ' },
    },
    {
        type: 'unknown',
        en: 'Dress',
        pl: 'Sukienka',
        jp: { word: 'ドレス' },
    },
    {
        type: 'unknown',
        en: 'Lovely',
        pl: 'Śliczny',
        jp: { word: 'すてき' },
    },
    {
        type: 'unknown',
        en: 'Good',
        pl: 'Dobry',
        jp: { word: 'いい' },
    },
    {
        type: 'unknown',
        en: 'Necktie',
        pl: 'Krawat',
        jp: { word: 'ネクタイ' },
    },
    {
        type: 'unknown',
        en: 'Cheap',
        pl: 'Tani',
        jp: { word: 'やすい' },
    },
    {
        type: 'unknown',
        en: 'How much is this?',
        pl: 'Ile to kosztuje?',
        jp: { word: 'これはいくらですか？' },
    },
    {
        type: 'unknown',
        en: 'Yen',
        pl: 'Jen',
        jp: { word: 'えん' },
    },
    {
        type: 'unknown',
        en: 'This umbrella costs 500 yen.',
        pl: 'Ten parasol kosztuje 500 jenów.',
        jp: { word: 'このかさは五百えんです。' },
    },
    {
        type: 'unknown',
        en: 'Black',
        pl: 'Czarny',
        jp: { word: 'くろい' },
    },
    {
        type: 'unknown',
        en: 'Shop',
        pl: 'Sklep',
        jp: { word: 'みせ' },
    },
    {
        type: 'unknown',
        en: 'Expensive',
        pl: 'Drogi',
        jp: { word: 'たかい' },
    },
    {
        type: 'unknown',
        en: "..., isn't it?",
        pl: '..., prawda?',
        jp: { word: 'ね' },
    },
    {
        type: 'unknown',
        en: 'Udon',
        pl: 'Udon',
        jp: { word: 'うどん' },
    },
    {
        type: 'unknown',
        en: 'Miso soup',
        pl: 'Zupa miso',
        jp: { word: 'みそしる' },
    },
    {
        type: 'unknown',
        en: 'Restaurant',
        pl: 'Restauracja',
        jp: { word: 'レストラン' },
    },
    {
        type: 'unknown',
        en: 'Tempura',
        pl: 'Tempura',
        jp: { word: 'てんぷら' },
    },
    {
        type: 'unknown',
        en: 'Black tea please.',
        pl: 'Poproszę czarną herbatę.',
        jp: { word: 'こうちゃをください。' },
    },
    {
        type: 'unknown',
        en: 'Water',
        pl: 'Woda',
        jp: { word: '水', pronunciation: 'みず' },
    },
    {
        type: 'unknown',
        en: 'Well then...',
        pl: 'Cóż, w takim razie ...',
        jp: { word: 'じゃあ…' },
    },
    {
        type: 'unknown',
        en: 'Onigiri',
        pl: 'Onigiri',
        jp: { word: 'おにぎり' },
    },
    {
        type: 'unknown',
        en: 'Big',
        pl: 'Duży',
        jp: { word: '大きい', pronunciation: 'おおきい' },
    },
    {
        type: 'unknown',
        en: 'Salad',
        pl: 'Sałatka',
        jp: { word: 'サラダ' },
    },
    {
        type: 'unknown',
        en: 'Soba',
        pl: 'Soba',
        jp: { word: 'そば' },
        description: 'Buckwheat noodles',
    },
    {
        type: 'unknown',
        en: "How's the miso soup?",
        pl: 'Jak jest zupa miso?',
        jp: { word: 'みそしるはどうですか？' },
    },
    {
        type: 'unknown',
        en: 'Small',
        pl: 'Mały',
        jp: { word: '小さい', pronunciation: 'ちいさい' },
    },
    {
        type: 'unknown',
        en: 'Black tea',
        pl: 'Czarna herbata',
        jp: { word: 'こうちゃ' },
    },
    {
        type: 'unknown',
        en: 'Ice cream',
        pl: 'Lody',
        jp: { word: 'アイスクリーム' },
    },
    {
        type: 'unknown',
        en: 'Iced coffee',
        pl: 'Kawa mrożona',
        jp: { word: 'アイスコーヒー' },
    },
    {
        type: 'unknown',
        en: 'A little',
        pl: 'Trochę',
        jp: { word: 'すこし' },
    },
    {
        type: 'unknown',
        en: 'Swim',
        pl: 'Pływać',
        jp: { word: 'およぎます' },
    },
    {
        type: 'unknown',
        en: 'Yoga',
        pl: 'Joga',
        jp: { word: 'ヨガ' },
    },
    {
        type: 'unknown',
        en: 'I do yoga every day.',
        pl: 'Codziennie uprawiam jogę.',
        jp: { word: 'まいにちヨガをします。' },
    },
    {
        type: 'unknown',
        en: 'With mr Ken',
        pl: 'Z panem Kenem',
        jp: { word: 'けんさんと' },
    },
    {
        type: 'unknown',
        en: 'By myself',
        pl: 'Samemu',
        jp: { word: 'ひとりで' },
    },
    {
        type: 'unknown',
        en: 'Weekend',
        pl: 'Weekend',
        jp: { word: 'しゅうまつ' },
    },
    {
        type: 'unknown',
        en: 'TV drama',
        pl: 'Serial telewizyjny',
        jp: { word: 'ドラマ' },
    },
    {
        type: 'unknown',
        en: 'Hang out',
        pl: 'Spędzać czas',
        jp: { word: 'あそびます' },
    },
];
