import type { TranslatedJapaneseText } from '../../types.ts';

export const duolingo_9: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Mount Fuji',
        pl: 'Góra Fuji',
        jp: { text: 'ふじさん' },
    },
    {
        type: 'noun',
        en: 'Souvenir',
        pl: 'Pamiątka',
        jp: { text: 'おみやげ' },
    },
    {
        type: 'noun',
        en: 'Sweets',
        pl: 'Słodycze',
        jp: { text: 'おかし' },
    },
    {
        type: 'noun',
        en: 'Postcard',
        pl: 'Pocztówka',
        jp: { text: 'ポストカード' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Wonderful',
        pl: 'Wspaniały',
        jp: { text: 'すてき' },
    },
    {
        type: 'phrase',
        en: 'What kind of ice cream do you like?',
        pl: 'Jakie lody lubisz?',
        jp: { text: 'どんなアイスクリームがすきですか。' },
    },
    {
        type: 'pre-noun-adjective',
        en: 'What kind of...',
        pl: 'Jaki rodzaj...',
        jp: { text: 'どんな' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Sit',
        pl: 'Siedzieć',
        jp: { text: 'すわる' },
        present: {
            masu: {
                affirmative: { text: 'すわります' },
                negative: { text: 'すわりません' },
            },
        },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dangerous',
        pl: 'Niebezpieczny',
        jp: { text: 'あぶない' },
    },
    {
        type: 'phrase',
        en: 'Feel bad',
        pl: 'Czuć się źle',
        jp: { text: 'ぐあいがわるいです。' },
    },
    {
        type: 'noun',
        en: 'Police',
        pl: 'Policja',
        jp: { text: 'けいさつ' },
    },
    {
        type: 'phrase',
        en: 'Police will come soon.',
        pl: 'Policja wkrótce przyjedzie.',
        jp: { text: 'けいさつはもうすぐきます。' },
    },
    {
        type: 'phrase',
        en: 'Taxi, please.',
        pl: 'Proszę taksówkę.',
        jp: { text: 'タクシーをおねがいします。' },
    },
    {
        type: 'noun',
        en: 'Allergy',
        pl: 'Alergia',
        jp: { text: 'アレルギー' },
    },
    {
        type: 'noun',
        en: 'Nearby / Neighborhood',
        pl: 'Okolica',
        jp: { text: 'ちかく' },
    },
    {
        type: 'noun',
        en: 'Today',
        pl: 'Dzisiaj',
        jp: { text: 'きょう' },
    },
    {
        type: 'phrase',
        en: 'I will rest today.',
        pl: 'Dzisiaj odpocznę.',
        jp: { text: 'きょうやすみます。' },
    },
    {
        type: 'noun',
        en: 'Park',
        pl: 'Park',
        jp: { text: 'こうえん' },
    },
    {
        type: 'noun',
        en: 'Rain',
        pl: 'Deszcz',
        jp: { text: 'あめ' },
    },
    {
        type: 'noun',
        en: 'Weather',
        pl: 'Pogoda',
        jp: { text: 'てんき' },
    },
    {
        type: 'noun',
        en: 'Spring',
        pl: 'Wiosna',
        jp: { text: 'はる' },
    },
    {
        type: 'noun',
        en: 'Summer',
        pl: 'Lato',
        jp: { text: 'なつ' },
    },
    {
        type: 'noun',
        en: 'Autumn',
        pl: 'Jesień',
        jp: { text: 'あき' },
    },
    {
        type: 'noun',
        en: 'Winter',
        pl: 'Zima',
        jp: { text: 'ふゆ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Warm',
        pl: 'Ciepły',
        jp: { text: 'あたたかい' },
    },
    {
        type: 'noun',
        en: 'Sunny',
        pl: 'Słoneczny',
        jp: { text: 'はれ' },
        description: 'Literally "clear weather"',
    },
    {
        type: 'phrase',
        en: 'I go to the beach in summer.',
        pl: 'Latem chodzę na plażę.',
        jp: { text: 'なつにうみにいきます。' },
        description: 'うみ means "sea". So the direct translation is "In summer, I go to the sea."',
    },
    {
        type: 'noun',
        en: 'Day',
        pl: 'Dzień',
        jp: { text: '日', pronunciation: 'ひ' },
    },
    {
        type: 'phrase',
        en: 'A sunny day',
        pl: 'Słoneczny dzień',
        jp: { text: 'はれのひ' },
    },
    {
        type: 'noun',
        en: 'Pool',
        pl: 'Basen',
        jp: { text: 'プール' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Hot',
        pl: 'Gorący',
        jp: { text: 'あつい' },
    },
    {
        type: 'noun',
        en: 'Fireworks',
        pl: 'Fajerwerki',
        jp: { text: 'はなび' },
    },
    {
        type: 'phrase',
        en: 'Summer break',
        pl: 'Wakacje letnie',
        jp: { text: 'なつやすみ' },
    },
    {
        type: 'noun',
        en: 'Break / Holiday',
        pl: 'Wakacje / Przerwa',
        jp: { text: 'やすみ' },
    },
    {
        type: 'noun',
        en: 'Cloudy',
        pl: 'Pochmurny',
        jp: { text: 'くもり' },
        description: 'Literally "cloudiness" or "clouded weather"',
    },
    {
        type: 'noun',
        en: 'This evening / Tonight',
        pl: 'Dziś wieczorem / Dziś nocą',
        jp: { text: 'こんばん' },
    },
    {
        type: 'noun',
        en: 'Concert',
        pl: 'Koncert',
        jp: { text: 'コンサート' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cold',
        pl: 'Zimny',
        jp: { text: 'さむい' },
    },
    {
        type: 'noun',
        en: 'Snow',
        pl: 'Śnieg',
        jp: { text: 'ゆき' },
    },
    {
        type: 'noun',
        en: 'Hot chocolate',
        pl: 'Gorąca czekolada',
        jp: { text: 'ココア' },
    },
    {
        type: 'noun',
        en: 'Hot spring',
        pl: 'Gorące źródło',
        jp: { text: 'おんせん' },
    },
    {
        type: 'adverb',
        en: 'Properly / Appropriately',
        pl: 'Właściwie / Odpowiednio',
        jp: { text: 'ちゃんと' },
    },
    {
        type: 'phrase',
        en: 'Eat your vegetables properly.',
        pl: 'Jedz warzywa właściwie.',
        jp: { text: 'やさいをちゃんとたべなさい。' },
    },
    {
        type: 'phrase',
        en: 'Today is still cold.',
        pl: 'Dziś jest nadal zimno.',
        jp: { text: 'きょうはまださむいです。' },
    },
    {
        type: 'phrase',
        en: 'What kind of person is your older sister?',
        pl: 'Jaka jest twoja starsza siostra?',
        jp: { text: 'おねえさんはどんなひとですか。' },
    },
    {
        type: 'noun',
        en: 'Coach',
        pl: 'Trener',
        jp: { text: 'コーチ' },
    },
];
