import type { JapaneseWord } from '../../types.ts';

export const duolingo_4: JapaneseWord[] = [
    {
        type: 'verb',
        en: 'To watch',
        pl: 'Oglądać',
        jp: '見ます',
        jp_pronunciation: 'みます',
    },
    {
        type: 'noun',
        en: 'Soccer',
        pl: 'Piłka nożna',
        jp: 'サッカー',
    },
    {
        type: 'verb',
        en: 'Do',
        pl: 'Robić',
        jp: 'します',
    },
    {
        type: 'noun',
        en: 'Basketball',
        pl: 'Koszykówka',
        jp: 'バスケットボール',
    },
    {
        type: 'other',
        en: 'Often',
        pl: 'Często',
        jp: 'よく',
    },
    {
        type: 'noun',
        en: 'JPop',
        pl: 'Japoński pop',
        jp: 'Jポップ',
    },
    {
        type: 'verb',
        en: 'To listen / To hear',
        pl: 'Słuchać / Słyszeć',
        jp: 'ききます',
    },
    {
        type: 'noun',
        en: 'Rock music',
        pl: 'Muzyka rockowa',
        jp: 'ロック',
    },
    {
        type: 'noun',
        en: 'TV',
        pl: 'Telewizja',
        jp: 'テレビ',
    },
    {
        type: 'noun',
        en: 'Movie',
        pl: 'Film',
        jp: 'えいが',
    },
    {
        type: 'other',
        en: 'Sometimes',
        pl: 'Czasami',
        jp: 'ときどき',
    },
    {
        type: 'noun',
        en: 'Music',
        pl: 'Muzyka',
        jp: 'おんがく',
    },
    {
        type: 'noun',
        en: 'Jazz',
        pl: 'Jazz',
        jp: 'ジャズ',
    },
    {
        type: 'noun',
        en: 'Book',
        pl: 'Książka',
        jp: '本',
        jp_pronunciation: 'ほん',
    },
    {
        type: 'verb',
        en: 'To read',
        pl: 'Czytać',
        jp: '読みます',
        jp_pronunciation: 'よみます',
    },
    {
        type: 'noun',
        en: 'News',
        pl: 'Wiadomości',
        jp: 'ニュース',
    },
    {
        type: 'noun',
        en: 'Magazine',
        pl: 'Czasopismo',
        jp: 'ざっし',
    },
    {
        type: 'noun',
        en: 'Manga',
        pl: 'Manga',
        jp: 'まんが',
    },
    {
        type: 'noun',
        en: 'Baseball',
        pl: 'Baseball',
        jp: 'やきゅう',
    },
    {
        type: 'verb',
        en: 'Eat',
        pl: 'Jeść',
        jp: '食べます',
        jp_pronunciation: 'たべます',
    },
    {
        type: 'noun',
        en: 'Every morning',
        pl: 'Każdego poranka',
        jp: 'まいあさ',
    },
    {
        type: 'verb',
        en: 'Drink',
        pl: 'Pić',
        jp: 'のみます',
    },
    {
        type: 'noun',
        en: 'Hour',
        pl: 'Godzina',
        jp: '時',
        jp_pronunciation: 'じ',
    },
    {
        type: 'noun',
        en: 'Dinner',
        pl: 'Kolacja',
        jp: 'ばんごはん',
    },
    {
        type: 'noun',
        en: 'What',
        pl: 'Co',
        jp: '何',
        jp_pronunciation: 'なに',
    },
    {
        type: 'noun',
        en: 'Bread',
        pl: 'Chleb',
        jp: 'パン',
    },
    {
        type: 'adjective',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: 'おいしい',
    },
    {
        type: 'noun',
        en: 'Sandwich',
        pl: 'Kanapka',
        jp: 'サンドイッチ',
    },
    {
        type: 'noun',
        en: 'Every day',
        pl: 'Codziennie',
        jp: 'まいにち',
    },
    {
        type: 'noun',
        en: 'Juice',
        pl: 'Sok',
        jp: 'ジュース',
    },
    {
        type: 'noun',
        en: 'Coffee',
        pl: 'Kawa',
        jp: 'コーヒー',
    },
    {
        type: 'noun',
        en: 'Breakfast',
        pl: 'Śniadanie',
        jp: 'あさごはん',
    },
    {
        type: 'noun',
        en: 'Boxed lunch',
        pl: 'Pudełkowy lunch',
        jp: 'べんとう',
    },
    {
        type: 'noun',
        en: 'Every night',
        pl: 'Każdej nocy',
        jp: 'まいばん',
    },
    {
        type: 'adjective',
        en: 'Old (thing)',
        pl: 'Stary (rzecz)',
        jp: '古い',
        jp_description: 'ふるい',
    },
    {
        type: 'adjective',
        en: 'New (thing)',
        pl: 'Nowy (rzecz)',
        jp: '新しい',
        jp_description: 'あたらしい',
    },
    {
        type: 'noun',
        en: 'Clothes',
        pl: 'Ubrania',
        jp: 'ふく',
    },
    {
        type: 'noun',
        en: 'Wallet',
        pl: 'Portfel',
        jp: 'さいふ',
    },
    {
        type: 'adjective',
        en: 'Unfashionable / Not trendy',
        pl: 'Niemodny / Nietrendy',
        jp: 'ダサい',
    },
    {
        type: 'noun',
        en: 'Skirt',
        pl: 'Spódnica',
        jp: 'スカート',
    },
];
