import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_1: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Cooked rice',
        pl: 'Gotowany ryż',
        jp: { text: 'ご飯', pronunciation: 'ごはん' },
    },
    {
        type: 'noun',
        en: 'Water',
        pl: 'Woda',
        jp: { text: '水', pronunciation: 'みず' },
    },
    {
        type: 'noun',
        en: 'Sushi',
        pl: 'Sushi',
        jp: { text: 'すし' },
    },
    {
        type: 'phrase',
        en: 'Please',
        pl: 'Proszę',
        jp: { text: 'ください' },
    },
    {
        type: 'particle',
        en: 'And',
        pl: 'I / Oraz',
        jp: { text: 'と' },
    },
    {
        type: 'noun',
        en: 'Green tea',
        pl: 'Zielona herbata',
        jp: { text: 'お茶', pronunciation: 'おちゃ' },
    },
    {
        type: 'verb',
        verb_type: 'auxiliary',
        en: 'Is',
        pl: 'Jest',
        jp: { text: 'です' },
    },
    {
        type: 'noun',
        en: 'Doctor',
        pl: 'Lekarz',
        jp: { text: '医者', pronunciation: 'いしゃ' },
    },
    {
        type: 'noun',
        en: 'Teacher',
        pl: 'Nauczyciel',
        jp: { text: '先生', pronunciation: 'せんせい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cool / Good-looking',
        pl: 'Fajny / Przystojny',
        jp: { text: '格好いい', pronunciation: 'かっこいい' },
    },
    {
        type: 'noun',
        en: 'Lawyer',
        pl: 'Prawnik',
        jp: { text: '弁護士', pronunciation: 'べんごし' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Kind / Gentle',
        pl: 'Uprzejmy / Życzliwy',
        jp: { text: '優しい', pronunciation: 'やさしい' },
    },
    {
        type: 'noun',
        en: 'Person',
        pl: 'Osoba',
        jp: { text: '人', pronunciation: 'ひと' },
    },
    {
        type: 'noun',
        en: 'Student',
        pl: 'Student',
        jp: { text: '学生', pronunciation: 'がくせい' },
    },
    {
        type: 'phrase',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: { text: 'こんにちは' },
    },
    {
        type: 'phrase',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: { text: 'おはようございます' },
        description: "Polite form of 'Good morning'. Casual form is just おはよう.",
    },
    {
        type: 'phrase',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: { text: 'こんばんは' },
    },
    {
        type: 'phrase',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: { text: 'お休みなさい', pronunciation: 'おやすみなさい' },
        description: "Polite form of 'Good night'. Casual form is just おやすみ.",
    },
    {
        type: 'phrase',
        en: 'Goodbye',
        pl: 'Do widzenia',
        jp: { text: 'さようなら' },
    },
    {
        type: 'suffix',
        en: 'Mr. / Ms.',
        pl: 'Pan / Pani',
        jp: { text: 'さん' },
        description: 'Polite suffix added to names.',
    },
    {
        type: 'phrase',
        en: 'Nice to meet you',
        pl: 'Miło cię poznać',
        jp: { text: 'どうぞよろしく' },
        description:
            "Used when meeting someone for the first time or at the end of a self-introduction. Literally means 'Please treat me well'.",
    },
    {
        type: 'phrase',
        en: 'See you tomorrow',
        pl: 'Do zobaczenia jutro',
        jp: { text: 'また明日', pronunciation: 'またあした' },
    },
    {
        type: 'pronoun',
        en: 'This (close to speaker)',
        pl: 'To (blisko mówiącego)',
        jp: { text: 'これ' },
    },
    {
        type: 'pronoun',
        en: 'That (close to listener)',
        pl: 'To (blisko słuchającego)',
        jp: { text: 'それ' },
    },
    {
        type: 'noun',
        en: 'Ramen',
        pl: 'Ramen',
        jp: { text: 'ラーメン' },
    },
    {
        type: 'noun',
        en: 'Curry',
        pl: 'Curry',
        jp: { text: 'カレー' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: { text: '美味しい', pronunciation: 'おいしい' },
    },
    {
        type: 'noun',
        en: 'Pizza',
        pl: 'Pizza',
        jp: { text: 'ピザ' },
    },
    {
        type: 'noun',
        en: 'Cake',
        pl: 'Ciasto',
        jp: { text: 'ケーキ' },
    },
    {
        type: 'phrase',
        en: 'Yes',
        pl: 'Tak',
        jp: { text: 'はい' },
    },
    {
        type: 'phrase',
        en: 'No',
        pl: 'Nie',
        jp: { text: 'いいえ' },
    },
    {
        type: 'suffix',
        en: 'Person from a country',
        pl: 'Osoba z danego kraju',
        jp: { text: '人', pronunciation: 'じん' },
        description: 'Suffix added to country names to indicate citizenship.',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Small',
        pl: 'Mały',
        jp: { text: '小さい', pronunciation: 'ちいさい' },
    },
    {
        type: 'phrase',
        en: 'Sorry / Excuse me',
        pl: 'Przepraszam',
        jp: { text: 'すみません' },
    },
];

export const duolingo1Bag: WordBag = {
    id: '72d4f2a1-6963-497e-85a6-b6c2458da116',
    name: 'Duolingo #1',
    words: duolingo_1,
};
