import type { JapaneseWord } from '../../types.ts';

export const duolingo_8: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Air conditioning',
        pl: 'Klimatyzacja',
        jp: 'エアコン',
    },
    {
        type: 'noun',
        en: 'Vacuum cleaner',
        pl: 'Odkurzacz',
        jp: 'そうじき',
    },
    {
        type: 'phrase',
        en: "I still don't have a vacuum cleaner.",
        pl: 'Nadal nie mam odkurzacza.',
        jp: 'まだそうじきはありません。',
    },
    {
        type: 'noun',
        en: 'Table',
        pl: 'Stół',
        jp: 'テーブル',
    },
    {
        type: 'noun',
        en: 'Japanese mattress',
        pl: 'Japoński materac',
        jp: 'ふとん',
    },
    {
        type: 'other',
        en: 'Probably',
        pl: 'Prawdopodobnie',
        jp: 'たぶん',
    },
    {
        type: 'noun',
        en: 'Microwave',
        pl: 'Mikrofalówka',
        jp: 'でんしレンジ',
    },
    {
        type: 'noun',
        en: 'Fridge',
        pl: 'Lodówka',
        jp: 'れいぞうこ',
    },
    {
        type: 'noun',
        en: 'Desk',
        pl: 'Biurko',
        jp: 'つくえ',
    },
    {
        type: 'noun',
        en: 'When',
        pl: 'Kiedy',
        jp: 'いつ',
    },
    {
        type: 'noun',
        en: 'This week',
        pl: 'Ten tydzień',
        jp: 'こんしゅう',
    },
    {
        type: 'noun',
        en: 'Washing machine',
        pl: 'Pralka',
        jp: 'せんたくき',
    },
    {
        type: 'adjective',
        en: 'High',
        pl: 'Wysoki',
        jp: '高い',
        jp_pronunciation: 'たかい',
    },
    {
        type: 'adjective',
        en: 'Expensive',
        pl: 'Drogi',
        jp: '高い',
        jp_pronunciation: 'たかい',
    },
    {
        type: 'phrase',
        en: 'Where are you from?',
        pl: 'Skąd jesteś?',
        jp: 'しゅっしんはどこですか。',
    },
    {
        type: 'noun',
        en: 'City',
        pl: 'Miasto (duże)',
        jp: 'とし',
    },
    {
        type: 'noun',
        en: 'Town',
        pl: 'Miasto (małe)',
        jp: 'まち',
    },
    {
        type: 'noun',
        en: 'Apartment',
        pl: 'Mieszkanie',
        jp: 'アパート',
    },
    {
        type: 'noun',
        en: 'Train',
        pl: 'Pociąg',
        jp: 'でんしゃ',
    },
    {
        type: 'noun',
        en: 'Shibuya',
        pl: 'Shibuya',
        jp: 'しぶや',
    },
    {
        type: 'noun',
        en: 'Nearby',
        pl: 'W pobliżu',
        jp: 'ちかく',
    },
    {
        type: 'verb',
        en: 'Go',
        pl: 'Iść',
        jp: '行きます',
        jp_pronunciation: 'いきます',
    },
    {
        type: 'noun',
        en: 'Bus',
        pl: 'Autobus',
        jp: 'バス',
    },
    {
        type: 'noun',
        en: 'Next',
        pl: 'Następny',
        jp: 'つぎ',
    },
    {
        type: 'noun',
        en: 'Yokohama',
        pl: 'Yokohama',
        jp: 'よこはま',
    },
    {
        type: 'noun',
        en: 'Akihabara',
        pl: 'Akihabara',
        jp: 'あきはばら',
    },
    {
        type: 'other',
        en: 'Soon',
        pl: 'Wkrótce',
        jp: 'もうすぐ',
    },
    {
        type: 'verb',
        en: 'Come',
        pl: 'Przyjść',
        jp: '来ます',
        jp_pronunciation: 'きます',
    },
    {
        type: 'noun',
        en: 'Asakusa',
        pl: 'Asakusa',
        jp: 'あさくさ',
    },
    {
        type: 'noun',
        en: 'Ueno Park',
        pl: 'Park Ueno',
        jp: 'うえのこうえん',
    },
    {
        type: 'adjective',
        en: 'Fast',
        pl: 'Szybki',
        jp: 'はやい',
    },
    {
        type: 'verb',
        en: 'Take (time)',
        pl: 'Zająć (czas)',
        jp: 'かかります',
    },
    {
        type: 'other',
        en: 'Around (for period of time)',
        pl: 'Około (dla okresu czasu)',
        jp: 'ぐらい',
    },
    {
        type: 'noun',
        en: 'Hour (period of time)',
        pl: 'Godzina (okres czasu)',
        jp: '時間',
        jp_pronunciation: 'じかん',
    },
    {
        type: 'adjective',
        en: 'Long',
        pl: 'Długi',
        jp: 'ながい',
    },
    {
        type: 'noun',
        en: 'Last station',
        pl: 'Ostatnia stacja',
        jp: 'しゅうてん',
    },
    {
        type: 'phrase',
        en: 'When will the next train come?',
        pl: 'Kiedy przyjedzie następny pociąg?',
        jp: 'つぎのでんしゃはいつきますか。',
    },
    {
        type: 'phrase',
        en: 'How long',
        pl: 'Jak długo',
        jp: 'どのぐらい',
    },
    {
        type: 'noun',
        en: 'Place',
        pl: 'Miejsce',
        jp: 'ところ',
    },
    {
        type: 'noun',
        en: 'Building',
        pl: 'Budynek',
        jp: 'たてもの',
    },
    {
        type: 'noun',
        en: 'Temple',
        pl: 'Świątynia',
        jp: 'おてら',
    },
    {
        type: 'noun',
        en: 'Pizzeria',
        pl: 'Pizzeria',
        jp: 'ピザや',
    },
    {
        type: 'noun',
        en: 'Ramen restaurant',
        pl: 'Restauracja z ramenem',
        jp: 'ラーメンや',
    },
    {
        type: 'noun',
        en: 'Harajuku',
        pl: 'Harajuku',
        jp: 'はらじゅく',
    },
    {
        type: 'noun',
        en: 'Shinto shrine',
        pl: 'Świątynia shinto',
        jp: 'じんじゃ',
    },
    {
        type: 'noun',
        en: 'Mountain',
        pl: 'Góra',
        jp: '山',
        jp_pronunciation: 'やま',
    },
];
