import type { JapaneseWord } from '../../types.ts';

export const duolingo_1: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Rice',
        pl: 'Ryż',
        jp: 'ごはん',
    },
    {
        type: 'unknown',
        en: 'Water',
        pl: 'Woda',
        jp: 'みず',
    },
    {
        type: 'unknown',
        en: 'Sushi',
        pl: 'Sushi',
        jp: 'すし',
    },
    {
        type: 'unknown',
        en: 'Please',
        pl: 'Proszę',
        jp: 'ください',
    },
    {
        type: 'unknown',
        en: 'And',
        pl: 'I / Oraz',
        jp: 'と',
    },
    {
        type: 'unknown',
        en: 'Tea',
        pl: 'Herbata',
        jp: 'おちゃ',
    },
    {
        type: 'unknown',
        en: 'Is',
        pl: 'Jest',
        jp: 'です',
    },
    {
        type: 'unknown',
        en: 'Doctor',
        pl: 'Lekarz',
        jp: 'いしゃ',
    },
    {
        type: 'unknown',
        en: 'Teacher',
        pl: 'Nauczyciel',
        jp: 'せんせい',
    },
    {
        type: 'unknown',
        en: 'Cool',
        pl: 'Fajny',
        jp: 'かっこいい',
    },
    {
        type: 'unknown',
        en: 'Lawyer',
        pl: 'Prawnik',
        jp: 'べんごし',
    },
    {
        type: 'unknown',
        en: 'Nice',
        pl: 'Miły',
        jp: 'やさしい',
    },
    {
        type: 'unknown',
        en: 'Person',
        pl: 'Osoba',
        jp: 'ひと',
    },
    {
        type: 'unknown',
        en: 'Student',
        pl: 'Uczeń',
        jp: 'がくせい',
    },
    {
        type: 'unknown',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: 'こんにちは',
    },
    {
        type: 'unknown',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: 'おはようございます',
        jp_description: "Polite form of 'Good morning'. Casual form is just おはよう.",
    },
    {
        type: 'unknown',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: 'こんばんは',
    },
    {
        type: 'unknown',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: 'おやすみなさい',
        jp_description: "Polite form of 'Good night'. Casual form is just おやすみ.",
    },
    {
        type: 'unknown',
        en: 'Goodbye',
        pl: 'Do widzenia',
        jp: 'さようなら',
    },
    {
        type: 'unknown',
        en: 'Mr. / Ms.',
        pl: 'Pan / Pani',
        jp: 'さん',
        jp_description: 'Polite suffix added to names.',
    },
    {
        type: 'unknown',
        en: 'Nice to get to know you',
        pl: 'Miło cię poznać',
        jp: 'どうぞよろしく',
        jp_description:
            "Used when meeting someone for the first time or at the end of a self-introduction. Literally means 'Please treat me well'.",
    },
    {
        type: 'unknown',
        en: 'See you tomorrow',
        pl: 'Do zobaczenia jutro',
        jp: 'またあした',
    },
    {
        type: 'unknown',
        en: 'This (close to speaker)',
        pl: 'To (blisko mówiącego)',
        jp: 'これ',
    },
    {
        type: 'unknown',
        en: 'That (close to listener)',
        pl: 'To (blisko słuchającego)',
        jp: 'それ',
    },
    {
        type: 'unknown',
        en: 'Ramen',
        pl: 'Ramen',
        jp: 'ラーメン',
    },
    {
        type: 'unknown',
        en: 'Curry',
        pl: 'Curry',
        jp: 'カレー',
    },
    {
        type: 'unknown',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: 'おいしい',
    },
    {
        type: 'unknown',
        en: 'Pizza',
        pl: 'Pizza',
        jp: 'ピザ',
    },
    {
        type: 'unknown',
        en: 'Cake',
        pl: 'Ciasto',
        jp: 'ケーキ',
    },
    {
        type: 'unknown',
        en: 'Yes',
        pl: 'Tak',
        jp: 'はい',
    },
    {
        type: 'unknown',
        en: 'No',
        pl: 'Nie',
        jp: 'いいえ',
    },
    {
        type: 'unknown',
        en: 'Citizen (suffix)',
        pl: 'Obywatel (przyrostek)',
        jp: 'じん',
        jp_description: 'Suffix added to country names to indicate citizenship.',
    },
    {
        type: 'unknown',
        en: 'Small',
        pl: 'Mały',
        jp: 'ちいさい',
    },
    {
        type: 'unknown',
        en: 'Sorry',
        pl: 'Przepraszam',
        jp: 'すみません',
    },
];
