import type { TranslatedJapaneseText, WordBag } from '../../types';

const duolingo_14: TranslatedJapaneseText[] = [
    {
        id: '45b2ca73-1b44-43fc-b217-ba22f3c2ad30',
        type: 'noun',
        en: 'Present',
        pl: 'Prezent',
        jp: { text: 'プレゼント' },
    },
    {
        id: '10fd5616-e17c-4449-ba24-f01750f96c7e',
        type: 'noun',
        en: 'Suit',
        pl: 'Garnitur',
        jp: { text: 'スーツ' },
    },
    {
        id: '088bcfc8-f567-47c3-97bd-9bd1de26dacb',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Wear',
        pl: 'Nosić',
        jp: { text: '着る', pronunciation: 'きる' },
    },
    {
        id: 'b139ee94-e963-4ae6-bc69-444bdc90f98e',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'White',
        pl: 'Biały',
        jp: { text: '白い', pronunciation: 'しろい' },
    },
    {
        id: 'f6bd83c1-edc9-4d2b-87c8-eee4e7692251',
        type: 'noun',
        en: 'Blouse',
        pl: 'Bluzka',
        jp: { text: 'ブラウス' },
    },
    {
        id: '3ed6be56-6c0d-44d1-a867-bc4eb317cbc9',
        type: 'noun',
        en: 'Movie theater',
        pl: 'Kino',
        jp: { text: '映画館', pronunciation: 'えいがかん' },
    },
    {
        id: '6f0a1929-79b7-4589-92d5-39f5187a6ff3',
        type: 'noun',
        en: 'Director',
        pl: 'Reżyser',
        jp: { text: '監督', pronunciation: 'かんとく' },
    },
    {
        id: '5ce61703-547c-49e5-b3b5-061384ffb1cc',
        type: 'noun',
        en: 'Hot dog',
        pl: 'Hot dog',
        jp: { text: 'ホットドッグ' },
    },
    {
        id: '8867921f-595b-4310-92e1-133264838b3a',
        type: 'noun',
        en: 'Popcorn',
        pl: 'Popcorn',
        jp: { text: 'ポップコーン' },
    },
    {
        id: '9ddfa9bb-d85b-42db-b8b8-3da9fc3e91f6',
        type: 'verb',
        verb_type: 'suru',
        en: 'Reserve',
        pl: 'Rezerwować',
        jp: { text: '予約する', pronunciation: 'よやくする' },
    },
    {
        id: '35330efd-7549-47ae-9ac6-590993f3c2bd',
        type: 'phrase',
        en: 'I will reserve a movie ticket.',
        pl: 'Zarezerwuję bilet na film.',
        jp: { text: '映画のチケットを予約します。', pronunciation: 'えいがのチケットをよやくします。' },
    },
    {
        id: '77d46530-0af3-42ed-9d08-05efb1e0965c',
        type: 'noun',
        en: 'Wine',
        pl: 'Wino',
        jp: { text: 'ワイン' },
    },
    {
        id: '9b2bb7e3-1cfd-493b-96bf-aac29e2662c4',
        type: 'noun',
        en: 'Steak',
        pl: 'Stek',
        jp: { text: 'ステーキ' },
    },
    {
        id: '119bba33-340a-4b56-8540-425e2ab210de',
        type: 'noun',
        en: 'Song',
        pl: 'Piosenka',
        jp: { text: '歌', pronunciation: 'うた' },
    },
    {
        id: '2e3900e5-3586-4489-9770-ac1aa9f456a0',
        type: 'phrase',
        en: 'I will sing a birthday song.',
        pl: 'Zaśpiewam piosenkę urodzinową.',
        jp: { text: '誕生日の歌を歌います。', pronunciation: 'たんじょうびのうたをうたいます。' },
    },
    {
        id: '7da9b6cb-168d-4c45-8f5b-4352322540e9',
        type: 'noun',
        en: 'Ticket window / Box office',
        pl: 'Okienko biletowe / Kasa biletowa',
        jp: { text: '切符売り場', pronunciation: 'きっぷうりば' },
    },
    {
        id: 'e5898007-7293-4bf4-89dd-0f68e33f89cd',
        type: 'noun',
        en: 'Monorail',
        pl: 'Kolejka jednoszynowa',
        jp: { text: 'モノレール' },
    },
    {
        id: 'f2ae3a05-46d6-4a55-a60d-c9acc39eb929',
        type: 'noun',
        en: 'Platform number one',
        pl: 'Peron numer jeden',
        jp: { text: '一番ホーム', pronunciation: 'いちばんホーム' },
    },
    {
        id: '70a28e06-2ba2-46fa-a469-f1e761ec8ee9',
        type: 'noun',
        en: 'Orange',
        pl: 'Pomarańcza',
        jp: { text: 'オレンジ' },
    },
    {
        id: 'faf992fc-4c2c-4569-98e5-f157aad76637',
        type: 'noun',
        en: 'High speed / Rapid',
        pl: 'Wysoka prędkość / Pospieszny',
        jp: { text: '快速', pronunciation: 'かいそく' },
    },
    {
        id: '8f69d5f8-304d-4cf0-b671-e2be2b8f9c63',
        type: 'noun',
        en: 'Rapid train',
        pl: 'Szybki pociąg',
        jp: { text: '快速電車', pronunciation: 'かいそくでんしゃ' },
    },
    {
        id: 'f260f8de-74dd-436e-97ef-a2698524f02c',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get off',
        pl: 'Wysiadać',
        jp: { text: '降りる', pronunciation: 'おりる' },
    },
    {
        id: '6ed58a00-06ce-46fc-9710-fd129380f9ca',
        type: 'phrase',
        en: 'I will get off at the next station.',
        pl: 'Wysiądę na następnym przystanku.',
        jp: { text: '次の駅で降ります。', pronunciation: 'つぎのえきでおります。' },
    },
    {
        id: '30ab7dbb-98da-4e7c-a08a-0f55faa7fa2e',
        type: 'phrase',
        en: 'I will get off the train.',
        pl: 'Wysiądę z pociągu.',
        jp: { text: '電車を降ります。', pronunciation: 'でんしゃをおります。' },
    },
    {
        id: '0e2d15ef-4825-497f-81fa-fd716d9e7645',
        type: 'noun',
        en: 'North exit',
        pl: 'Wyjście północne',
        jp: { text: '北口', pronunciation: 'きたぐち' },
    },
    {
        id: '39398630-752c-4c70-b1ce-b12afc3f143e',
        type: 'noun',
        en: 'Escalator',
        pl: 'Schody ruchome',
        jp: { text: 'エスカレーター' },
    },
    {
        id: 'c43e677e-5ac9-444c-9a2b-716bd3f0a473',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Transfer',
        pl: 'Przesiadać się',
        jp: { text: '乗り換える', pronunciation: 'のりかえる' },
    },
    {
        id: '8d7d69ff-c642-4e97-8483-db57e2e1c566',
        type: 'noun',
        en: 'Tour',
        pl: 'Wycieczka',
        jp: { text: 'ツアー' },
    },
    {
        id: '2601a7a0-2b8d-4189-abc4-0d11bdfb4f0c',
        type: 'verb',
        verb_type: 'godan',
        en: 'Pay',
        pl: 'Płacić',
        jp: { text: '払う', pronunciation: 'はらう' },
    },
    {
        id: 'a8dea32f-efd3-4200-a723-15841fc9e4d5',
        type: 'noun',
        en: 'Information desk',
        pl: 'Punkt informacyjny',
        jp: { text: 'インフォメーション' },
    },
    {
        id: 'fae6ee0b-9ccf-4f02-b924-cc2ea9df3678',
        type: 'noun',
        en: 'Drink',
        pl: 'Napój',
        jp: { text: '飲み物', pronunciation: 'のみもの' },
    },
    {
        id: '5e8d5f7e-1954-449c-abd9-78f4915b0763',
        type: 'noun',
        en: 'South exit',
        pl: 'Wyjście południowe',
        jp: { text: '南口', pronunciation: 'みなみぐち' },
    },
    {
        id: 'f3a1c559-f6ef-4465-84d1-1bf720f9deff',
        type: 'verb',
        verb_type: 'suru',
        en: 'Relax',
        pl: 'Relaksować się',
        jp: { text: 'ゆっくりする' },
        description: 'ゆっくりする is an adverb + する rather than a noun + する, which is atypical for suru verbs.',
    },
    {
        id: '8abb1773-f516-4504-9f4f-c0d12ae930f0',
        type: 'verb',
        verb_type: 'godan',
        en: 'Call / Invite / Summon',
        pl: 'Wołać / Zapraszać / Przywoływać',
        jp: { text: '呼ぶ', pronunciation: 'よぶ' },
    },
    {
        id: 'd2b05bb0-1c28-4c0f-8934-9978b81252cb',
        type: 'phrase',
        en: 'I will call a taxi at the north exit.',
        pl: 'Zamówię taksówkę przy wyjściu północnym.',
        jp: { text: '北口でタクシーを呼びます。', pronunciation: 'きたぐちでタクシーをよびます。' },
    },
    {
        id: '06923650-1e51-46d2-8fad-716ea04ff34c',
        type: 'phrase',
        en: 'Which bus do I take?',
        pl: 'Którym autobusem mam jechać?',
        jp: { text: 'どのバスに乗りますか。', pronunciation: 'どのバスにのりますか。' },
    },
    {
        id: '6b8695eb-635b-4c2f-8f9f-3eabced9aab1',
        type: 'noun',
        en: 'First year student',
        pl: 'Student pierwszego roku',
        jp: { text: '一年生', pronunciation: 'いちねんせい' },
    },
    {
        id: 'f8efef97-ea2d-475b-a1ea-7d615d9b6010',
        type: 'noun',
        en: 'Second year student',
        pl: 'Student drugiego roku',
        jp: { text: '二年生', pronunciation: 'にねんせい' },
    },
    {
        id: 'be7ed6f7-10e4-47dd-8292-e707529e4553',
        type: 'noun',
        en: 'Third year student',
        pl: 'Student trzeciego roku',
        jp: { text: '三年生', pronunciation: 'さんねんせい' },
    },
    {
        id: '12f6af6d-0615-4007-a369-02cb44509c99',
        type: 'noun',
        en: 'Fourth year student',
        pl: 'Student czwartego roku',
        jp: { text: '四年生', pronunciation: 'よねんせい' },
    },
    {
        id: '67e4d47b-bf49-48ab-bda5-23507cd7a75e',
        type: 'phrase',
        en: 'Which year student are you?',
        pl: 'Studentem którego roku jesteś?',
        jp: { text: '何年生ですか。', pronunciation: 'なんねんせいですか。' },
    },
    {
        id: '3b7cc7a7-7082-48e7-b67d-f9ed917f9151',
        type: 'noun',
        en: 'University major',
        pl: 'Kierunek studiów',
        jp: { text: '専攻', pronunciation: 'せんこう' },
    },
    {
        id: 'b7e17195-9adc-4e51-a30f-eba290c3edb2',
        type: 'noun',
        en: 'Mathematics',
        pl: 'Matematyka',
        jp: { text: '数学', pronunciation: 'すうがく' },
    },
    {
        id: '740a8794-5989-4ef8-9946-3495736885f5',
        type: 'noun',
        en: 'Business',
        pl: 'Biznes',
        jp: { text: 'ビジネス' },
    },
    {
        id: '0a2824ef-5d4b-4413-9272-3e7f9feae5e4',
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: { text: 'ドイツ' },
    },
    {
        id: '3e30de78-7118-47e9-a215-17752ad2210f',
        type: 'noun',
        en: 'Language',
        pl: 'Język',
        jp: { text: '言語', pronunciation: 'げんご' },
    },
    {
        id: 'caca0ff1-357a-4693-8de8-42b6609dfba9',
        type: 'noun',
        en: 'Philippines',
        pl: 'Filipiny',
        jp: { text: 'フィリピン' },
    },
    {
        id: '9531baec-5bed-484d-829b-3a215222f480',
        type: 'phrase',
        en: 'Which languages do you know?',
        pl: 'Jakie języki znasz?',
        jp: { text: 'どの言語ができますか。', pronunciation: 'どのげんごができますか。' },
    },
    {
        id: 'c4b3b7e2-4622-466b-8761-1f075d52bb25',
        type: 'noun',
        en: 'Dormitory',
        pl: 'Akademik',
        jp: { text: '寮', pronunciation: 'りょう' },
    },
    {
        id: '9c4bf5ab-8329-422a-80c0-62f9e03f0403',
        type: 'noun',
        en: 'Campus',
        pl: 'Kampus',
        jp: { text: 'キャンパス' },
    },
    {
        id: '43a4602e-40bf-4697-8acc-5f29446de7ee',
        type: 'phrase',
        en: 'Tokyo station is near my dormitory.',
        pl: 'Stacja Tokyo jest blisko mojego akademika.',
        jp: { text: '東京駅は私の寮の近くです。', pronunciation: 'とうきょうえきはわたしのりょうのちかくです。' },
    },
    {
        id: 'a9493845-0ebf-43fa-b94c-0bfaba1857be',
        type: 'noun',
        en: 'Roommate',
        pl: 'Współlokator / Współlokatorka',
        jp: { text: 'ルームメート' },
    },
    {
        id: '83a6c48f-8d36-4a5e-8b8d-6d1edc23ad99',
        type: 'noun',
        pl: 'Koło zainteresowań',
        en: 'Club (university) / Circle of interest',
        jp: { text: 'サークル' },
    },
    {
        id: '3219adfd-8033-4e6c-8170-89a1d9c1f258',
        type: 'noun',
        en: 'Board game',
        pl: 'Gra planszowa',
        jp: { text: 'ボードゲーム' },
    },
    {
        id: 'cad021e6-cce0-4dd5-8423-d2b1749ebcf3',
        type: 'noun',
        en: 'Volunteer',
        pl: 'Wolontariusz / Wolontariuszka',
        jp: { text: 'ボランティア' },
    },
    {
        id: '36869aa6-1983-4ddc-9d99-8c292cd95f3a',
        type: 'noun',
        en: 'Chess',
        pl: 'Szachy',
        jp: { text: 'チェス' },
    },
    {
        id: '963f10c1-617f-4459-908d-5643a4ce2882',
        type: 'verb',
        en: 'Enter / Come in / Join',
        pl: 'Wejść / Dołączyć',
        verb_type: 'godan',
        jp: { text: '入る', pronunciation: 'はいる' },
    },
    {
        id: 'eb52c3d2-9c05-40c4-848d-39a98d49947a',
        type: 'phrase',
        en: 'I will join the chess club.',
        pl: 'Dołączę do klubu szachowego.',
        jp: { text: 'チェスサークルに入ります。', pronunciation: 'チェスサークルにはいります。' },
    },
    {
        id: '16e03179-7e67-43b3-b66a-db1e37594bc0',
        type: 'verb',
        verb_type: 'godan',
        en: 'Speak / Talk',
        pl: 'Mówić / Rozmawiać',
        jp: { text: '話す', pronunciation: 'はなす' },
    },
    {
        id: 'd5ee2a30-f221-4218-aeed-ec1c455b7413',
        type: 'phrase',
        en: 'I speak German with my roommate.',
        pl: 'Mówię po niemiecku z moim współlokatorem.',
        jp: { text: 'ルームメートとドイツ語を話します。', pronunciation: 'ルームメートとドイツごをはなします。' },
    },
    {
        id: '41e0f6fb-fba5-499b-8d54-cb35aff395c3',
        type: 'noun',
        en: 'Animal',
        pl: 'Zwierzę',
        jp: { text: '動物', pronunciation: 'どうぶつ' },
    },
    {
        id: 'c74b4db8-c15d-476d-93d1-46ff3b768649',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Popular',
        pl: 'Popularny',
        jp: { text: '人気', pronunciation: 'にんき' },
    },
    {
        id: '72bb2eb1-b6ff-47b8-8c6a-49c057bcb20f',
        type: 'noun',
        en: 'Cappuccino',
        pl: 'Cappuccino',
        jp: { text: 'カプチーノ' },
    },
    {
        id: '1da4da8a-b06e-4a2a-a9ec-dddff1724b22',
        type: 'noun',
        en: 'Brown color',
        pl: 'Brąz / Kolor brązowy',
        jp: { text: '茶色', pronunciation: 'ちゃいろ' },
    },
    {
        id: '3beeb198-ee78-482a-aa7b-0036dcfdec30',
        type: 'noun',
        en: 'Eyes',
        pl: 'Oczy',
        jp: { text: '目', pronunciation: 'め' },
    },
];

export const duolingo14Bag: WordBag = {
    id: '74409eaa-ba40-4c46-a889-05e2b3ad3194',
    name: 'Duolingo #14',
    category: 'duolingo',
    words: duolingo_14,
};
