import type { JapaneseWord } from '../../types.ts';

export const duolingo_3: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Live / Reside',
        pl: 'Żyć / Mieszkać',
        jp: 'すんでいます',
    },
    {
        type: 'unknown',
        en: '(to live) in',
        pl: '(mieszkać) w',
        jp: 'に',
    },
    {
        type: 'unknown',
        en: "What's your name?",
        pl: 'Jak masz na imię?',
        jp: 'おなまえは？',
    },
    {
        type: 'unknown',
        en: 'City',
        pl: 'Miasto',
        jp: 'とし',
    },
    {
        type: 'unknown',
        en: 'Lively / Energetic / Busy',
        pl: 'Żywy / Energiczny / Ruchliwy',
        jp: 'にぎやか',
    },
    {
        type: 'unknown',
        en: 'Quiet / Peaceful',
        pl: 'Cichy / Spokojny',
        jp: 'しずか',
    },
    {
        type: 'unknown',
        en: 'Clean',
        pl: 'Czysty',
        jp: 'きれい',
    },
    {
        type: 'unknown',
        en: 'Town',
        pl: 'Miasteczko',
        jp: 'まち',
    },
    {
        type: 'unknown',
        en: 'Very',
        pl: 'Bardzo',
        jp: 'とても',
    },
    {
        type: 'unknown',
        en: 'Loud',
        pl: 'Głośny',
        jp: 'うるさい',
    },
    {
        type: 'unknown',
        en: 'How is...',
        pl: 'Jakie jest...',
        jp: 'どうですか',
    },
    {
        type: 'unknown',
        en: '... years old',
        pl: '... lat',
        jp: 'さい',
    },
    {
        type: 'unknown',
        en: 'Famous',
        pl: 'Sławny',
        jp: 'ゆうめい',
    },
    {
        type: 'unknown',
        en: 'Wife',
        pl: 'Żona',
        jp: 'つま',
    },
    {
        type: 'unknown',
        en: 'Husband',
        pl: 'Mąż',
        jp: 'おっと',
    },
    {
        type: 'unknown',
        en: 'Family',
        pl: 'Rodzina',
        jp: 'かぞく',
    },
    {
        type: 'unknown',
        en: 'Busy',
        pl: 'Zajęty',
        jp: 'いそがしい',
    },
    {
        type: 'unknown',
        en: 'Engineer',
        pl: 'Inżynier',
        jp: 'エンジニア',
    },
    {
        type: 'unknown',
        en: 'Funny',
        pl: 'Zabawny',
        jp: 'おもしろい',
    },
    {
        type: 'unknown',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: 'かいしゃいん',
    },
    {
        type: 'unknown',
        en: 'Nurse',
        pl: 'Pielęgniarka',
        jp: 'かんごし',
    },
    {
        type: 'unknown',
        en: 'Student (university)',
        pl: 'Student (uniwersytet)',
        jp: 'だいがくせい',
    },
    {
        type: 'unknown',
        en: 'Fashionable / Trendy',
        pl: 'Modny / Trendy',
        jp: 'おしゃれ',
    },
    {
        type: 'unknown',
        en: 'Smart',
        pl: 'Mądry',
        jp: 'あたまがいい',
    },
    {
        type: 'unknown',
        en: 'Welcome',
        pl: 'Witamy',
        jp: 'ようこそ',
    },
    {
        type: 'unknown',
        en: 'Anime',
        pl: 'Anime',
        jp: 'アニメ',
    },
];
