import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingBooks: TranslatedJapaneseText[] = [
    {
        id: 'f60bec09-ecaf-4442-b82d-550014b1c6fb',
        type: 'numeral',
        en: 'One book',
        pl: 'Jedna książka',
        jp: { text: '一冊', pronunciation: 'いっさつ' },
    },
    {
        id: 'd5639728-4d48-4634-9079-63ba9601dc55',
        type: 'numeral',
        en: 'Two books',
        pl: 'Dwie książki',
        jp: { text: '二冊', pronunciation: 'にさつ' },
    },
    {
        id: 'f7ebad0d-7931-4dc1-ba13-4d5416543b65',
        type: 'numeral',
        en: 'Three books',
        pl: 'Trzy książki',
        jp: { text: '三冊', pronunciation: 'さんさつ' },
    },
    {
        id: '02390120-23f7-44ff-b338-a4d7ce7c18da',
        type: 'numeral',
        en: 'Four books',
        pl: 'Cztery książki',
        jp: { text: '四冊', pronunciation: 'よんさつ' },
    },
    {
        id: 'fea85816-5bb9-4565-ad3f-f409b8d25b19',
        type: 'numeral',
        en: 'Five books',
        pl: 'Pięć książek',
        jp: { text: '五冊', pronunciation: 'ごさつ' },
    },
    {
        id: '3d53db44-ed55-4ea5-bba2-96373a351840',
        type: 'numeral',
        en: 'Six books',
        pl: 'Sześć książek',
        jp: { text: '六冊', pronunciation: 'ろくさつ' },
    },
    {
        id: 'e3b1151e-32a6-4267-884a-ba87bf3ca940',
        type: 'numeral',
        en: 'Seven books',
        pl: 'Siedem książek',
        jp: { text: '七冊', pronunciation: 'ななさつ' },
    },
    {
        id: '3a218c88-04ce-49b6-a1bf-79e0479b9bc2',
        type: 'numeral',
        en: 'Eight books',
        pl: 'Osiem książek',
        jp: { text: '八冊', pronunciation: 'はっさつ' },
    },
    {
        id: 'b1e1aa0a-10a3-4b3e-a4d4-8e81f1a9c8bb',
        type: 'numeral',
        en: 'Nine books',
        pl: 'Dziewięć książek',
        jp: { text: '九冊', pronunciation: 'きゅうさつ' },
    },
    {
        id: '3c6a687b-9956-4286-9e9d-9f2da38b3b2b',
        type: 'numeral',
        en: 'Ten books',
        pl: 'Dziesięć książek',
        jp: { text: '十冊', pronunciation: ['じゅっさつ', 'じっさつ'] },
    },
    {
        id: 'a5e3d9cf-2fb9-467b-a6c2-6302ece59f26',
        type: 'numeral',
        en: 'Eleven books',
        pl: 'Jedenaście książek',
        jp: { text: '十一冊', pronunciation: 'じゅういっさつ' },
    },
    {
        id: 'a4e6e24f-460e-4a79-bc7f-c0bc0a2e6777',
        type: 'numeral',
        en: 'Twelve books',
        pl: 'Dwanaście książek',
        jp: { text: '十二冊', pronunciation: 'じゅうにさつ' },
    },
    {
        id: 'a086d414-0819-4762-b5ad-70e95d721585',
        type: 'numeral',
        en: 'Thirteen books',
        pl: 'Trzynaście książek',
        jp: { text: '十三冊', pronunciation: 'じゅうさんさつ' },
    },
    {
        id: '7d2b5cf3-3633-4ebe-863b-429f7b7164d1',
        type: 'numeral',
        en: 'Fourteen books',
        pl: 'Czternaście książek',
        jp: { text: '十四冊', pronunciation: 'じゅうよんさつ' },
    },
    {
        id: 'e35b0112-cf6d-44c7-bb50-d4c8593c9465',
        type: 'numeral',
        en: 'Fifteen books',
        pl: 'Piętnaście książek',
        jp: { text: '十五冊', pronunciation: 'じゅうごさつ' },
    },
    {
        id: 'fa346bca-602e-4eb7-97a8-3f92f00f3c2c',
        type: 'numeral',
        en: 'Sixteen books',
        pl: 'Szesnaście książek',
        jp: { text: '十六冊', pronunciation: 'じゅうろくさつ' },
    },
    {
        id: '7ef0d0a3-714e-4063-82ab-10aa4fcb18a0',
        type: 'numeral',
        en: 'Seventeen books',
        pl: 'Siedemnaście książek',
        jp: { text: '十七冊', pronunciation: 'じゅうななさつ' },
    },
    {
        id: 'e3bf3bc4-9582-4dd7-8f73-70b0b85eaf5b',
        type: 'numeral',
        en: 'Eighteen books',
        pl: 'Osiemnaście książek',
        jp: { text: '十八冊', pronunciation: 'じゅうはっさつ' },
    },
    {
        id: '111aa72f-f553-4a79-93ef-719b09029533',
        type: 'numeral',
        en: 'Nineteen books',
        pl: 'Dziewiętnaście książek',
        jp: { text: '十九冊', pronunciation: 'じゅうきゅうさつ' },
    },
    {
        id: '2e50b474-55ad-4b52-99fb-31fcc8906e5a',
        type: 'numeral',
        en: 'Twenty books',
        pl: 'Dwadzieścia książek',
        jp: { text: '二十冊', pronunciation: ['にじゅっさつ', 'にじっさつ'] },
    },
];

export const countingBooksBag: WordBag = {
    id: '5f3d8224-0189-4691-b1f4-113ba6da8a4c',
    name: 'Counting Books',
    category: 'counting',
    words: countingBooks,
};
