import { type TranslatedJapaneseText, type WordBag } from '../../types';

const countingLongCylindricalThings: TranslatedJapaneseText[] = [
    {
        id: 'addac4fc-e285-4fd4-a638-ce82e5db7f1f',
        type: 'numeral',
        en: 'One long cylindrical thing',
        pl: 'Jeden długi cylindryczny przedmiot',
        jp: { text: '一本', pronunciation: 'いっぽん' },
    },
    {
        id: 'c1fd936c-d00d-4822-97a4-9b76f39da0db',
        type: 'numeral',
        en: 'Two long cylindrical things',
        pl: 'Dwa długie cylindryczne przedmioty',
        jp: { text: '二本', pronunciation: 'にほん' },
    },
    {
        id: 'c03f9049-bb91-48d5-928b-9949462637c9',
        type: 'numeral',
        en: 'Three long cylindrical things',
        pl: 'Trzy długie cylindryczne przedmioty',
        jp: { text: '三本', pronunciation: 'さんぼん' },
    },
    {
        id: '8c47a5e2-6dd9-4924-adb1-382e253b279f',
        type: 'numeral',
        en: 'Four long cylindrical things',
        pl: 'Cztery długie cylindryczne przedmioty',
        jp: { text: '四本', pronunciation: 'よんほん' },
    },
    {
        id: '052fa8fc-0a35-4c23-9dc1-f65ccc3327f2',
        type: 'numeral',
        en: 'Five long cylindrical things',
        pl: 'Pięć długich cylindrycznych przedmiotów',
        jp: { text: '五本', pronunciation: 'ごほん' },
    },
    {
        id: '76b07c6d-a958-41cb-8da2-370c6072b30b',
        type: 'numeral',
        en: 'Six long cylindrical things',
        pl: 'Sześć długich cylindrycznych przedmiotów',
        jp: { text: '六本', pronunciation: 'ろっぽん' },
    },
    {
        id: '99179a59-1f2f-47b3-a72b-ffe3744f7b8f',
        type: 'numeral',
        en: 'Seven long cylindrical things',
        pl: 'Siedem długich cylindrycznych przedmiotów',
        jp: { text: '七本', pronunciation: 'ななほん' },
    },
    {
        id: 'd55612ec-39c7-47f4-a19f-07d984483ccd',
        type: 'numeral',
        en: 'Eight long cylindrical things',
        pl: 'Osiem długich cylindrycznych przedmiotów',
        jp: { text: '八本', pronunciation: 'はっぽん' },
    },
    {
        id: '5021a29b-4b56-4133-8ed8-b8ffd4b8e833',
        type: 'numeral',
        en: 'Nine long cylindrical things',
        pl: 'Dziewięć długich cylindrycznych przedmiotów',
        jp: { text: '九本', pronunciation: 'きゅうほん' },
    },
    {
        id: '49d70663-6ca2-4cf3-b473-a6dbd63b8024',
        type: 'numeral',
        en: 'Ten long cylindrical things',
        pl: 'Dziesięć długich cylindrycznych przedmiotów',
        jp: { text: '十本', pronunciation: 'じゅっぽん' },
    },
    {
        id: 'd776824e-55b5-485d-ba7a-c0cdd2b7a98e',
        type: 'numeral',
        en: 'Eleven long cylindrical things',
        pl: 'Jedenaście długich cylindrycznych przedmiotów',
        jp: { text: '十一本', pronunciation: 'じゅういっぽん' },
    },
    {
        id: 'bbdea17f-ba58-4146-a292-93096a10e4eb',
        type: 'numeral',
        en: 'Twelve long cylindrical things',
        pl: 'Dwanaście długich cylindrycznych przedmiotów',
        jp: { text: '十二本', pronunciation: 'じゅうにほん' },
    },
    {
        id: '1895b341-33f3-4da7-8294-46148f99b892',
        type: 'numeral',
        en: 'Thirteen long cylindrical things',
        pl: 'Trzynaście długich cylindrycznych przedmiotów',
        jp: { text: '十三本', pronunciation: 'じゅうさんぼん' },
    },
    {
        id: 'a6b4c3ba-a68e-49a4-add7-a9283bd29ff6',
        type: 'numeral',
        en: 'Fourteen long cylindrical things',
        pl: 'Czternaście długich cylindrycznych przedmiotów',
        jp: { text: '十四本', pronunciation: 'じゅうよんほん' },
    },
    {
        id: 'a229c44a-4619-4120-a4f6-c2b7a10801bb',
        type: 'numeral',
        en: 'Fifteen long cylindrical things',
        pl: 'Piętnaście długich cylindrycznych przedmiotów',
        jp: { text: '十五本', pronunciation: 'じゅうごほん' },
    },
    {
        id: 'a0628c64-4944-46b0-8cbb-39f603e21bee',
        type: 'numeral',
        en: 'Sixteen long cylindrical things',
        pl: 'Szesnaście długich cylindrycznych przedmiotów',
        jp: { text: '十六本', pronunciation: 'じゅうろっぽん' },
    },
    {
        id: 'b2590adf-ac14-4940-b377-0afc81a3a703',
        type: 'numeral',
        en: 'Seventeen long cylindrical things',
        pl: 'Siedemnaście długich cylindrycznych przedmiotów',
        jp: { text: '十七本', pronunciation: 'じゅうななほん' },
    },
    {
        id: 'cdd0b7c4-465d-45c1-83a2-bf9205e544ed',
        type: 'numeral',
        en: 'Eighteen long cylindrical things',
        pl: 'Osiemnaście długich cylindrycznych przedmiotów',
        jp: { text: '十八本', pronunciation: 'じゅうはっぽん' },
    },
    {
        id: '886c0c8f-f72d-4457-8dc1-35e63d9fbf42',
        type: 'numeral',
        en: 'Nineteen long cylindrical things',
        pl: 'Dziewiętnaście długich cylindrycznych przedmiotów',
        jp: { text: '十九本', pronunciation: 'じゅうきゅうほん' },
    },
    {
        id: 'f2cd8111-8df1-414a-b909-55b119b04487',
        type: 'numeral',
        en: 'Twenty long cylindrical things',
        pl: 'Dwadzieścia długich cylindrycznych przedmiotów',
        jp: { text: '二十本', pronunciation: 'にじゅっぽん' },
    },
];

export const countingLongCylindricalThingsBag: WordBag = {
    id: '18a934d5-156a-4300-a2ca-f09ed5886797',
    name: 'Counting Long Cylindrical Things',
    words: countingLongCylindricalThings,
};
