import type { JapaneseWord } from '../../types';

export const countingFloors: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'First floor',
        pl: 'Pierwsze piętro',
        jp: { word: '一階', pronunciation: 'いっかい' },
    },
    {
        type: 'numeral',
        en: 'Second floor',
        pl: 'Drugie piętro',
        jp: { word: '二階', pronunciation: 'にかい' },
    },
    {
        type: 'numeral',
        en: 'Third floor',
        pl: 'Trzecie piętro',
        jp: { word: '三階', pronunciation: 'さんがい' },
    },
    {
        type: 'numeral',
        en: 'Fourth floor',
        pl: 'Czwarte piętro',
        jp: { word: '四階', pronunciation: 'よんかい' },
    },
    {
        type: 'numeral',
        en: 'Fifth floor',
        pl: 'Piąte piętro',
        jp: { word: '五階', pronunciation: 'ごかい' },
    },
    {
        type: 'numeral',
        en: 'Sixth floor',
        pl: 'Szóste piętro',
        jp: { word: '六階', pronunciation: 'ろっかい' },
    },
    {
        type: 'numeral',
        en: 'Seventh floor',
        pl: 'Siódme piętro',
        jp: { word: '七階', pronunciation: 'ななかい' },
    },
    {
        type: 'numeral',
        en: 'Eighth floor',
        pl: 'Ósme piętro',
        jp: { word: '八階', pronunciation: 'はっかい' },
    },
    {
        type: 'numeral',
        en: 'Ninth floor',
        pl: 'Dziewiąte piętro',
        jp: { word: '九階', pronunciation: 'きゅうかい' },
    },
    {
        type: 'numeral',
        en: 'Tenth floor',
        pl: 'Dziesiąte piętro',
        jp: { word: '十階', pronunciation: 'じゅっかい' },
    },
    {
        type: 'numeral',
        en: 'Eleventh floor',
        pl: 'Jedenaste piętro',
        jp: { word: '十一階', pronunciation: 'じゅういっかい' },
    },
    {
        type: 'numeral',
        en: 'Twelfth floor',
        pl: 'Dwunaste piętro',
        jp: { word: '十二階', pronunciation: 'じゅうにかい' },
    },
    {
        type: 'numeral',
        en: 'Thirteenth floor',
        pl: 'Trzynaste piętro',
        jp: { word: '十三階', pronunciation: 'じゅうさんがい' },
    },
    {
        type: 'numeral',
        en: 'Fourteenth floor',
        pl: 'Czternaste piętro',
        jp: { word: '十四階', pronunciation: 'じゅうよんかい' },
    },
    {
        type: 'numeral',
        en: 'Fifteenth floor',
        pl: 'Piętnaste piętro',
        jp: { word: '十五階', pronunciation: 'じゅうごかい' },
    },
    {
        type: 'numeral',
        en: 'Sixteenth floor',
        pl: 'Szesnaste piętro',
        jp: { word: '十六階', pronunciation: 'じゅうろっかい' },
    },
    {
        type: 'numeral',
        en: 'Seventeenth floor',
        pl: 'Siedemnaste piętro',
        jp: { word: '十七階', pronunciation: 'じゅうななかい' },
    },
    {
        type: 'numeral',
        en: 'Eighteenth floor',
        pl: 'Osiemnaste piętro',
        jp: { word: '十八階', pronunciation: 'じゅうはっかい' },
    },
    {
        type: 'numeral',
        en: 'Nineteenth floor',
        pl: 'Dziewiętnaste piętro',
        jp: { word: '十九階', pronunciation: 'じゅうきゅうかい' },
    },
    {
        type: 'numeral',
        en: 'Twentieth floor',
        pl: 'Dwudzieste piętro',
        jp: { word: '二十階', pronunciation: 'にじゅっかい' },
    },
    {
        type: 'numeral',
        en: 'Which floor',
        pl: 'Które piętro',
        jp: { word: '何階', pronunciation: 'なんがい' },
    },
];
