import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingSmallAndMediumAnimals: TranslatedJapaneseText[] = [
    {
        id: '6f4a7f92-6456-4263-bf1d-5b85b4fbdc5c',
        type: 'numeral',
        en: 'One animal',
        pl: 'Jedno zwierzę',
        jp: { text: '一匹', pronunciation: 'いっぴき' },
    },
    {
        id: 'd422dafa-dded-4e7e-afd3-8b1c8d92f177',
        type: 'numeral',
        en: 'Two animals',
        pl: 'Dwa zwierzęta',
        jp: { text: '二匹', pronunciation: 'にひき' },
    },
    {
        id: '1ac4beef-3f27-4e4b-80e9-a35f3d780ec8',
        type: 'numeral',
        en: 'Three animals',
        pl: 'Trzy zwierzęta',
        jp: { text: '三匹', pronunciation: 'さんびき' },
    },
    {
        id: '5f90b4c6-e7a2-45aa-aa9e-6fc72bfb7034',
        type: 'numeral',
        en: 'Four animals',
        pl: 'Cztery zwierzęta',
        jp: { text: '四匹', pronunciation: 'よんひき' },
    },
    {
        id: 'd0c002c0-60e7-4c50-b3bd-0f19dbb22b7b',
        type: 'numeral',
        en: 'Five animals',
        pl: 'Pięć zwierząt',
        jp: { text: '五匹', pronunciation: 'ごひき' },
    },
    {
        id: 'c396593f-35ad-4b86-865f-56b8849d58f9',
        type: 'numeral',
        en: 'Six animals',
        pl: 'Sześć zwierząt',
        jp: { text: '六匹', pronunciation: 'ろっぴき' },
    },
    {
        id: 'fe8b3b0a-b872-4573-89f0-3fe62b14dee7',
        type: 'numeral',
        en: 'Seven animals',
        pl: 'Siedem zwierząt',
        jp: { text: '七匹', pronunciation: 'ななひき' },
    },
    {
        id: 'b8726696-8e07-4516-b5bd-c83299b6b8bf',
        type: 'numeral',
        en: 'Eight animals',
        pl: 'Osiem zwierząt',
        jp: { text: '八匹', pronunciation: 'はっぴき' },
    },
    {
        id: 'a8f7cc6e-44ac-431a-a094-66767cebdfbc',
        type: 'numeral',
        en: 'Nine animals',
        pl: 'Dziewięć zwierząt',
        jp: { text: '九匹', pronunciation: 'きゅうひき' },
    },
    {
        id: '095029b0-472f-4017-aea8-6b5ba74de7fd',
        type: 'numeral',
        en: 'Ten animals',
        pl: 'Dziesięć zwierząt',
        jp: { text: '十匹', pronunciation: 'じゅっぴき' },
    },
    {
        id: '357cd5a8-2e28-4e72-ae6f-3dec4f5ac8cc',
        type: 'numeral',
        en: 'Eleven animals',
        pl: 'Jedenaście zwierząt',
        jp: { text: '十一匹', pronunciation: 'じゅういっぴき' },
    },
    {
        id: '20872e46-4c2f-4164-85fd-ae1d6e8e92a8',
        type: 'numeral',
        en: 'Twelve animals',
        pl: 'Dwanaście zwierząt',
        jp: { text: '十二匹', pronunciation: 'じゅうにひき' },
    },
    {
        id: '23173b18-e94e-45af-95aa-408cf0139aa4',
        type: 'numeral',
        en: 'Thirteen animals',
        pl: 'Trzynaście zwierząt',
        jp: { text: '十三匹', pronunciation: 'じゅうさんびき' },
    },
    {
        id: 'f6db338d-8f5e-483b-bd68-aee9f69d231b',
        type: 'numeral',
        en: 'Fourteen animals',
        pl: 'Czternaście zwierząt',
        jp: { text: '十四匹', pronunciation: 'じゅうよんひき' },
    },
    {
        id: '03a80d66-875f-40ae-9f45-bff4010e84bd',
        type: 'numeral',
        en: 'Fifteen animals',
        pl: 'Piętnaście zwierząt',
        jp: { text: '十五匹', pronunciation: 'じゅうごひき' },
    },
    {
        id: '7840b2dc-f4d8-4ebc-b3c2-b35b69154605',
        type: 'numeral',
        en: 'Sixteen animals',
        pl: 'Szesnaście zwierząt',
        jp: { text: '十六匹', pronunciation: 'じゅうろっぴき' },
    },
    {
        id: '5fa8cde8-380a-45b9-b857-2ecd57d035ac',
        type: 'numeral',
        en: 'Seventeen animals',
        pl: 'Siedemnaście zwierząt',
        jp: { text: '十七匹', pronunciation: 'じゅうななひき' },
    },
    {
        id: '7e7e80d0-fad7-4c63-9ee8-240ade14037f',
        type: 'numeral',
        en: 'Eighteen animals',
        pl: 'Osiemnaście zwierząt',
        jp: { text: '十八匹', pronunciation: 'じゅうはっぴき' },
    },
    {
        id: '4d6b601c-84f7-4e5f-a1a4-23cdcc618dbb',
        type: 'numeral',
        en: 'Nineteen animals',
        pl: 'Dziewiętnaście zwierząt',
        jp: { text: '十九匹', pronunciation: 'じゅうきゅうひき' },
    },
    {
        id: 'e72d4a03-c539-4fd0-b645-7dfb5063b595',
        type: 'numeral',
        en: 'Twenty animals',
        pl: 'Dwadzieścia zwierząt',
        jp: { text: '二十匹', pronunciation: 'にじゅっぴき' },
    },
];

export const countingSmallAndMediumAnimalsBag: WordBag = {
    id: '8b15f7be-7a2d-468b-a3ba-2f1c72497a66',
    name: 'Counting Small and Medium Animals',
    words: countingSmallAndMediumAnimals,
};
