import type { JapaneseWord } from '../../types';

export const countingThinObjects: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'One thin object',
        pl: 'Jeden płaski przedmiot',
        jp: '一枚',
        jp_pronunciation: 'いちまい',
    },
    {
        type: 'numeral',
        en: 'Two thin objects',
        pl: 'Dwa płaskie przedmioty',
        jp: '二枚',
        jp_pronunciation: 'にまい',
    },
    {
        type: 'numeral',
        en: 'Three thin objects',
        pl: 'Trzy płaskie przedmioty',
        jp: '三枚',
        jp_pronunciation: 'さんまい',
    },
    {
        type: 'numeral',
        en: 'Four thin objects',
        pl: 'Cztery płaskie przedmioty',
        jp: '四枚',
        jp_pronunciation: 'よんまい',
    },
    {
        type: 'numeral',
        en: 'Five thin objects',
        pl: 'Pięć płaskich przedmiotów',
        jp: '五枚',
        jp_pronunciation: 'ごまい',
    },
    {
        type: 'numeral',
        en: 'Six thin objects',
        pl: 'Sześć płaskich przedmiotów',
        jp: '六枚',
        jp_pronunciation: 'ろくまい',
    },
    {
        type: 'numeral',
        en: 'Seven thin objects',
        pl: 'Siedem płaskich przedmiotów',
        jp: '七枚',
        jp_pronunciation: 'ななまい',
    },
    {
        type: 'numeral',
        en: 'Eight thin objects',
        pl: 'Osiem płaskich przedmiotów',
        jp: '八枚',
        jp_pronunciation: 'はちまい',
    },
    {
        type: 'numeral',
        en: 'Nine thin objects',
        pl: 'Dziewięć płaskich przedmiotów',
        jp: '九枚',
        jp_pronunciation: 'きゅうまい',
    },
    {
        type: 'numeral',
        en: 'Ten thin objects',
        pl: 'Dziesięć płaskich przedmiotów',
        jp: '十枚',
        jp_pronunciation: 'じゅうまい',
    },
    {
        type: 'numeral',
        en: 'Eleven thin objects',
        pl: 'Jedenaście płaskich przedmiotów',
        jp: '十一枚',
        jp_pronunciation: 'じゅういちまい',
    },
    {
        type: 'numeral',
        en: 'Twelve thin objects',
        pl: 'Dwanaście płaskich przedmiotów',
        jp: '十二枚',
        jp_pronunciation: 'じゅうにまい',
    },
    {
        type: 'numeral',
        en: 'Thirteen thin objects',
        pl: 'Trzynaście płaskich przedmiotów',
        jp: '十三枚',
        jp_pronunciation: 'じゅうさんまい',
    },
    {
        type: 'numeral',
        en: 'Fourteen thin objects',
        pl: 'Czternaście płaskich przedmiotów',
        jp: '十四枚',
        jp_pronunciation: 'じゅうよんまい',
    },
    {
        type: 'numeral',
        en: 'Fifteen thin objects',
        pl: 'Piętnaście płaskich przedmiotów',
        jp: '十五枚',
        jp_pronunciation: 'じゅうごまい',
    },
    {
        type: 'numeral',
        en: 'Sixteen thin objects',
        pl: 'Szesnaście płaskich przedmiotów',
        jp: '十六枚',
        jp_pronunciation: 'じゅうろくまい',
    },
    {
        type: 'numeral',
        en: 'Seventeen thin objects',
        pl: 'Siedemnaście płaskich przedmiotów',
        jp: '十七枚',
        jp_pronunciation: 'じゅうななまい',
    },
    {
        type: 'numeral',
        en: 'Eighteen thin objects',
        pl: 'Osiemnaście płaskich przedmiotów',
        jp: '十八枚',
        jp_pronunciation: 'じゅうはちまい',
    },
    {
        type: 'numeral',
        en: 'Nineteen thin objects',
        pl: 'Dziewiętnaście płaskich przedmiotów',
        jp: '十九枚',
        jp_pronunciation: 'じゅうきゅうまい',
    },
    {
        type: 'numeral',
        en: 'Twenty thin objects',
        pl: 'Dwadzieścia płaskich przedmiotów',
        jp: '二十枚',
        jp_pronunciation: 'にじゅうまい',
    },
];
