import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingThings: TranslatedJapaneseText[] = [
    {
        id: 'bda89a74-c242-4a92-b3e4-3bc4d79dded2',
        type: 'numeral',
        en: 'One thing',
        pl: 'Jedna rzecz',
        jp: { text: '一つ', pronunciation: 'ひとつ' },
    },
    {
        id: '9a2a093a-bbd4-4b14-a0df-d66f379ce2a6',
        type: 'numeral',
        en: 'Two things',
        pl: 'Dwie rzeczy',
        jp: { text: '二つ', pronunciation: 'ふたつ' },
    },
    {
        id: 'a07f6041-bdbb-4161-8f9c-0d55c182f3f4',
        type: 'numeral',
        en: 'Three things',
        pl: 'Trzy rzeczy',
        jp: { text: '三つ', pronunciation: 'みっつ' },
    },
    {
        id: 'd37d6e24-9ee6-4435-b419-3f90ebdfeba0',
        type: 'numeral',
        en: 'Four things',
        pl: 'Cztery rzeczy',
        jp: { text: '四つ', pronunciation: 'よっつ' },
    },
    {
        id: 'cbe1b93e-1512-4de0-a6e6-080ee70649c5',
        type: 'numeral',
        en: 'Five things',
        pl: 'Pięć rzeczy',
        jp: { text: '五つ', pronunciation: 'いつつ' },
    },
    {
        id: 'a4ddf9ec-bdf1-46a5-8802-09f5a2bd5d25',
        type: 'numeral',
        en: 'Six things',
        pl: 'Sześć rzeczy',
        jp: { text: '六つ', pronunciation: 'むっつ' },
    },
    {
        id: 'ef8c8663-d1ca-4ff1-8a26-9718c0a14422',
        type: 'numeral',
        en: 'Seven things',
        pl: 'Siedem rzeczy',
        jp: { text: '七つ', pronunciation: 'ななつ' },
    },
    {
        id: '412b8a15-e061-4d32-baff-05de92537676',
        type: 'numeral',
        en: 'Eight things',
        pl: 'Osiem rzeczy',
        jp: { text: '八つ', pronunciation: 'やっつ' },
    },
    {
        id: '7712e136-028f-4da1-9bc1-82a2234e4f94',
        type: 'numeral',
        en: 'Nine things',
        pl: 'Dziewięć rzeczy',
        jp: { text: '九つ', pronunciation: 'ここのつ' },
    },
    {
        id: 'e8054872-b9dc-486c-bc1e-c2d607e220ee',
        type: 'numeral',
        en: 'Ten things',
        pl: 'Dziesięć rzeczy',
        jp: { text: '十', pronunciation: 'とお' },
    },
    {
        id: '24958697-c7a6-4f43-aec4-5dab9e115a06',
        type: 'phrase',
        en: 'How many ramen do you want?',
        pl: 'Ile ramenów chciałbyś?',
        jp: { text: 'ラーメンがいくつ欲しいですか。', pronunciation: 'ラーメンがいくつほしいですか。' },
    },
    {
        id: 'f9fc4523-e6b4-4df1-ac64-a05a94bac9e2',
        type: 'numeral',
        en: 'How many things',
        pl: 'Ile rzeczy',
        jp: { text: 'いくつ' },
    },
    {
        id: '07af7cbe-b4e1-4faf-8e01-55d524497cc1',
        type: 'numeral',
        en: 'Eleven things',
        pl: 'Jedenaście rzeczy',
        jp: { text: '十一個', pronunciation: 'じゅういっこ' },
    },
    {
        id: 'dad78a6b-5d04-42a7-9696-735e9ca72f3e',
        type: 'numeral',
        en: 'Twelve things',
        pl: 'Dwanaście rzeczy',
        jp: { text: '十二個', pronunciation: 'じゅうにこ' },
    },
    {
        id: 'f5bbb62c-bc80-40bb-8220-03a919b45c1a',
        type: 'numeral',
        en: 'Thirteen things',
        pl: 'Trzynaście rzeczy',
        jp: { text: '十三個', pronunciation: 'じゅうさんこ' },
    },
    {
        id: 'a3932277-e2b1-4d14-8664-17adcb86fd31',
        type: 'numeral',
        en: 'Fourteen things',
        pl: 'Czternaście rzeczy',
        jp: { text: '十四個', pronunciation: 'じゅうよんこ' },
    },
    {
        id: 'b2dbd578-f58b-4010-bd6d-8bc7e9d50908',
        type: 'numeral',
        en: 'Fifteen things',
        pl: 'Piętnaście rzeczy',
        jp: { text: '十五個', pronunciation: 'じゅうごこ' },
    },
    {
        id: 'fd3e918b-3bab-4aeb-93ee-953918be38f1',
        type: 'numeral',
        en: 'Sixteen things',
        pl: 'Szesnaście rzeczy',
        jp: { text: '十六個', pronunciation: 'じゅうろっこ' },
    },
    {
        id: '9b51d4b6-86ab-4a79-b641-5d4eed1d246b',
        type: 'numeral',
        en: 'Seventeen things',
        pl: 'Siedemnaście rzeczy',
        jp: { text: '十七個', pronunciation: 'じゅうななこ' },
    },
    {
        id: '91940b79-0f9d-4495-9eb6-21dc5b376712',
        type: 'numeral',
        en: 'Eighteen things',
        pl: 'Osiemnaście rzeczy',
        jp: { text: '十八個', pronunciation: 'じゅうはっこ' },
    },
    {
        id: '7a843af8-3137-4933-b7cb-da0ecdafb1fa',
        type: 'numeral',
        en: 'Nineteen things',
        pl: 'Dziewiętnaście rzeczy',
        jp: { text: '十九個', pronunciation: 'じゅうきゅうこ' },
    },
    {
        id: '21f59251-aba2-4517-abb3-f9543285db8d',
        type: 'numeral',
        en: 'Twenty things',
        pl: 'Dwadzieścia rzeczy',
        jp: { text: '二十個', pronunciation: 'にじゅっこ' },
    },
];

export const countingThingsBag: WordBag = {
    id: 'f1f12e01-87cf-437d-b67f-696a17be41d5',
    name: 'Counting Things',
    words: countingThings,
};
