import type { JapaneseWord } from '../../types';

export const countingFloors: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'First floor',
        pl: 'Pierwsze piętro',
        jp: '一階',
        jp_pronunciation: 'いっかい',
    },
    {
        type: 'numeral',
        en: 'Second floor',
        pl: 'Drugie piętro',
        jp: '二階',
        jp_pronunciation: 'にかい',
    },
    {
        type: 'numeral',
        en: 'Third floor',
        pl: 'Trzecie piętro',
        jp: '三階',
        jp_pronunciation: 'さんがい',
    },
    {
        type: 'numeral',
        en: 'Fourth floor',
        pl: 'Czwarte piętro',
        jp: '四階',
        jp_pronunciation: 'よんかい',
    },
    {
        type: 'numeral',
        en: 'Fifth floor',
        pl: 'Piąte piętro',
        jp: '五階',
        jp_pronunciation: 'ごかい',
    },
    {
        type: 'numeral',
        en: 'Sixth floor',
        pl: 'Szóste piętro',
        jp: '六階',
        jp_pronunciation: 'ろっかい',
    },
    {
        type: 'numeral',
        en: 'Seventh floor',
        pl: 'Siódme piętro',
        jp: '七階',
        jp_pronunciation: 'ななかい',
    },
    {
        type: 'numeral',
        en: 'Eighth floor',
        pl: 'Ósme piętro',
        jp: '八階',
        jp_pronunciation: 'はっかい',
    },
    {
        type: 'numeral',
        en: 'Ninth floor',
        pl: 'Dziewiąte piętro',
        jp: '九階',
        jp_pronunciation: 'きゅうかい',
    },
    {
        type: 'numeral',
        en: 'Tenth floor',
        pl: 'Dziesiąte piętro',
        jp: '十階',
        jp_pronunciation: 'じゅっかい',
    },
    {
        type: 'numeral',
        en: 'Eleventh floor',
        pl: 'Jedenaste piętro',
        jp: '十一階',
        jp_pronunciation: 'じゅういっかい',
    },
    {
        type: 'numeral',
        en: 'Twelfth floor',
        pl: 'Dwunaste piętro',
        jp: '十二階',
        jp_pronunciation: 'じゅうにかい',
    },
    {
        type: 'numeral',
        en: 'Thirteenth floor',
        pl: 'Trzynaste piętro',
        jp: '十三階',
        jp_pronunciation: 'じゅうさんがい',
    },
    {
        type: 'numeral',
        en: 'Fourteenth floor',
        pl: 'Czternaste piętro',
        jp: '十四階',
        jp_pronunciation: 'じゅうよんかい',
    },
    {
        type: 'numeral',
        en: 'Fifteenth floor',
        pl: 'Piętnaste piętro',
        jp: '十五階',
        jp_pronunciation: 'じゅうごかい',
    },
    {
        type: 'numeral',
        en: 'Sixteenth floor',
        pl: 'Szesnaste piętro',
        jp: '十六階',
        jp_pronunciation: 'じゅうろっかい',
    },
    {
        type: 'numeral',
        en: 'Seventeenth floor',
        pl: 'Siedemnaste piętro',
        jp: '十七階',
        jp_pronunciation: 'じゅうななかい',
    },
    {
        type: 'numeral',
        en: 'Eighteenth floor',
        pl: 'Osiemnaste piętro',
        jp: '十八階',
        jp_pronunciation: 'じゅうはっかい',
    },
    {
        type: 'numeral',
        en: 'Nineteenth floor',
        pl: 'Dziewiętnaste piętro',
        jp: '十九階',
        jp_pronunciation: 'じゅうきゅうかい',
    },
    {
        type: 'numeral',
        en: 'Twentieth floor',
        pl: 'Dwudzieste piętro',
        jp: '二十階',
        jp_pronunciation: 'にじゅっかい',
    },
    {
        type: 'numeral',
        en: 'Which floor',
        pl: 'Które piętro',
        jp: '何階',
        jp_pronunciation: 'なんがい',
    },
];
