import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingThinObjects: TranslatedJapaneseText[] = [
    {
        id: 'e3de6ac8-3293-47a5-a00a-36b200bec912',
        type: 'numeral',
        en: 'One thin object',
        pl: 'Jeden płaski przedmiot',
        jp: { text: '一枚', pronunciation: 'いちまい' },
    },
    {
        id: '9e65fd54-812d-4be7-8363-f06fdc5ea1f3',
        type: 'numeral',
        en: 'Two thin objects',
        pl: 'Dwa płaskie przedmioty',
        jp: { text: '二枚', pronunciation: 'にまい' },
    },
    {
        id: '8b8f075c-a352-48f7-a581-ff7df92ef978',
        type: 'numeral',
        en: 'Three thin objects',
        pl: 'Trzy płaskie przedmioty',
        jp: { text: '三枚', pronunciation: 'さんまい' },
    },
    {
        id: '2a79555e-7a1a-491d-952c-3bff4854ccda',
        type: 'numeral',
        en: 'Four thin objects',
        pl: 'Cztery płaskie przedmioty',
        jp: { text: '四枚', pronunciation: 'よんまい' },
    },
    {
        id: '4c3a9b29-08ca-4b6b-824b-d18ffd5910f1',
        type: 'numeral',
        en: 'Five thin objects',
        pl: 'Pięć płaskich przedmiotów',
        jp: { text: '五枚', pronunciation: 'ごまい' },
    },
    {
        id: 'cacce48c-18f4-4226-8580-fb6b3428eb08',
        type: 'numeral',
        en: 'Six thin objects',
        pl: 'Sześć płaskich przedmiotów',
        jp: { text: '六枚', pronunciation: 'ろくまい' },
    },
    {
        id: 'c8af270a-4e55-464d-a9ce-225708452514',
        type: 'numeral',
        en: 'Seven thin objects',
        pl: 'Siedem płaskich przedmiotów',
        jp: { text: '七枚', pronunciation: 'ななまい' },
    },
    {
        id: '6beb8c1e-5b4b-4b91-a82c-813be7945c47',
        type: 'numeral',
        en: 'Eight thin objects',
        pl: 'Osiem płaskich przedmiotów',
        jp: { text: '八枚', pronunciation: 'はちまい' },
    },
    {
        id: 'c647e7e3-fac4-435c-bf74-2f9c0264937c',
        type: 'numeral',
        en: 'Nine thin objects',
        pl: 'Dziewięć płaskich przedmiotów',
        jp: { text: '九枚', pronunciation: 'きゅうまい' },
    },
    {
        id: 'e4d3e11b-cb6c-40fe-8252-56ed10cd207c',
        type: 'numeral',
        en: 'Ten thin objects',
        pl: 'Dziesięć płaskich przedmiotów',
        jp: { text: '十枚', pronunciation: 'じゅうまい' },
    },
    {
        id: '154fa5ab-d636-4bca-a338-5c56797c187b',
        type: 'numeral',
        en: 'Eleven thin objects',
        pl: 'Jedenaście płaskich przedmiotów',
        jp: { text: '十一枚', pronunciation: 'じゅういちまい' },
    },
    {
        id: '1c0a4c14-555d-4837-8ee8-8d0af0236e00',
        type: 'numeral',
        en: 'Twelve thin objects',
        pl: 'Dwanaście płaskich przedmiotów',
        jp: { text: '十二枚', pronunciation: 'じゅうにまい' },
    },
    {
        id: '91c1a128-7e65-41f9-9f69-4bdb90a759f5',
        type: 'numeral',
        en: 'Thirteen thin objects',
        pl: 'Trzynaście płaskich przedmiotów',
        jp: { text: '十三枚', pronunciation: 'じゅうさんまい' },
    },
    {
        id: '96d2f756-3a6d-4447-aeae-c280504272f2',
        type: 'numeral',
        en: 'Fourteen thin objects',
        pl: 'Czternaście płaskich przedmiotów',
        jp: { text: '十四枚', pronunciation: 'じゅうよんまい' },
    },
    {
        id: 'b7d6d8a0-6079-4f59-966e-69b438cb080f',
        type: 'numeral',
        en: 'Fifteen thin objects',
        pl: 'Piętnaście płaskich przedmiotów',
        jp: { text: '十五枚', pronunciation: 'じゅうごまい' },
    },
    {
        id: 'e6558323-270a-4e82-b586-294968d22bdf',
        type: 'numeral',
        en: 'Sixteen thin objects',
        pl: 'Szesnaście płaskich przedmiotów',
        jp: { text: '十六枚', pronunciation: 'じゅうろくまい' },
    },
    {
        id: 'dcf00e88-621b-4586-bea8-8d0fa802d3e7',
        type: 'numeral',
        en: 'Seventeen thin objects',
        pl: 'Siedemnaście płaskich przedmiotów',
        jp: { text: '十七枚', pronunciation: 'じゅうななまい' },
    },
    {
        id: '374e1fed-adf3-496e-8307-38009fa080fa',
        type: 'numeral',
        en: 'Eighteen thin objects',
        pl: 'Osiemnaście płaskich przedmiotów',
        jp: { text: '十八枚', pronunciation: 'じゅうはちまい' },
    },
    {
        id: '22dd4e61-d3ef-41cd-989d-cb367352d89f',
        type: 'numeral',
        en: 'Nineteen thin objects',
        pl: 'Dziewiętnaście płaskich przedmiotów',
        jp: { text: '十九枚', pronunciation: 'じゅうきゅうまい' },
    },
    {
        id: '7a09154c-5877-4981-b757-ae65193c0778',
        type: 'numeral',
        en: 'Twenty thin objects',
        pl: 'Dwadzieścia płaskich przedmiotów',
        jp: { text: '二十枚', pronunciation: 'にじゅうまい' },
    },
];

export const countingThinObjectsBag: WordBag = {
    id: '03f1b394-7ca4-4f53-aff3-f94dfa1f5737',
    name: 'Counting Thin Objects',
    words: countingThinObjects,
};
