import type { JapaneseWord } from '../../types.ts';

export const countingThings: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'One thing',
        pl: 'Jedna rzecz',
        jp: { word: 'ひとつ' },
    },
    {
        type: 'numeral',
        en: 'Two things',
        pl: 'Dwie rzeczy',
        jp: { word: 'ふたつ' },
    },
    {
        type: 'numeral',
        en: 'Three things',
        pl: 'Trzy rzeczy',
        jp: { word: 'みっつ' },
    },
    {
        type: 'numeral',
        en: 'Four things',
        pl: 'Cztery rzeczy',
        jp: { word: 'よっつ' },
    },
    {
        type: 'numeral',
        en: 'Five things',
        pl: 'Pięć rzeczy',
        jp: { word: 'いつつ' },
    },
    {
        type: 'numeral',
        en: 'Six things',
        pl: 'Sześć rzeczy',
        jp: { word: 'むっつ' },
    },
    {
        type: 'numeral',
        en: 'Seven things',
        pl: 'Siedem rzeczy',
        jp: { word: 'ななつ' },
    },
    {
        type: 'numeral',
        en: 'Eight things',
        pl: 'Osiem rzeczy',
        jp: { word: 'やっつ' },
    },
    {
        type: 'numeral',
        en: 'Nine things',
        pl: 'Dziewięć rzeczy',
        jp: { word: 'ここのつ' },
    },
    {
        type: 'numeral',
        en: 'Ten things',
        pl: 'Dziesięć rzeczy',
        jp: { word: 'とお' },
    },
    {
        type: 'phrase',
        en: 'How many ramen do you want?',
        pl: 'Ile ramenów chcesz?',
        jp: { word: 'ラーメンがいくつほしいですか' },
    },
    {
        type: 'numeral',
        en: 'Eleven things',
        pl: 'Jedenaście rzeczy',
        jp: { word: 'じゅういっこ' },
    },
    {
        type: 'numeral',
        en: 'Twelve things',
        pl: 'Dwanaście rzeczy',
        jp: { word: 'じゅうにこ' },
    },
    {
        type: 'numeral',
        en: 'Thirteen things',
        pl: 'Trzynaście rzeczy',
        jp: { word: 'じゅうさんこ' },
    },
    {
        type: 'numeral',
        en: 'Fourteen things',
        pl: 'Czternaście rzeczy',
        jp: { word: 'じゅうよんこ' },
    },
    {
        type: 'numeral',
        en: 'Fifteen things',
        pl: 'Piętnaście rzeczy',
        jp: { word: 'じゅうごこ' },
    },
    {
        type: 'numeral',
        en: 'Sixteen things',
        pl: 'Szesnaście rzeczy',
        jp: { word: 'じゅうろっこ' },
    },
    {
        type: 'numeral',
        en: 'Seventeen things',
        pl: 'Siedemnaście rzeczy',
        jp: { word: 'じゅうななこ' },
    },
    {
        type: 'numeral',
        en: 'Eighteen things',
        pl: 'Osiemnaście rzeczy',
        jp: { word: 'じゅうはっこ' },
    },
    {
        type: 'numeral',
        en: 'Nineteen things',
        pl: 'Dziewiętnaście rzeczy',
        jp: { word: 'じゅうきゅうこ' },
    },
    {
        type: 'numeral',
        en: 'Twenty things',
        pl: 'Dwadzieścia rzeczy',
        jp: { word: 'にじゅっこ' },
    },
];
