import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingSmallThings: TranslatedJapaneseText[] = [
    {
        id: '9233c338-3912-48c9-95d3-a9a5f37b0928',
        type: 'numeral',
        en: 'One small thing',
        pl: 'Jedna mała rzecz',
        jp: { text: '一個', pronunciation: 'いっこ' },
    },
    {
        id: '8695f8ef-7f92-4e22-bd8d-e5596d228c23',
        type: 'numeral',
        en: 'Two small things',
        pl: 'Dwie małe rzeczy',
        jp: { text: '二個', pronunciation: 'にこ' },
    },
    {
        id: '563fd695-2127-4d86-89f2-bb60ab6e511f',
        type: 'numeral',
        en: 'Three small things',
        pl: 'Trzy małe rzeczy',
        jp: { text: '三個', pronunciation: 'さんこ' },
    },
    {
        id: 'f8b79920-c7a6-4375-8f97-637ee73cc5c8',
        type: 'numeral',
        en: 'Four small things',
        pl: 'Cztery małe rzeczy',
        jp: { text: '四個', pronunciation: 'よんこ' },
    },
    {
        id: '029c6058-fcf1-4b20-9a10-273a566675fa',
        type: 'numeral',
        en: 'Five small things',
        pl: 'Pięć małych rzeczy',
        jp: { text: '五個', pronunciation: 'ごこ' },
    },
    {
        id: 'e88b5ffe-c66d-41d3-8df7-7f5283370490',
        type: 'numeral',
        en: 'Six small things',
        pl: 'Sześć małych rzeczy',
        jp: { text: '六個', pronunciation: 'ろっこ' },
    },
    {
        id: '2ed6186e-a9ae-4772-955e-9eda30ee0314',
        type: 'numeral',
        en: 'Seven small things',
        pl: 'Siedem małych rzeczy',
        jp: { text: '七個', pronunciation: 'ななこ' },
    },
    {
        id: 'cecd725c-3eaf-4af4-8637-45f61103a269',
        type: 'numeral',
        en: 'Eight small things',
        pl: 'Osiem małych rzeczy',
        jp: { text: '八個', pronunciation: 'はっこ' },
    },
    {
        id: 'c347b90d-eb5c-4194-922a-eb4235924d60',
        type: 'numeral',
        en: 'Nine small things',
        pl: 'Dziewięć małych rzeczy',
        jp: { text: '九個', pronunciation: 'きゅうこ' },
    },
    {
        id: '90d5063c-c82d-44cf-a4ae-f72aa0d302e5',
        type: 'numeral',
        en: 'Ten small things',
        pl: 'Dziesięć małych rzeczy',
        jp: { text: '十個', pronunciation: 'じゅっこ' },
    },
    {
        id: '07af7cbe-b4e1-4faf-8e01-55d524497cc1',
        type: 'numeral',
        en: 'Eleven small things',
        pl: 'Jedenaście małych rzeczy',
        jp: { text: '十一個', pronunciation: 'じゅういっこ' },
    },
    {
        id: 'dad78a6b-5d04-42a7-9696-735e9ca72f3e',
        type: 'numeral',
        en: 'Twelve small things',
        pl: 'Dwanaście małych rzeczy',
        jp: { text: '十二個', pronunciation: 'じゅうにこ' },
    },
    {
        id: 'f5bbb62c-bc80-40bb-8220-03a919b45c1a',
        type: 'numeral',
        en: 'Thirteen small things',
        pl: 'Trzynaście małych rzeczy',
        jp: { text: '十三個', pronunciation: 'じゅうさんこ' },
    },
    {
        id: 'a3932277-e2b1-4d14-8664-17adcb86fd31',
        type: 'numeral',
        en: 'Fourteen small things',
        pl: 'Czternaście małych rzeczy',
        jp: { text: '十四個', pronunciation: 'じゅうよんこ' },
    },
    {
        id: 'b2dbd578-f58b-4010-bd6d-8bc7e9d50908',
        type: 'numeral',
        en: 'Fifteen small things',
        pl: 'Piętnaście małych rzeczy',
        jp: { text: '十五個', pronunciation: 'じゅうごこ' },
    },
    {
        id: 'fd3e918b-3bab-4aeb-93ee-953918be38f1',
        type: 'numeral',
        en: 'Sixteen small things',
        pl: 'Szesnaście małych rzeczy',
        jp: { text: '十六個', pronunciation: 'じゅうろっこ' },
    },
    {
        id: '9b51d4b6-86ab-4a79-b641-5d4eed1d246b',
        type: 'numeral',
        en: 'Seventeen small things',
        pl: 'Siedemnaście małych rzeczy',
        jp: { text: '十七個', pronunciation: 'じゅうななこ' },
    },
    {
        id: '91940b79-0f9d-4495-9eb6-21dc5b376712',
        type: 'numeral',
        en: 'Eighteen small things',
        pl: 'Osiemnaście małych rzeczy',
        jp: { text: '十八個', pronunciation: 'じゅうはっこ' },
    },
    {
        id: '7a843af8-3137-4933-b7cb-da0ecdafb1fa',
        type: 'numeral',
        en: 'Nineteen small things',
        pl: 'Dziewiętnaście małych rzeczy',
        jp: { text: '十九個', pronunciation: 'じゅうきゅうこ' },
    },
    {
        id: '21f59251-aba2-4517-abb3-f9543285db8d',
        type: 'numeral',
        en: 'Twenty small things',
        pl: 'Dwadzieścia małych rzeczy',
        jp: { text: '二十個', pronunciation: 'にじゅっこ' },
    },
    {
        id: 'b3a43ecc-0aab-48e5-8a17-4233d836fee2',
        type: 'numeral',
        en: 'How many small things',
        pl: 'Ile małych rzeczy',
        jp: { text: '何個', pronunciation: 'なんこ' },
    },
];

export const countingSmallThingsBag: WordBag = {
    id: '318e8cc5-b63a-4d33-a527-5a108aa5a32a',
    name: 'Counting Small Things',
    category: 'counting',
    words: countingSmallThings,
};
