import type { TranslatedJapaneseText, WordBag } from '../../types';

const countingRepetitiveActions: TranslatedJapaneseText[] = [
    {
        id: 'cdb27b48-b771-437b-9c7a-7c3165f0a02b',
        type: 'numeral',
        en: 'One time',
        pl: 'Raz',
        jp: { text: '一回', pronunciation: 'いっかい' },
    },
    {
        id: 'c472234f-b024-44cb-89b8-4178a7829ff8',
        type: 'numeral',
        en: 'Two times',
        pl: 'Dwa razy',
        jp: { text: '二回', pronunciation: 'にかい' },
    },
    {
        id: 'e4385642-a5b7-47f2-9b03-368a9733f657',
        type: 'numeral',
        en: 'Three times',
        pl: 'Trzy razy',
        jp: { text: '三回', pronunciation: 'さんかい' },
    },
    {
        id: '8bb2de12-8abc-4e74-a38c-cbc290c59ed3',
        type: 'numeral',
        en: 'Four times',
        pl: 'Cztery razy',
        jp: { text: '四回', pronunciation: 'よんかい' },
    },
    {
        id: 'f838b6d8-2bc8-482d-90b9-f4136321b51f',
        type: 'numeral',
        en: 'Five times',
        pl: 'Pięć razy',
        jp: { text: '五回', pronunciation: 'ごかい' },
    },
    {
        id: '7c003e5e-2fd2-4a5d-8bf8-b2ddf54abe6f',
        type: 'numeral',
        en: 'Six times',
        pl: 'Sześć razy',
        jp: { text: '六回', pronunciation: 'ろっかい' },
    },
    {
        id: '43855736-3140-4245-9426-0b7d137f95bc',
        type: 'numeral',
        en: 'Seven times',
        pl: 'Siedem razy',
        jp: { text: '七回', pronunciation: 'ななかい' },
    },
    {
        id: '3dfd9133-1f39-4d6b-a965-58630d8c06ec',
        type: 'numeral',
        en: 'Eight times',
        pl: 'Osiem razy',
        jp: { text: '八回', pronunciation: ['はっかい', 'はちかい'] },
    },
    {
        id: '61ecfe78-a30d-445a-844a-21760c42bb73',
        type: 'numeral',
        en: 'Nine times',
        pl: 'Dziewięć razy',
        jp: { text: '九回', pronunciation: 'きゅうかい' },
    },
    {
        id: '8f685d26-4bd9-46aa-9ba3-2afc13870ca5',
        type: 'numeral',
        en: 'Ten times',
        pl: 'Dziesięć razy',
        jp: { text: '十回', pronunciation: ['じゅっかい', 'じっかい'] },
    },
    {
        id: '4a139a8f-1619-43f5-846b-b454a1a66077',
        type: 'numeral',
        en: 'Eleven times',
        pl: 'Jedenaście razy',
        jp: { text: '十一回', pronunciation: 'じゅういっかい' },
    },
    {
        id: '533bcd26-8c6b-4fa4-847f-1d7942b2a434',
        type: 'numeral',
        en: 'Twelve times',
        pl: 'Dwanaście razy',
        jp: { text: '十二回', pronunciation: 'じゅうにかい' },
    },
    {
        id: '7430b0c1-f70f-4a3e-aed7-0b6ff8dd481b',
        type: 'numeral',
        en: 'Thirteen times',
        pl: 'Trzynaście razy',
        jp: { text: '十三回', pronunciation: 'じゅうさんかい' },
    },
    {
        id: '01d70645-ebfc-4923-a9a4-ca8dbec419dc',
        type: 'numeral',
        en: 'Fourteen times',
        pl: 'Czternaście razy',
        jp: { text: '十四回', pronunciation: 'じゅうよんかい' },
    },
    {
        id: '2912b662-2294-458c-a794-4f6fe499da53',
        type: 'numeral',
        en: 'Fifteen times',
        pl: 'Piętnaście razy',
        jp: { text: '十五回', pronunciation: 'じゅうごかい' },
    },
    {
        id: 'ffee0156-6a2c-42ea-b6e8-dbf366bed59d',
        type: 'numeral',
        en: 'Sixteen times',
        pl: 'Szesnaście razy',
        jp: { text: '十六回', pronunciation: 'じゅうろっかい' },
    },
    {
        id: '15219e87-71ea-4d22-9570-2974c8579704',
        type: 'numeral',
        en: 'Seventeen times',
        pl: 'Siedemnaście razy',
        jp: { text: '十七回', pronunciation: 'じゅうななかい' },
    },
    {
        id: '56ac77d1-dc67-4307-9e42-bc85ec7cddd4',
        type: 'numeral',
        en: 'Eighteen times',
        pl: 'Osiemnaście razy',
        jp: { text: '十八回', pronunciation: 'じゅうはっかい' },
    },
    {
        id: '790d6c4c-04a6-4bf7-8377-7fda1d0aa7d4',
        type: 'numeral',
        en: 'Nineteen times',
        pl: 'Dziewiętnaście razy',
        jp: { text: '十九回', pronunciation: 'じゅうきゅうかい' },
    },
    {
        id: '4c4db539-cc68-4da8-a805-63233c10d48b',
        type: 'numeral',
        en: 'Twenty times',
        pl: 'Dwadzieścia razy',
        jp: { text: '二十回', pronunciation: 'にじゅっかい' },
    },
    {
        id: '2ac5a654-d878-4f9e-bdce-cea3b4afd06b',
        type: 'numeral',
        en: 'One hundred times',
        pl: 'Sto razy',
        jp: { text: '百回', pronunciation: 'ひゃっかい' },
    },
    {
        id: '51648421-73cf-4fd5-a7dc-df1ca569907c',
        type: 'numeral',
        en: 'How many times',
        pl: 'Ile razy',
        jp: { text: '何回', pronunciation: 'なんかい' },
    },
];

export const countingRepetitiveActionsBag: WordBag = {
    id: 'fed3c8e6-be7a-49ec-9f61-ff4efde37988',
    name: 'Counting Repetitive Actions',
    words: countingRepetitiveActions,
};
