import { type JapaneseWord } from '../../types';

export const countingLongCylindricalThings: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'One long cylindrical thing',
        pl: 'Jeden długi cylindryczny przedmiot',
        jp: '一本',
        jp_pronunciation: 'いっぽん',
    },
    {
        type: 'numeral',
        en: 'Two long cylindrical things',
        pl: 'Dwa długie cylindryczne przedmioty',
        jp: '二本',
        jp_pronunciation: 'にほん',
    },
    {
        type: 'numeral',
        en: 'Three long cylindrical things',
        pl: 'Trzy długie cylindryczne przedmioty',
        jp: '三本',
        jp_pronunciation: 'さんぼん',
    },
    {
        type: 'numeral',
        en: 'Four long cylindrical things',
        pl: 'Cztery długie cylindryczne przedmioty',
        jp: '四本',
        jp_pronunciation: 'よんほん',
    },
    {
        type: 'numeral',
        en: 'Five long cylindrical things',
        pl: 'Pięć długich cylindrycznych przedmiotów',
        jp: '五本',
        jp_pronunciation: 'ごほん',
    },
    {
        type: 'numeral',
        en: 'Six long cylindrical things',
        pl: 'Sześć długich cylindrycznych przedmiotów',
        jp: '六本',
        jp_pronunciation: 'ろっぽん',
    },
    {
        type: 'numeral',
        en: 'Seven long cylindrical things',
        pl: 'Siedem długich cylindrycznych przedmiotów',
        jp: '七本',
        jp_pronunciation: 'ななほん',
    },
    {
        type: 'numeral',
        en: 'Eight long cylindrical things',
        pl: 'Osiem długich cylindrycznych przedmiotów',
        jp: '八本',
        jp_pronunciation: 'はっぽん',
    },
    {
        type: 'numeral',
        en: 'Nine long cylindrical things',
        pl: 'Dziewięć długich cylindrycznych przedmiotów',
        jp: '九本',
        jp_pronunciation: 'きゅうほん',
    },
    {
        type: 'numeral',
        en: 'Ten long cylindrical things',
        pl: 'Dziesięć długich cylindrycznych przedmiotów',
        jp: '十本',
        jp_pronunciation: 'じゅっぽん',
    },
    {
        type: 'numeral',
        en: 'Eleven long cylindrical things',
        pl: 'Jedenaście długich cylindrycznych przedmiotów',
        jp: '十一本',
        jp_pronunciation: 'じゅういっぽん',
    },
    {
        type: 'numeral',
        en: 'Twelve long cylindrical things',
        pl: 'Dwanaście długich cylindrycznych przedmiotów',
        jp: '十二本',
        jp_pronunciation: 'じゅうにほん',
    },
    {
        type: 'numeral',
        en: 'Thirteen long cylindrical things',
        pl: 'Trzynaście długich cylindrycznych przedmiotów',
        jp: '十三本',
        jp_pronunciation: 'じゅうさんぼん',
    },
    {
        type: 'numeral',
        en: 'Fourteen long cylindrical things',
        pl: 'Czternaście długich cylindrycznych przedmiotów',
        jp: '十四本',
        jp_pronunciation: 'じゅうよんほん',
    },
    {
        type: 'numeral',
        en: 'Fifteen long cylindrical things',
        pl: 'Piętnaście długich cylindrycznych przedmiotów',
        jp: '十五本',
        jp_pronunciation: 'じゅうごほん',
    },
    {
        type: 'numeral',
        en: 'Sixteen long cylindrical things',
        pl: 'Szesnaście długich cylindrycznych przedmiotów',
        jp: '十六本',
        jp_pronunciation: 'じゅうろっぽん',
    },
    {
        type: 'numeral',
        en: 'Seventeen long cylindrical things',
        pl: 'Siedemnaście długich cylindrycznych przedmiotów',
        jp: '十七本',
        jp_pronunciation: 'じゅうななほん',
    },
    {
        type: 'numeral',
        en: 'Eighteen long cylindrical things',
        pl: 'Osiemnaście długich cylindrycznych przedmiotów',
        jp: '十八本',
        jp_pronunciation: 'じゅうはっぽん',
    },
    {
        type: 'numeral',
        en: 'Nineteen long cylindrical things',
        pl: 'Dziewiętnaście długich cylindrycznych przedmiotów',
        jp: '十九本',
        jp_pronunciation: 'じゅうきゅうほん',
    },
    {
        type: 'numeral',
        en: 'Twenty long cylindrical things',
        pl: 'Dwadzieścia długich cylindrycznych przedmiotów',
        jp: '二十本',
        jp_pronunciation: 'にじゅっぽん',
    },
];
