import type { JapaneseWord } from '../types.ts';

export const countingThings: JapaneseWord[] = [
    {
        type: 'numeral',
        en: 'One thing',
        pl: 'Jedna rzecz',
        jp: 'ひとつ',
    },
    {
        type: 'numeral',
        en: 'Two things',
        pl: 'Dwie rzeczy',
        jp: 'ふたつ',
    },
    {
        type: 'numeral',
        en: 'Three things',
        pl: 'Trzy rzeczy',
        jp: 'みっつ',
    },
    {
        type: 'numeral',
        en: 'Four things',
        pl: 'Cztery rzeczy',
        jp: 'よっつ',
    },
    {
        type: 'numeral',
        en: 'Five things',
        pl: 'Pięć rzeczy',
        jp: 'いつつ',
    },
    {
        type: 'numeral',
        en: 'Six things',
        pl: 'Sześć rzeczy',
        jp: 'むっつ',
    },
    {
        type: 'numeral',
        en: 'Seven things',
        pl: 'Siedem rzeczy',
        jp: 'ななつ',
    },
    {
        type: 'numeral',
        en: 'Eight things',
        pl: 'Osiem rzeczy',
        jp: 'やっつ',
    },
    {
        type: 'numeral',
        en: 'Nine things',
        pl: 'Dziewięć rzeczy',
        jp: 'ここのつ',
    },
    {
        type: 'numeral',
        en: 'Ten things',
        pl: 'Dziesięć rzeczy',
        jp: 'とお',
    },
    {
        type: 'numeral',
        en: 'How many ramens do you want?',
        pl: 'Ile ramenów chcesz?',
        jp: 'ラーメンがいくつほしいですか',
    },
    {
        type: 'numeral',
        en: 'Eleven things',
        pl: 'Jedenaście rzeczy',
        jp: 'じゅういっこ',
    },
    {
        type: 'numeral',
        en: 'Twelve things',
        pl: 'Dwanaście rzeczy',
        jp: 'じゅうにこ',
    },
    {
        type: 'numeral',
        en: 'Thirteen things',
        pl: 'Trzynaście rzeczy',
        jp: 'じゅうさんこ',
    },
    {
        type: 'numeral',
        en: 'Fourteen things',
        pl: 'Czternaście rzeczy',
        jp: 'じゅうよんこ',
    },
    {
        type: 'numeral',
        en: 'Fifteen things',
        pl: 'Piętnaście rzeczy',
        jp: 'じゅうごこ',
    },
    {
        type: 'numeral',
        en: 'Sixteen things',
        pl: 'Szesnaście rzeczy',
        jp: 'じゅうろっこ',
    },
    {
        type: 'numeral',
        en: 'Seventeen things',
        pl: 'Siedemnaście rzeczy',
        jp: 'じゅうななこ',
    },
    {
        type: 'numeral',
        en: 'Eighteen things',
        pl: 'Osiemnaście rzeczy',
        jp: 'じゅうはっこ',
    },
    {
        type: 'numeral',
        en: 'Nineteen things',
        pl: 'Dziewiętnaście rzeczy',
        jp: 'じゅうきゅうこ',
    },
    {
        type: 'numeral',
        en: 'Twenty things',
        pl: 'Dwadzieścia rzeczy',
        jp: 'にじゅっこ',
    },
];
