import type { JapaneseWord } from '../../types.ts';

export const countriesEurope: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Spain',
        pl: 'Hiszpania',
        jp: { word: 'スペイン' },
    },
    {
        type: 'noun',
        en: 'Portugal',
        pl: 'Portugalia',
        jp: { word: 'ポルトガル' },
    },
    {
        type: 'noun',
        en: 'France',
        pl: 'Francja',
        jp: { word: 'フランス' },
    },
    {
        type: 'noun',
        en: 'Ireland',
        pl: 'Irlandia',
        jp: { word: 'アイルランド' },
    },
    {
        type: 'noun',
        en: 'Great Britain',
        pl: 'Wielka Brytania',
        jp: { word: 'イギリス' },
    },
    {
        type: 'noun',
        en: 'Iceland',
        pl: 'Islandia',
        jp: { word: 'アイスランド' },
    },
    {
        type: 'noun',
        en: 'Belgium',
        pl: 'Belgia',
        jp: { word: 'ベルギー' },
    },
    {
        type: 'noun',
        en: 'Netherlands',
        pl: 'Holandia',
        jp: { word: 'オランダ' },
    },
    {
        type: 'noun',
        en: 'Luxembourg',
        pl: 'Luksemburg',
        jp: { word: 'ルクセンブルク' },
    },
    {
        type: 'noun',
        en: 'Switzerland',
        pl: 'Szwajcaria',
        jp: { word: 'スイス' },
    },
    {
        type: 'noun',
        en: 'Denmark',
        pl: 'Dania',
        jp: { word: 'デンマーク' },
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: { word: 'ドイツ' },
    },
    {
        type: 'noun',
        en: 'Austria',
        pl: 'Austria',
        jp: { word: 'オーストリア' },
    },
    {
        type: 'noun',
        en: 'Italy',
        pl: 'Włochy',
        jp: { word: 'イタリア' },
    },
    {
        type: 'noun',
        en: 'Slovenia',
        pl: 'Słowenia',
        jp: { word: 'スロベニア' },
    },
    {
        type: 'noun',
        en: 'Norway',
        pl: 'Norwegia',
        jp: { word: 'ノルウェー' },
    },
    {
        type: 'noun',
        en: 'Sweden',
        pl: 'Szwecja',
        jp: { word: 'スウェーデン' },
    },
    {
        type: 'noun',
        en: 'Finland',
        pl: 'Finlandia',
        jp: { word: 'フィンランド' },
    },
    {
        type: 'noun',
        en: 'Estonia',
        pl: 'Estonia',
        jp: { word: 'エストニア' },
    },
    {
        type: 'noun',
        en: 'Latvia',
        pl: 'Łotwa',
        jp: { word: 'ラトビア' },
    },
    {
        type: 'noun',
        en: 'Lithuania',
        pl: 'Litwa',
        jp: { word: 'リトアニア' },
    },
    {
        type: 'noun',
        en: 'Russia',
        pl: 'Rosja',
        jp: { word: 'ロシア' },
    },
    {
        type: 'noun',
        en: 'Belarus',
        pl: 'Białoruś',
        jp: { word: 'ベラルーシ' },
    },
    {
        type: 'noun',
        en: 'Ukraine',
        pl: 'Ukraina',
        jp: { word: 'ウクライナ' },
    },
    {
        type: 'noun',
        en: 'Poland',
        pl: 'Polska',
        jp: { word: 'ポーランド' },
    },
    {
        type: 'noun',
        en: 'Czechia',
        pl: 'Czechy',
        jp: { word: 'チェコ' },
    },
    {
        type: 'noun',
        en: 'Slovakia',
        pl: 'Słowacja',
        jp: { word: 'スロバキア' },
    },
    {
        type: 'noun',
        en: 'Hungary',
        pl: 'Węgry',
        jp: { word: 'ハンガリー' },
    },
    {
        type: 'noun',
        en: 'Romania',
        pl: 'Rumunia',
        jp: { word: 'ルーマニア' },
    },
    {
        type: 'noun',
        en: 'Moldova',
        pl: 'Mołdawia',
        jp: { word: 'モルドバ' },
    },
    {
        type: 'noun',
        en: 'Serbia',
        pl: 'Serbia',
        jp: { word: 'セルビア' },
    },
    {
        type: 'noun',
        en: 'Bulgaria',
        pl: 'Bułgaria',
        jp: { word: 'ブルガリア' },
    },
    {
        type: 'noun',
        en: 'Croatia',
        pl: 'Chorwacja',
        jp: { word: 'クロアチア' },
    },
    {
        type: 'noun',
        en: 'Bosnia and Herzegovina',
        pl: 'Bośnia i Hercegowina',
        jp: { word: 'ボスニア・ヘルツェゴビナ' },
    },
    {
        type: 'noun',
        en: 'Montenegro',
        pl: 'Czarnogóra',
        jp: { word: 'モンテネグロ' },
    },
    {
        type: 'noun',
        en: 'Albania',
        pl: 'Albania',
        jp: { word: 'アルバニア' },
    },
    {
        type: 'noun',
        en: 'Kosovo',
        pl: 'Kosowo',
        jp: { word: 'コソボ' },
    },
    {
        type: 'noun',
        en: 'North Macedonia',
        pl: 'Północna Macedonia',
        jp: { word: '北マケドニア' },
    },
    {
        type: 'noun',
        en: 'Greece',
        pl: 'Grecja',
        jp: { word: 'ギリシャ' },
    },
    {
        type: 'noun',
        en: 'Andorra',
        pl: 'Andora',
        jp: { word: 'アンドラ' },
    },
    {
        type: 'noun',
        en: 'Liechtenstein',
        pl: 'Liechtenstein',
        jp: { word: 'リヒテンシュタイン' },
    },
    {
        type: 'noun',
        en: 'Monaco',
        pl: 'Monako',
        jp: { word: 'モナコ' },
    },
    {
        type: 'noun',
        en: 'San Marino',
        pl: 'San Marino',
        jp: { word: 'サンマリノ' },
    },
    {
        type: 'noun',
        en: 'Turkey',
        pl: 'Turcja',
        jp: { word: 'トルコ' },
    },
    {
        type: 'noun',
        en: 'Vatican City',
        pl: 'Watykan',
        jp: { word: 'バチカン' },
    },
];
