import type { JapaneseWord } from '../../types.ts';

export const countriesEurope: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Spain',
        pl: 'Hiszpania',
        jp: 'スペイン',
    },
    {
        type: 'noun',
        en: 'Portugal',
        pl: 'Portugalia',
        jp: 'ポルトガル',
    },
    {
        type: 'noun',
        en: 'France',
        pl: 'Francja',
        jp: 'フランス',
    },
    {
        type: 'noun',
        en: 'Ireland',
        pl: 'Irlandia',
        jp: 'アイルランド',
    },
    {
        type: 'noun',
        en: 'Great Britain',
        pl: 'Wielka Brytania',
        jp: 'イギリス',
    },
    {
        type: 'noun',
        en: 'Iceland',
        pl: 'Islandia',
        jp: 'アイスランド',
    },
    {
        type: 'noun',
        en: 'Belgium',
        pl: 'Belgia',
        jp: 'ベルギー',
    },
    {
        type: 'noun',
        en: 'Netherlands',
        pl: 'Holandia',
        jp: 'オランダ',
    },
    {
        type: 'noun',
        en: 'Luxembourg',
        pl: 'Luksemburg',
        jp: 'ルクセンブルク',
    },
    {
        type: 'noun',
        en: 'Switzerland',
        pl: 'Szwajcaria',
        jp: 'スイス',
    },
    {
        type: 'noun',
        en: 'Denmark',
        pl: 'Dania',
        jp: 'デンマーク',
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: 'ドイツ',
    },
    {
        type: 'noun',
        en: 'Austria',
        pl: 'Austria',
        jp: 'オーストリア',
    },
    {
        type: 'noun',
        en: 'Italy',
        pl: 'Włochy',
        jp: 'イタリア',
    },
    {
        type: 'noun',
        en: 'Slovenia',
        pl: 'Słowenia',
        jp: 'スロベニア',
    },
    {
        type: 'noun',
        en: 'Norway',
        pl: 'Norwegia',
        jp: 'ノルウェー',
    },
    {
        type: 'noun',
        en: 'Sweden',
        pl: 'Szwecja',
        jp: 'スウェーデン',
    },
    {
        type: 'noun',
        en: 'Finland',
        pl: 'Finlandia',
        jp: 'フィンランド',
    },
    {
        type: 'noun',
        en: 'Estonia',
        pl: 'Estonia',
        jp: 'エストニア',
    },
    {
        type: 'noun',
        en: 'Latvia',
        pl: 'Łotwa',
        jp: 'ラトビア',
    },
    {
        type: 'noun',
        en: 'Lithuania',
        pl: 'Litwa',
        jp: 'リトアニア',
    },
    {
        type: 'noun',
        en: 'Russia',
        pl: 'Rosja',
        jp: 'ロシア',
    },
    {
        type: 'noun',
        en: 'Belarus',
        pl: 'Białoruś',
        jp: 'ベラルーシ',
    },
    {
        type: 'noun',
        en: 'Ukraine',
        pl: 'Ukraina',
        jp: 'ウクライナ',
    },
    {
        type: 'noun',
        en: 'Poland',
        pl: 'Polska',
        jp: 'ポーランド',
    },
    {
        type: 'noun',
        en: 'Czechia',
        pl: 'Czechy',
        jp: 'チェコ',
    },
    {
        type: 'noun',
        en: 'Slovakia',
        pl: 'Słowacja',
        jp: 'スロバキア',
    },
    {
        type: 'noun',
        en: 'Hungary',
        pl: 'Węgry',
        jp: 'ハンガリー',
    },
    {
        type: 'noun',
        en: 'Romania',
        pl: 'Rumunia',
        jp: 'ルーマニア',
    },
    {
        type: 'noun',
        en: 'Moldova',
        pl: 'Mołdawia',
        jp: 'モルドバ',
    },
    {
        type: 'noun',
        en: 'Serbia',
        pl: 'Serbia',
        jp: 'セルビア',
    },
    {
        type: 'noun',
        en: 'Bulgaria',
        pl: 'Bułgaria',
        jp: 'ブルガリア',
    },
    {
        type: 'noun',
        en: 'Croatia',
        pl: 'Chorwacja',
        jp: 'クロアチア',
    },
    {
        type: 'noun',
        en: 'Bosnia and Herzegovina',
        pl: 'Bośnia i Hercegowina',
        jp: 'ボスニア・ヘルツェゴビナ',
    },
    {
        type: 'noun',
        en: 'Montenegro',
        pl: 'Czarnogóra',
        jp: 'モンテネグロ',
    },
    {
        type: 'noun',
        en: 'Albania',
        pl: 'Albania',
        jp: 'アルバニア',
    },
    {
        type: 'noun',
        en: 'Kosovo',
        pl: 'Kosowo',
        jp: 'コソボ',
    },
    {
        type: 'noun',
        en: 'North Macedonia',
        pl: 'Północna Macedonia',
        jp: '北マケドニア',
    },
    {
        type: 'noun',
        en: 'Greece',
        pl: 'Grecja',
        jp: 'ギリシャ',
    },
    {
        type: 'noun',
        en: 'Andorra',
        pl: 'Andora',
        jp: 'アンドラ',
    },
    {
        type: 'noun',
        en: 'Liechtenstein',
        pl: 'Liechtenstein',
        jp: 'リヒテンシュタイン',
    },
    {
        type: 'noun',
        en: 'Monaco',
        pl: 'Monako',
        jp: 'モナコ',
    },
    {
        type: 'noun',
        en: 'San Marino',
        pl: 'San Marino',
        jp: 'サンマリノ',
    },
    {
        type: 'noun',
        en: 'Turkey',
        pl: 'Turcja',
        jp: 'トルコ',
    },
    {
        type: 'noun',
        en: 'Vatican City',
        pl: 'Watykan',
        jp: 'バチカン',
    },
];
