import type { TranslatedJapaneseText, WordBag } from '../../types';

const countriesEurope: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Spain',
        pl: 'Hiszpania',
        jp: { text: 'スペイン' },
    },
    {
        type: 'noun',
        en: 'Portugal',
        pl: 'Portugalia',
        jp: { text: 'ポルトガル' },
    },
    {
        type: 'noun',
        en: 'France',
        pl: 'Francja',
        jp: { text: 'フランス' },
    },
    {
        type: 'noun',
        en: 'Ireland',
        pl: 'Irlandia',
        jp: { text: 'アイルランド' },
    },
    {
        type: 'noun',
        en: 'Great Britain',
        pl: 'Wielka Brytania',
        jp: { text: 'イギリス' },
    },
    {
        type: 'noun',
        en: 'Iceland',
        pl: 'Islandia',
        jp: { text: 'アイスランド' },
    },
    {
        type: 'noun',
        en: 'Belgium',
        pl: 'Belgia',
        jp: { text: 'ベルギー' },
    },
    {
        type: 'noun',
        en: 'Netherlands',
        pl: 'Holandia',
        jp: { text: 'オランダ' },
    },
    {
        type: 'noun',
        en: 'Luxembourg',
        pl: 'Luksemburg',
        jp: { text: 'ルクセンブルク' },
    },
    {
        type: 'noun',
        en: 'Switzerland',
        pl: 'Szwajcaria',
        jp: { text: 'スイス' },
    },
    {
        type: 'noun',
        en: 'Denmark',
        pl: 'Dania',
        jp: { text: 'デンマーク' },
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: { text: 'ドイツ' },
    },
    {
        type: 'noun',
        en: 'Austria',
        pl: 'Austria',
        jp: { text: 'オーストリア' },
    },
    {
        type: 'noun',
        en: 'Italy',
        pl: 'Włochy',
        jp: { text: 'イタリア' },
    },
    {
        type: 'noun',
        en: 'Slovenia',
        pl: 'Słowenia',
        jp: { text: 'スロベニア' },
    },
    {
        type: 'noun',
        en: 'Norway',
        pl: 'Norwegia',
        jp: { text: 'ノルウェー' },
    },
    {
        type: 'noun',
        en: 'Sweden',
        pl: 'Szwecja',
        jp: { text: 'スウェーデン' },
    },
    {
        type: 'noun',
        en: 'Finland',
        pl: 'Finlandia',
        jp: { text: 'フィンランド' },
    },
    {
        type: 'noun',
        en: 'Estonia',
        pl: 'Estonia',
        jp: { text: 'エストニア' },
    },
    {
        type: 'noun',
        en: 'Latvia',
        pl: 'Łotwa',
        jp: { text: 'ラトビア' },
    },
    {
        type: 'noun',
        en: 'Lithuania',
        pl: 'Litwa',
        jp: { text: 'リトアニア' },
    },
    {
        type: 'noun',
        en: 'Russia',
        pl: 'Rosja',
        jp: { text: 'ロシア' },
    },
    {
        type: 'noun',
        en: 'Belarus',
        pl: 'Białoruś',
        jp: { text: 'ベラルーシ' },
    },
    {
        type: 'noun',
        en: 'Ukraine',
        pl: 'Ukraina',
        jp: { text: 'ウクライナ' },
    },
    {
        type: 'noun',
        en: 'Poland',
        pl: 'Polska',
        jp: { text: 'ポーランド' },
    },
    {
        type: 'noun',
        en: 'Czechia',
        pl: 'Czechy',
        jp: { text: 'チェコ' },
    },
    {
        type: 'noun',
        en: 'Slovakia',
        pl: 'Słowacja',
        jp: { text: 'スロバキア' },
    },
    {
        type: 'noun',
        en: 'Hungary',
        pl: 'Węgry',
        jp: { text: 'ハンガリー' },
    },
    {
        type: 'noun',
        en: 'Romania',
        pl: 'Rumunia',
        jp: { text: 'ルーマニア' },
    },
    {
        type: 'noun',
        en: 'Moldova',
        pl: 'Mołdawia',
        jp: { text: 'モルドバ' },
    },
    {
        type: 'noun',
        en: 'Serbia',
        pl: 'Serbia',
        jp: { text: 'セルビア' },
    },
    {
        type: 'noun',
        en: 'Bulgaria',
        pl: 'Bułgaria',
        jp: { text: 'ブルガリア' },
    },
    {
        type: 'noun',
        en: 'Croatia',
        pl: 'Chorwacja',
        jp: { text: 'クロアチア' },
    },
    {
        type: 'noun',
        en: 'Bosnia and Herzegovina',
        pl: 'Bośnia i Hercegowina',
        jp: { text: 'ボスニア・ヘルツェゴビナ' },
    },
    {
        type: 'noun',
        en: 'Montenegro',
        pl: 'Czarnogóra',
        jp: { text: 'モンテネグロ' },
    },
    {
        type: 'noun',
        en: 'Albania',
        pl: 'Albania',
        jp: { text: 'アルバニア' },
    },
    {
        type: 'noun',
        en: 'Kosovo',
        pl: 'Kosowo',
        jp: { text: 'コソボ' },
    },
    {
        type: 'noun',
        en: 'North Macedonia',
        pl: 'Północna Macedonia',
        jp: { text: '北マケドニア', pronunciation: 'きたマケドニア' },
    },
    {
        type: 'noun',
        en: 'Greece',
        pl: 'Grecja',
        jp: { text: 'ギリシャ' },
    },
    {
        type: 'noun',
        en: 'Andorra',
        pl: 'Andora',
        jp: { text: 'アンドラ' },
    },
    {
        type: 'noun',
        en: 'Liechtenstein',
        pl: 'Liechtenstein',
        jp: { text: 'リヒテンシュタイン' },
    },
    {
        type: 'noun',
        en: 'Monaco',
        pl: 'Monako',
        jp: { text: 'モナコ' },
    },
    {
        type: 'noun',
        en: 'San Marino',
        pl: 'San Marino',
        jp: { text: 'サンマリノ' },
    },
    {
        type: 'noun',
        en: 'Turkey',
        pl: 'Turcja',
        jp: { text: 'トルコ' },
    },
    {
        type: 'noun',
        en: 'Vatican City',
        pl: 'Watykan',
        jp: { text: 'バチカン' },
    },
];

export const countriesEuropeBag: WordBag = {
    id: 'efcf6fe8-9b79-436f-8c4d-0987393fb4c6',
    name: 'Countries Europe',
    words: countriesEurope,
};
