import {
    countriesEUBag,
    weekBag,
    duolingo1Bag,
    duolingo2Bag,
    duolingo3Bag,
    duolingo4Bag,
    duolingo5Bag,
    duolingo6Bag,
    familyBag,
    genki0Bag,
    genki1Bag,
    genki1MajorsBag,
    genki2Bag,
    genki3Bag,
    genki4Bag,
    numbersBag,
    sakura1_1Bag,
    sakura1_2Bag,
    sakura1_3Bag,
    sakura1_4Bag,
    sakura1_5Bag,
    sakura1_6Bag,
    sakura1_7Bag,
    sakura1_8Bag,
    sakura1_8AnimalsBag,
    sakura1_8FruitsAndVegetablesBag,
    sakura1_8SportsBag,
    hoursBag,
    minutesBag,
    sakura1_9Bag,
    sakura1_10Bag,
    countingThingsBag,
    monthsBag,
    sakura1_11Bag,
    duolingo7Bag,
    countriesAsiaBag,
    duolingo8Bag,
    sakura1_12Bag,
    duolingo9Bag,
    sakura2_1Bag,
    sakura2_2Bag,
    directionsBag,
    sakura2_3Bag,
    duolingo10Bag,
    sakura2_4Bag,
    duolingo11Bag,
    sakura2_5Bag,
    sakura2_6Bag,
    yearsBag,
    daysOfMonthBag,
    genki5Bag,
    countingFloorsBag,
    duolingo12Bag,
    type WordBag,
    countingThinObjectsBag,
    countingLongCylindricalThingsBag,
} from '../../japanese';

export const groupedBags: Record<string, WordBag[]> = {
    'Time ⏰': [weekBag, hoursBag, minutesBag, monthsBag, daysOfMonthBag, yearsBag],
    'Counting 🔢': [countingThinObjectsBag, countingLongCylindricalThingsBag, countingThingsBag, countingFloorsBag],
    'Essentials 📌': [familyBag, numbersBag, directionsBag],
    'Genki books 📚': [genki0Bag, genki1Bag, genki1MajorsBag, genki2Bag, genki3Bag, genki4Bag, genki5Bag],
    'Classes 🎓': [
        sakura1_1Bag,
        sakura1_2Bag,
        sakura1_3Bag,
        sakura1_4Bag,
        sakura1_5Bag,
        sakura1_6Bag,
        sakura1_7Bag,
        sakura1_8Bag,
        sakura1_8SportsBag,
        sakura1_8FruitsAndVegetablesBag,
        sakura1_8AnimalsBag,
        sakura1_9Bag,
        sakura1_10Bag,
        sakura1_11Bag,
        sakura1_12Bag,
        sakura2_1Bag,
        sakura2_2Bag,
        sakura2_3Bag,
        sakura2_4Bag,
        sakura2_5Bag,
        sakura2_6Bag,
    ],
    'Apps 📱': [
        duolingo1Bag,
        duolingo2Bag,
        duolingo3Bag,
        duolingo4Bag,
        duolingo5Bag,
        duolingo6Bag,
        duolingo7Bag,
        duolingo8Bag,
        duolingo9Bag,
        duolingo10Bag,
        duolingo11Bag,
        duolingo12Bag,
    ],
    'Geography 🌍 🌎 🌏': [countriesEUBag, countriesAsiaBag],
};
