import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_4_3: TranslatedJapaneseText[] = [
    {
        id: '63248c8e-f80e-4684-be7f-4092af0b4d4d',
        type: 'noun',
        en: 'Time / Occasion / Case',
        pl: 'Czas / Okazja / Przypadek',
        jp: { text: '時', pronunciation: 'とき' },
    },
    {
        id: '82e493d2-e0a9-4536-80db-3a628f82b294',
        type: 'noun',
        en: 'Dream / Wish',
        pl: 'Sen / Marzenie',
        jp: { text: '夢', pronunciation: 'ゆめ' },
    },
    {
        id: '7790815a-fdd3-4861-bf94-2a2c1873f1e0',
        type: 'noun',
        en: 'Hanafuda',
        pl: 'Hanafuda',
        jp: { text: '花札', pronunciation: 'はなふだ' },
    },
    {
        id: '92be2215-68ae-4bbd-a4e3-0bd252ee0e9f',
        type: 'noun',
        en: 'Particle',
        pl: 'Partykuła',
        jp: { text: '助詞', pronunciation: 'じょし' },
    },
    {
        id: '7fb62b58-3811-4f0f-bd1b-8aea4c6fa099',
        type: 'noun',
        en: 'Review',
        pl: 'Powtórka',
        jp: { text: 'レビュー' },
    },
    {
        id: 'bead35ab-9b2f-4831-b29b-7d9aab249d33',
        type: 'noun',
        en: 'Organizing / Arrangement',
        pl: 'Organizacja / Porządkowanie',
        jp: { text: '整理', pronunciation: 'せいり' },
    },
    {
        id: 'c18505e5-bf7c-48db-897c-24994e2765f9',
        type: 'verb',
        verb_type: 'suru',
        en: 'Organize / Arrange',
        pl: 'Organizować / Układać',
        jp: { text: '整理する', pronunciation: 'せいりする' },
    },
    {
        id: 'd0af5612-b24c-4158-a0d4-3c79648e2392',
        type: 'noun',
        en: 'Comedy',
        pl: 'Komedia',
        jp: { text: 'コメディー' },
    },
    {
        id: 'f7885bf8-4a51-4f90-a3ed-2726c1d3c1a1',
        type: 'noun',
        en: 'Action',
        pl: 'Akcja',
        jp: { text: 'アクション' },
    },
    {
        id: '63b2c921-2f34-4ff3-81a4-fbedddacde93',
        type: 'noun',
        en: 'Horror',
        pl: 'Horror',
        jp: { text: 'ホラー' },
    },
    {
        id: '7b1fb667-a2c4-4737-9e8d-59cb39f0ee15',
        type: 'noun',
        en: 'Romance',
        pl: 'Romans',
        jp: { text: '恋愛', pronunciation: 'れんあい' },
    },
    {
        id: '7a9a834f-d187-4eaf-8430-46f458b90e21',
        type: 'noun',
        en: 'Anime',
        pl: 'Anime',
        jp: { text: 'アニメ' },
    },
    {
        id: '95bc3fa9-72e9-441e-a673-15829457f7e2',
        type: 'noun',
        en: 'Classical music',
        pl: 'Muzyka klasyczna',
        jp: { text: 'クラシック' },
    },
    {
        id: '3b1f5dca-34cd-4d42-87ba-b3bb6e90bdfe',
        type: 'noun',
        en: 'Jazz',
        pl: 'Jazz',
        jp: { text: 'ジャズ' },
    },
    {
        id: '20f1d4f5-4da2-45fd-973f-7aecd59c7706',
        type: 'noun',
        en: 'Pop music',
        pl: 'Muzyka pop',
        jp: { text: 'ポップス' },
    },
    {
        id: '971cdc1e-6c1d-4278-8059-12333b043975',
        type: 'noun',
        en: 'Song',
        pl: 'Piosenka',
        jp: { text: '歌', pronunciation: 'うた' },
    },
    {
        id: 'eee9362c-c992-430d-b04a-297df9581752',
        type: 'noun',
        en: 'Manga',
        pl: 'Manga',
        jp: { text: '漫画', pronunciation: 'まんが' },
    },
    {
        id: '27362863-fee6-4576-a7cb-a89aaf22e832',
        type: 'noun',
        en: 'Novel',
        pl: 'Powieść',
        jp: { text: '小説', pronunciation: 'しょうせつ' },
    },
    {
        id: 'd9457332-9a1f-4a5e-8975-bcdd466c69ed',
        type: 'noun',
        en: 'Literature',
        pl: 'Literatura',
        jp: { text: '文学', pronunciation: 'ぶんがく' },
    },
    {
        id: '1d525b23-de0e-4ca5-bc06-e4ca9064752f',
        type: 'noun',
        en: 'Mystery',
        pl: 'Kryminał',
        jp: { text: 'ミステリー' },
    },
    {
        id: 'bb91ff7d-a9ab-46e6-9e20-07fc6c831e83',
        type: 'noun',
        en: 'Science fiction',
        pl: 'Fantastyka naukowa',
        jp: { text: 'SF', pronunciation: 'エスエフ' },
    },
    {
        id: '048de02e-33f0-4b19-95f9-2736d4afffcf',
        type: 'verb',
        verb_type: 'suru',
        en: 'Read (a book)',
        pl: 'Czytać (książkę)',
        jp: { text: '読書をする', pronunciation: 'どくしょをする' },
    },
    {
        id: '5ffcafbd-ea91-4896-b201-1c83b95a10c3',
        type: 'noun',
        en: 'Dance',
        pl: 'Taniec',
        jp: { text: 'ダンス' },
    },
    {
        id: '4fd285c8-4448-4da1-a81e-20077352c99a',
        type: 'noun',
        en: 'Foreign language',
        pl: 'Język obcy',
        jp: { text: '外国語', pronunciation: 'がいこくご' },
    },
    {
        id: 'dfa97439-d04b-4ea2-9f67-6eb90b8fbb65',
        type: 'noun',
        en: 'Short Japanese poem',
        pl: 'Krótki japoński wiersz',
        jp: { text: '俳句', pronunciation: 'はいく' },
    },
    {
        id: '933f7616-5d55-4bcd-b01e-c2ab3a18ef93',
        type: 'noun',
        en: 'Origami',
        pl: 'Origami',
        jp: { text: '折り紙', pronunciation: 'おりがみ' },
    },
    {
        id: 'bbf700c2-173c-4b11-9ea0-eacedab82220',
        type: 'noun',
        en: 'Tea ceremony',
        pl: 'Ceremonia herbaciana',
        jp: { text: '茶道', pronunciation: 'さどう' },
    },
    {
        id: '52d9f0bf-9b52-46bd-b7dd-38fb2f1d03d0',
        type: 'noun',
        en: 'Japanese art of flower arrangement',
        pl: 'Japońska sztuka układania kwiatów',
        jp: { text: '生け花', pronunciation: 'いけばな' },
    },
    {
        id: 'f962434c-4ce8-487b-8dd9-1219933da4ec',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Very fond of / Beloved',
        pl: 'Bardzo lubiany / Ukochany',
        jp: { text: '大好き', pronunciation: 'だいすき' },
    },
    {
        id: '1da59ffa-8042-47e8-976f-cd627a7f973c',
        type: 'phrase',
        en: 'What instrument can you play?',
        pl: 'Na jakim instrumencie potrafisz grać?',
        jp: { text: 'どんな楽器ができますか。', pronunciation: 'どんながっきができますか。' },
    },
    {
        id: 'fd60e356-84c3-4a55-9f6c-c2c6905ad84d',
        type: 'phrase',
        en: 'I can play the piano.',
        pl: 'Potrafię grać na pianinie.',
        jp: { text: 'ピアノができます。', pronunciation: 'ぴあのができます。' },
    },
    {
        id: 'f1d501f3-f353-4de8-ba85-8b98ff6a7311',
        type: 'phrase',
        en: "I can't play any musical instrument.",
        pl: 'Nie potrafię grać na żadnym instrumencie.',
        jp: { text: '楽器はできません。', pronunciation: 'がっきはできません。' },
    },
    {
        id: '23c60ec9-3845-47b1-8f77-f40344f3af7e',
        type: 'phrase',
        en: 'I like playing football.',
        pl: 'Lubię grać w piłkę nożną.',
        jp: { text: 'サッカーをすることが好きです。', pronunciation: 'さっかーをすることがすきです。' },
    },
    {
        id: 'e871a1db-21ef-47ad-94b7-d58de7c7eb28',
        type: 'phrase',
        en: 'I like running.',
        pl: 'Lubię biegać.',
        jp: { text: '走ることが好きです。', pronunciation: 'はしることがすきです。' },
    },
    {
        id: 'bdc78adf-df3e-41c2-8304-722bd93699de',
        type: 'noun',
        en: 'Masu form',
        pl: 'Forma masu',
        jp: { text: 'ます形', pronunciation: 'ますけい' },
    },
    {
        id: '4a92f426-e910-4889-b5e9-f411c1257196',
        type: 'noun',
        en: 'Dictionary form',
        pl: 'Forma słownikowa',
        jp: { text: '辞書形', pronunciation: 'じしょけい' },
    },
];

export const sakura4_3Bag: WordBag = {
    id: '60b750eb-dcbd-419f-bab0-9a12e28ccefc',
    name: 'Sakura #4.3',
    category: 'sakura',
    words: sakura_4_3,
};
