import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_4_1: TranslatedJapaneseText[] = [
    {
        id: '991bf979-1c33-4e58-9cf2-61baa3f38485',
        type: 'noun',
        en: 'Muslim',
        pl: 'Muzułmanin',
        jp: { text: 'ムスリム' },
    },
    {
        id: 'f0a3bcf8-9598-45ad-8db6-690c001ed313',
        type: 'phrase',
        en: 'I eat ramen with chopsticks.',
        pl: 'Jem ramen pałeczkami.',
        jp: { text: '箸でラーメンを食べます。', pronunciation: 'はしでラーメンをたべます。' },
    },
    {
        id: '00efb39d-0783-47c5-aa50-f04bd8eca4d3',
        type: 'phrase',
        en: 'I write a letter with a pen.',
        pl: 'Piszę list długopisem.',
        jp: { text: 'ペンで手紙を書きます。', pronunciation: 'ペンでてがみをかきます。' },
    },
    {
        id: 'd2baf039-e24e-4852-9eef-e489fffcd2d1',
        type: 'phrase',
        en: 'What do you eat pizza with?',
        pl: 'Czym jesz pizzę?',
        jp: { text: '何でピザを食べますか。', pronunciation: 'なにでピザをたべますか。' },
    },
    {
        id: '5a23671f-4c4c-4069-9164-c48990a4ac94',
        type: 'noun',
        en: 'Fork',
        pl: 'Widelec',
        jp: { text: 'フォーク' },
    },
    {
        id: 'a2c960de-c78b-47be-8c63-f90452cdf505',
        type: 'noun',
        en: 'Spoon',
        pl: 'Łyżka',
        jp: { text: 'スプーン' },
    },
    {
        id: '056cfc52-fd38-4807-b6c9-915ec8c06a8c',
        type: 'phrase',
        en: 'I watch news on TV.',
        pl: 'Oglądam wiadomości w telewizji.',
        jp: { text: 'テレビでニュースを見ます。', pronunciation: 'テレビでニュースをみます。' },
    },
    {
        id: 'bd162587-5be9-4140-b8d8-8cd993fd4d90',
        type: 'noun',
        en: 'Rice (raw)',
        pl: 'Ryż (surowy)',
        jp: { text: '米', pronunciation: 'こめ' },
    },
    {
        id: '0941f2e8-97e8-4422-be62-faa8471d47dd',
        type: 'phrase',
        en: 'What language do you speak at work?',
        pl: 'Jakim językiem mówisz w pracy?',
        jp: { text: '仕事で何語で話しますか。', pronunciation: 'しごとでなにごではなしますか。' },
    },
    {
        id: '5d5ef51f-b551-43c3-b7e2-e2f5d3c1f817',
        type: 'phrase',
        en: 'I write my book in Japanese.',
        pl: 'Piszę moją książkę po japońsku.',
        jp: { text: '私は日本語で本を書きます。', pronunciation: 'わたしはにほんごでほんをかきます。' },
    },
    {
        id: '9ff4a376-6575-4f03-80c4-f94cbc48647a',
        type: 'noun',
        en: 'Tokyo Tower',
        pl: 'Wieża Tokijska',
        jp: { text: '東京タワー', pronunciation: 'とうきょうタワー' },
    },
    {
        id: '27488eb9-cd21-4d4b-aba4-19c9b7602ae1',
        type: 'phrase',
        en: 'It is best to go to the airport by train.',
        pl: 'Najlepiej jechać na lotnisko pociągiem.',
        jp: { text: '空港は電車がいいですよ。', pronunciation: 'くうこうはでんしゃがいいですよ。' },
        description: 'よ at the end of the sentence is a common thing when giving an advice.',
    },
    {
        id: '263c5f6d-d578-4266-83e7-5dd7414c0ff5',
        type: 'phrase',
        en: "It's because it is fast.",
        pl: 'Ponieważ jest szybki.',
        jp: { text: '速いですから。', pronunciation: 'はやいですから。' },
        description: 'から is a suffix that is used to explain the reason for something - like "because" in English.',
    },
    {
        id: '0cb84327-c9ce-41f7-ac3d-b731a562caf8',
        type: 'noun',
        en: 'Advice (loan word)',
        pl: 'Rada (zapożyczone słowo)',
        jp: { text: 'アドバイス' },
    },
    {
        id: '890b566f-b9f9-4f09-a7dd-05107953ea10',
        type: 'adverb',
        en: 'For the first time',
        pl: 'Po raz pierwszy',
        jp: { text: '初めて', pronunciation: 'はじめて' },
    },
    {
        id: '67e6d9c7-61aa-46f9-b89d-f4f6da9b36b2',
        type: 'adverb',
        en: 'Why / For what reason',
        pl: 'Dlaczego / Z jakiego powodu',
        jp: { text: 'どうして' },
    },
    {
        id: '4764ae4f-5621-421b-8689-b531dd9aee02',
        type: 'phrase',
        en: 'Why?',
        pl: 'Dlaczego?',
        jp: { text: 'どうしてですか。' },
    },
];

export const sakura4_1Bag: WordBag = {
    id: 'e553f591-535a-4ea8-850e-8b34c34b24cb',
    name: 'Sakura #4.1',
    category: 'sakura',
    words: sakura_4_1,
};
