import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_4_9: TranslatedJapaneseText[] = [
    {
        id: 'b3b8b0e2-5aff-4d35-b7d2-28b394d670bc',
        type: 'noun',
        en: 'Teacup',
        pl: 'Filiżanka',
        jp: { text: 'ティーカップ' },
    },
    {
        id: '7cc6acc1-39fd-4b1f-a3b2-6cc44a4d69c4',
        type: 'noun',
        en: 'Picture postcard',
        pl: 'Pocztówka',
        jp: { text: '絵葉書', pronunciation: 'えはがき' },
    },
    {
        id: 'dfa99d65-028c-4a7f-b23b-dca24308f0e1',
        type: 'noun',
        en: 'Computer mouse',
        pl: 'Mysz komputerowa',
        jp: { text: 'マウス' },
    },
    {
        id: '214aeb6d-f5b7-4bcf-aa90-2a3329995d0d',
        type: 'noun',
        en: 'Video camera',
        pl: 'Kamera wideo',
        jp: { text: 'ビデオカメラ' },
    },
    {
        id: '9c42de4e-5e4e-4bf1-98cc-ce6260d21909',
        type: 'noun',
        en: 'Handkerchief',
        pl: 'Chusteczka (materiałowa)',
        jp: { text: 'ハンカチ' },
    },
    {
        id: '4771e3ec-39bc-4d2e-a54c-228ee7fd5d26',
        type: 'noun',
        en: 'Electronic dictionary',
        pl: 'Słownik elektroniczny',
        jp: { text: '電子辞書', pronunciation: 'でんしじしょ' },
    },
    {
        id: '91ca5762-4114-4735-9eaa-b8b54560084b',
        type: 'noun',
        en: 'Accessory',
        pl: 'Akcesorium',
        jp: { text: 'アクセサリー' },
    },
    {
        id: '48ee7090-9517-4262-8c86-d6086e62513f',
        type: 'noun',
        en: 'Purpose / Goal',
        pl: 'Cel',
        jp: { text: '目的', pronunciation: 'もくてき' },
    },
    {
        id: 'bd19edf7-4937-4055-8a25-084e7b16c398',
        type: 'noun',
        en: 'Bar',
        pl: 'Bar',
        jp: { text: 'バー' },
    },
    {
        id: 'cf8b1f2a-31b8-471f-a3f6-c2368c9ae166',
        type: 'noun',
        en: 'Merchandise',
        pl: 'Towary / Gadżety / Artykuły promocyjne',
        jp: { text: 'グッズ' },
    },
    {
        id: '89c28c3c-b744-4d36-98ad-97069a71e773',
        type: 'noun',
        en: 'Public square',
        pl: 'Rynek / Plac miejski',
        jp: { text: '広場', pronunciation: 'ひろば' },
    },
    {
        id: 'fd0fe973-b19d-4498-b450-a0ddaf38442e',
        type: 'verb',
        verb_type: 'ichidan',
        transitivity: 'transitive',
        en: 'Borrow',
        pl: 'Pożyczać',
        jp: { text: '借りる', pronunciation: 'かりる' },
    },
    {
        id: 'fb2958c0-2cd0-471d-96b1-21ef87a58b8d',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Regrettable / Unfortunate / Disappointing',
        pl: 'Godny ubolewania / Niefortunny / Rozczarowujący',
        jp: { text: '残念', pronunciation: 'ざんねん' },
    },
    {
        id: '5e466e1b-5f42-4cc2-9174-2953a8dd6162',
        type: 'noun',
        en: 'Fashion show',
        pl: 'Pokaz mody',
        jp: { text: 'ファッションショー' },
    },
    {
        id: '6d759aa4-3b60-4143-b460-f740770cb18e',
        type: 'phrase',
        en: 'Would you like to go to the library to read a book?',
        pl: 'Czy chciałbyś iść do biblioteki, aby przeczytać książkę?',
        jp: { text: '図書館に本を読みに行きませんか。', pronunciation: 'としょかんにほんをよみにいきませんか。' },
    },
    {
        id: '93c0b091-a025-4ca2-8dec-534ceda5636a',
        type: 'phrase',
        en: 'Do you want to go to the cinema to watch a movie?',
        pl: 'Czy chcesz iść do kina, aby obejrzeć film?',
        jp: { text: '映画館に映画を見に行きませんか。', pronunciation: 'えいがかんにえいがをみにいきませんか。' },
    },
    {
        id: 'f4f34f70-93b4-4df1-b586-ccb796040402',
        type: 'phrase',
        en: "Yes, let's go!",
        pl: 'Tak, chodźmy!',
        jp: { text: 'はい、行きましょう！', pronunciation: 'はい、いきましょう！' },
    },
    {
        id: 'b3eeabd7-1474-485b-873e-bc6b11a58c04',
        type: 'noun',
        en: 'Park (loan word)',
        pl: 'Park (zapożyczone słowo)',
        jp: { text: 'パーク' },
    },
    {
        id: '6b12d380-af86-4f8e-bf73-e938b681173e',
        type: 'noun',
        en: 'Event',
        pl: 'Wydarzenie',
        jp: { text: 'イベント' },
    },
];

export const sakura4_9Bag: WordBag = {
    id: '3c8b0d02-d1e2-4591-844a-324e47046f03',
    name: 'Sakura #4.9',
    category: 'sakura',
    words: sakura_4_9,
};
