import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_4_7: TranslatedJapaneseText[] = [
    {
        id: 'fccb4c58-c098-42ad-938c-5148c27e9e3f',
        type: 'noun',
        en: 'After / Later',
        pl: 'Po / Później',
        jp: { text: '後', pronunciation: 'あと' },
    },
    {
        id: '2e80363b-e918-45fc-841d-c88942088cbe',
        type: 'verb',
        verb_type: 'godan',
        transitivity: 'ambitransitive',
        en: 'End / Finish / Complete',
        pl: 'Skończyć / Zakończyć',
        jp: { text: '終わる', pronunciation: 'おわる' },
    },
    {
        id: '18c10256-6f3d-46f3-bba8-ca9f7b263b07',
        type: 'phrase',
        en: 'First Monday of January',
        pl: 'Pierwszy poniedziałek stycznia',
        jp: { text: '一月第一月曜日', pronunciation: 'いちがつだいいちげつようび' },
    },
    {
        id: '4509e140-ef12-4976-879c-3a4d6fc5800e',
        type: 'phrase',
        en: 'Second Thursday of November',
        pl: 'Drugi czwartek listopada',
        jp: { text: '十一月第二木曜日', pronunciation: 'じゅういちがつだいにもくようび' },
    },
    {
        id: 'd577f530-c50a-47f8-a38e-b6eb443f28da',
        type: 'phrase',
        en: 'Third Wednesday of April',
        pl: 'Trzecia środa kwietnia',
        jp: { text: '四月第三水曜日', pronunciation: 'しがつだいさんすいようび' },
    },
    {
        id: '3e9c33e6-e42b-48a9-845e-8f763ccf778a',
        type: 'noun',
        en: "New Year's Day",
        pl: 'Nowy Rok',
        jp: { text: '元日', pronunciation: 'がんじつ' },
    },
    {
        id: '15e4448e-54b2-4d82-b00d-4dd3e6258f3e',
        type: 'noun',
        en: 'Coming of Age Day',
        pl: 'Dzień Osiągnięcia Pełnoletności',
        jp: { text: '成人の日', pronunciation: 'せいじんのひ' },
    },
    {
        id: '173a2aa3-6168-4520-b378-08f882552fef',
        type: 'noun',
        en: 'National Foundation Day',
        pl: 'Dzień Założenia Państwa',
        jp: { text: '建国記念日', pronunciation: 'けんこくきねんび' },
    },
    {
        id: '1d0fe947-ca10-4c66-82c8-dc6e9058945e',
        type: 'noun',
        en: "Emperor's Birthday",
        pl: 'Urodziny Cesarza',
        jp: { text: '天皇誕生日', pronunciation: 'てんのうたんじょうび' },
    },
    {
        id: 'dd07d6df-8302-42e7-9a96-ea6c7730a773',
        type: 'noun',
        en: 'Emperor of Japan',
        pl: 'Cesarz Japonii',
        jp: { text: '天皇', pronunciation: 'てんのう' },
    },
    {
        id: 'cb61afe2-dbcc-4e51-878f-37d64b745ab5',
        type: 'noun',
        en: 'Vernal Equinox Day',
        pl: 'Dzień Równonocy Wiosennej',
        jp: { text: '春分の日', pronunciation: 'しゅんぶんのひ' },
    },
    {
        id: '996df5f2-e533-4154-a218-b98c24bf208b',
        type: 'noun',
        en: 'Shōwa Day',
        pl: 'Dzień Shōwa',
        jp: { text: '昭和の日', pronunciation: 'しょうわのひ' },
    },
    {
        id: '0989918b-40b7-4db4-8ba7-615837fda229',
        type: 'noun',
        en: 'Constitution Memorial Day',
        pl: 'Dzień Pamięci Konstytucji',
        jp: { text: '憲法記念日', pronunciation: 'けんぽうきねんび' },
    },
    {
        id: 'bb368fbe-6266-4b75-a6e6-3a86f2c23d2a',
        type: 'noun',
        en: 'Greenery Day',
        pl: 'Dzień Zieleni',
        jp: { text: 'みどりの日', pronunciation: 'みどりのひ' },
    },
    {
        id: 'c603d33e-2fed-41f8-b1ce-c24e6da70d6c',
        type: 'noun',
        en: "Children's Day",
        pl: 'Dzień Dziecka',
        jp: { text: 'こどもの日', pronunciation: 'こどものひ' },
    },
    {
        id: '34d6aaa3-e898-48c8-9817-58e0b2a36133',
        type: 'noun',
        en: 'Marine Day',
        pl: 'Dzień Morza',
        jp: { text: '海の日', pronunciation: 'うみのひ' },
    },
    {
        id: 'd4d67d72-51bd-485c-99c9-578018849a79',
        type: 'noun',
        en: 'Mountain Day',
        pl: 'Dzień Gór',
        jp: { text: '山の日', pronunciation: 'やまのひ' },
    },
    {
        id: 'b7db1c60-01df-46e6-8355-4284a190e7f5',
        type: 'noun',
        en: 'Respect for the Aged Day',
        pl: 'Dzień Szacunku dla Osób Starszych',
        jp: { text: '敬老の日', pronunciation: 'けいろうのひ' },
    },
    {
        id: 'fce33c01-7c17-485f-8150-08f6a3ab7241',
        type: 'noun',
        en: 'Autumnal Equinox Day',
        pl: 'Dzień Równonocy Jesiennej',
        jp: { text: '秋分の日', pronunciation: 'しゅうぶんのひ' },
    },
    {
        id: '35b3af3e-175b-4b58-9703-4d4a3fbb5dac',
        type: 'noun',
        en: 'Culture Day',
        pl: 'Dzień Kultury',
        jp: { text: '文化の日', pronunciation: 'ぶんかのひ' },
    },
    {
        id: '91edf2ad-4b96-42d7-8944-8481224d5d9a',
        type: 'noun',
        en: 'Labor Thanksgiving Day',
        pl: 'Dzień Dziękczynienia za Pracę',
        jp: { text: '勤労感謝の日', pronunciation: 'きんろうかんしゃのひ' },
    },
    {
        id: '4e7419a2-1b8d-4108-9205-f26f973cd025',
        type: 'noun',
        en: 'Poster',
        pl: 'Plakat',
        jp: { text: 'ポスター' },
    },
    {
        id: 'cffb1300-746f-444d-af06-1ea4624ea041',
        type: 'noun',
        en: 'Calendar',
        pl: 'Kalendarz',
        jp: { text: 'カレンダー' },
    },
    {
        id: '8d22f609-1cd7-4b4f-b087-ddf8c93e9727',
        type: 'noun',
        en: 'Match / Game',
        pl: 'Mecz / Gra',
        jp: { text: '試合', pronunciation: 'しあい' },
    },
    {
        id: '25103caf-c6ae-430e-b030-b438f50d0d22',
        type: 'noun',
        en: 'International',
        pl: 'Międzynarodowy',
        jp: { text: '国際', pronunciation: 'こくさい' },
    },
    {
        id: '7f14b2eb-b867-4f36-b0b6-dfb88e0173a0',
        type: 'noun',
        en: 'Hall',
        pl: 'Sala / Aula',
        jp: { text: 'ホール' },
    },
    {
        id: 'c2fbcc30-36bc-475d-acb1-31716a2b0c88',
        type: 'adverb',
        en: 'Probably',
        pl: 'Prawdopodobnie',
        jp: { text: '多分', pronunciation: 'たぶん' },
    },
    {
        id: 'c666c743-0fc7-41fe-bffc-f4a1ba6b0657',
        type: 'noun',
        en: 'Obon Festival',
        pl: 'Święto Obon',
        jp: { text: 'お盆', pronunciation: 'おぼん' },
    },
    {
        id: '5e3b78fc-82fd-41d5-8a7c-6c3de3d73482',
        type: 'noun',
        en: 'Dance',
        pl: 'Taniec',
        jp: { text: '踊り', pronunciation: 'おどり' },
    },
    {
        id: '864e1e1a-0b6b-4702-ac69-ecff69730734',
        type: 'noun',
        en: 'Obon Festival Dance',
        pl: 'Taniec podczas święta Obon',
        jp: { text: '盆踊り', pronunciation: 'ぼんおどり' },
    },
    {
        id: 'b6684ea6-1070-4e10-9e2d-6eeb9255b0f9',
        type: 'phrase',
        en: 'There is a festival in the town next month.',
        pl: 'W przyszłym miesiącu w mieście odbędzie się festiwal.',
        jp: { text: '来月町で祭りがあります。', pronunciation: 'らいげつまちでまつりがあります。' },
    },
    {
        id: 'f3d1afa8-66af-4aa0-91da-d7efbad2442d',
        type: 'phrase',
        en: 'On April 24th, there is a party at the school.',
        pl: '24 kwietnia w szkole odbędzie się impreza.',
        jp: {
            text: '四月二十四日に学校でパーティーがあります。',
            pronunciation: 'しがつにじゅうよっかにがっこうでパーティーがあります。',
        },
    },
    {
        id: '93693df5-a8c6-4106-a355-66bfbb69a5a9',
        type: 'noun',
        en: 'Contest',
        pl: 'Konkurs',
        jp: { text: 'コンテスト' },
    },
    {
        id: 'f6cc7b42-649d-4d78-8bdc-9664c8ed2785',
        type: 'noun',
        en: 'Bonsai',
        pl: 'Bonsai',
        jp: { text: '盆栽', pronunciation: 'ぼんさい' },
    },
    {
        id: 'e603914a-7b40-4fba-b764-aae4e31b8fc8',
        type: 'noun',
        en: 'Drum',
        pl: 'Bęben',
        jp: { text: '太鼓', pronunciation: 'たいこ' },
    },
    {
        id: '5323c426-9a56-495d-9d80-c61e104c867e',
        type: 'noun',
        en: 'Traditional form of drama and music',
        pl: 'Tradycyjna forma dramatu i muzyki',
        jp: { text: '歌舞伎', pronunciation: 'かぶき' },
    },
    {
        id: '3e00503c-f98e-4d34-9c5e-4f91bd6c29ae',
        type: 'noun',
        en: 'Fireworks display',
        pl: 'Pokaz sztucznych ogni',
        jp: { text: '花火大会', pronunciation: 'はなびたいかい' },
    },
    {
        id: '7933adc9-776b-476c-a107-98fe947f67a8',
        type: 'noun',
        en: 'Ticket (for plane, concert, etc.)',
        pl: 'Bilet (na samolot, koncert, itp.)',
        jp: { text: 'チケット' },
    },
];

export const sakura4_7Bag: WordBag = {
    id: 'd2679d6a-fdc2-41f6-a912-389e73ee31e6',
    name: 'Sakura #4.7',
    category: 'sakura',
    words: sakura_4_7,
};
