import { numbers } from "./vocabulary/numbers.ts";
import { type WordBag } from "./types.ts";
import { colors } from "./vocabulary/colors.ts"
import { family } from "./vocabulary/family.ts";
import { duolingo_1 } from "./vocabulary/duolingo/duolingo_1.ts";
import { duolingo_2 } from "./vocabulary/duolingo/duolingo_2.ts";
import { duolingo_3 } from "./vocabulary/duolingo/duolingo_3.ts";
import { duolingo_4 } from "./vocabulary/duolingo/duolingo_4.ts";
import { duolingo_5 } from "./vocabulary/duolingo/duolingo_5.ts";
import { duolingo_6 } from "./vocabulary/duolingo/duolingo_6.ts";
import { countriesEurope } from "./vocabulary/countries/countriesEurope.ts";
import { genki_0 } from "./vocabulary/genki/genki_0.ts";
import { genki_1 } from "./vocabulary/genki/genki_1.ts";
import { sakura_1 } from "./vocabulary/sakura/sakura_1.ts";
import { sakura_2 } from "./vocabulary/sakura/sakura_2.ts";
import { sakura_3 } from "./vocabulary/sakura/sakura_3.ts";
import { sakura_4 } from "./vocabulary/sakura/sakura_4.ts";

export type { JapaneseWord, WordBag } from "./types.ts";

// UUIDs are generated by hand
export const availableWordBags: WordBag[] = [
    {
        "id": "83be35f1-ba1d-4a71-86df-1a52fc4b51ce",
        "name": "Family",
        "words": family,
    },
    {
        "id": "05253d28-8ebf-4793-bcb2-11b117a36f86",
        "name": "Numbers",
        "words": numbers,
    },
    {
        "id": "a6d25f35-b38e-4598-9c52-c27f8827f5d5",
        "name": "Colors",
        "words": colors,
    },
    {
        "id": "72d4f2a1-6963-497e-85a6-b6c2458da116",
        "name": "Duolingo #1",
        "words": duolingo_1,
    },
    {
        "id": "38e00aa9-dc82-4a80-ba40-eb14ddea1a86",
        "name": "Duolingo #2",
        "words": duolingo_2,
    },
    {
        "id": "1cb3b262-0fb8-4f4c-b222-352c3d082736",
        "name": "Duolingo #3",
        "words": duolingo_3,
    },
    {
        "id": "a8b187d2-4b51-4382-a13b-45bd5479cda5",
        "name": "Duolingo #4",
        "words": duolingo_4,
    },
    {
        "id": "89a8a523-b1f2-48c7-849d-d27f0bed07a0",
        "name": "Duolingo #5",
        "words": duolingo_5,
    },
    {
        "id": "7202e479-2fd1-4df3-9d73-47704f77919d",
        "name": "Duolingo #6",
        "words": duolingo_6,
    },
    {
        "id": "efcf6fe8-9b79-436f-8c4d-0987393fb4c6",
        "name": "Countries EU",
        "words": countriesEurope,
    },
    {
        "id": "56d838c8-4a95-4eb0-b903-14528a8dc6d6",
        "name": "Genki #0",
        "words": genki_0,
    },
    {
        "id": "9ce8f1cc-8504-4639-867c-59458ab6e39f",
        "name": "Genki #1",
        "words": genki_1,
    },
    {
        "id": "63ac3538-65e8-46a3-a248-a2a7560cc046",
        "name": "Sakura #1",
        "words": sakura_1,
    },
    {
        "id": "e4755c96-cd28-40d5-8962-a8d00d23967b",
        "name": "Sakura #2",
        "words": sakura_2,
    },
    {
        "id": "169b93bd-599a-4976-8ab2-d280e2af4f63",
        "name": "Sakura #3",
        "words": sakura_3,
    },
    {
        "id": "4c96ca61-8767-4120-8291-19241e14370f",
        "name": "Sakura #4",
        "words": sakura_4,
    }
]

export const findBagById = (id: string): WordBag | undefined => availableWordBags.find(bag => bag.id === id);
