import type { JapaneseWord } from '../../types.ts';

export const daysOfMonth: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'First day of the month',
        pl: 'Pierwszy dzień miesiąca',
        jp: { word: '一日', pronunciation: 'ついたち' },
    },
    {
        type: 'noun',
        en: 'Second day of the month',
        pl: 'Drugi dzień miesiąca',
        jp: { word: '二日', pronunciation: 'ふつか' },
    },
    {
        type: 'noun',
        en: 'Third day of the month',
        pl: 'Trzeci dzień miesiąca',
        jp: { word: '三日', pronunciation: 'みっか' },
    },
    {
        type: 'noun',
        en: 'Fourth day of the month',
        pl: 'Czwarty dzień miesiąca',
        jp: { word: '四日', pronunciation: 'よっか' },
    },
    {
        type: 'noun',
        en: 'Fifth day of the month',
        pl: 'Piąty dzień miesiąca',
        jp: { word: '五日', pronunciation: 'いつか' },
    },
    {
        type: 'noun',
        en: 'Sixth day of the month',
        pl: 'Szósty dzień miesiąca',
        jp: { word: '六日', pronunciation: 'むいか' },
    },
    {
        type: 'noun',
        en: 'Seventh day of the month',
        pl: 'Siódmy dzień miesiąca',
        jp: { word: '七日', pronunciation: 'なのか' },
    },
    {
        type: 'noun',
        en: 'Eighth day of the month',
        pl: 'Ósmy dzień miesiąca',
        jp: { word: '八日', pronunciation: 'ようか' },
    },
    {
        type: 'noun',
        en: 'Ninth day of the month',
        pl: 'Dziewiąty dzień miesiąca',
        jp: { word: '九日', pronunciation: 'ここのか' },
    },
    {
        type: 'noun',
        en: 'Tenth day of the month',
        pl: 'Dziesiąty dzień miesiąca',
        jp: { word: '十日', pronunciation: 'とおか' },
    },
    {
        type: 'noun',
        en: 'Eleventh day of the month',
        pl: 'Jedenasty dzień miesiąca',
        jp: { word: '十一日', pronunciation: 'じゅういちにち' },
    },
    {
        type: 'noun',
        en: 'Twelfth day of the month',
        pl: 'Dwunasty dzień miesiąca',
        jp: { word: '十二日', pronunciation: 'じゅうににち' },
    },
    {
        type: 'noun',
        en: 'Thirteenth day of the month',
        pl: 'Trzynasty dzień miesiąca',
        jp: { word: '十三日', pronunciation: 'じゅうさんにち' },
    },
    {
        type: 'noun',
        en: 'Fourteenth day of the month',
        pl: 'Czternasty dzień miesiąca',
        jp: { word: '十四日', pronunciation: 'じゅうよっか' },
    },
    {
        type: 'noun',
        en: 'Fifteenth day of the month',
        pl: 'Piętnasty dzień miesiąca',
        jp: { word: '十五日', pronunciation: 'じゅうごにち' },
    },
    {
        type: 'noun',
        en: 'Sixteenth day of the month',
        pl: 'Szesnasty dzień miesiąca',
        jp: { word: '十六日', pronunciation: 'じゅうろくにち' },
    },
    {
        type: 'noun',
        en: 'Seventeenth day of the month',
        pl: 'Siedemnasty dzień miesiąca',
        jp: { word: '十七日', pronunciation: 'じゅうしちにち' },
    },
    {
        type: 'noun',
        en: 'Eighteenth day of the month',
        pl: 'Osiemnasty dzień miesiąca',
        jp: { word: '十八日', pronunciation: 'じゅうはちにち' },
    },
    {
        type: 'noun',
        en: 'Nineteenth day of the month',
        pl: 'Dziewiętnasty dzień miesiąca',
        jp: { word: '十九日', pronunciation: 'じゅうくにち' },
    },
    {
        type: 'noun',
        en: 'Twentieth day of the month',
        pl: 'Dwudziesty dzień miesiąca',
        jp: { word: '二十日', pronunciation: 'はつか' },
    },
    {
        type: 'noun',
        en: 'Twenty-first day of the month',
        pl: 'Dwudziesty pierwszy dzień miesiąca',
        jp: { word: '二十一日', pronunciation: 'にじゅういちにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-second day of the month',
        pl: 'Dwudziesty drugi dzień miesiąca',
        jp: { word: '二十二日', pronunciation: 'にじゅうににち' },
    },
    {
        type: 'noun',
        en: 'Twenty-third day of the month',
        pl: 'Dwudziesty trzeci dzień miesiąca',
        jp: { word: '二十三日', pronunciation: 'にじゅうさんにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-fourth day of the month',
        pl: 'Dwudziesty czwarty dzień miesiąca',
        jp: { word: '二十四日', pronunciation: 'にじゅうよっか' },
    },
    {
        type: 'noun',
        en: 'Twenty-fifth day of the month',
        pl: 'Dwudziesty piąty dzień miesiąca',
        jp: { word: '二十五日', pronunciation: 'にじゅうごにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-sixth day of the month',
        pl: 'Dwudziesty szósty dzień miesiąca',
        jp: { word: '二十六日', pronunciation: 'にじゅうろくにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-seventh day of the month',
        pl: 'Dwudziesty siódmy dzień miesiąca',
        jp: { word: '二十七日', pronunciation: 'にじゅうしちにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-eighth day of the month',
        pl: 'Dwudziesty ósmy dzień miesiąca',
        jp: { word: '二十八日', pronunciation: 'にじゅうはちにち' },
    },
    {
        type: 'noun',
        en: 'Twenty-ninth day of the month',
        pl: 'Dwudziesty dziewiąty dzień miesiąca',
        jp: { word: '二十九日', pronunciation: 'にじゅうくにち' },
    },
    {
        type: 'noun',
        en: 'Thirtieth day of the month',
        pl: 'Trzydziesty dzień miesiąca',
        jp: { word: '三十日', pronunciation: 'さんじゅうにち' },
    },
    {
        type: 'noun',
        en: 'Thirty-first day of the month',
        pl: 'Trzydziesty pierwszy dzień miesiąca',
        jp: { word: '三十一日', pronunciation: 'さんじゅういちにち' },
    },
];
