import type { JapaneseWord } from '../../types.ts';

export const daysOfMonth: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'First day of the month',
        pl: 'Pierwszy dzień miesiąca',
        jp: '一日',
        jp_pronunciation: 'ついたち',
    },
    {
        type: 'noun',
        en: 'Second day of the month',
        pl: 'Drugi dzień miesiąca',
        jp: '二日',
        jp_pronunciation: 'ふつか',
    },
    {
        type: 'noun',
        en: 'Third day of the month',
        pl: 'Trzeci dzień miesiąca',
        jp: '三日',
        jp_pronunciation: 'みっか',
    },
    {
        type: 'noun',
        en: 'Fourth day of the month',
        pl: 'Czwarty dzień miesiąca',
        jp: '四日',
        jp_pronunciation: 'よっか',
    },
    {
        type: 'noun',
        en: 'Fifth day of the month',
        pl: 'Piąty dzień miesiąca',
        jp: '五日',
        jp_pronunciation: 'いつか',
    },
    {
        type: 'noun',
        en: 'Sixth day of the month',
        pl: 'Szósty dzień miesiąca',
        jp: '六日',
        jp_pronunciation: 'むいか',
    },
    {
        type: 'noun',
        en: 'Seventh day of the month',
        pl: 'Siódmy dzień miesiąca',
        jp: '七日',
        jp_pronunciation: 'なのか',
    },
    {
        type: 'noun',
        en: 'Eighth day of the month',
        pl: 'Ósmy dzień miesiąca',
        jp: '八日',
        jp_pronunciation: 'ようか',
    },
    {
        type: 'noun',
        en: 'Ninth day of the month',
        pl: 'Dziewiąty dzień miesiąca',
        jp: '九日',
        jp_pronunciation: 'ここのか',
    },
    {
        type: 'noun',
        en: 'Tenth day of the month',
        pl: 'Dziesiąty dzień miesiąca',
        jp: '十日',
        jp_pronunciation: 'とおか',
    },
    {
        type: 'noun',
        en: 'Eleventh day of the month',
        pl: 'Jedenasty dzień miesiąca',
        jp: '十一日',
        jp_pronunciation: 'じゅういちにち',
    },
    {
        type: 'noun',
        en: 'Twelfth day of the month',
        pl: 'Dwunasty dzień miesiąca',
        jp: '十二日',
        jp_pronunciation: 'じゅうににち',
    },
    {
        type: 'noun',
        en: 'Thirteenth day of the month',
        pl: 'Trzynasty dzień miesiąca',
        jp: '十三日',
        jp_pronunciation: 'じゅうさんにち',
    },
    {
        type: 'noun',
        en: 'Fourteenth day of the month',
        pl: 'Czternasty dzień miesiąca',
        jp: '十四日',
        jp_pronunciation: 'じゅうよっか',
    },
    {
        type: 'noun',
        en: 'Fifteenth day of the month',
        pl: 'Piętnasty dzień miesiąca',
        jp: '十五日',
        jp_pronunciation: 'じゅうごにち',
    },
    {
        type: 'noun',
        en: 'Sixteenth day of the month',
        pl: 'Szesnasty dzień miesiąca',
        jp: '十六日',
        jp_pronunciation: 'じゅうろくにち',
    },
    {
        type: 'noun',
        en: 'Seventeenth day of the month',
        pl: 'Siedemnasty dzień miesiąca',
        jp: '十七日',
        jp_pronunciation: 'じゅうしちにち',
    },
    {
        type: 'noun',
        en: 'Eighteenth day of the month',
        pl: 'Osiemnasty dzień miesiąca',
        jp: '十八日',
        jp_pronunciation: 'じゅうはちにち',
    },
    {
        type: 'noun',
        en: 'Nineteenth day of the month',
        pl: 'Dziewiętnasty dzień miesiąca',
        jp: '十九日',
        jp_pronunciation: 'じゅうくにち',
    },
    {
        type: 'noun',
        en: 'Twentieth day of the month',
        pl: 'Dwudziesty dzień miesiąca',
        jp: '二十日',
        jp_pronunciation: 'はつか',
    },
    {
        type: 'noun',
        en: 'Twenty-first day of the month',
        pl: 'Dwudziesty pierwszy dzień miesiąca',
        jp: '二十一日',
        jp_pronunciation: 'にじゅういちにち',
    },
    {
        type: 'noun',
        en: 'Twenty-second day of the month',
        pl: 'Dwudziesty drugi dzień miesiąca',
        jp: '二十二日',
        jp_pronunciation: 'にじゅうににち',
    },
    {
        type: 'noun',
        en: 'Twenty-third day of the month',
        pl: 'Dwudziesty trzeci dzień miesiąca',
        jp: '二十三日',
        jp_pronunciation: 'にじゅうさんにち',
    },
    {
        type: 'noun',
        en: 'Twenty-fourth day of the month',
        pl: 'Dwudziesty czwarty dzień miesiąca',
        jp: '二十四日',
        jp_pronunciation: 'にじゅうよっか',
    },
    {
        type: 'noun',
        en: 'Twenty-fifth day of the month',
        pl: 'Dwudziesty piąty dzień miesiąca',
        jp: '二十五日',
        jp_pronunciation: 'にじゅうごにち',
    },
    {
        type: 'noun',
        en: 'Twenty-sixth day of the month',
        pl: 'Dwudziesty szósty dzień miesiąca',
        jp: '二十六日',
        jp_pronunciation: 'にじゅうろくにち',
    },
    {
        type: 'noun',
        en: 'Twenty-seventh day of the month',
        pl: 'Dwudziesty siódmy dzień miesiąca',
        jp: '二十七日',
        jp_pronunciation: 'にじゅうしちにち',
    },
    {
        type: 'noun',
        en: 'Twenty-eighth day of the month',
        pl: 'Dwudziesty ósmy dzień miesiąca',
        jp: '二十八日',
        jp_pronunciation: 'にじゅうはちにち',
    },
    {
        type: 'noun',
        en: 'Twenty-ninth day of the month',
        pl: 'Dwudziesty dziewiąty dzień miesiąca',
        jp: '二十九日',
        jp_pronunciation: 'にじゅうくにち',
    },
    {
        type: 'noun',
        en: 'Thirtieth day of the month',
        pl: 'Trzydziesty dzień miesiąca',
        jp: '三十日',
        jp_pronunciation: 'さんじゅうにち',
    },
    {
        type: 'noun',
        en: 'Thirty-first day of the month',
        pl: 'Trzydziesty pierwszy dzień miesiąca',
        jp: '三十一日',
        jp_pronunciation: 'さんじゅういちにち',
    },
];
