import type { TranslatedJapaneseText, WordBag } from '../../types';

const daysOfMonth: TranslatedJapaneseText[] = [
    {
        id: '4108563d-bde6-4d47-871f-057374c32621',
        type: 'noun',
        en: 'First day of the month',
        pl: 'Pierwszy dzień miesiąca',
        jp: { text: '一日', pronunciation: 'ついたち' },
    },
    {
        id: '65bece33-c4a2-4932-bc80-6202b106de90',
        type: 'noun',
        en: 'Second day of the month',
        pl: 'Drugi dzień miesiąca',
        jp: { text: '二日', pronunciation: 'ふつか' },
    },
    {
        id: '97fea4d3-a3f7-4afe-85a4-9914f3d29f3e',
        type: 'noun',
        en: 'Third day of the month',
        pl: 'Trzeci dzień miesiąca',
        jp: { text: '三日', pronunciation: 'みっか' },
    },
    {
        id: '153fb0be-75a3-489e-81a6-d2160ec96dce',
        type: 'noun',
        en: 'Fourth day of the month',
        pl: 'Czwarty dzień miesiąca',
        jp: { text: '四日', pronunciation: 'よっか' },
    },
    {
        id: '5b59b887-b025-4a9f-b1bd-a73b6ae180ce',
        type: 'noun',
        en: 'Fifth day of the month',
        pl: 'Piąty dzień miesiąca',
        jp: { text: '五日', pronunciation: 'いつか' },
    },
    {
        id: '234c1573-efb8-470a-be3d-f409be65b24d',
        type: 'noun',
        en: 'Sixth day of the month',
        pl: 'Szósty dzień miesiąca',
        jp: { text: '六日', pronunciation: 'むいか' },
    },
    {
        id: '83db8319-8db9-4d8d-b7ed-74a94a0fc884',
        type: 'noun',
        en: 'Seventh day of the month',
        pl: 'Siódmy dzień miesiąca',
        jp: { text: '七日', pronunciation: 'なのか' },
    },
    {
        id: 'bf6b96f1-b671-44bb-bfc0-51b9b6d05580',
        type: 'noun',
        en: 'Eighth day of the month',
        pl: 'Ósmy dzień miesiąca',
        jp: { text: '八日', pronunciation: 'ようか' },
    },
    {
        id: 'fe52927f-25d7-426b-a646-f3406f198b60',
        type: 'noun',
        en: 'Ninth day of the month',
        pl: 'Dziewiąty dzień miesiąca',
        jp: { text: '九日', pronunciation: 'ここのか' },
    },
    {
        id: '4a8ace82-32fc-42b2-8d30-5f80b0c12c99',
        type: 'noun',
        en: 'Tenth day of the month',
        pl: 'Dziesiąty dzień miesiąca',
        jp: { text: '十日', pronunciation: 'とおか' },
    },
    {
        id: '89b15e67-66c0-40a7-aacb-0f8ed46d7369',
        type: 'noun',
        en: 'Eleventh day of the month',
        pl: 'Jedenasty dzień miesiąca',
        jp: { text: '十一日', pronunciation: 'じゅういちにち' },
    },
    {
        id: '58f2de41-627c-44d7-acd0-2dc400272726',
        type: 'noun',
        en: 'Twelfth day of the month',
        pl: 'Dwunasty dzień miesiąca',
        jp: { text: '十二日', pronunciation: 'じゅうににち' },
    },
    {
        id: '94038376-bc28-4ac9-b5c2-afe7e5e71ffc',
        type: 'noun',
        en: 'Thirteenth day of the month',
        pl: 'Trzynasty dzień miesiąca',
        jp: { text: '十三日', pronunciation: 'じゅうさんにち' },
    },
    {
        id: 'be5048de-017f-48e1-ade8-bd6e186158ef',
        type: 'noun',
        en: 'Fourteenth day of the month',
        pl: 'Czternasty dzień miesiąca',
        jp: { text: '十四日', pronunciation: 'じゅうよっか' },
    },
    {
        id: '231d0bef-d2d1-4b24-8218-c210dabab075',
        type: 'noun',
        en: 'Fifteenth day of the month',
        pl: 'Piętnasty dzień miesiąca',
        jp: { text: '十五日', pronunciation: 'じゅうごにち' },
    },
    {
        id: 'cec4d5ae-ec09-45f7-873b-fc03b9033bc0',
        type: 'noun',
        en: 'Sixteenth day of the month',
        pl: 'Szesnasty dzień miesiąca',
        jp: { text: '十六日', pronunciation: 'じゅうろくにち' },
    },
    {
        id: '845f996f-1556-4112-ac95-a64243947e5c',
        type: 'noun',
        en: 'Seventeenth day of the month',
        pl: 'Siedemnasty dzień miesiąca',
        jp: { text: '十七日', pronunciation: 'じゅうしちにち' },
    },
    {
        id: '2d2b7018-0502-411b-923e-4a2978f40143',
        type: 'noun',
        en: 'Eighteenth day of the month',
        pl: 'Osiemnasty dzień miesiąca',
        jp: { text: '十八日', pronunciation: 'じゅうはちにち' },
    },
    {
        id: 'a4ad045a-4b1a-40e3-b7af-0689e17cfed9',
        type: 'noun',
        en: 'Nineteenth day of the month',
        pl: 'Dziewiętnasty dzień miesiąca',
        jp: { text: '十九日', pronunciation: 'じゅうくにち' },
    },
    {
        id: '7992c426-11d1-4d96-a8f1-34a733be36cf',
        type: 'noun',
        en: 'Twentieth day of the month',
        pl: 'Dwudziesty dzień miesiąca',
        jp: { text: '二十日', pronunciation: 'はつか' },
    },
    {
        id: '957f3a47-a0ba-4aaa-aa6c-d54510bf6970',
        type: 'noun',
        en: 'Twenty-first day of the month',
        pl: 'Dwudziesty pierwszy dzień miesiąca',
        jp: { text: '二十一日', pronunciation: 'にじゅういちにち' },
    },
    {
        id: '958d25b5-e2ec-461c-a099-2e00dd4ac48a',
        type: 'noun',
        en: 'Twenty-second day of the month',
        pl: 'Dwudziesty drugi dzień miesiąca',
        jp: { text: '二十二日', pronunciation: 'にじゅうににち' },
    },
    {
        id: '54bfdaa7-994f-450b-9559-05308d31b5b0',
        type: 'noun',
        en: 'Twenty-third day of the month',
        pl: 'Dwudziesty trzeci dzień miesiąca',
        jp: { text: '二十三日', pronunciation: 'にじゅうさんにち' },
    },
    {
        id: '9f6a356b-370b-465a-bb4d-2b5f4d42ce0f',
        type: 'noun',
        en: 'Twenty-fourth day of the month',
        pl: 'Dwudziesty czwarty dzień miesiąca',
        jp: { text: '二十四日', pronunciation: 'にじゅうよっか' },
    },
    {
        id: 'a6c464e5-3513-4d90-b5a4-62397dcf29ad',
        type: 'noun',
        en: 'Twenty-fifth day of the month',
        pl: 'Dwudziesty piąty dzień miesiąca',
        jp: { text: '二十五日', pronunciation: 'にじゅうごにち' },
    },
    {
        id: 'ffc68097-94b1-427f-93ba-d42317228c4c',
        type: 'noun',
        en: 'Twenty-sixth day of the month',
        pl: 'Dwudziesty szósty dzień miesiąca',
        jp: { text: '二十六日', pronunciation: 'にじゅうろくにち' },
    },
    {
        id: 'c1d9d29a-4367-477b-b072-d6a236d4ea67',
        type: 'noun',
        en: 'Twenty-seventh day of the month',
        pl: 'Dwudziesty siódmy dzień miesiąca',
        jp: { text: '二十七日', pronunciation: 'にじゅうしちにち' },
    },
    {
        id: 'e911e04e-e071-4a10-9577-a0192e68a00a',
        type: 'noun',
        en: 'Twenty-eighth day of the month',
        pl: 'Dwudziesty ósmy dzień miesiąca',
        jp: { text: '二十八日', pronunciation: 'にじゅうはちにち' },
    },
    {
        id: 'dff5480f-d960-418d-9458-6b183fcce341',
        type: 'noun',
        en: 'Twenty-ninth day of the month',
        pl: 'Dwudziesty dziewiąty dzień miesiąca',
        jp: { text: '二十九日', pronunciation: 'にじゅうくにち' },
    },
    {
        id: '7b2e816a-f9cc-479f-a6b0-368036a3700a',
        type: 'noun',
        en: 'Thirtieth day of the month',
        pl: 'Trzydziesty dzień miesiąca',
        jp: { text: '三十日', pronunciation: 'さんじゅうにち' },
    },
    {
        id: 'daebfdd0-9eca-44e7-b66a-8b2b965ad5b1',
        type: 'noun',
        en: 'Thirty-first day of the month',
        pl: 'Trzydziesty pierwszy dzień miesiąca',
        jp: { text: '三十一日', pronunciation: 'さんじゅういちにち' },
    },
];

export const daysOfMonthBag: WordBag = {
    id: '61da60a2-4e5f-4dd2-b419-0c9557593e9c',
    name: 'Days of Month',
    category: 'time',
    words: daysOfMonth,
};
