import type { JapaneseWord } from '../../types';

export const minutes: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'One minute',
        pl: 'Jedna minuta',
        jp: '一分',
        jp_pronunciation: 'いっぷん',
    },
    {
        type: 'noun',
        en: 'Two minutes',
        pl: 'Dwie minuty',
        jp: '二分',
        jp_pronunciation: 'にふん',
    },
    {
        type: 'noun',
        en: 'Three minutes',
        pl: 'Trzy minuty',
        jp: '三分',
        jp_pronunciation: 'さんぷん',
    },
    {
        type: 'noun',
        en: 'Four minutes',
        pl: 'Cztery minuty',
        jp: '四分',
        jp_pronunciation: 'よんぷん',
    },
    {
        type: 'noun',
        en: 'Five minutes',
        pl: 'Pięć minut',
        jp: '五分',
        jp_pronunciation: 'ごふん',
    },
    {
        type: 'noun',
        en: 'Six minutes',
        pl: 'Sześć minut',
        jp: '六分',
        jp_pronunciation: 'ろっぷん',
    },
    {
        type: 'noun',
        en: 'Seven minutes',
        pl: 'Siedem minut',
        jp: '七分',
        jp_pronunciation: 'ななふん',
    },
    {
        type: 'noun',
        en: 'Eight minutes',
        pl: 'Osiem minut',
        jp: '八分',
        jp_pronunciation: 'はっぷん',
    },
    {
        type: 'noun',
        en: 'Nine minutes',
        pl: 'Dziewięć minut',
        jp: '九分',
        jp_pronunciation: 'きゅうふん',
    },
    {
        type: 'noun',
        en: 'Ten minutes',
        pl: 'Dziesięć minut',
        jp: '十分',
        jp_pronunciation: 'じゅっぷん',
    },
    {
        type: 'noun',
        en: 'Eleven minutes',
        pl: 'Jedenaście minut',
        jp: '十一分',
        jp_pronunciation: 'じゅういっぷん',
    },
    {
        type: 'noun',
        en: 'Twelve minutes',
        pl: 'Dwanaście minut',
        jp: '十二分',
        jp_pronunciation: 'じゅうにふん',
    },
    {
        type: 'noun',
        en: 'Thirteen minutes',
        pl: 'Trzynaście minut',
        jp: '十三分',
        jp_pronunciation: 'じゅうさんぷん',
    },
    {
        type: 'noun',
        en: 'Half past',
        pl: '30 minut po',
        jp: '半',
        jp_pronunciation: 'はん',
    },
    {
        type: 'noun',
        en: 'Minute',
        pl: 'Minuta',
        jp: '分',
        jp_pronunciation: 'ふん',
    },
];
