import type { TranslatedJapaneseText, WordBag } from '../../types';

const numberOfDays: TranslatedJapaneseText[] = [
    {
        id: '4ddabdae-e808-4bac-81d9-e5f9fa6ccc4d',
        type: 'noun',
        en: 'One day',
        pl: 'Jeden dzień',
        jp: { text: '一日', pronunciation: 'いちにち' },
    },
    {
        id: '3d18e153-80b4-4710-aa52-38d23072af3d',
        type: 'noun',
        en: 'Two days',
        pl: 'Dwa dni',
        jp: { text: '二日', pronunciation: 'ふつか' },
    },
    {
        id: '3ce74569-125d-48ef-959a-5ca5037b2c36',
        type: 'noun',
        en: 'Three days',
        pl: 'Trzy dni',
        jp: { text: '三日', pronunciation: 'みっか' },
    },
    {
        id: '4d8743a7-fc93-4132-a2d0-39f831af5fff',
        type: 'noun',
        en: 'Four days',
        pl: 'Cztery dni',
        jp: { text: '四日', pronunciation: 'よっか' },
    },
    {
        id: 'aa6ec8e9-1a98-4bab-a0b6-7a33e136c79d',
        type: 'noun',
        en: 'Five days',
        pl: 'Pięć dni',
        jp: { text: '五日', pronunciation: 'いつか' },
    },
    {
        id: '95d5b27e-535c-48c2-9faa-2c3e41933722',
        type: 'noun',
        en: 'Six days',
        pl: 'Sześć dni',
        jp: { text: '六日', pronunciation: 'むいか' },
    },
    {
        id: 'd30c563c-ba28-4db4-b7b3-432a58b6299b',
        type: 'noun',
        en: 'Seven days',
        pl: 'Siedem dni',
        jp: { text: '七日', pronunciation: 'なのか' },
    },
    {
        id: 'faf5223e-6986-4777-a61c-a7114c287afd',
        type: 'noun',
        en: 'Eight days',
        pl: 'Osiem dni',
        jp: { text: '八日', pronunciation: 'ようか' },
    },
    {
        id: '6f04b3e5-9a97-428d-a966-19b8453e6b53',
        type: 'noun',
        en: 'Nine days',
        pl: 'Dziewięć dni',
        jp: { text: '九日', pronunciation: 'ここのか' },
    },
    {
        id: 'c4702bd0-44b5-46e8-af5e-245fafe66a7b',
        type: 'noun',
        en: 'Ten days',
        pl: 'Dziesięć dni',
        jp: { text: '十日', pronunciation: 'とおか' },
    },
    {
        id: '344bb4e8-fb0e-4eab-ade7-6268ff3ee7b2',
        type: 'noun',
        en: 'Eleven days',
        pl: 'Jedenaście dni',
        jp: { text: '十一日', pronunciation: 'じゅういちにち' },
    },
    {
        id: 'ad6f2626-f2f2-4b77-8fde-4d5216be54bd',
        type: 'noun',
        en: 'Twelve days',
        pl: 'Dwanaście dni',
        jp: { text: '十二日', pronunciation: 'じゅうににち' },
    },
    {
        id: '9513fc7e-ca35-4d22-8ebe-a10b84af39b5',
        type: 'noun',
        en: 'Thirteen days',
        pl: 'Trzynaście dni',
        jp: { text: '十三日', pronunciation: 'じゅうさんにち' },
    },
    {
        id: '963a6148-4d57-45d9-a21f-8676d64d355a',
        type: 'noun',
        en: 'Fourteen days',
        pl: 'Czternaście dni',
        jp: { text: '十四日', pronunciation: 'じゅうよっか' },
    },
    {
        id: 'cf252eb3-b42c-4efc-bc2c-e8ee9738afb3',
        type: 'noun',
        en: 'Fifteen days',
        pl: 'Piętnaście dni',
        jp: { text: '十五日', pronunciation: 'じゅうごにち' },
    },
    {
        id: '44d3188d-3e60-40a1-8d02-0992932b6820',
        type: 'noun',
        en: 'Sixteen days',
        pl: 'Szesnaście dni',
        jp: { text: '十六日', pronunciation: 'じゅうろくにち' },
    },
    {
        id: '53726ba2-6d3d-4f37-816e-3aa6a9b8323d',
        type: 'noun',
        en: 'Seventeen days',
        pl: 'Siedemnaście dni',
        jp: { text: '十七日', pronunciation: 'じゅうしちにち' },
    },
    {
        id: 'ae97c43d-9dbb-472f-9df0-0ee5342e1e84',
        type: 'noun',
        en: 'Eighteen days',
        pl: 'Osiemnaście dni',
        jp: { text: '十八日', pronunciation: 'じゅうはちにち' },
    },
    {
        id: '6414729e-4ce2-4eab-8777-6eb146ded985',
        type: 'noun',
        en: 'Nineteen days',
        pl: 'Dziewiętnaście dni',
        jp: { text: '十九日', pronunciation: 'じゅうくにち' },
    },
    {
        id: '2925a4ed-1862-4c19-8aa6-40cd4593c68d',
        type: 'noun',
        en: 'Twenty days',
        pl: 'Dwadzieścia dni',
        jp: { text: '二十日', pronunciation: 'はつか' },
    },
    {
        id: 'f31ae1c8-f88c-44b0-ab9b-eb167976d5bf',
        type: 'noun',
        en: 'Forty-nine days',
        pl: 'Czterdzieści dziewięć dni',
        jp: { text: '四十九日', pronunciation: ['しじゅうくにち', 'よんじゅうくにち'] },
        description:
            'The first pronunciation is used when used in context "the forty-ninth day after someone\'s death". The second pronunciation is used in other contexts.',
    },
    {
        id: '80a75ac7-c5f7-42da-b9f9-bc2916ec52e4',
        type: 'noun',
        en: 'One hundred days',
        pl: 'Sto dni',
        jp: { text: '百日', pronunciation: 'ひゃくにち' },
    },
    {
        id: 'f4826883-3250-4e74-af0c-82be89250876',
        type: 'noun',
        en: 'One thousand days',
        pl: 'Tysiąc dni',
        jp: { text: '千日', pronunciation: 'せんにち' },
    },
    {
        id: '349ac85b-fa95-449f-aa26-8231ff0a8e5d',
        type: 'noun',
        en: 'Ten thousand days',
        pl: 'Dziesięć tysięcy dni',
        jp: { text: '一万日', pronunciation: 'いちまんにち' },
    },
    {
        id: 'dbac5ecb-dc27-421e-a3a0-68b26b9448de',
        type: 'noun',
        en: 'How many days',
        pl: 'Ile dni',
        jp: { text: '何日', pronunciation: 'なんにち' },
    },
];

export const numberOfDaysBag: WordBag = {
    id: 'c66a78ea-9449-43f7-8efb-9c4a1023e83f',
    name: 'Number of Days',
    category: 'time',
    words: numberOfDays,
};
