import type { TranslatedJapaneseText, WordBag } from '../../types';

const numberOfMonths: TranslatedJapaneseText[] = [
    {
        id: '49e5620e-08af-415f-a954-bda96e997622',
        type: 'noun',
        en: 'One month',
        pl: 'Jeden miesiąc',
        jp: { text: '一ヶ月', pronunciation: 'いっかげつ' },
    },
    {
        id: 'a4f5e605-a6ba-429a-83f5-6f3798d96f3f',
        type: 'noun',
        en: 'Two months',
        pl: 'Dwa miesiące',
        jp: { text: '二ヶ月', pronunciation: 'にかげつ' },
    },
    {
        id: '5b51c3a3-dc1a-4aaa-baf6-3d9ed3d33516',
        type: 'noun',
        en: 'Three months',
        pl: 'Trzy miesiące',
        jp: { text: '三ヶ月', pronunciation: 'さんかげつ' },
    },
    {
        id: 'f4b2ab98-79fd-4897-937d-ece84cea35b4',
        type: 'noun',
        en: 'Four months',
        pl: 'Cztery miesiące',
        jp: { text: '四ヶ月', pronunciation: 'よんかげつ' },
    },
    {
        id: '99c9df40-6d14-487f-bf37-b9f1cc0d2158',
        type: 'noun',
        en: 'Five months',
        pl: 'Pięć miesięcy',
        jp: { text: '五ヶ月', pronunciation: 'ごかげつ' },
    },
    {
        id: '3005ffe6-1007-412c-b0da-d56cc29fd1e0',
        type: 'noun',
        en: 'Six months',
        pl: 'Sześć miesięcy',
        jp: { text: '六ヶ月', pronunciation: 'ろっかげつ' },
    },
    {
        id: 'dd6f5ac4-9371-4763-b89e-0c9473a36924',
        type: 'noun',
        en: 'Seven months',
        pl: 'Siedem miesięcy',
        jp: { text: '七ヶ月', pronunciation: 'ななかげつ' },
    },
    {
        id: 'dee6b3ce-e6d2-4fe8-99a1-bb57ef5e683a',
        type: 'noun',
        en: 'Eight months',
        pl: 'Osiem miesięcy',
        jp: { text: '八ヶ月', pronunciation: ['はっかげつ', 'はちかげつ'] },
    },
    {
        id: 'ae81ae88-60bc-467f-984c-2cdf79f51fcf',
        type: 'noun',
        en: 'Nine months',
        pl: 'Dziewięć miesięcy',
        jp: { text: '九ヶ月', pronunciation: 'きゅうかげつ' },
    },
    {
        id: '6d235a40-5d49-49df-8c2f-66ad6e0b9981',
        type: 'noun',
        en: 'Ten months',
        pl: 'Dziesięć miesięcy',
        jp: { text: '十ヶ月', pronunciation: ['じゅっかげつ', 'じっかげつ'] },
    },
    {
        id: '836656a8-b8c6-4fa0-8141-5ed429bd99bd',
        type: 'noun',
        en: 'Eleven months',
        pl: 'Jedenaście miesięcy',
        jp: { text: '十一ヶ月', pronunciation: 'じゅういっかげつ' },
    },
    {
        id: '71e202c6-f6f9-4480-8353-28ba9b78fa06',
        type: 'noun',
        en: 'Twelve months',
        pl: 'Dwanaście miesięcy',
        jp: { text: '十二ヶ月', pronunciation: 'じゅうにかげつ' },
    },
    {
        id: '1938eb49-7e7c-451a-a93b-a3a4af0e3445',
        type: 'noun',
        en: 'Thirteen months',
        pl: 'Trzynaście miesięcy',
        jp: { text: '十三ヶ月', pronunciation: 'じゅうさんかげつ' },
    },
    {
        id: '2cbe78b2-51ce-4531-8f0f-b1a4b7c0ede2',
        type: 'noun',
        en: 'Fourteen months',
        pl: 'Czternaście miesięcy',
        jp: { text: '十四ヶ月', pronunciation: 'じゅうよんかげつ' },
    },
    {
        id: 'bb5ae520-861b-4508-a65c-027db7bea370',
        type: 'noun',
        en: 'Fifteen months',
        pl: 'Piętnaście miesięcy',
        jp: { text: '十五ヶ月', pronunciation: 'じゅうごかげつ' },
    },
    {
        id: 'b1e51e57-b6c3-4f8f-879f-a94bc7e95d0a',
        type: 'noun',
        en: 'Sixteen months',
        pl: 'Szesnaście miesięcy',
        jp: { text: '十六ヶ月', pronunciation: 'じゅうろっかげつ' },
    },
    {
        id: '31c63ee7-c2c8-4f9c-8f34-ce4a00966a63',
        type: 'noun',
        en: 'Seventeen months',
        pl: 'Siedemnaście miesięcy',
        jp: { text: '十七ヶ月', pronunciation: 'じゅうななかげつ' },
    },
    {
        id: 'b85030da-0207-4430-8e16-7c9c9e149b45',
        type: 'noun',
        en: 'Eighteen months',
        pl: 'Osiemnaście miesięcy',
        jp: { text: '十八ヶ月', pronunciation: ['じゅうはちかげつ', 'じゅうはっかげつ'] },
    },
    {
        id: '0733c956-ee1e-4cf5-9db2-3be0353239d4',
        type: 'noun',
        en: 'Nineteen months',
        pl: 'Dziewiętnaście miesięcy',
        jp: { text: '十九ヶ月', pronunciation: 'じゅうきゅうかげつ' },
    },
    {
        id: '55e326c4-83d7-4556-8aa0-54fbddc1b38d',
        type: 'noun',
        en: 'Twenty months',
        pl: 'Dwadzieścia miesięcy',
        jp: { text: '二十ヶ月', pronunciation: ['にじゅっかげつ', 'にじっかげつ'] },
    },
];

export const numberOfMonthsBag: WordBag = {
    id: 'be1c8f91-853a-46d8-9fa0-fc45f7902cb9',
    name: 'Number of Months',
    category: 'time',
    words: numberOfMonths,
};
