import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_2_11: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Bus',
        pl: 'Autobus',
        jp: { text: 'バス' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Beautiful (not "clean")',
        pl: 'Piękny (nie "czysty")',
        jp: { text: '美しい', pronunciation: 'うつくしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tasty',
        pl: 'Smaczny',
        jp: { text: '美味しい', pronunciation: 'おいしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Bad-tasting',
        pl: 'Niesmaczny',
        jp: { text: '不味い', pronunciation: 'まずい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Expensive',
        pl: 'Drogi',
        jp: { text: '高い', pronunciation: 'たかい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cheap',
        pl: 'Tani',
        jp: { text: '安い', pronunciation: 'やすい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fast',
        pl: 'Szybki',
        jp: { text: '速い', pronunciation: 'はやい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Slow',
        pl: 'Powolny',
        jp: { text: '遅い', pronunciation: 'おそい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Big',
        pl: 'Duży',
        jp: { text: '大きい', pronunciation: 'おおきい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Small',
        pl: 'Mały',
        jp: { text: '小さい', pronunciation: 'ちいさい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Hot (weather / perceived)',
        pl: 'Gorący (pogoda / odczuwalna temperatura)',
        jp: { text: '暑い', pronunciation: 'あつい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cold (weather / perceived)',
        pl: 'Zimny (pogoda / odczuwalna temperatura)',
        jp: { text: '寒い', pronunciation: 'さむい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Hot (thing)',
        pl: 'Gorący (rzecz)',
        jp: { text: '熱い', pronunciation: 'あつい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cold (thing)',
        pl: 'Zimny (rzecz)',
        jp: { text: '冷たい', pronunciation: 'つめたい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tall',
        pl: 'Wysoki',
        jp: { text: '高い', pronunciation: 'たかい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short (height)',
        pl: 'Niski',
        jp: { text: '低い', pronunciation: 'ひくい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Tall (person)',
        pl: 'Wysoki (osoba)',
        jp: { text: '背が高い', pronunciation: 'せがたかい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short (person)',
        pl: 'Niski (osoba)',
        jp: { text: '背が低い', pronunciation: 'せがひくい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective-irregular',
        en: 'Good',
        pl: 'Dobry',
        jp: { text: 'いい' },
        negative: { text: 'よくない' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Bad',
        pl: 'Zły',
        jp: { text: '悪い', pronunciation: 'わるい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'New',
        pl: 'Nowy',
        jp: { text: '新しい', pronunciation: 'あたらしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Old (thing)',
        pl: 'Stary (rzecz)',
        jp: { text: '古い', pronunciation: 'ふるい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Bright / Cheerful',
        pl: 'Jasny / Radosny',
        jp: { text: '明るい', pronunciation: 'あかるい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dark / Gloomy',
        pl: 'Ciemny / Ponury',
        jp: { text: '暗い', pronunciation: 'くらい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Wide / Spacious',
        pl: 'Szeroki / Przestronny',
        jp: { text: '広い', pronunciation: 'ひろい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Narrow / Cramped',
        pl: 'Wąski / Ciasny',
        jp: { text: '狭い', pronunciation: 'せまい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Long',
        pl: 'Długi',
        jp: { text: '長い', pronunciation: 'ながい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Short (length)',
        pl: 'Krótki (długość)',
        jp: { text: '短い', pronunciation: 'みじかい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Close',
        pl: 'Bliski',
        jp: { text: '近い', pronunciation: 'ちかい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Far',
        pl: 'Daleki',
        jp: { text: '遠い', pronunciation: 'とおい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Interesting',
        pl: 'Interesujący',
        jp: { text: '面白い', pronunciation: 'おもしろい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Fun / Enjoyable',
        pl: 'Przyjemny',
        jp: { text: '楽しい', pronunciation: 'たのしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Boring',
        pl: 'Nudny',
        jp: { text: 'つまらない' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Noisy',
        pl: 'Głośny',
        jp: { text: 'うるさい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Difficult',
        pl: 'Trudny',
        jp: { text: '難しい', pronunciation: 'むずかしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Busy',
        pl: 'Zajęty',
        jp: { text: '忙しい', pronunciation: 'いそがしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Cute',
        pl: 'Uroczy',
        jp: { text: '可愛い', pronunciation: 'かわいい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective-irregular',
        en: 'Handsome / Cool',
        pl: 'Przystojny / Fajny',
        jp: { text: 'かっこいい' },
        negative: { text: 'かっこよくない' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Nice / Kind (can be used for all people)',
        pl: 'Miły / Uprzejmy (może być używane do wszystkich osób)',
        jp: { text: '優しい', pronunciation: 'やさしい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Scary',
        pl: 'Straszny',
        jp: { text: '怖い', pronunciation: 'こわい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Terrible',
        pl: 'Okropny',
        jp: { text: 'ひどい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Dirty',
        pl: 'Brudny',
        jp: { text: '汚い', pronunciation: 'きたない' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Liked',
        pl: 'Lubiany',
        jp: { text: '好き', pronunciation: 'すき' },
    },
    {
        type: 'phrase',
        en: 'I like elephants.',
        pl: 'Lubię słonie.',
        jp: { text: '象が好きです。', pronunciation: 'ぞうがすきです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Disliked',
        pl: 'Nielubiany',
        jp: { text: '嫌い', pronunciation: 'きらい' },
    },
    {
        type: 'phrase',
        en: 'I dislike biology.',
        pl: 'Nie lubię biologii.',
        jp: { text: '生物学が嫌いです。', pronunciation: 'せいぶつがくがきらいです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Good at / Skilled (when referring to someone else)',
        pl: 'Dobry w / Utalentowany (gdy mowa o kimś innym)',
        jp: { text: '上手', pronunciation: 'じょうず' },
    },
    {
        type: 'phrase',
        en: 'She is good at cooking.',
        pl: 'Ona jest dobra w gotowaniu.',
        jp: { text: '料理が上手です。', pronunciation: 'りょうりがじょうずです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Bad at / Unskilled (when referring to someone else)',
        pl: 'Zły w / Słaby w (gdy mowa o kimś innym)',
        jp: { text: '下手', pronunciation: 'へた' },
    },
    {
        type: 'phrase',
        en: 'He is bad at sports.',
        pl: 'On jest słaby w sporcie.',
        jp: { text: 'スポーツが下手です。', pronunciation: 'スポーツがへたです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Good at / Skilled (when referring to oneself)',
        pl: 'Dobry w / Utalentowany (gdy mowa o sobie)',
        jp: { text: '得意', pronunciation: 'とくい' },
    },
    {
        type: 'phrase',
        en: 'I am good at math.',
        pl: 'Jestem dobry w matematyce.',
        jp: { text: '数学が得意です。', pronunciation: 'すうがくがとくいです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Bad at / Unskilled (when referring to oneself)',
        pl: 'Zły w / Słaby w (gdy mowa o sobie)',
        jp: { text: '苦手', pronunciation: 'にがて' },
    },
    {
        type: 'phrase',
        en: 'I am bad at Japanese.',
        pl: 'Jestem słaby w japońskim.',
        jp: { text: '日本語が苦手です。', pronunciation: 'にほんごがにがてです。' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Lively',
        pl: 'Pełen życia / Gwarny',
        jp: { text: '賑やか', pronunciation: 'にぎやか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Quiet',
        pl: 'Cichy',
        jp: { text: '静か', pronunciation: 'しずか' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Beautiful / Clean',
        pl: 'Piękny / Czysty',
        jp: { text: 'きれい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Famous',
        pl: 'Sławny',
        jp: { text: '有名', pronunciation: 'ゆうめい' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient',
        pl: 'Praktyczny / Dogodny',
        jp: { text: '便利', pronunciation: 'べんり' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Easy',
        pl: 'Łatwy',
        jp: { text: '簡単', pronunciation: 'かんたん' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Healthy / Energetic',
        pl: 'Zdrowy / Energiczny',
        jp: { text: '元気', pronunciation: 'げんき' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Nice / Kind (can only be used for not close people)',
        pl: 'Miły / Uprzejmy (może być używane tylko do osób, z którymi nie jesteśmy blisko)',
        jp: { text: '親切', pronunciation: 'しんせつ' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Free (not busy)',
        pl: 'Wolny (nie zajęty)',
        jp: { text: '暇', pronunciation: 'ひま' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Weird',
        pl: 'Dziwny',
        jp: { text: '変', pronunciation: 'へん' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Terrible / Difficult',
        pl: 'Trudny / Ciężki',
        jp: { text: '大変', pronunciation: 'たいへん' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective-irregular',
        en: 'Smart / Intelligent',
        pl: 'Mądry / Inteligentny',
        jp: { text: '頭がいい', pronunciation: 'あたまがいい' },
        negative: { text: '頭がよくない', pronunciation: 'あたまがよくない' },
    },
    {
        type: 'noun',
        en: 'Money',
        pl: 'Pieniądze',
        jp: { text: 'お金', pronunciation: 'おかね' },
    },
    {
        type: 'noun',
        en: 'Fermented soybeans',
        pl: 'Sfermentowana soja',
        jp: { text: '納豆', pronunciation: 'なっとう' },
    },
    {
        type: 'phrase',
        en: 'Okay',
        pl: 'Okej',
        jp: { text: 'オーケー' },
    },
    {
        type: 'noun',
        en: 'Cake',
        pl: 'Tort / Ciasto',
        jp: { text: 'ケーキ' },
    },
    {
        type: 'noun',
        en: 'Wear / Clothing',
        pl: 'Ubranie',
        jp: { text: 'ウェア' },
    },
    {
        type: 'noun',
        en: 'Cola',
        pl: 'Cola',
        jp: { text: 'コーラ' },
    },
    {
        type: 'noun',
        en: 'Kiwi',
        pl: 'Kiwi',
        jp: { text: 'キウイフルーツ' },
    },
    {
        type: 'noun',
        en: 'Cocoa / Hot cocoa',
        pl: 'Kakałko',
        jp: { text: 'ココア' },
    },
];

export const sakura2_11Bag: WordBag = {
    id: 'c31013ad-da4a-448e-b325-9d949fdb1a29',
    name: 'Sakura #2.11',
    words: sakura_2_11,
};
