import type { JapaneseWord } from '../../../types';

export const sakura_2_7: JapaneseWord[] = [
    {
        type: 'phrase',
        en: "I'm at home.",
        pl: 'Jestem w domu.',
        jp: { word: '私は家にいます。', pronunciation: 'わたしはうちにいます。' },
    },
    {
        type: 'noun',
        en: 'Menu',
        pl: 'Menu',
        jp: { word: 'メニュー' },
    },
    {
        type: 'noun',
        en: 'Hamburger',
        pl: 'Hamburger',
        jp: { word: 'ハンバーガー' },
    },
    {
        type: 'noun',
        en: 'Hot dog',
        pl: 'Hot dog',
        jp: { word: 'ホットドッグ' },
    },
    {
        type: 'noun',
        en: 'Fries',
        pl: 'Frytki',
        jp: { word: 'フライドポテト' },
    },
    {
        type: 'noun',
        en: 'Coffee',
        pl: 'Kawa',
        jp: { word: 'コーヒー' },
    },
    {
        type: 'noun',
        en: 'Black tea',
        pl: 'Czarna herbata',
        jp: { word: '紅茶', pronunciation: 'こうちゃ' },
    },
    {
        type: 'noun',
        en: 'Orange juice',
        pl: 'Sok pomarańczowy',
        jp: { word: 'オレンジジュース' },
    },
    {
        type: 'noun',
        en: 'Cola',
        pl: 'Cola',
        jp: { word: 'コーラ' },
    },
    {
        type: 'phrase',
        en: 'Welcome!',
        pl: 'Witamy!',
        jp: { word: 'いらっしゃいませ！' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Disliked',
        pl: 'Nielubiany',
        jp: { word: 'きらい' },
    },
    {
        type: 'noun',
        en: 'PC',
        pl: 'Komputer osobisty',
        jp: { word: 'パソコン' },
    },
    {
        type: 'noun',
        en: 'Animal',
        pl: 'Zwierzę',
        jp: { word: '動物', pronunciation: 'どうぶつ' },
    },
    {
        type: 'noun',
        en: 'Bird',
        pl: 'Ptak',
        jp: { word: '鳥', pronunciation: 'とり' },
    },
    {
        type: 'noun',
        en: 'Gate',
        pl: 'Brama',
        jp: { word: '門', pronunciation: 'もん' },
    },
    {
        type: 'noun',
        en: 'Progress',
        pl: 'Postęp',
        jp: { word: '進歩', pronunciation: 'しんぽ' },
    },
    {
        type: 'noun',
        en: 'Answer / Reply',
        pl: 'Odpowiedź',
        jp: { word: 'へんじ' },
    },
    {
        type: 'noun',
        en: 'Gold',
        pl: 'Złoto',
        jp: { word: '金', pronunciation: 'きん' },
    },
    {
        type: 'noun',
        en: 'Entrance / Front door',
        pl: 'Wejście / Drzwi frontowe',
        jp: { word: '玄関', pronunciation: 'げんかん' },
    },
    {
        type: 'noun',
        en: 'All',
        pl: 'Wszystko',
        jp: { word: '全部', pronunciation: 'ぜんぶ' },
    },
    {
        type: 'noun',
        en: 'Next time',
        pl: 'Następnym razem',
        jp: { word: '今度', pronunciation: 'こんど' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Inconvenient',
        pl: 'Niedogodny',
        jp: { word: '不便', pronunciation: 'ふべん' },
    },
    {
        type: 'noun',
        en: 'Silver',
        pl: 'Srebro',
        jp: { word: '銀', pronunciation: 'ぎん' },
    },
    {
        type: 'noun',
        en: 'Laundry',
        pl: 'Pranie',
        jp: { word: '洗濯', pronunciation: 'せんたく' },
    },
    {
        type: 'noun',
        en: 'Middle / Center',
        pl: 'Środek / Centrum',
        jp: { word: '真ん中', pronunciation: 'まんなか' },
    },
    {
        type: 'noun',
        en: 'Popularity',
        pl: 'Popularność',
        jp: { word: '人気', pronunciation: 'にんき' },
    },
    {
        type: 'noun',
        en: 'Human',
        pl: 'Człowiek',
        jp: { word: '人間', pronunciation: 'にんげん' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient / Easy to use',
        pl: 'Wygodny / Łatwy w użyciu',
        jp: { word: '便利', pronunciation: 'べんり' },
    },
    {
        type: 'noun',
        en: 'Relief / Peace of mind',
        pl: 'Spokój / Ukojenie',
        jp: { word: '安心', pronunciation: 'あんしん' },
    },
    {
        type: 'adverb',
        en: 'So / So much',
        pl: 'Tak / Tak bardzo',
        jp: { word: 'そんなに' },
    },
    {
        type: 'phrase',
        en: "I didn't work that much yesterday.",
        pl: 'Nie pracowałem tak dużo wczoraj.',
        jp: { word: 'きのうそんなにしごとしませんでした。' },
    },
    {
        type: 'noun',
        en: 'Relation',
        pl: 'Relacja',
        jp: { word: '関係', pronunciation: 'かんけい' },
    },
    {
        type: 'adverb',
        en: 'Please / Here you are',
        pl: 'Proszę',
        jp: { word: 'どうぞ' },
    },
    {
        type: 'noun',
        en: 'High school',
        pl: 'Liceum',
        jp: { word: '高校', pronunciation: 'こうこう' },
    },
    {
        type: 'noun',
        en: 'Truth',
        pl: 'Prawda',
        jp: { word: '本当', pronunciation: 'ほんとう' },
    },
    {
        type: 'noun',
        en: 'Car (formal)',
        pl: 'Samochód (formalnie)',
        jp: { word: '自動車', pronunciation: 'じどうしゃ' },
    },
    {
        type: 'noun',
        en: 'Plane',
        pl: 'Samolot',
        jp: { word: '飛行機', pronunciation: 'ひこうき' },
    },
    {
        type: 'noun',
        en: 'Opposite side',
        pl: 'Przeciwna strona',
        jp: { word: '向こう', pronunciation: 'むこう' },
    },
    {
        type: 'noun',
        en: 'Preparation',
        pl: 'Przygotowanie',
        jp: { word: '用意', pronunciation: 'ようい' },
    },
    {
        type: 'noun',
        en: 'Cleaning',
        pl: 'Sprzątanie',
        jp: { word: '掃除', pronunciation: 'そうじ' },
    },
    {
        type: 'noun',
        en: 'Major (in school)',
        pl: 'Kierunek studiów',
        jp: { word: '専攻', pronunciation: 'せんこう' },
    },
    {
        type: 'noun',
        en: 'Reward / Prize',
        pl: 'Nagroda',
        jp: { word: '褒美', pronunciation: 'ほうび' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'A lot of',
        pl: 'Liczny / Dużo',
        jp: { word: '多い', pronunciation: 'おおい' },
    },
    {
        type: 'noun',
        en: 'Main street',
        pl: 'Główna ulica',
        jp: { word: '大通り', pronunciation: 'おおどおり' },
    },
    {
        type: 'noun',
        en: 'Cheek (of the face)',
        pl: 'Policzek',
        jp: { word: '頬', pronunciation: 'ほお' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'To pass through',
        pl: 'Przechodzić przez',
        jp: { word: '通る', pronunciation: 'とおる' },
        present: {
            masu: {
                affirmative: { word: '通ります', pronunciation: 'とおります' },
                negative: { word: '通りません', pronunciation: 'とおりません' },
            },
        },
    },
    {
        type: 'noun',
        en: 'Ice',
        pl: 'Lód',
        jp: { word: '氷', pronunciation: 'こおり' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Cover',
        pl: 'Przykrywać / Zakrywać',
        jp: { word: '覆う', pronunciation: 'おおう' },
        present: {
            masu: {
                affirmative: { word: '覆います', pronunciation: 'おおいます' },
                negative: { word: '覆いません', pronunciation: 'おおいません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'My favorite animal is a cow.',
        pl: 'Moim ulubionym zwierzęciem jest krowa.',
        jp: { word: '私の好きな動物は牛です。', pronunciation: 'わたしのすきなどうぶつはうしです。' },
    },
    {
        type: 'phrase',
        en: 'My least favorite food is pumpkin.',
        pl: 'Moim najmniej ulubionym jedzeniem jest dynia.',
        jp: { word: '私の嫌いな食べ物はかぼちゃです。', pronunciation: 'わたしのきらいなたべものはかぼちゃです。' },
    },
];
