import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_2_8: TranslatedJapaneseText[] = [
    {
        id: '249dbf69-9fd3-45f7-ac4f-9ca26252d670',
        type: 'phrase',
        en: 'I learn Japanese.',
        pl: 'Uczę się japońskiego.',
        jp: { text: '日本語を勉強します。', pronunciation: 'にほんごをべんきょうします。' },
    },
    {
        id: 'e4d264bd-b169-41fa-8c8c-a2d79cb5614a',
        type: 'phrase',
        en: 'Long time no see.',
        pl: 'Dawno się nie widzieliśmy.',
        jp: { text: 'お久しぶりです。', pronunciation: 'おひさしぶりです。' },
    },
    {
        id: 'd08225fb-54e3-4dad-b46e-714517f3fa45',
        type: 'noun',
        en: 'Cooking / Cuisine / Dish',
        pl: 'Gotowanie / Kuchnia / Danie',
        jp: { text: '料理', pronunciation: 'りょうり' },
    },
    {
        id: '49947159-944d-4d33-846c-d20c75e1aa8e',
        type: 'noun',
        en: 'Season',
        pl: 'Pora roku',
        jp: { text: '季節', pronunciation: 'きせつ' },
    },
    {
        id: '99f858a8-be91-4c00-a8ce-f8de68bfd06d',
        type: 'noun',
        en: 'Spring',
        pl: 'Wiosna',
        jp: { text: '春', pronunciation: 'はる' },
    },
    {
        id: '0aee82f6-cb4a-4c22-8296-47cb49039e21',
        type: 'noun',
        en: 'Summer',
        pl: 'Lato',
        jp: { text: '夏', pronunciation: 'なつ' },
    },
    {
        id: '385c9041-2155-4c72-9ba3-b35cca52d4f8',
        type: 'noun',
        en: 'Autumn / Fall',
        pl: 'Jesień',
        jp: { text: '秋', pronunciation: 'あき' },
    },
    {
        id: '2ca1795d-64a8-4648-93d1-1609461e56a4',
        type: 'noun',
        en: 'Winter',
        pl: 'Zima',
        jp: { text: '冬', pronunciation: 'ふゆ' },
    },
    {
        id: '684f5640-0193-4eae-be11-0ed5f153e52d',
        type: 'phrase',
        en: 'What is your favorite season?',
        pl: 'Jaka jest twoja ulubiona pora roku?',
        jp: { text: '好きな季節はいつですか。', pronunciation: 'すきなきせつはいつですか。' },
        description:
            "In Japanese you don't ask 'What is your favorite season?' directly. Instead, you say something that translates to 'When is your favorite season?'.",
    },
    {
        id: 'de7f795f-080b-4b0e-90c7-586961042975',
        type: 'phrase',
        en: 'What is your favorite city?',
        pl: 'Jakie jest twoje ulubione miasto?',
        jp: { text: '好きな都市はどこですか。', pronunciation: 'すきなとしはどこですか。' },
        description:
            "In Japanese you don't ask 'What is your favorite city?' directly. Instead, you say something that translates to 'Where is your favorite city?'.",
    },
    {
        id: '73948124-151a-432d-93be-9827a244c60d',
        type: 'phrase',
        en: 'What is your favorite park?',
        pl: 'Jaki jest twój ulubiony park?',
        jp: { text: '好きな公園はどこですか。', pronunciation: 'すきなこうえんはどこですか。' },
        description: 'The same pattern as in the city example applies here.',
    },
    {
        id: '54b06f88-60b4-4f0c-b7cc-37423ff1cbf4',
        type: 'phrase',
        en: 'What is your favorite cafe?',
        pl: 'Jaka jest twoja ulubiona kawiarnia?',
        jp: { text: '好きな喫茶店はどこですか。', pronunciation: 'すきなきっさてんはどこですか。' },
        description: 'The same pattern as in the city example applies here.',
    },
    {
        id: '4f620c5b-a019-4a48-b192-ce9e47d3ac28',
        type: 'noun',
        en: 'Singer',
        pl: 'Piosenkarz',
        jp: { text: '歌手', pronunciation: 'かしゅ' },
    },
    {
        id: 'e241e275-c05f-44ef-9b54-24cd7d1f9cfe',
        type: 'phrase',
        en: 'Who is your favorite singer?',
        pl: 'Kto jest twoim ulubionym piosenkarzem?',
        jp: { text: '好きな歌手は誰ですか。', pronunciation: 'すきなかしゅはだれですか。' },
    },
    {
        id: 'e1113cf8-1ce2-4ab1-af46-598ba05f7440',
        type: 'noun',
        en: 'Pianist',
        pl: 'Pianista',
        jp: { text: 'ピアニスト' },
    },
    {
        id: '8def94dd-26cc-440b-ba59-22087f01ef20',
        type: 'noun',
        en: 'Election',
        pl: 'Wybory',
        jp: { text: '選挙', pronunciation: 'せんきょ' },
    },
    {
        id: '5dd64812-66eb-401c-8167-d3b2f69b7f33',
        type: 'noun',
        en: 'Address',
        pl: 'Adres',
        jp: { text: '住所', pronunciation: 'じゅうしょ' },
    },
    {
        id: '8300a0c8-e0ea-43b6-b5d0-6248c0b8e435',
        type: 'noun',
        en: 'Serious injury',
        pl: 'Poważny uraz',
        jp: { text: '重傷', pronunciation: 'じゅうしょう' },
    },
    {
        id: 'ee95d74b-c1ac-484f-ab08-12d7530beedd',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Pure white',
        pl: 'Śnieżnobiały',
        jp: { text: '真っ白', pronunciation: 'まっしろ' },
    },
    {
        id: 'f15b535a-3b8f-466a-97e3-489ccbff56c7',
        type: 'noun',
        en: 'Bowl (for rice or tea)',
        pl: 'Miska (na ryż lub herbatę)',
        jp: { text: '茶碗', pronunciation: 'ちゃわん' },
        description:
            'It used to mean only a tea bowl for tea ceremonies, but now it can also mean a regular bowl for rice or other food.',
    },
    {
        id: 'e93caa13-9d43-4c0e-adf2-b7a7dbcf0172',
        type: 'noun',
        en: 'Research / Study',
        pl: 'Badania / Nauka',
        jp: { text: '研究', pronunciation: 'けんきゅう' },
    },
    {
        id: '45284c44-7294-4ab3-aa1b-df4795db2965',
        type: 'noun',
        en: 'Abbreviated character / Simplified kanji',
        pl: 'Znak skrócony / Uproszczone kanji',
        jp: { text: '略字', pronunciation: 'りゃくじ' },
    },
    {
        id: 'da23828b-5cdf-4653-8f30-c7ce85b9bbf2',
        type: 'noun',
        en: 'Guest room',
        pl: 'Pokój gościnny',
        jp: { text: '客間', pronunciation: 'きゃくま' },
    },
    {
        id: '4a6b2ce5-dd2c-49ed-bfa5-76ce563944a9',
        type: 'noun',
        en: 'Woman / Female (sex)',
        pl: 'Kobieta (płeć)',
        jp: { text: '女性', pronunciation: 'じょせい' },
    },
    {
        id: '4473e12a-d315-4577-a8d8-d9f570d050f1',
        type: 'adverb',
        en: 'Clap, clap',
        pl: 'Klask, klask',
        jp: {
            text: 'パチパチ',
        },
    },
    {
        id: '66e789f6-20cc-4635-92a1-32b29c79818b',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Complex / Complicated',
        pl: 'Złożony / Skomplikowany',
        jp: { text: '複雑', pronunciation: 'ふくざつ' },
    },
    {
        id: 'a6aa4f12-6615-445c-a814-b16e74c68d72',
        type: 'noun',
        en: 'Mountain range',
        pl: 'Pasmo górskie',
        jp: { text: '山脈', pronunciation: 'さんみゃく' },
    },
    {
        id: '17389e78-4438-4e31-bfa1-f699a0e03972',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Direct / Immediate / Personal',
        pl: 'Bezpośredni / Natychmiastowy / Osobisty',
        jp: { text: '直接', pronunciation: 'ちょくせつ' },
    },
    {
        id: '0276bde5-7944-421e-a86a-b1191a9cbeaa',
        type: 'adverb',
        en: 'Not at all / Not a bit',
        pl: 'Wcale nie / Ani trochę',
        jp: { text: 'ちっとも' },
        description: 'This can be written in kanji, but it is usually written in hiragana in modern Japanese.',
    },
    {
        id: 'b26519e8-0aff-4aad-a6d1-72ff25192f33',
        type: 'noun',
        en: 'Scenery / Landscape',
        pl: 'Sceneria / Krajobraz',
        jp: { text: '景色', pronunciation: 'けしき' },
    },
    {
        id: 'ef9fe2e9-cc8c-452c-aab7-d39c92e243dc',
        type: 'noun',
        en: 'Doll / Puppet / Marionette',
        pl: 'Marionetka / Pacynka / Lalka',
        jp: { text: '人形', pronunciation: 'にんぎょう' },
    },
];

export const sakura2_8Bag: WordBag = {
    id: '34ec2540-cd2d-405a-8cca-1cf75f8b0237',
    name: 'Sakura #2.8',
    words: sakura_2_8,
};
