import type { JapaneseWord } from '../../../types';

export const sakura_2_7: JapaneseWord[] = [
    {
        type: 'phrase',
        en: "I'm at home.",
        pl: 'Jestem w domu.',
        jp: '私は家にいます。',
        jp_pronunciation: 'わたしはうちにいます。',
    },
    {
        type: 'noun',
        en: 'Menu',
        pl: 'Menu',
        jp: 'メニュー',
    },
    {
        type: 'noun',
        en: 'Hamburger',
        pl: 'Hamburger',
        jp: 'ハンバーガー',
    },
    {
        type: 'noun',
        en: 'Hot dog',
        pl: 'Hot dog',
        jp: 'ホットドッグ',
    },
    {
        type: 'noun',
        en: 'Fries',
        pl: 'Frytki',
        jp: 'フライドポテト',
    },
    {
        type: 'noun',
        en: 'Coffee',
        pl: 'Kawa',
        jp: 'コーヒー',
    },
    {
        type: 'noun',
        en: 'Black tea',
        pl: 'Czarna herbata',
        jp: '紅茶',
        jp_pronunciation: 'こうちゃ',
    },
    {
        type: 'noun',
        en: 'Orange juice',
        pl: 'Sok pomarańczowy',
        jp: 'オレンジジュース',
    },
    {
        type: 'noun',
        en: 'Cola',
        pl: 'Cola',
        jp: 'コーラ',
    },
    {
        type: 'phrase',
        en: 'Welcome!',
        pl: 'Witamy!',
        jp: 'いらっしゃいませ！',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Disliked',
        pl: 'Nielubiany',
        jp: 'きらい',
    },
    {
        type: 'noun',
        en: 'PC',
        pl: 'Komputer osobisty',
        jp: 'パソコン',
    },
    {
        type: 'noun',
        en: 'Animal',
        pl: 'Zwierzę',
        jp: '動物',
        jp_pronunciation: 'どうぶつ',
    },
    {
        type: 'noun',
        en: 'Bird',
        pl: 'Ptak',
        jp: '鳥',
        jp_pronunciation: 'とり',
    },
    {
        type: 'noun',
        en: 'Gate',
        pl: 'Brama',
        jp: '門',
        jp_pronunciation: 'もん',
    },
    {
        type: 'noun',
        en: 'Progress',
        pl: 'Postęp',
        jp: '進歩',
        jp_pronunciation: 'しんぽ',
    },
    {
        type: 'noun',
        en: 'Answer / Reply',
        pl: 'Odpowiedź',
        jp: 'へんじ',
    },
    {
        type: 'noun',
        en: 'Gold',
        pl: 'Złoto',
        jp: '金',
        jp_pronunciation: 'きん',
    },
    {
        type: 'noun',
        en: 'Entrance / Front door',
        pl: 'Wejście / Drzwi frontowe',
        jp: '玄関',
        jp_pronunciation: 'げんかん',
    },
    {
        type: 'noun',
        en: 'All',
        pl: 'Wszystko',
        jp: '全部',
        jp_pronunciation: 'ぜんぶ',
    },
    {
        type: 'noun',
        en: 'Next time',
        pl: 'Następnym razem',
        jp: '今度',
        jp_pronunciation: 'こんど',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Inconvenient',
        pl: 'Niedogodny',
        jp: '不便',
        jp_pronunciation: 'ふべん',
    },
    {
        type: 'noun',
        en: 'Silver',
        pl: 'Srebro',
        jp: '銀',
        jp_pronunciation: 'ぎん',
    },
    {
        type: 'noun',
        en: 'Laundry',
        pl: 'Pranie',
        jp: '洗濯',
        jp_pronunciation: 'せんたく',
    },
    {
        type: 'noun',
        en: 'Middle / Center',
        pl: 'Środek / Centrum',
        jp: '真ん中',
        jp_pronunciation: 'まんなか',
    },
    {
        type: 'noun',
        en: 'Popularity',
        pl: 'Popularność',
        jp: '人気',
        jp_pronunciation: 'にんき',
    },
    {
        type: 'noun',
        en: 'Human',
        pl: 'Człowiek',
        jp: '人間',
        jp_pronunciation: 'にんげん',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Convenient / Easy to use',
        pl: 'Wygodny / Łatwy w użyciu',
        jp: '便利',
        jp_pronunciation: 'べんり',
    },
    {
        type: 'noun',
        en: 'Relief / Peace of mind',
        pl: 'Spokój / Ukojenie',
        jp: '安心',
        jp_pronunciation: 'あんしん',
    },
    {
        type: 'adverb',
        en: 'So / So much',
        pl: 'Tak / Tak bardzo',
        jp: 'そんなに',
    },
    {
        type: 'phrase',
        en: "I didn't work that much yesterday.",
        pl: 'Nie pracowałem tak dużo wczoraj.',
        jp: 'きのうそんなにしごとしませんでした。',
    },
    {
        type: 'noun',
        en: 'Relation',
        pl: 'Relacja',
        jp: '関係',
        jp_pronunciation: 'かんけい',
    },
    {
        type: 'adverb',
        en: 'Please / Here you are',
        pl: 'Proszę',
        jp: 'どうぞ',
    },
    {
        type: 'noun',
        en: 'High school',
        pl: 'Liceum',
        jp: '高校',
        jp_pronunciation: 'こうこう',
    },
    {
        type: 'noun',
        en: 'Truth',
        pl: 'Prawda',
        jp: '本当',
        jp_pronunciation: 'ほんとう',
    },
    {
        type: 'noun',
        en: 'Car (formal)',
        pl: 'Samochód (formalnie)',
        jp: '自動車',
        jp_pronunciation: 'じどうしゃ',
    },
    {
        type: 'noun',
        en: 'Plane',
        pl: 'Samolot',
        jp: '飛行機',
        jp_pronunciation: 'ひこうき',
    },
    {
        type: 'noun',
        en: 'Opposite side',
        pl: 'Przeciwna strona',
        jp: '向こう',
        jp_pronunciation: 'むこう',
    },
    {
        type: 'noun',
        en: 'Preparation',
        pl: 'Przygotowanie',
        jp: '用意',
        jp_pronunciation: 'ようい',
    },
    {
        type: 'noun',
        en: 'Cleaning',
        pl: 'Sprzątanie',
        jp: '掃除',
        jp_pronunciation: 'そうじ',
    },
    {
        type: 'noun',
        en: 'Major (in school)',
        pl: 'Kierunek studiów',
        jp: '専攻',
        jp_pronunciation: 'せんこう',
    },
    {
        type: 'noun',
        en: 'Reward / Prize',
        pl: 'Nagroda',
        jp: '褒美',
        jp_pronunciation: 'ほうび',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'A lot of',
        pl: 'Liczny / Dużo',
        jp: '多い',
        jp_pronunciation: 'おおい',
    },
    {
        type: 'noun',
        en: 'Main street',
        pl: 'Główna ulica',
        jp: '大通り',
        jp_pronunciation: 'おおどおり',
    },
    {
        type: 'noun',
        en: 'Cheek (of the face)',
        pl: 'Policzek',
        jp: '頬',
        jp_pronunciation: 'ほお',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'To pass through',
        pl: 'Przechodzić przez',
        jp: '通る',
        jp_pronunciation: 'とおる',
        masu_form: '通ります (とおります)',
        masen_form: '通りません (とおりません)',
    },
    {
        type: 'noun',
        en: 'Ice',
        pl: 'Lód',
        jp: '氷',
        jp_pronunciation: 'こおり',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Cover',
        pl: 'Przykrywać / Zakrywać',
        jp: '覆う',
        jp_pronunciation: 'おおう',
        masu_form: '覆います (おおいます)',
        masen_form: '覆いません (おおいません)',
    },
];
