import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_2_4: TranslatedJapaneseText[] = [
    {
        id: 'c8513fb3-c317-48f4-ba8c-2448a2b87b63',
        type: 'noun',
        en: 'Birthday party',
        pl: 'Przyjęcie urodzinowe',
        jp: { text: 'バースデーパーティー' },
    },
    {
        id: '3c98fe15-2f02-494d-b094-ce420dbe108c',
        type: 'phrase',
        en: 'Saturday is okay.',
        pl: 'Sobota może być. (Nie mam nic przeciwko sobocie.)',
        jp: { text: '土曜日はだいじょうぶです。', pronunciation: 'どようびはだいじょうぶです。' },
    },
    {
        id: '1b27b97b-aa66-4602-ad33-389d36e7278a',
        type: 'phrase',
        en: 'Saturday works for me.',
        pl: 'Sobota mi pasuje.',
        jp: { text: '土曜日はいいです。', pronunciation: 'どようびはいいです。' },
    },
    {
        id: '0c899f39-3f27-4533-ae37-c75760910672',
        type: 'phrase',
        en: 'Any time is fine.',
        pl: 'Obojętnie kiedy.',
        jp: { text: 'いつでもいいです。' },
    },
    {
        id: 'da4639a1-17ce-4175-bf4d-9f475ce02411',
        type: 'phrase',
        en: 'Any hour works for me.',
        pl: 'Każda godzina mi pasuje.',
        jp: { text: '何時でもいいです。', pronunciation: 'なんじでもいいです。' },
    },
    {
        id: 'fd96d5b6-2a69-41d3-8801-9a1daaf95591',
        type: 'noun',
        en: 'Circle / Correct',
        pl: 'Koło / Poprawne',
        jp: { text: 'まる' },
        description: 'Symbol indicating something is correct or good.',
    },
    {
        id: '589bde81-61fa-4d19-8d5f-3a7d5bf2baa9',
        type: 'noun',
        en: 'Cross / Incorrect',
        pl: 'Krzyżyk / Niepoprawne',
        jp: { text: 'ばつ' },
        description: 'Symbol indicating something is incorrect or bad.',
    },
    {
        id: '9db615e0-6dd5-408f-8f3f-004a4f25a9e3',
        type: 'phrase',
        en: "Does 7 o'clock work for you?",
        pl: 'Czy godzina 7 ci pasuje?',
        jp: { text: '七時はいいですか。', pronunciation: 'しちじはいいですか。' },
    },
    {
        id: 'e94c87c0-17bd-47c9-b832-1a58fb5e75a6',
        type: 'noun',
        en: 'Live / Concert',
        pl: 'Koncert / Transmisja na żywo',
        jp: { text: 'ライブ' },
    },
    {
        id: '083a9a07-0237-4742-b1f2-927aed93be72',
        type: 'phrase',
        en: "Thursday doesn't work for me.",
        pl: 'Czwartek mi nie pasuje.',
        jp: { text: '木曜日はだめです。', pronunciation: 'もくようびはだめです。' },
    },
    {
        id: '0b10f471-9e71-43f3-ae14-27a8e21288a5',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Not good',
        pl: 'Niedobry / Nie w porządku',
        jp: { text: 'だめ' },
    },
    {
        id: '059effee-ccef-4c2a-a384-384554537842',
        type: 'phrase',
        en: 'What time is good for you?',
        pl: 'Która godzina ci pasuje?',
        jp: { text: '何時がいいですか。', pronunciation: 'なんじがいいですか。' },
    },
    {
        id: 'f5f6fd29-4c75-4fd5-901c-dc098c7e111b',
        type: 'phrase',
        en: 'When is good for you?',
        pl: 'Kiedy ci pasuje?',
        jp: { text: 'いつがいいですか。' },
    },
    {
        id: '4f6c8565-c862-4a43-b61a-7802c7755dd6',
        type: 'phrase',
        en: "It's fine.",
        pl: 'W porządku.',
        jp: { text: 'いいですよ。' },
    },
    {
        id: 'd5a4d377-d672-46ba-bff0-ef436cbdf808',
        type: 'noun',
        en: 'Dried seaweed',
        pl: 'Suszone wodorosty',
        jp: { text: 'のり' },
    },
    {
        id: '0494e06f-45b9-4b16-a28a-087c304d041a',
        type: 'noun',
        en: 'Overtime',
        pl: 'Nadgodziny',
        jp: { text: 'ざんぎょう' },
    },
    {
        id: '53eba20a-a793-4634-96fb-448737cc3d97',
        type: 'verb',
        verb_type: 'suru',
        en: 'Work overtime',
        pl: 'Pracować po godzinach',
        jp: { text: 'ざんぎょうをする' },
    },
];

export const sakura2_4Bag: WordBag = {
    id: '754ed98b-dd89-4a04-a77f-b44f4670ce8c',
    name: 'Sakura #2.4',
    category: 'sakura',
    words: sakura_2_4,
};
