import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_2_1: TranslatedJapaneseText[] = [
    {
        id: '794979ca-b0e6-4acc-9b0a-9383c5e0bd1e',
        type: 'phrase',
        en: 'Happy New Year!',
        pl: 'Szczęśliwego Nowego Roku!',
        jp: { text: 'あけましておめでとう。' },
    },
    {
        id: 'd1ec2da8-fe76-4e6c-8609-0403c00605a8',
        type: 'phrase',
        en: 'Please treat me well this year too.',
        pl: 'W tym roku również proszę o życzliwość.',
        jp: { text: '今年もよろしく。', pronunciation: 'ことしもよろしく。' },
    },
    {
        id: '5f7debdb-a1ef-42b6-b2b3-02ad42c4d1a2',
        type: 'noun',
        en: 'Evening',
        pl: 'Wieczór',
        jp: { text: '夕方', pronunciation: 'ゆうがた' },
    },
    {
        id: '9e8e6800-ae5c-4c63-bd03-558e33bf2ad2',
        type: 'noun',
        en: "Hairdresser's salon",
        pl: 'Salon fryzjerski',
        jp: { text: '美容院', pronunciation: 'びよういん' },
    },
    {
        id: 'fa75bda2-921c-4a9a-bd9f-e963e568ef36',
        type: 'noun',
        en: 'Art museum',
        pl: 'Muzeum sztuki',
        jp: { text: '美術館', pronunciation: 'びじゅつかん' },
    },
    {
        id: 'e3cc07dd-f8ac-4457-a742-2468d25f26fc',
        type: 'noun',
        en: 'Museum',
        pl: 'Muzeum',
        jp: { text: '博物館', pronunciation: 'はくぶつかん' },
    },
    {
        id: 'fc71c2d6-97a1-4cd7-8dfe-8212d80d2097',
        type: 'noun',
        en: 'Concert',
        pl: 'Koncert',
        jp: { text: 'コンサート' },
    },
    {
        id: '6da0b611-33ab-40ce-a7d4-ecaafd00a2af',
        type: 'noun',
        en: 'Party',
        pl: 'Impreza',
        jp: { text: 'パーティー' },
    },
    {
        id: '086e7bc1-04c2-4bde-94a2-d24445fcef46',
        type: 'verb',
        verb_type: 'suru',
        en: 'Throw a party',
        pl: 'Urządzić imprezę',
        jp: { text: 'パーティーをする' },
    },
    {
        id: 'a9b8d80e-2c21-41a5-9d54-8f1f1d8326e4',
        type: 'verb',
        verb_type: 'suru',
        en: 'Have a meal',
        pl: 'Zjeść posiłek',
        jp: { text: '食事をする', pronunciation: 'しょくじをする' },
    },
    {
        id: 'ebc72412-d908-4392-b10c-c06fe27c8500',
        type: 'noun',
        en: 'Meal',
        pl: 'Posiłek',
        jp: { text: '食事', pronunciation: 'しょくじ' },
    },
    {
        id: '8b9228e1-080e-44c4-9b47-1b7e846ab2fe',
        type: 'phrase',
        en: 'Wednesday next week',
        pl: 'Środa w przyszłym tygodniu',
        jp: { text: '来週の水曜日', pronunciation: 'らいしゅうのすいようび' },
    },
    {
        id: '559ba570-d22f-4639-94ec-06c8c14e45e0',
        type: 'noun',
        en: 'Yesterday',
        pl: 'Wczoraj',
        jp: { text: '昨日', pronunciation: 'きのう' },
    },
    {
        id: 'a62750e4-de54-4e73-90e5-90a6079812de',
        type: 'noun',
        en: 'Christmas',
        pl: 'Boże Narodzenie',
        jp: { text: 'クリスマス' },
    },
    {
        id: 'b237c85f-f73e-4670-8551-a4753c3ae22b',
        type: 'phrase',
        en: 'On evenings I go for a walk.',
        pl: 'Wieczorami chodzę na spacer.',
        jp: { text: '夕方散歩をします。', pronunciation: 'ゆうがたさんぽをします' },
        description:
            'Note there is no particle "に" after "ゆうがた". The same applies to other time expressions like "あさ" (morning) or "ばん" (night).',
    },
    {
        id: 'fd82ba44-fb6c-4d5d-a265-a0349ea00bee',
        type: 'phrase',
        en: 'I go to the art museum on Friday.',
        pl: 'W piątek idę do muzeum sztuki.',
        jp: { text: '金曜日に美術館に行きます。', pronunciation: 'きんようびにびじゅつかんにいきます' },
        description: 'The particle "に" is used after "きんようび" (Friday), just like with other days of the week.',
    },
    {
        id: '45357a0a-11d9-44ba-ba3f-5c4549975df2',
        type: 'phrase',
        en: 'On Friday evening I watch TV.',
        pl: 'W piątkowy wieczór oglądam telewizję.',
        jp: { text: '金曜日の夕方テレビを見ます。', pronunciation: 'きんようびのゆうがたテレビをみます' },
        description:
            'The particle "の" is used to connect "きんようび" (Friday) and "ゆうがた" (evening) to form "Friday evening". There is no particle "に" after "ゆうがた" (evening).',
    },
    {
        id: 'a0d89e9a-d132-4700-9b61-7f3ed0c4d31d',
        type: 'phrase',
        en: "Yesterday at 9 o'clock I ate sushi.",
        pl: 'Wczoraj o dziewiątej jadłem sushi.',
        jp: { text: '昨日の九時に寿司を食べました。', pronunciation: 'きのうのくじにすしをたべました' },
        description: 'The particle "に" is used after "くじ", even though before it there is "きのう" (yesterday).',
    },
    {
        id: 'adbe61fe-7d38-4d77-84d4-40ce7b618e42',
        type: 'phrase',
        en: 'Today I will do chores. Tomorrow I will do chores too.',
        pl: 'Dziś będę wykonywać obowiązki domowe. Jutro też będę wykonywać obowiązki domowe.',
        jp: {
            text: '今日家事をします。明日も家事をします。',
            pronunciation: 'きょうかじをします。あしたもかじをします',
        },
    },
    {
        id: '67a37c72-cbe1-4f63-aa14-31db09bddc78',
        type: 'phrase',
        en: "Next week I won't meet my mom.",
        pl: 'W przyszłym tygodniu nie spotkam się z mamą.',
        jp: { text: '来週母と会いません。', pronunciation: 'らいしゅうははとあいません' },
    },
    {
        id: '42f425fc-9259-4111-8c89-53268a0d42ee',
        type: 'phrase',
        en: 'Did you read a book yesterday?',
        pl: 'Czy czytałeś książkę wczoraj?',
        jp: { text: '昨日本を読みましたか。', pronunciation: 'きのうほんをよみましたか' },
    },
    {
        id: '97061083-e408-44ed-a4ad-045cd7c244b0',
        type: 'phrase',
        en: "I didn't wear a jacket yesterday.",
        pl: 'Wczoraj nie założyłem kurtki.',
        jp: { text: '昨日ジャケットは着ませんでした。', pronunciation: 'きのうジャケットはきませんでした' },
    },
];

export const sakura2_1Bag: WordBag = {
    id: '16ad0aab-df84-46c1-801e-ad829f453a05',
    name: 'Sakura #2.1',
    words: sakura_2_1,
};
