import type { JapaneseWord } from '../../../types';

export const sakura_1_12: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Friends will come to my house.',
        pl: 'Przyjaciele przyjdą do mojego domu.',
        jp: 'ともだちがわたしのうちにきます。',
    },
    {
        type: 'pronoun',
        en: 'When',
        pl: 'Kiedy',
        jp: 'いつ',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Use',
        pl: 'Używać',
        jp: 'つかう',
        masu_form: 'つかいます',
        masen_form: 'つかいません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Meet',
        pl: 'Spotykać',
        jp: '会う',
        jp_pronunciation: 'あう',
        masu_form: '会います (あいます)',
        masen_form: '会いません (あいません)',
    },
    {
        type: 'phrase',
        en: 'With whom do you meet?',
        pl: 'Z kim się spotykasz?',
        jp: 'だれとあいますか？',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Make / Create',
        pl: 'Robić / Tworzyć',
        jp: 'つくる',
        masu_form: 'つくります',
        masen_form: 'つくりません',
    },
    {
        type: 'phrase',
        en: 'I use a phone.',
        pl: 'Używam telefonu.',
        jp: 'でんわをつかいます。',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Take (an object or picture)',
        pl: 'Brać (przedmiot) lub robić (zdjęcie)',
        jp: '撮る',
        jp_pronunciation: 'とる',
        masu_form: '撮ります (とります)',
        masen_form: '撮りません (とりません)',
    },
    {
        type: 'phrase',
        en: 'Take pictures',
        pl: 'Robić zdjęcia',
        jp: 'しゃしんをとる',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Send',
        pl: 'Wysyłać',
        jp: 'おくる',
        masu_form: 'おくります',
        masen_form: 'おくりません',
    },
    {
        type: 'phrase',
        en: 'Send a letter',
        pl: 'Wysyłać list',
        jp: 'てがみをおくります',
    },
    {
        type: 'noun',
        en: 'Package',
        pl: 'Paczka',
        jp: 'にもつ',
    },
    {
        type: 'phrase',
        en: 'Play by yourself',
        pl: 'Bawić się samemu',
        jp: 'ひとりであそぶ',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Play / Have fun / Hang out',
        pl: 'Bawić się / Miło spędzać czas',
        jp: 'あそぶ',
        masu_form: 'あそびます',
        masen_form: 'あそびません',
    },
    {
        type: 'noun',
        en: 'Musical instrument',
        pl: 'Instrument muzyczny',
        jp: 'がっき',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: 'ひく',
        masu_form: 'ひきます',
        masen_form: 'ひきません',
    },
    {
        type: 'phrase',
        en: 'Play an instrument',
        pl: 'Grać na instrumencie',
        jp: 'がっきをひく',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Rest',
        pl: 'Odpoczywać',
        jp: 'やすむ',
        masu_form: 'やすみます',
        masen_form: 'やすみません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Swim',
        pl: 'Pływać',
        jp: 'およぐ',
        masu_form: 'およぎます',
        masen_form: 'およぎません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: 'はなす',
        masu_form: 'はなします',
        masen_form: 'はなしません',
    },
    {
        type: 'phrase',
        en: 'Who are you talking with?',
        pl: 'Z kim rozmawiasz?',
        jp: 'だれとはなしますか？',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Teach',
        pl: 'Uczyć (kogoś)',
        jp: 'おしえる',
        masu_form: 'おしえます',
        masen_form: 'おしえません',
    },
    {
        type: 'phrase',
        en: 'I teach my children math.',
        pl: 'Uczę moje dzieci matematyki.',
        jp: 'わたしはこどもにすうがくをおしえます。',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Put on (clothes)',
        pl: 'Zakładać (ubrania)',
        jp: 'きる',
        masu_form: 'きます',
        masen_form: 'きません',
    },
    {
        type: 'phrase',
        en: 'Put on a jacket',
        pl: 'Zakładać kurtkę',
        jp: 'ジャケットをきる',
    },
    {
        type: 'phrase',
        en: 'All day',
        pl: 'Cały dzień',
        jp: 'いちにちじゅう',
    },
    {
        type: 'phrase',
        en: 'Cook',
        pl: 'Gotować',
        jp: 'りょうりをする',
    },
    {
        type: 'phrase',
        en: 'Do sports',
        pl: 'Uprawiać sport',
        jp: 'スポーツをする',
    },
    {
        type: 'phrase',
        en: 'I shop twice every week.',
        pl: 'Robię zakupy dwa razy w każdy tydzień.',
        jp: 'まいしゅうにかいかいものをします。',
    },
    {
        type: 'phrase',
        en: 'Cook pierogi',
        pl: 'Gotować pierogi',
        jp: 'ピエロギをつくります',
    },
    {
        type: 'phrase',
        en: 'Cook Japanese food',
        pl: 'Gotować japońskie jedzenie',
        jp: 'にほんのりょうりをつくる',
    },
    {
        type: 'noun',
        en: 'Copy',
        pl: 'Kopia',
        jp: 'コピー',
    },
    {
        type: 'phrase',
        en: 'Make a copy',
        pl: 'Robić kopię',
        jp: 'コピーをする',
    },
    {
        type: 'noun',
        en: 'Piano',
        pl: 'Pianino',
        jp: 'ピアノ',
    },
    {
        type: 'noun',
        en: 'Guitar',
        pl: 'Gitara',
        jp: 'ギター',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Yellow',
        pl: 'Żółty',
        jp: 'きいろい',
    },
    {
        type: 'noun',
        en: 'Street',
        pl: 'Ulica',
        jp: 'とおり',
    },
    {
        type: 'noun',
        en: 'Air',
        pl: 'Powietrze',
        jp: 'くうき',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Big',
        pl: 'Duży',
        jp: 'おおきい',
    },
    {
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: 'おおかみ',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Small',
        pl: 'Mały',
        jp: 'ちいさい',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Far',
        pl: 'Daleko',
        jp: 'とおい',
    },
    {
        type: 'noun',
        en: 'Fridge',
        pl: 'Lodówka',
        jp: 'れいぞうこ',
    },
];
