import type { JapaneseWord } from '../../../types';

export const sakura_1_5: JapaneseWord[] = [
    {
        type: 'pronoun',
        en: 'Who',
        pl: 'Kto',
        jp: 'だれ',
    },
    {
        type: 'phrase',
        en: 'Whose bike is this?',
        pl: 'Czyj to rower?',
        jp: 'これはだれのじてんしゃですか。',
    },
    {
        type: 'noun',
        en: 'Cherry / Cherry blossom',
        pl: 'Wiśnia / Kwiat wiśni',
        jp: 'さくら',
    },
    {
        type: 'noun',
        en: 'Medicine / Drug',
        pl: 'Lekarstwo / Lek',
        jp: 'くすり',
    },
    {
        type: 'noun',
        en: 'Car',
        pl: 'Samochód',
        jp: 'くるま',
    },
    {
        type: 'noun',
        en: 'History',
        pl: 'Historia',
        jp: 'れきし',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'White',
        pl: 'Biały',
        jp: 'しろい',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Black',
        pl: 'Czarny',
        jp: 'くろい',
    },
    {
        type: 'noun',
        en: 'River',
        pl: 'Rzeka',
        jp: 'かわ',
    },
    {
        type: 'noun',
        en: 'Mandarin',
        pl: 'Mandarynka',
        jp: 'みかん',
    },
    {
        type: 'phrase',
        en: 'How old are you? (informal)',
        pl: 'Ile masz lat? (nieformalnie)',
        jp: 'なんさいですか。',
    },
    {
        type: 'phrase',
        en: 'How old are you? (formal)',
        pl: 'Ile ma pan/pani lat? (formalnie)',
        jp: 'おいくつですか。',
    },
    {
        type: 'phrase',
        en: 'How old is your mother?',
        pl: 'Ile lat ma twoja mama?',
        jp: 'おかあさんは おいくつですか。',
    },
    {
        type: 'phrase',
        en: "I don't have an older sister.",
        pl: 'Nie mam starszej siostry.',
        jp: 'あねはいません。',
    },
    {
        type: 'noun',
        en: 'Phone number',
        pl: 'Numer telefonu',
        jp: 'でんわばんごう',
    },
    {
        type: 'noun',
        en: 'One year old',
        pl: 'Jeden rok (wiek)',
        jp: 'いっさい',
    },
    {
        type: 'noun',
        en: 'Two years old',
        pl: 'Dwa lata (wiek)',
        jp: 'にさい',
    },
    {
        type: 'noun',
        en: 'Three years old',
        pl: 'Trzy lata (wiek)',
        jp: 'さんさい',
    },
    {
        type: 'noun',
        en: 'Four years old',
        pl: 'Cztery lata (wiek)',
        jp: 'よんさい',
    },
    {
        type: 'noun',
        en: 'Five years old',
        pl: 'Pięć lat (wiek)',
        jp: 'ごさい',
    },
    {
        type: 'noun',
        en: 'Six years old',
        pl: 'Sześć lat (wiek)',
        jp: 'ろくさい',
    },
    {
        type: 'noun',
        en: 'Seven years old',
        pl: 'Siedem lat (wiek)',
        jp: 'ななさい',
    },
    {
        type: 'noun',
        en: 'Eight years old',
        pl: 'Osiem lat (wiek)',
        jp: 'はっさい',
    },
    {
        type: 'noun',
        en: 'Nine years old',
        pl: 'Dziewięć lat (wiek)',
        jp: 'きゅうさい',
    },
    {
        type: 'noun',
        en: 'Ten years old',
        pl: 'Dziesięć lat (wiek)',
        jp: 'じゅっさい',
    },
    {
        type: 'noun',
        en: 'Eleven years old',
        pl: 'Jedenaście lat (wiek)',
        jp: 'じゅういっさい',
    },
    {
        type: 'noun',
        en: 'Seventeen years old',
        pl: 'Siedemnaście lat (wiek)',
        jp: 'じゅうななさい',
    },
    {
        type: 'noun',
        en: 'Nineteen years old',
        pl: 'Dziewiętnaście lat (wiek)',
        jp: 'じゅうきゅうさい',
    },
    {
        type: 'noun',
        en: 'Twenty years old',
        pl: 'Dwadzieścia lat (wiek)',
        jp: 'はたち',
    },
    {
        type: 'noun',
        en: 'Twenty eight years old',
        pl: 'Dwadzieścia osiem lat (wiek)',
        jp: 'にじゅうはっさい',
    },
    {
        type: 'noun',
        en: 'Thirty years old',
        pl: 'Trzydzieści lat (wiek)',
        jp: 'さんじゅっさい',
    },
    {
        type: 'noun',
        en: 'One person',
        pl: 'Jedna osoba',
        jp: 'ひとり',
    },
    {
        type: 'noun',
        en: 'Two people',
        pl: 'Dwie osoby',
        jp: 'ふたり',
    },
    {
        type: 'noun',
        en: 'Three people',
        pl: 'Trzy osoby',
        jp: 'さんにん',
    },
    {
        type: 'noun',
        en: 'Four people',
        pl: 'Cztery osoby',
        jp: 'よにん',
    },
    {
        type: 'noun',
        en: 'Five people',
        pl: 'Pięć osób',
        jp: 'ごにん',
    },
    {
        type: 'noun',
        en: 'Six people',
        pl: 'Sześć osób',
        jp: 'ろくにん',
    },
    {
        type: 'noun',
        en: 'Seven people',
        pl: 'Siedem osób',
        jp: 'ななにん',
    },
    {
        type: 'noun',
        en: 'Eight people',
        pl: 'Osiem osób',
        jp: 'はちにん',
    },
    {
        type: 'noun',
        en: 'Nine people',
        pl: 'Dziewięć osób',
        jp: 'きゅうにん',
    },
    {
        type: 'noun',
        en: 'Ten people',
        pl: 'Dziesięć osób',
        jp: 'じゅうにん',
    },
    {
        type: 'noun',
        en: 'Eleven people',
        pl: 'Jedenaście osób',
        jp: 'じゅういちにん',
    },
    {
        type: 'noun',
        en: 'Twelve people',
        pl: 'Dwanaście osób',
        jp: 'じゅうににん',
    },
    {
        type: 'phrase',
        en: 'How many people are in your family?',
        pl: 'Ile osób jest w twojej rodzinie?',
        jp: 'かぞくはなんにんですか。',
    },
    {
        type: 'phrase',
        en: 'My family has four people.',
        pl: 'Moja rodzina liczy cztery osoby.',
        jp: 'かぞくはよにんです。',
    },
    {
        type: 'phrase',
        en: 'I have two older sisters.',
        pl: 'Mam dwie starsze siostry.',
        jp: 'あねがふたりいます。',
    },
];
