import type { JapaneseWord } from '../../../types';

export const sakura_1_7: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: 'しんぶん',
    },
    {
        type: 'noun',
        en: 'Bag',
        pl: 'Torba',
        jp: 'かばん',
    },
    {
        type: 'noun',
        en: 'Fireworks',
        pl: 'Fajerwerki',
        jp: 'はなび',
    },
    {
        type: 'noun',
        en: 'Children',
        pl: 'Dzieci',
        jp: 'こども',
    },
    {
        type: 'noun',
        en: 'Abacus',
        pl: 'Liczydło',
        jp: 'そろばん',
    },
    {
        type: 'pronoun',
        en: 'I (male)',
        pl: 'Ja (męskie)',
        jp: 'ぼく',
    },
    {
        type: 'noun',
        en: 'Phone',
        pl: 'Telefon',
        jp: 'でんわ',
    },
    {
        type: 'noun',
        en: 'Family (polite)',
        pl: 'Rodzina (grzecznie)',
        jp: 'ごかぞく',
    },
    {
        type: 'noun',
        en: 'Future',
        pl: 'Przyszłość',
        jp: 'しょうらい',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Important',
        pl: 'Ważny',
        jp: 'たいせつ',
    },
    {
        type: 'phrase',
        en: 'Who is part of your family?',
        pl: 'Kto jest częścią twojej rodziny?',
        jp: 'だれがいますか。',
        jp_description:
            'Literally: "Who is there?". When this phrase is used in a family context, it refers to family members.',
    },
    {
        type: 'suffix',
        en: 'City',
        pl: 'Miasto',
        jp: '市',
        jp_pronunciation: 'し',
    },
    {
        type: 'noun',
        en: 'Leszno city',
        pl: 'Miasto Leszno',
        jp: 'レスノ市',
        jp_description: 'Note that "city" here is translated as "市" (し) as a suffix.',
    },
    {
        type: 'pronoun',
        en: 'We',
        pl: 'My',
        jp: 'わたしたち',
    },
    {
        type: 'noun',
        en: 'Food',
        pl: 'Jedzenie',
        jp: 'たべもの',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Eat',
        pl: 'Jeść',
        jp: 'たべる',
        masu_form: 'たべます',
        masen_form: 'たべません',
    },
    {
        type: 'noun',
        en: 'Meat',
        pl: 'Mięso',
        jp: 'にく',
    },
    {
        type: 'noun',
        en: 'Fish',
        pl: 'Ryba',
        jp: 'さかな',
    },
    {
        type: 'noun',
        en: 'Vegetables',
        pl: 'Warzywa',
        jp: 'やさい',
    },
    {
        type: 'noun',
        en: 'Egg',
        pl: 'Jajko',
        jp: 'たまご',
    },
    {
        type: 'noun',
        en: 'Bread',
        pl: 'Chleb',
        jp: 'パン',
    },
    {
        type: 'noun',
        en: 'Miso soup',
        pl: 'Zupa miso',
        jp: 'みそしる',
    },
    {
        type: 'noun',
        en: 'Rice',
        pl: 'Ryż',
        jp: 'ごはん',
    },
    {
        type: 'noun',
        en: 'Fruit',
        pl: 'Owoce',
        jp: 'くだもの',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Drink',
        pl: 'Pić',
        jp: 'のむ',
        masu_form: 'のみます',
        masen_form: 'のみません',
    },
    {
        type: 'noun',
        en: 'Drink',
        pl: 'Napój',
        jp: 'のみもの',
    },
    {
        type: 'noun',
        en: 'Water',
        pl: 'Woda',
        jp: 'みず',
    },
    {
        type: 'noun',
        en: 'Green tea',
        pl: 'Zielona herbata',
        jp: 'おちゃ',
    },
    {
        type: 'noun',
        en: 'Coffee',
        pl: 'Kawa',
        jp: 'コーヒー',
    },
    {
        type: 'noun',
        en: 'Black tea',
        pl: 'Czarna herbata',
        jp: 'こうちゃ',
    },
    {
        type: 'noun',
        en: 'Juice',
        pl: 'Sok',
        jp: 'ジュース',
    },
    {
        type: 'noun',
        en: 'Milk',
        pl: 'Mleko',
        jp: 'ぎゅうにゅう',
    },
];
