import type { JapaneseWord } from '../../../types';

export const sakura_1_3: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Meat',
        pl: 'Mięso',
        jp: { word: 'にく' },
    },
    {
        type: 'noun',
        en: 'Fish',
        pl: 'Ryba',
        jp: { word: 'さかな' },
    },
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: { word: 'いぬ' },
    },
    {
        type: 'noun',
        en: 'Cat',
        pl: 'Kot',
        jp: { word: 'ねこ' },
    },
    {
        type: 'noun',
        en: 'Chopsticks',
        pl: 'Pałeczki do jedzenia',
        jp: { word: 'はし' },
    },
    {
        type: 'noun',
        en: 'Ship',
        pl: 'Statek',
        jp: { word: 'ふね' },
    },
    {
        type: 'noun',
        en: 'Person',
        pl: 'Osoba',
        jp: { word: 'ひと' },
    },
    {
        type: 'noun',
        en: 'Flower',
        pl: 'Kwiat',
        jp: { word: 'はな' },
    },
    {
        type: 'conjunction',
        en: 'And',
        pl: 'I / Oraz',
        jp: { word: 'と' },
    },
    {
        type: 'particle',
        en: 'Also',
        pl: 'Też / Również',
        jp: { word: 'も' },
    },
    {
        type: 'noun',
        en: 'Profession / Job',
        pl: 'Zawód',
        jp: { word: 'しごと' },
    },
    {
        type: 'phrase',
        en: "What's your job?",
        pl: 'Jaki jest twój zawód?',
        jp: { word: 'おしごとは。' },
    },
    {
        type: 'noun',
        en: 'Notebook',
        pl: 'Notatnik',
        jp: { word: 'ノート' },
    },
    {
        type: 'noun',
        en: 'Book',
        pl: 'Książka',
        jp: { word: '本', pronunciation: 'ほん' },
    },
    {
        type: 'noun',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: { word: 'しんぶん' },
    },
    {
        type: 'noun',
        en: 'Clock',
        pl: 'Zegar',
        jp: { word: 'とけい' },
    },
    {
        type: 'noun',
        en: 'Bag',
        pl: 'Torba',
        jp: { word: 'かばん' },
    },
    {
        type: 'noun',
        en: 'Desk',
        pl: 'Biurko',
        jp: { word: 'つくえ' },
    },
    {
        type: 'noun',
        en: 'Chair',
        pl: 'Krzesło',
        jp: { word: 'いす' },
    },
    {
        type: 'noun',
        en: 'Key',
        pl: 'Klucz',
        jp: { word: 'かぎ' },
    },
    {
        type: 'noun',
        en: 'Car',
        pl: 'Samochód',
        jp: { word: 'くるま' },
    },
    {
        type: 'phrase',
        en: 'What is this?',
        pl: 'Co to jest?',
        jp: { word: 'これはなんですか。' },
    },
    {
        type: 'noun',
        en: 'Pen',
        pl: 'Długopis',
        jp: { word: 'ペン' },
    },
    {
        type: 'pronoun',
        en: 'This (close to me)',
        pl: 'To (blisko mnie)',
        jp: { word: 'これ' },
    },
    {
        type: 'pronoun',
        en: 'That (close to you)',
        pl: 'Tamto (blisko ciebie)',
        jp: { word: 'それ' },
    },
    {
        type: 'pronoun',
        en: 'That (far from us)',
        pl: 'Tamto (daleko od nas)',
        jp: { word: 'あれ' },
    },
    {
        type: 'noun',
        en: 'Headphones',
        pl: 'Słuchawki',
        jp: { word: 'ヘッドホン' },
    },
    {
        type: 'phrase',
        en: 'I know Japanese. I also know English.',
        pl: 'Znam japoński. Znam też angielski.',
        jp: { word: 'わたしはにほんごができます。わたしはえいごもできます。' },
        description: "Pay attention that 'も' is used after 'えいご', not after 'わたし'.",
    },
];
