import type { JapaneseWord } from '../../../types';

export const sakura_1_8_sports: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Basketball',
        pl: 'Koszykówka',
        jp: { word: 'バスケットボール' },
    },
    {
        type: 'noun',
        en: 'Baseball',
        pl: 'Baseball',
        jp: { word: 'やきゅう' },
    },
    {
        type: 'noun',
        en: 'Soccer',
        pl: 'Piłka nożna',
        jp: { word: 'サッカー' },
    },
    {
        type: 'noun',
        en: 'Volleyball',
        pl: 'Siatkówka',
        jp: { word: 'バレーボール' },
    },
    {
        type: 'noun',
        en: 'Golf',
        pl: 'Golf',
        jp: { word: 'ゴルフ' },
    },
    {
        type: 'noun',
        en: 'Skiing',
        pl: 'Narciarstwo',
        jp: { word: 'スキー' },
    },
    {
        type: 'noun',
        en: 'Figure Skating',
        pl: 'Łyżwiarstwo figurowe',
        jp: { word: 'フィギュアスケート' },
    },
    {
        type: 'noun',
        en: 'Snowboarding',
        pl: 'Snowboarding',
        jp: { word: 'スノーボード' },
    },
    {
        type: 'noun',
        en: 'Ice Hockey',
        pl: 'Hokej na lodzie',
        jp: { word: 'アイスホッケー' },
    },
    {
        type: 'noun',
        en: 'Skating (Ice)',
        pl: 'Łyżwiarstwo',
        jp: { word: 'スケート' },
    },
    {
        type: 'noun',
        en: 'Running',
        pl: 'Bieganie',
        jp: { word: 'ランニング' },
    },
    {
        type: 'noun',
        en: 'Badminton',
        pl: 'Badminton',
        jp: { word: 'バドミントン' },
    },
    {
        type: 'noun',
        en: 'Tennis',
        pl: 'Tenis',
        jp: { word: 'テニス' },
    },
    {
        type: 'noun',
        en: 'Table Tennis',
        pl: 'Tenis stołowy',
        jp: { word: 'たっきゅう' },
    },
    {
        type: 'noun',
        en: 'Swimming',
        pl: 'Pływanie',
        jp: { word: 'すいえい' },
    },
    {
        type: 'noun',
        en: 'Judo',
        pl: 'Judo',
        jp: { word: 'じゅうどう' },
    },
    {
        type: 'noun',
        en: 'Japanese archery',
        pl: 'Japońskie łucznictwo',
        jp: { word: 'きゅうどう' },
    },
    {
        type: 'noun',
        en: 'Kendo',
        pl: 'Kendo',
        jp: { word: 'けんどう' },
    },
    {
        type: 'noun',
        en: 'Karate',
        pl: 'Karate',
        jp: { word: 'からて' },
    },
    {
        type: 'noun',
        en: 'Boxing',
        pl: 'Boks',
        jp: { word: 'ボクシング' },
    },
    {
        type: 'noun',
        en: 'Canoeing',
        pl: 'Kajakarstwo',
        jp: { word: 'カヌー' },
    },
    {
        type: 'noun',
        en: 'Mountain Biking',
        pl: 'Kolarstwo górskie',
        jp: { word: 'マウンテンバイク' },
    },
    {
        type: 'noun',
        en: 'Gymnastics',
        pl: 'Gimnastyka',
        jp: { word: 'たいそう' },
    },
    {
        type: 'noun',
        en: 'Skateboarding',
        pl: 'Jazda na deskorolce',
        jp: { word: 'スケートボード' },
    },
    {
        type: 'noun',
        en: 'Horseback Riding',
        pl: 'Jeździectwo',
        jp: { word: 'じょうば' },
    },
];
