import type { JapaneseWord } from '../../../types';

export const sakura_8_sports: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Basketball',
        pl: 'Koszykówka',
        jp: 'バスケットボール',
    },
    {
        type: 'noun',
        en: 'Baseball',
        pl: 'Baseball',
        jp: 'やきゅう',
    },
    {
        type: 'noun',
        en: 'Soccer',
        pl: 'Piłka nożna',
        jp: 'サッカー',
    },
    {
        type: 'noun',
        en: 'Volleyball',
        pl: 'Siatkówka',
        jp: 'バレーボール',
    },
    {
        type: 'noun',
        en: 'Golf',
        pl: 'Golf',
        jp: 'ゴルフ',
    },
    {
        type: 'noun',
        en: 'Skiing',
        pl: 'Narciarstwo',
        jp: 'スキー',
    },
    {
        type: 'noun',
        en: 'Figure Skating',
        pl: 'Łyżwiarstwo figurowe',
        jp: 'フィギュアスケート',
    },
    {
        type: 'noun',
        en: 'Snowboarding',
        pl: 'Snowboarding',
        jp: 'スノーボード',
    },
    {
        type: 'noun',
        en: 'Ice Hockey',
        pl: 'Hokej na lodzie',
        jp: 'アイスホッケー',
    },
    {
        type: 'noun',
        en: 'Skating (Ice)',
        pl: 'Łyżwiarstwo',
        jp: 'スケート',
    },
    {
        type: 'noun',
        en: 'Running',
        pl: 'Bieganie',
        jp: 'ランニング',
    },
    {
        type: 'noun',
        en: 'Badminton',
        pl: 'Badminton',
        jp: 'バドミントン',
    },
    {
        type: 'noun',
        en: 'Tennis',
        pl: 'Tenis',
        jp: 'テニス',
    },
    {
        type: 'noun',
        en: 'Table Tennis',
        pl: 'Tenis stołowy',
        jp: 'たっきゅう',
    },
    {
        type: 'noun',
        en: 'Swimming',
        pl: 'Pływanie',
        jp: 'すいえい',
    },
    {
        type: 'noun',
        en: 'Judo',
        pl: 'Judo',
        jp: 'じゅうどう',
    },
    {
        type: 'noun',
        en: 'Japanese archery',
        pl: 'Japońskie łucznictwo',
        jp: 'きゅうどう',
    },
    {
        type: 'noun',
        en: 'Kendo',
        pl: 'Kendo',
        jp: 'けんどう',
    },
    {
        type: 'noun',
        en: 'Karate',
        pl: 'Karate',
        jp: 'からて',
    },
    {
        type: 'noun',
        en: 'Boxing',
        pl: 'Boks',
        jp: 'ボクシング',
    },
    {
        type: 'noun',
        en: 'Canoeing',
        pl: 'Kajakarstwo',
        jp: 'カヌー',
    },
    {
        type: 'noun',
        en: 'Mountain Biking',
        pl: 'Kolarstwo górskie',
        jp: 'マウンテンバイク',
    },
    {
        type: 'noun',
        en: 'Gymnastics',
        pl: 'Gimnastyka',
        jp: 'たいそう',
    },
    {
        type: 'noun',
        en: 'Skateboarding',
        pl: 'Jazda na deskorolce',
        jp: 'スケートボード',
    },
    {
        type: 'noun',
        en: 'Horseback Riding',
        pl: 'Jeździectwo',
        jp: 'じょうば',
    },
];
