import type { JapaneseWord } from '../../../types';

export const sakura_1_1: JapaneseWord[] = [
    {
        type: 'phrase',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: { word: 'おはようございます' },
    },
    {
        type: 'phrase',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: { word: 'こんにちは' },
    },
    {
        type: 'phrase',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: { word: 'こんばんは' },
    },
    {
        type: 'phrase',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: { word: 'おやすみ(なさい)' },
    },
    {
        type: 'phrase',
        en: 'Goodbye (forever)',
        pl: 'Żegnaj (na zawsze)',
        jp: { word: 'さようなら' },
    },
    {
        type: 'phrase',
        en: 'Goodbye (see you later)',
        pl: 'Do widzenia (do zobaczenia później)',
        jp: { word: 'じゃあね / またね' },
    },
    {
        type: 'phrase',
        en: 'Goodbye (business situation, person leaving)',
        pl: 'Do widzenia (sytuacja biznesowa, osoba odchodząca)',
        jp: { word: 'おさきにしつれいします' },
    },
    {
        type: 'phrase',
        en: 'Goodbye (business situation, person staying)',
        pl: 'Do widzenia (sytuacja biznesowa, osoba zostająca)',
        jp: { word: 'おつかれさまでした' },
        description: 'Literally means "you must be tired".',
    },
    {
        type: 'particle',
        en: 'No; No problem',
        pl: 'Nie; Nie ma problemu',
        jp: { word: 'いいえ' },
    },
    {
        type: 'phrase',
        en: 'Thank you',
        pl: 'Dziękuję',
        jp: { word: 'ありがとうございます' },
    },
    {
        type: 'phrase',
        en: "I'm sorry; Excuse me; Thank you (for your trouble)",
        pl: 'Przepraszam; Dziękuję (za kłopot)',
        jp: { word: 'すみません' },
    },
    {
        type: 'suffix',
        en: 'Mr./Ms.',
        pl: 'Pan/Pani',
        jp: { word: '...さん' },
    },
    {
        type: 'phrase',
        en: 'Present!',
        pl: 'Obecny!',
        jp: { word: 'います' },
    },
    {
        type: 'particle',
        en: 'Yes',
        pl: 'Tak',
        jp: { word: 'はい' },
    },
    {
        type: 'noun',
        en: 'Classroom',
        pl: 'Sala lekcyjna',
        jp: { word: 'きょうしつ' },
    },
    {
        type: 'phrase',
        en: 'Not present; Absent',
        pl: 'Nieobecny',
        jp: { word: 'いません' },
    },
    {
        type: 'phrase',
        en: 'Not yet',
        pl: 'Jeszcze nie',
        jp: { word: 'まだです' },
    },
    {
        type: 'phrase',
        en: 'Please listen',
        pl: 'Proszę słuchać',
        jp: { word: 'きいてください' },
    },
    {
        type: 'phrase',
        en: 'Please write',
        pl: 'Proszę pisać',
        jp: { word: 'かいてください' },
    },
    {
        type: 'phrase',
        en: 'Please read',
        pl: 'Proszę czytać',
        jp: { word: 'よんでください' },
    },
    {
        type: 'noun',
        en: 'Page',
        pl: 'Strona',
        jp: { word: 'ページ' },
    },
    {
        type: 'phrase',
        en: 'Please open the book at page 10.',
        pl: 'Proszę otworzyć książkę na stronie 10.',
        jp: { word: 'じゅうページをあけてください。' },
    },
    {
        type: 'verb',
        en: 'Open',
        pl: 'Otwierać',
        jp: { word: 'あける' },
        verb_type: 'ichidan',
        present: {
            masu: {
                affirmative: { word: 'あけます' },
                negative: { word: 'あけません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'Please speak',
        pl: 'Proszę mówić',
        jp: { word: 'いってください' },
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Say; Speak; Tell',
        pl: 'Mówić; Powiedzieć',
        jp: { word: 'いう' },
        present: {
            masu: {
                affirmative: { word: 'いいます' },
                negative: { word: 'いいません' },
            },
        },
    },
    {
        type: 'phrase',
        en: 'Please look',
        pl: 'Proszę patrzeć',
        jp: { word: 'みてください' },
    },
    {
        type: 'phrase',
        en: 'Please talk in pairs.',
        pl: 'Proszę rozmawiać w parach.',
        jp: { word: 'ペアではなしてください。' },
    },
    {
        type: 'phrase',
        en: 'I understood',
        pl: 'Zrozumiałem',
        jp: { word: 'わかりました' },
    },
    {
        type: 'phrase',
        en: "I don't understand",
        pl: 'Nie rozumiem',
        jp: { word: 'わかりません' },
    },
    {
        type: 'phrase',
        en: "It's easy",
        pl: 'To jest łatwe',
        jp: { word: 'かんたんです' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Easy',
        pl: 'Łatwy',
        jp: { word: 'かんたん' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Difficult',
        pl: 'Trudny',
        jp: { word: 'むずかしい' },
    },
    {
        type: 'phrase',
        en: "It's difficult",
        pl: 'To jest trudne',
        jp: { word: 'むずかしいです' },
    },
    {
        type: 'phrase',
        en: "It's ok",
        pl: 'W porządku',
        jp: { word: 'だいじょうぶです' },
    },
    {
        type: 'phrase',
        en: 'Good job!',
        pl: 'Dobra robota!',
        jp: { word: 'じょうずです' },
    },
    {
        type: 'phrase',
        en: "It's homework",
        pl: 'To jest praca domowa',
        jp: { word: 'しゅくだいです' },
    },
    {
        type: 'phrase',
        en: 'Almost, but not correct',
        pl: 'Prawie, ale niepoprawne',
        jp: { word: 'おしいです' },
    },
    {
        type: 'phrase',
        en: "It's not correct",
        pl: 'To nie jest poprawne',
        jp: { word: 'ちがいます' },
    },
    {
        type: 'phrase',
        en: 'Please one more time',
        pl: 'Proszę jeszcze raz',
        jp: { word: 'もういちどおねがいします' },
    },
    {
        type: 'phrase',
        en: 'I have a question',
        pl: 'Mam pytanie',
        jp: { word: 'しつもんがあります' },
    },
    {
        type: 'phrase',
        en: "What does '... ' mean?",
        pl: "Co znaczy '... '?",
        jp: { word: '...はなんですか？' },
    },
    {
        type: 'phrase',
        en: 'Please speak slowly.',
        pl: 'Proszę mówić wolno.',
        jp: { word: 'ゆっくりおねがいします。' },
    },
    {
        type: 'phrase',
        en: 'Please be careful',
        pl: 'Proszę uważać',
        jp: { word: 'きをつけてください' },
    },
    {
        type: 'phrase',
        en: "I don't have questions.",
        pl: 'Nie mam pytań.',
        jp: { word: 'しつもんはありません。' },
    },
    {
        type: 'noun',
        en: 'Student (general)',
        pl: 'Uczeń (ogólnie)',
        jp: { word: 'がくせい' },
    },
    {
        type: 'noun',
        en: 'Student (6-12 years old)',
        pl: 'Uczeń (6-12 lat)',
        jp: { word: 'しょうがくせい' },
    },
    {
        type: 'noun',
        en: 'Student (12-15 years old)',
        pl: 'Uczeń (12-15 lat)',
        jp: { word: 'ちゅうがくせい' },
    },
    {
        type: 'noun',
        en: 'Student (15-18 years old)',
        pl: 'Uczeń (15-18 lat)',
        jp: { word: 'こうこうせい' },
    },
    {
        type: 'noun',
        en: 'University student (18-22 years old)',
        pl: 'Student (18-22 lata)',
        jp: { word: 'だいがくせい' },
    },
    {
        type: 'phrase',
        en: 'Nice to meet you (said at the beginning)',
        pl: 'Miło mi cię poznać (powiedziane na początku)',
        jp: { word: 'はじめまして' },
    },
    {
        type: 'phrase',
        en: 'Nice to meet you (said at the end)',
        pl: 'Miło mi cię poznać (powiedziane na końcu)',
        jp: { word: 'どうぞよろしく' },
    },
    {
        type: 'phrase',
        en: 'Is (casual)',
        pl: 'Jest (nieformalnie)',
        jp: { word: 'だよ' },
    },
    {
        type: 'noun',
        en: 'Teacher (humble)',
        pl: 'Nauczyciel (skromnie)',
        jp: { word: 'きょうし' },
    },
    {
        type: 'noun',
        en: 'Teacher (polite)',
        pl: 'Nauczyciel (grzecznie)',
        jp: { word: 'せんせい' },
    },
    {
        type: 'noun',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: { word: 'かいしゃいん' },
    },
    {
        type: 'noun',
        en: 'Housewife / Househusband',
        pl: 'Gospodyni domowa / Gospodarz domowy',
        jp: { word: 'しゅふ' },
    },
    {
        type: 'noun',
        en: 'Government worker',
        pl: 'Urzędnik państwowy',
        jp: { word: 'こうむいん' },
    },
    {
        type: 'noun',
        en: 'Engineer',
        pl: 'Inżynier',
        jp: { word: 'エンジニア' },
    },
    {
        type: 'phrase',
        en: "What's your name?",
        pl: 'Jak masz na imię?',
        jp: { word: 'おなまえは？' },
    },
];
