import type { JapaneseWord } from '../../../types';

export const sakura_1_2: JapaneseWord[] = [
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Red',
        pl: 'Czerwony',
        jp: { word: 'あかい' },
    },
    {
        type: 'noun',
        en: 'Train station',
        pl: 'Dworzec kolejowy',
        jp: { word: 'えき' },
    },
    {
        type: 'noun',
        en: 'Up / Above',
        pl: 'Nad / Na górze',
        jp: { word: 'うえ' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Blue',
        pl: 'Niebieski',
        jp: { word: 'あおい' },
    },
    {
        type: 'adverb',
        en: 'Here',
        pl: 'Tutaj',
        jp: { word: 'ここ' },
    },
    {
        type: 'noun',
        en: 'Umbrella',
        pl: 'Parasol',
        jp: { word: 'かさ' },
    },
    {
        type: 'noun',
        en: 'Sweets / Candy',
        pl: 'Słodycze / Cukierki',
        jp: { word: 'おかし' },
    },
    {
        type: 'noun',
        en: 'Chair',
        pl: 'Krzesło',
        jp: { word: 'いす' },
    },
    {
        type: 'noun',
        en: 'Leg / Foot',
        pl: 'Noga / Stopa',
        jp: { word: 'あし' },
    },
    {
        type: 'noun',
        en: 'Home',
        pl: 'Dom (miejsce zamieszkania)',
        jp: { word: 'うち' },
    },
    {
        type: 'noun',
        en: 'Hand',
        pl: 'Ręka',
        jp: { word: 'て' },
    },
    {
        type: 'noun',
        en: 'Physical Education',
        pl: 'Wychowanie fizyczne',
        jp: { word: 'たいいく' },
    },
    {
        type: 'noun',
        en: 'Japan',
        pl: 'Japonia',
        jp: { word: 'にほん' },
    },
    {
        type: 'noun',
        en: 'Germany',
        pl: 'Niemcy',
        jp: { word: 'ドイツ' },
    },
    {
        type: 'noun',
        en: 'China',
        pl: 'Chiny',
        jp: { word: 'ちゅうごく' },
    },
    {
        type: 'noun',
        en: 'Egypt',
        pl: 'Egipt',
        jp: { word: 'エジプト' },
    },
    {
        type: 'noun',
        en: 'South Korea',
        pl: 'Korea Południowa',
        jp: { word: 'かんこく' },
    },
    {
        type: 'noun',
        en: 'Australia',
        pl: 'Australia',
        jp: { word: 'オーストラリア' },
    },
    {
        type: 'suffix',
        en: 'Language',
        pl: 'Język',
        jp: { word: 'ご' },
    },
    {
        type: 'noun',
        en: 'English',
        pl: 'Angielski',
        jp: { word: 'えいご' },
    },
    {
        type: 'noun',
        en: 'Spanish',
        pl: 'Hiszpański',
        jp: { word: 'スペインご' },
    },
    {
        type: 'noun',
        en: 'Arabic',
        pl: 'Arabski',
        jp: { word: 'アラビアご' },
    },
    {
        type: 'noun',
        en: 'Country',
        pl: 'Kraj',
        jp: { word: 'くに' },
    },
    {
        type: 'noun',
        en: 'Hindu',
        pl: 'Hindi',
        jp: { word: 'ヒンディーご' },
    },
    {
        type: 'phrase',
        en: 'What is your country?',
        pl: 'Jaki jest twój kraj?',
        jp: { word: 'おくには。' },
    },
    {
        type: 'phrase',
        en: 'What languages do you know?',
        pl: 'Jakimi językami potrafisz mówić?',
        jp: { word: 'なにごができますか。' },
    },
    {
        type: 'phrase',
        en: 'What is your nationality?',
        pl: 'Jakiej jesteś narodowości?',
        jp: { word: 'なにじんですか。' },
    },
    {
        type: 'phrase',
        en: 'I speak Japanese and English.',
        pl: 'Mówię po japońsku i angielsku.',
        jp: { word: 'にほんごとえいごができます。' },
    },
    {
        type: 'phrase',
        en: "I can't speak Chinese.",
        pl: 'Nie potrafię mówić po chińsku.',
        jp: { word: 'ちゅうごくごはできません。' },
    },
    {
        type: 'phrase',
        en: 'Where are you from?',
        pl: 'Skąd jesteś?',
        jp: { word: 'どちらからきましたか。' },
    },
    {
        type: 'phrase',
        en: 'I am from Poland.',
        pl: 'Jestem z Polski.',
        jp: { word: 'ポーランドからきました。' },
    },
    {
        type: 'phrase',
        en: 'While studying',
        pl: 'Uczę się',
        jp: { word: 'べんきょうちゅう' },
    },
    {
        type: 'phrase',
        en: "I'm learning Japanese.",
        pl: 'Uczę się japońskiego.',
        jp: { word: 'にほんごをべんきょうちゅうです。' },
    },
    {
        type: 'verb',
        verb_type: 'irregular',
        en: 'Come (from)',
        pl: 'Pochodzić (z)',
        jp: { word: 'きます' },
        present: {
            masu: {
                affirmative: { word: 'きます' },
                negative: { word: 'きません' },
            },
        },
    },
    {
        type: 'suffix',
        en: 'Citizen',
        pl: 'Obywatel',
        jp: { word: 'じん' },
    },
    {
        type: 'noun',
        en: 'Poland',
        pl: 'Polska',
        jp: { word: 'ポーランド' },
    },
    {
        type: 'noun',
        en: 'Great Britain',
        pl: 'Wielka Brytania',
        jp: { word: 'イギリス' },
    },
    {
        type: 'noun',
        en: 'France',
        pl: 'Francja',
        jp: { word: 'フランス' },
    },
    {
        type: 'noun',
        en: 'Russia',
        pl: 'Rosja',
        jp: { word: 'ロシア' },
    },
    {
        type: 'noun',
        en: 'Ukraine',
        pl: 'Ukraina',
        jp: { word: 'ウクライナ' },
    },
    {
        type: 'noun',
        en: 'Spain',
        pl: 'Hiszpania',
        jp: { word: 'スペイン' },
    },
    {
        type: 'noun',
        en: 'Portugal',
        pl: 'Portugalia',
        jp: { word: 'ポルトガル' },
    },
    {
        type: 'noun',
        en: 'India',
        pl: 'Indie',
        jp: { word: 'インド' },
    },
    {
        type: 'noun',
        en: 'USA',
        pl: 'USA',
        jp: { word: 'アメリカ' },
    },
    {
        type: 'noun',
        en: 'Canada',
        pl: 'Kanada',
        jp: { word: 'カナダ' },
    },
    {
        type: 'noun',
        en: 'New Zealand',
        pl: 'Nowa Zelandia',
        jp: { word: 'ニュージーランド' },
    },
    {
        type: 'noun',
        en: 'Brazil',
        pl: 'Brazylia',
        jp: { word: 'ブラジル' },
    },
    {
        type: 'noun',
        en: 'Mexico',
        pl: 'Meksyk',
        jp: { word: 'メキシコ' },
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Can',
        pl: 'Potrafić',
        jp: { word: 'できる' },
        present: {
            masu: {
                affirmative: { word: 'できます' },
                negative: { word: 'できません' },
            },
        },
    },
    {
        type: 'adverb',
        en: 'A little',
        pl: 'Trochę',
        jp: { word: 'すこし / ちょっと' },
    },
    {
        type: 'phrase',
        en: 'Not enough',
        pl: 'Niewystarczająco',
        jp: { word: 'まだまだです。' },
    },
    {
        type: 'adverb',
        en: 'Very',
        pl: 'Bardzo',
        jp: { word: 'とても' },
    },
];
