import type { JapaneseWord } from '../../../types';

export const sakura_1_9: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'To have / To exist (inanimate)',
        pl: 'Mieć / Istnieć (nieożywione)',
        jp: 'あります',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'To have / To exist / There is (animate)',
        pl: 'Mieć / Istnieć / Być (ożywione)',
        jp: 'いる',
        masu_form: 'います',
        masen_form: 'いません',
    },
    {
        type: 'unknown',
        en: 'Young',
        pl: 'Młody',
        jp: 'わかい',
    },
    {
        type: 'unknown',
        en: 'Close',
        pl: 'Blisko',
        jp: 'ちかい',
    },
    {
        type: 'unknown',
        en: 'Tokyo is close to Kamakura.',
        pl: 'Tokio jest blisko Kamakury.',
        jp: 'とうきょうはかまくらにちかいです。',
    },
    {
        type: 'unknown',
        en: 'Homework',
        pl: 'Praca domowa',
        jp: 'しゅくだい',
    },
    {
        type: 'unknown',
        en: 'Dictionary',
        pl: 'Słownik',
        jp: 'じしょ',
    },
    {
        type: 'unknown',
        en: '300',
        pl: '300',
        jp: 'さんびゃく',
    },
    {
        type: 'unknown',
        en: '600',
        pl: '600',
        jp: 'ろっぴゃく',
    },
    {
        type: 'unknown',
        en: '100',
        pl: '100',
        jp: 'ひゃく',
    },
    {
        type: 'unknown',
        en: 'Art',
        pl: 'Sztuka',
        jp: 'びじゅつ',
    },
    {
        type: 'unknown',
        en: 'Train',
        pl: 'Pociąg',
        jp: 'でんしゃ',
    },
    {
        type: 'unknown',
        en: 'Every day',
        pl: 'Codziennie',
        jp: 'まいにち',
    },
    {
        type: 'unknown',
        en: 'Always',
        pl: 'Zawsze',
        jp: 'いつも',
    },
    {
        type: 'unknown',
        en: 'Often',
        pl: 'Często',
        jp: 'よく',
    },
    {
        type: 'unknown',
        en: 'Sometimes',
        pl: 'Czasami',
        jp: 'ときどき',
    },
    {
        type: 'unknown',
        en: 'Rarely',
        pl: 'Rzadko',
        jp: 'あまり',
    },
    {
        type: 'unknown',
        en: 'Never',
        pl: 'Nigdy',
        jp: 'ぜんぜん',
    },
    {
        type: 'unknown',
        en: 'I rarely eat ramen.',
        pl: 'Rzadko jem ramen.',
        jp: 'あまりラーメンはたべません。',
    },
    {
        type: 'unknown',
        en: 'To watch',
        pl: 'Oglądać',
        jp: 'みます',
    },
    {
        type: 'unknown',
        en: 'To not watch',
        pl: 'Nie oglądać',
        jp: 'みません',
    },
    {
        type: 'unknown',
        en: 'Movie',
        pl: 'Film',
        jp: 'えいが',
    },
    {
        type: 'unknown',
        en: 'Photo',
        pl: 'Zdjęcie',
        jp: 'しゃしん',
    },
    {
        type: 'unknown',
        en: 'TV',
        pl: 'Telewizor',
        jp: 'テレビ',
    },
    {
        type: 'unknown',
        en: 'YouTube',
        pl: 'YouTube',
        jp: 'ユーチューブ',
    },
    {
        type: 'unknown',
        en: 'I often watch movies.',
        pl: 'Często oglądam filmy.',
        jp: 'よくえいがをみます。',
    },
    {
        type: 'unknown',
        en: 'I never watch TV.',
        pl: 'Nigdy nie oglądam telewizji.',
        jp: 'ぜんぜんテレビはみません。',
    },
    {
        type: 'unknown',
        en: 'What do you watch?',
        pl: 'Co oglądasz?',
        jp: 'なにをみますか',
    },
];
