import type { JapaneseWord } from '../../../types';

export const sakura_1_1: JapaneseWord[] = [
    {
        type: 'unknown',
        en: 'Good morning',
        pl: 'Dzień dobry (rano)',
        jp: 'おはようございます',
    },
    {
        type: 'unknown',
        en: 'Good afternoon',
        pl: 'Dzień dobry (po południu)',
        jp: 'こんにちは',
    },
    {
        type: 'unknown',
        en: 'Good evening',
        pl: 'Dobry wieczór',
        jp: 'こんばんは',
    },
    {
        type: 'unknown',
        en: 'Good night',
        pl: 'Dobranoc',
        jp: 'おやすみ(なさい)',
    },
    {
        type: 'unknown',
        en: 'Goodbye (forever)',
        pl: 'Żegnaj (na zawsze)',
        jp: 'さようなら',
    },
    {
        type: 'unknown',
        en: 'Goodbye (see you later)',
        pl: 'Do widzenia (do zobaczenia później)',
        jp: 'じゃあね / またね',
    },
    {
        type: 'unknown',
        en: 'Goodbye (business situation, person leaving)',
        pl: 'Do widzenia (sytuacja biznesowa, osoba odchodząca)',
        jp: 'おさきにしつれいします',
    },
    {
        type: 'unknown',
        en: 'Goodbye (business situation, person staying)',
        pl: 'Do widzenia (sytuacja biznesowa, osoba zostająca)',
        jp: 'おつかれさまでした',
        jp_description: "Literally means 'you must be tired' xd",
    },
    {
        type: 'unknown',
        en: 'No; No problem',
        pl: 'Nie; Nie ma problemu',
        jp: 'いいえ',
    },
    {
        type: 'unknown',
        en: 'Thank you',
        pl: 'Dziękuję',
        jp: 'ありがとうございます',
    },
    {
        type: 'unknown',
        en: "I'm sorry; Excuse me; Thank you (for your trouble)",
        pl: 'Przepraszam; Dziękuję (za kłopot)',
        jp: 'すみません',
    },
    {
        type: 'unknown',
        en: 'Mr./Ms.',
        pl: 'Pan/Pani',
        jp: '...さん',
    },
    {
        type: 'unknown',
        en: 'Present!',
        pl: 'Obecny!',
        jp: 'います',
    },
    {
        type: 'unknown',
        en: 'Yes',
        pl: 'Tak',
        jp: 'はい',
    },
    {
        type: 'unknown',
        en: 'Classroom',
        pl: 'Sala lekcyjna',
        jp: 'きょうしつ',
    },
    {
        type: 'unknown',
        en: 'Not present; Absent',
        pl: 'Nieobecny',
        jp: 'いません',
    },
    {
        type: 'unknown',
        en: 'Not yet',
        pl: 'Jeszcze nie',
        jp: 'まだです',
    },
    {
        type: 'unknown',
        en: 'Please listen',
        pl: 'Proszę słuchać',
        jp: 'きいてください',
    },
    {
        type: 'unknown',
        en: 'Please write',
        pl: 'Proszę pisać',
        jp: 'かいてください',
    },
    {
        type: 'unknown',
        en: 'Please read',
        pl: 'Proszę czytać',
        jp: 'よんでください',
    },
    {
        type: 'unknown',
        en: 'Page',
        pl: 'Strona',
        jp: 'ページ',
    },
    {
        type: 'unknown',
        en: 'Please open (the book)',
        pl: 'Proszę otworzyć (książkę)',
        jp: 'あけてください',
    },
    {
        type: 'unknown',
        en: 'Please speak',
        pl: 'Proszę mówić',
        jp: 'いってください',
    },
    {
        type: 'unknown',
        en: 'Please look',
        pl: 'Proszę patrzeć',
        jp: 'みてください',
    },
    {
        type: 'unknown',
        en: 'Please talk in pairs',
        pl: 'Proszę rozmawiać w parach',
        jp: 'ペアではなしてください',
    },
    {
        type: 'unknown',
        en: 'I understood',
        pl: 'Zrozumiałem',
        jp: 'わかりました',
    },
    {
        type: 'unknown',
        en: "I don't understand",
        pl: 'Nie rozumiem',
        jp: 'わかりません',
    },
    {
        type: 'unknown',
        en: "It's easy",
        pl: 'To jest łatwe',
        jp: 'かんたんです',
    },
    {
        type: 'unknown',
        en: "It's difficult",
        pl: 'To jest trudne',
        jp: 'むずかしいです',
    },
    {
        type: 'unknown',
        en: "It's ok",
        pl: 'W porządku',
        jp: 'だいじょうぶです',
    },
    {
        type: 'unknown',
        en: 'Good job!',
        pl: 'Dobra robota!',
        jp: 'じょうずです',
    },
    {
        type: 'unknown',
        en: "It's homework",
        pl: 'To jest praca domowa',
        jp: 'しゅくだいです',
    },
    {
        type: 'unknown',
        en: 'Almost, but not correct',
        pl: 'Prawie, ale niepoprawne',
        jp: 'おしいです',
    },
    {
        type: 'unknown',
        en: "It's not correct",
        pl: 'To nie jest poprawne',
        jp: 'ちがいます',
    },
    {
        type: 'unknown',
        en: 'Please one more time',
        pl: 'Proszę jeszcze raz',
        jp: 'もういちどおねがいします',
    },
    {
        type: 'unknown',
        en: 'I have a question',
        pl: 'Mam pytanie',
        jp: 'しつもんがあります',
    },
    {
        type: 'unknown',
        en: "What does '... ' mean?",
        pl: "Co znaczy '... '?",
        jp: '...はなんですか？',
    },
    {
        type: 'unknown',
        en: 'Please speak slowly',
        pl: 'Proszę mówić wolno',
        jp: 'ゆっくりおねがいします',
    },
    {
        type: 'unknown',
        en: 'Please be careful',
        pl: 'Proszę uważać',
        jp: 'きをつけてください',
    },
    {
        type: 'unknown',
        en: "I don't have a question",
        pl: 'Nie mam pytania',
        jp: 'しつもんはありません',
    },
    {
        type: 'unknown',
        en: 'Student (general)',
        pl: 'Uczeń (ogólnie)',
        jp: 'がくせい',
    },
    {
        type: 'unknown',
        en: 'Student (6-12 years old)',
        pl: 'Uczeń (6-12 lat)',
        jp: 'しょうがくせい',
    },
    {
        type: 'unknown',
        en: 'Student (12-15 years old)',
        pl: 'Uczeń (12-15 lat)',
        jp: 'ちゅうがくせい',
    },
    {
        type: 'unknown',
        en: 'Student (15-18 years old)',
        pl: 'Uczeń (15-18 lat)',
        jp: 'こうこうせい',
    },
    {
        type: 'unknown',
        en: 'University student (18-22 years old)',
        pl: 'Student (18-22 lata)',
        jp: 'だいがくせい',
    },
    {
        type: 'unknown',
        en: 'Nice to meet you (said at the beginning)',
        pl: 'Miło mi cię poznać (powiedziane na początku)',
        jp: 'はじめまして',
    },
    {
        type: 'unknown',
        en: 'Nice to meet you (said at the end)',
        pl: 'Miło mi cię poznać (powiedziane na końcu)',
        jp: 'どうぞよろしく',
    },
    {
        type: 'unknown',
        en: 'Is (casual)',
        pl: 'Jest (nieformalnie)',
        jp: 'だよ',
    },
    {
        type: 'unknown',
        en: 'Teacher (humble)',
        pl: 'Nauczyciel (skromnie)',
        jp: 'きょうし',
    },
    {
        type: 'unknown',
        en: 'Teacher (polite)',
        pl: 'Nauczyciel (grzecznie)',
        jp: 'せんせい',
    },
    {
        type: 'unknown',
        en: 'Company employee',
        pl: 'Pracownik firmy',
        jp: 'かいしゃいん',
    },
    {
        type: 'unknown',
        en: 'Housewife / Househusband',
        pl: 'Gospodyni domowa / Gospodarz domowy',
        jp: 'しゅふ',
    },
    {
        type: 'unknown',
        en: 'Government worker',
        pl: 'Urzędnik państwowy',
        jp: 'こうむいん',
    },
    {
        type: 'unknown',
        en: 'Engineer',
        pl: 'Inżynier',
        jp: 'エンジニア',
    },
    {
        type: 'unknown',
        en: "What's your name?",
        pl: 'Jak masz na imię?',
        jp: 'おなまえは？',
    },
];
