import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_1_11: TranslatedJapaneseText[] = [
    {
        id: '48a7e933-8509-4b1f-a385-573d39af5ad2',
        type: 'pronoun',
        en: 'You (polite)',
        pl: 'Ty (formalnie)',
        jp: { text: 'あなた' },
    },
    {
        id: '5009f5e4-e37d-40fd-87dd-7438ada4616b',
        type: 'pronoun',
        en: 'You (casual)',
        pl: 'Ty (potocznie)',
        jp: { text: '君', pronunciation: 'きみ' },
    },
    {
        id: 'db6b7b82-d9db-436c-af0d-34b80bee7483',
        type: 'noun',
        en: 'Hospital',
        pl: 'Szpital',
        jp: { text: '病院', pronunciation: 'びょういん' },
    },
    {
        id: '1ef43304-4e0c-4a16-8cec-34b0ef27300c',
        type: 'noun',
        en: 'New year',
        pl: 'Nowy rok',
        jp: { text: 'お正月', pronunciation: 'おしょうがつ' },
    },
    {
        id: '15f279c4-b4a3-4d15-aee9-a7efc127be29',
        type: 'noun',
        en: 'Birthday',
        pl: 'Urodziny',
        jp: { text: '誕生日', pronunciation: 'たんじょうび' },
    },
    {
        id: '72e3c36d-afb8-47c0-9cd8-2f832f9cf6b0',
        type: 'noun',
        en: 'Time',
        pl: 'Czas',
        jp: { text: '時間', pronunciation: 'じかん' },
    },
    {
        id: 'c1f38197-0613-4283-90b8-1715f370631c',
        type: 'noun',
        en: 'Now',
        pl: 'Teraz',
        jp: { text: '今', pronunciation: 'いま' },
    },
    {
        id: '648feed7-45f9-4e0a-b163-8b665f4e6b70',
        type: 'phrase',
        en: 'What time is it now?',
        pl: 'Która jest teraz godzina?',
        jp: { text: '今何時ですか。', pronunciation: 'いまなんじですか。' },
    },
    {
        id: 'addaa2a4-3292-4973-91c3-7735dea5ead0',
        type: 'noun',
        en: 'AM',
        pl: 'Przed południem',
        jp: { text: '午前', pronunciation: 'ごぜん' },
    },
    {
        id: '8b60dd68-f46e-4af8-a39a-ceb93a05fdcc',
        type: 'noun',
        en: 'PM',
        pl: 'Po południu',
        jp: { text: '午後', pronunciation: 'ごご' },
    },
    {
        id: 'e521a724-5326-48ec-864e-f86ffca729dc',
        type: 'noun',
        en: 'Morning',
        pl: 'Rano',
        jp: { text: '朝', pronunciation: 'あさ' },
    },
    {
        id: 'ad79dfc8-6a85-425a-b1e8-910413d68a1f',
        type: 'noun',
        en: 'Noon',
        pl: 'Południe',
        jp: { text: '昼', pronunciation: 'ひる' },
    },
    {
        id: 'a4033493-09f2-4019-9573-4154699e796a',
        type: 'noun',
        en: 'Night',
        pl: 'Noc',
        jp: { text: '夜', pronunciation: 'よる' },
    },
    {
        id: '27bc6e37-6275-48be-89c4-a8243ff97283',
        type: 'suffix',
        en: 'Around (time)',
        pl: 'Około (godziny)',
        jp: { text: 'ごろ' },
    },
    {
        id: '74cbb749-77f0-4495-9bbe-f8ff5e31c49d',
        type: 'verb',
        verb_type: 'suru',
        en: 'Work',
        pl: 'Pracować',
        jp: { text: '仕事をする', pronunciation: 'しごとをする' },
    },
    {
        id: '72af981b-b14e-4d2a-a709-f236ba25d727',
        type: 'verb',
        verb_type: 'godan',
        en: 'Go back',
        pl: 'Wracać',
        jp: { text: '帰る', pronunciation: 'かえる' },
    },
    {
        id: '4cce8062-b0b7-40bf-a43d-80d8cbc254d0',
        type: 'phrase',
        en: 'Go back home',
        pl: 'Wracać do domu',
        jp: { text: '家に帰る', pronunciation: 'うちにかえる' },
    },
    {
        id: 'ade02651-5b27-47fb-a7fe-e8241f4cfa0c',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Wake up',
        pl: 'Budzić się',
        jp: { text: '起きる', pronunciation: 'おきる' },
    },
    {
        id: 'eab568eb-2e35-4bae-9156-d34d0d327a9b',
        type: 'verb',
        verb_type: 'godan',
        en: 'Go',
        pl: 'Iść',
        jp: { text: '行く', pronunciation: 'いく' },
        te_form: { text: '行って', pronunciation: 'いって' },
    },
    {
        id: 'eca04828-7566-41bf-8d0c-d2836cb96861',
        type: 'phrase',
        en: 'Go to work',
        pl: 'Iść do pracy',
        jp: { text: '会社に行く', pronunciation: 'かいしゃにいく' },
    },
    {
        id: 'e70a9824-206b-44f5-9986-14b5520005c3',
        type: 'phrase',
        en: "It's 7 AM now.",
        pl: 'Jest teraz siódma rano.',
        jp: { text: '今午前七時です。', pronunciation: 'いまごぜんしちじです。' },
    },
    {
        id: '80075e5d-2b40-4222-a94b-e743593601e5',
        type: 'phrase',
        en: 'When do you take a shower?',
        pl: 'O której bierzesz prysznic?',
        jp: { text: '何時にシャワーを浴びますか。', pronunciation: 'なんじにシャワーをあびますか。' },
    },
    {
        id: '8a79f760-64ae-4bcb-9b7f-8026882dcc50',
        type: 'phrase',
        en: 'What time is it now in Tokyo?',
        pl: 'Która jest teraz godzina w Tokio?',
        jp: { text: '東京は今何時ですか。', pronunciation: 'とうきょうはいまなんじですか。' },
    },
    {
        id: 'fcea0f1b-df4f-47dd-9821-82e4a8185f75',
        type: 'noun',
        en: 'Diary',
        pl: 'Pamiętnik',
        jp: { text: '日記', pronunciation: 'にっき' },
    },
    {
        id: '51b69cd6-8640-4015-81d3-af9648cdb121',
        type: 'noun',
        en: 'Blog',
        pl: 'Blog',
        jp: { text: 'ブログ' },
    },
    {
        id: 'b2bc4f0b-38fb-4ea8-b36e-2a45d9664a0e',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Take (a shower)',
        pl: 'Brać (prysznic)',
        jp: { text: '浴びる', pronunciation: 'あびる' },
    },
    {
        id: '2371060a-533d-4670-9c8f-086b3656f1cc',
        type: 'phrase',
        en: 'Take a shower',
        pl: 'Brać prysznic',
        jp: { text: 'シャワーを浴びる', pronunciation: 'シャワーをあびる' },
    },
    {
        id: 'da42627e-f0cb-419e-adf1-5b1b5b354b1a',
        type: 'phrase',
        en: 'Take a bath',
        pl: 'Brać kąpiel',
        jp: { text: 'お風呂に入る', pronunciation: 'おふろにはいる' },
    },
    {
        id: 'c940aafe-e13a-4152-bdef-9c379a0089a9',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Sleep',
        pl: 'Spać',
        jp: { text: '寝る', pronunciation: 'ねる' },
    },
    {
        id: '8a90df30-c87d-41d3-b7a5-6fa29989956c',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Busy',
        pl: 'Zajęty',
        jp: { text: '忙しい', pronunciation: 'いそがしい' },
    },
    {
        id: 'd46f9dc9-e415-4e5a-8d97-e8e111ad2d06',
        type: 'phrase',
        en: 'I am busy.',
        pl: 'Jestem zajęty.',
        jp: { text: '忙しいです。', pronunciation: 'いそがしいです。' },
    },
    {
        id: 'd028fcb3-b057-4536-b01d-ec1cfbd8bad4',
        type: 'verb',
        verb_type: 'suru',
        en: 'Work out',
        pl: 'Ćwiczyć',
        jp: { text: '運動をする', pronunciation: 'うんどうをする' },
    },
    {
        id: '033add82-10e7-42f0-8aaa-758cbc614c4d',
        type: 'verb',
        verb_type: 'suru',
        en: 'Do housework',
        pl: 'Robić prace domowe',
        jp: { text: '家事をする', pronunciation: 'かじをする' },
    },
    {
        id: '27284dd5-718d-42a4-8b3d-d4360b0a1a5e',
        type: 'phrase',
        en: 'Read newspaper at home',
        pl: 'Czytać gazetę w domu',
        jp: { text: '家で新聞を読む', pronunciation: 'うちでしんぶんをよむ' },
    },
    {
        id: '7c404965-7cd1-4dff-b359-0fc5b1c85c61',
        type: 'phrase',
        en: 'Go to work by train',
        pl: 'Jechać do pracy pociągiem',
        jp: { text: '電車で会社に行く', pronunciation: 'でんしゃでかいしゃにいく' },
    },
    {
        id: '0afae062-3839-43c6-b1b5-3f84a79dfb6a',
        type: 'verb',
        verb_type: 'suru',
        en: 'Take a walk',
        pl: 'Spacerować',
        jp: { text: '散歩をする', pronunciation: 'さんぽをする' },
    },
    {
        id: '90489f62-d0ea-47a9-b76f-5712fc276318',
        type: 'verb',
        verb_type: 'godan',
        en: 'Enter',
        pl: 'Wchodzić',
        jp: { text: '入る', pronunciation: 'はいる' },
    },
    {
        id: '4ac0a847-da22-41d5-9b26-c88370508d59',
        type: 'phrase',
        en: 'Enter the school',
        pl: 'Wchodzić do szkoły',
        jp: { text: '学校に入る', pronunciation: 'がっこうにはいる' },
    },
];

export const sakura1_11Bag: WordBag = {
    id: 'b10b4340-1df6-42c3-a1be-633b109fd6a0',
    name: 'Sakura #1.11',
    category: 'sakura',
    words: sakura_1_11,
};
