import type { JapaneseWord } from '../../../types';

export const sakura_1_3: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Meat',
        pl: 'Mięso',
        jp: 'にく',
    },
    {
        type: 'noun',
        en: 'Fish',
        pl: 'Ryba',
        jp: 'さかな',
    },
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: 'いぬ',
    },
    {
        type: 'noun',
        en: 'Cat',
        pl: 'Kot',
        jp: 'ねこ',
    },
    {
        type: 'noun',
        en: 'Chopsticks',
        pl: 'Pałeczki do jedzenia',
        jp: 'はし',
    },
    {
        type: 'noun',
        en: 'Ship',
        pl: 'Statek',
        jp: 'ふね',
    },
    {
        type: 'noun',
        en: 'Person',
        pl: 'Osoba',
        jp: 'ひと',
    },
    {
        type: 'noun',
        en: 'Flower',
        pl: 'Kwiat',
        jp: 'はな',
    },
    {
        type: 'conjunction',
        en: 'And',
        pl: 'I / Oraz',
        jp: 'と',
    },
    {
        type: 'particle',
        en: 'Also',
        pl: 'Też / Również',
        jp: 'も',
    },
    {
        type: 'noun',
        en: 'Profession / Job',
        pl: 'Zawód',
        jp: 'しごと',
    },
    {
        type: 'phrase',
        en: "What's your job?",
        pl: 'Jaki jest twój zawód?',
        jp: 'おしごとは。',
    },
    {
        type: 'noun',
        en: 'Notebook',
        pl: 'Notatnik',
        jp: 'ノート',
    },
    {
        type: 'noun',
        en: 'Book',
        pl: 'Książka',
        jp: '本',
        jp_pronunciation: 'ほん',
    },
    {
        type: 'noun',
        en: 'Newspaper',
        pl: 'Gazeta',
        jp: 'しんぶん',
    },
    {
        type: 'noun',
        en: 'Clock',
        pl: 'Zegar',
        jp: 'とけい',
    },
    {
        type: 'noun',
        en: 'Bag',
        pl: 'Torba',
        jp: 'かばん',
    },
    {
        type: 'noun',
        en: 'Desk',
        pl: 'Biurko',
        jp: 'つくえ',
    },
    {
        type: 'noun',
        en: 'Chair',
        pl: 'Krzesło',
        jp: 'いす',
    },
    {
        type: 'noun',
        en: 'Key',
        pl: 'Klucz',
        jp: 'かぎ',
    },
    {
        type: 'noun',
        en: 'Car',
        pl: 'Samochód',
        jp: 'くるま',
    },
    {
        type: 'phrase',
        en: 'What is this?',
        pl: 'Co to jest?',
        jp: 'これはなんですか。',
    },
    {
        type: 'noun',
        en: 'Pen',
        pl: 'Długopis',
        jp: 'ペン',
    },
    {
        type: 'pronoun',
        en: 'This (close to me)',
        pl: 'To (blisko mnie)',
        jp: 'これ',
    },
    {
        type: 'pronoun',
        en: 'That (close to you)',
        pl: 'Tamto (blisko ciebie)',
        jp: 'それ',
    },
    {
        type: 'pronoun',
        en: 'That (far from us)',
        pl: 'Tamto (daleko od nas)',
        jp: 'あれ',
    },
    {
        type: 'noun',
        en: 'Headphones',
        pl: 'Słuchawki',
        jp: 'ヘッドホン',
    },
    {
        type: 'phrase',
        en: 'I know Japanese. I also know English.',
        pl: 'Znam japoński. Znam też angielski.',
        jp: 'わたしはにほんごができます。わたしはえいごもできます。',
        jp_description: "Pay attention that 'も' is used after 'えいご', not after 'わたし'.",
    },
];
