import type { JapaneseWord } from '../../../types';

export const sakura_1_8_animals: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: { word: 'いぬ' },
    },
    {
        type: 'noun',
        en: 'Cat',
        pl: 'Kot',
        jp: { word: 'ねこ' },
    },
    {
        type: 'noun',
        en: 'Lion',
        pl: 'Lew',
        jp: { word: 'ライオン' },
    },
    {
        type: 'noun',
        en: 'Elephant',
        pl: 'Słoń',
        jp: { word: 'ぞう' },
    },
    {
        type: 'noun',
        en: 'Horse',
        pl: 'Koń',
        jp: { word: 'うま' },
    },
    {
        type: 'noun',
        en: 'Cow',
        pl: 'Krowa',
        jp: { word: 'うし' },
    },
    {
        type: 'noun',
        en: 'Monkey',
        pl: 'Małpa',
        jp: { word: 'さる' },
    },
    {
        type: 'noun',
        en: 'Rabbit',
        pl: 'Królik',
        jp: { word: 'うさぎ' },
    },
    {
        type: 'noun',
        en: 'Giraffe',
        pl: 'Żyrafa',
        jp: { word: 'きりん' },
    },
    {
        type: 'noun',
        en: 'Bear',
        pl: 'Niedźwiedź',
        jp: { word: 'くま' },
    },
    {
        type: 'noun',
        en: 'Fox',
        pl: 'Lis',
        jp: { word: 'きつね' },
    },
    {
        type: 'noun',
        en: 'Squirrel',
        pl: 'Wiewiórka',
        jp: { word: 'りす' },
    },
    {
        type: 'noun',
        en: 'Tiger',
        pl: 'Tygrys',
        jp: { word: 'とら' },
    },
    {
        type: 'noun',
        en: 'Gorilla',
        pl: 'Goryl',
        jp: { word: 'ゴリラ' },
    },
    {
        type: 'noun',
        en: 'Kangaroo',
        pl: 'Kangur',
        jp: { word: 'カンガルー' },
    },
    {
        type: 'noun',
        en: 'Hippopotamus',
        pl: 'Hipopotam',
        jp: { word: 'かば' },
    },
    {
        type: 'noun',
        en: 'Zebra',
        pl: 'Zebra',
        jp: { word: 'しまうま' },
    },
    {
        type: 'noun',
        en: 'Deer',
        pl: 'Jeleń',
        jp: { word: 'しか' },
    },
    {
        type: 'noun',
        en: 'Panda',
        pl: 'Panda',
        jp: { word: 'パンダ' },
    },
    {
        type: 'noun',
        en: 'Pig',
        pl: 'Świnia',
        jp: { word: 'ぶた' },
    },
    {
        type: 'noun',
        en: 'Goat',
        pl: 'Koza',
        jp: { word: 'やぎ' },
    },
    {
        type: 'noun',
        en: 'Sheep',
        pl: 'Owca',
        jp: { word: 'ひつじ' },
    },
    {
        type: 'noun',
        en: 'Alpaca',
        pl: 'Alpaka',
        jp: { word: 'アルパカ' },
    },
    {
        type: 'noun',
        en: 'Raccoon',
        pl: 'Szop pracz',
        jp: { word: 'あらいぐま' },
    },
    {
        type: 'noun',
        en: 'Raccoon Dog (Tanuki)',
        pl: 'Jenot',
        jp: { word: 'たぬき' },
    },
    {
        type: 'noun',
        en: 'Koala',
        pl: 'Koala',
        jp: { word: 'コアラ' },
    },
    {
        type: 'noun',
        en: 'Rhinoceros',
        pl: 'Nosorożec',
        jp: { word: 'さい' },
    },
    {
        type: 'noun',
        en: 'Wild Boar',
        pl: 'Dzik',
        jp: { word: 'いのしし' },
    },
    {
        type: 'noun',
        en: 'Donkey',
        pl: 'Osioł',
        jp: { word: 'ろば' },
    },
    {
        type: 'noun',
        en: 'Camel',
        pl: 'Wielbłąd',
        jp: { word: 'らくだ' },
    },
    {
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: { word: 'おおかみ' },
    },
    {
        type: 'noun',
        en: 'Sloth',
        pl: 'Leniwiec',
        jp: { word: 'なまけもの' },
    },
    {
        type: 'noun',
        en: 'Chicken',
        pl: 'Kurczak',
        jp: { word: 'にわとり' },
    },
    {
        type: 'noun',
        en: 'Hamster',
        pl: 'Chomik',
        jp: { word: 'ハムスター' },
    },
    {
        type: 'noun',
        en: 'Mouse',
        pl: 'Mysz',
        jp: { word: 'ねずみ' },
    },
    {
        type: 'noun',
        en: 'Hedgehog',
        pl: 'Jeż',
        jp: { word: 'はりねずみ' },
    },
    {
        type: 'noun',
        en: 'Guinea pig',
        pl: 'Świnka morska',
        jp: { word: 'モルモット' },
    },
    {
        type: 'noun',
        en: 'Mole',
        pl: 'Kret',
        jp: { word: 'もぐら' },
    },
    {
        type: 'noun',
        en: 'Pigeon',
        pl: 'Gołąb',
        jp: { word: 'はと' },
    },
    {
        type: 'noun',
        en: 'Snake',
        pl: 'Wąż',
        jp: { word: 'へび' },
    },
];
