import type { JapaneseWord } from '../../../types';

export const sakura_1_11: JapaneseWord[] = [
    {
        type: 'pronoun',
        en: 'You (polite)',
        pl: 'Ty (grzecznie)',
        jp: 'あなた',
    },
    {
        type: 'pronoun',
        en: 'You (casual)',
        pl: 'Ty (potocznie)',
        jp: 'きみ',
    },
    {
        type: 'noun',
        en: 'Hospital',
        pl: 'Szpital',
        jp: 'びょういん',
    },
    {
        type: 'noun',
        en: 'New year',
        pl: 'Nowy rok',
        jp: 'おしょうがつ',
    },
    {
        type: 'noun',
        en: 'Birthday',
        pl: 'Urodziny',
        jp: 'たんじょうび',
    },
    {
        type: 'noun',
        en: 'Time',
        pl: 'Czas',
        jp: 'じかん',
    },
    {
        type: 'noun',
        en: 'Now',
        pl: 'Teraz',
        jp: 'いま',
    },
    {
        type: 'phrase',
        en: 'What time is it now?',
        pl: 'Która jest teraz godzina?',
        jp: 'いまなんじですか',
    },
    {
        type: 'noun',
        en: 'AM',
        pl: 'Przed południem',
        jp: 'ごぜん',
    },
    {
        type: 'noun',
        en: 'PM',
        pl: 'Po południu',
        jp: 'ごご',
    },
    {
        type: 'noun',
        en: 'Morning',
        pl: 'Rano',
        jp: 'あさ',
    },
    {
        type: 'noun',
        en: 'Noon',
        pl: 'Południe',
        jp: 'ひる',
    },
    {
        type: 'noun',
        en: 'Night',
        pl: 'Noc',
        jp: 'よる',
    },
    {
        type: 'suffix',
        en: 'Around',
        pl: 'Około',
        jp: 'ごろ',
    },
    {
        type: 'verb',
        verb_type: 'irregular',
        en: 'Work',
        pl: 'Pracować',
        jp: 'しごとをする',
        masu_form: 'しごとをします',
        masen_form: 'しごとをしません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Go back',
        pl: 'Wracać',
        jp: 'かえる',
        masu_form: 'かえります',
        masen_form: 'かえりません',
    },
    {
        type: 'phrase',
        en: 'Go back home',
        pl: 'Wracać do domu',
        jp: 'うちにかえる',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Wake up',
        pl: 'Budzić się',
        jp: 'おきる',
        masu_form: 'おきます',
        masen_form: 'おきません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Go',
        pl: 'Iść',
        jp: 'いく',
        masu_form: 'いきます',
        masen_form: 'いきません',
    },
    {
        type: 'phrase',
        en: 'Go to work',
        pl: 'Iść do pracy',
        jp: 'かいしゃにいく',
    },
    {
        type: 'phrase',
        en: "It's 7 AM now.",
        pl: 'Jest teraz siódma rano.',
        jp: 'いまごぜんしちじです。',
    },
    {
        type: 'phrase',
        en: 'When do you take a shower?',
        pl: 'O której bierzesz prysznic?',
        jp: 'なんじにシャワーをあびますか。',
    },
    {
        type: 'phrase',
        en: 'What time is it now in Tokyo?',
        pl: 'Która jest teraz godzina w Tokio?',
        jp: 'とうきょうはいまなんじですか。',
    },
    {
        type: 'noun',
        en: 'Diary',
        pl: 'Pamiętnik',
        jp: 'にっき',
    },
    {
        type: 'noun',
        en: 'Blog',
        pl: 'Blog',
        jp: 'ブログ',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Take (a shower)',
        pl: 'Brać (prysznic)',
        jp: 'あびる',
        masu_form: 'あびます',
        masen_form: 'あびません',
    },
    {
        type: 'phrase',
        en: 'Take a shower',
        pl: 'Brać prysznic',
        jp: 'シャワーをあびる',
    },
    {
        type: 'phrase',
        en: 'Take a bath',
        pl: 'Brać kąpiel',
        jp: 'おふろにはいる',
    },
    {
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Sleep',
        pl: 'Spać',
        jp: 'ねる',
        masu_form: 'ねます',
        masen_form: 'ねません',
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Busy',
        pl: 'Zajęty',
        jp: 'いそがしい',
    },
    {
        type: 'phrase',
        en: 'I am busy.',
        pl: 'Jestem zajęty.',
        jp: 'いそがしいです。',
    },
    {
        type: 'phrase',
        en: 'Work out',
        pl: 'Ćwiczyć',
        jp: 'うんどうをする',
    },
    {
        type: 'phrase',
        en: 'Do housework',
        pl: 'Robić prace domowe',
        jp: 'かじをする',
    },
    {
        type: 'phrase',
        en: 'Read newspaper at home',
        pl: 'Czytać gazetę w domu',
        jp: 'うちでしんぶんをよむ',
    },
    {
        type: 'phrase',
        en: 'Go to work by train',
        pl: 'Jechać do pracy pociągiem',
        jp: 'でんしゃでかいしゃにいく',
    },
    {
        type: 'phrase',
        en: 'Walk',
        pl: 'Spacerować',
        jp: 'さんぽをする',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Enter',
        pl: 'Wchodzić',
        jp: 'はいる',
        masu_form: 'はいります',
        masen_form: 'はいりません',
    },
    {
        type: 'phrase',
        en: 'Enter the school',
        pl: 'Wchodzić do szkoły',
        jp: 'がっこうにはいる',
    },
];
