import type { TranslatedJapaneseText } from '../../../types';

export const sakura_1_8: TranslatedJapaneseText[] = [
    {
        type: 'numeral',
        en: '4 things',
        pl: 'Cztery rzeczy',
        jp: { text: 'よっつ' },
    },
    {
        type: 'noun',
        en: 'Stamp',
        pl: 'Znaczek',
        jp: { text: 'きって' },
    },
    {
        type: 'noun',
        en: 'Magazine',
        pl: 'Czasopismo',
        jp: { text: 'ざっし' },
    },
    {
        type: 'numeral',
        en: 'Eight thousand',
        pl: 'Osiem tysięcy',
        jp: { text: 'はっせん' },
    },
    {
        type: 'numeral',
        en: 'Three things',
        pl: 'Trzy rzeczy',
        jp: { text: 'みっつ' },
    },
    {
        type: 'noun',
        en: 'One long object',
        pl: 'Jeden długi przedmiot',
        jp: { text: 'いっぽん' },
    },
    {
        type: 'noun',
        en: 'Ticket',
        pl: 'Bilet',
        jp: { text: 'きっぷ' },
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Liked / Favorite',
        pl: 'Lubiany / Ulubiony',
        jp: { text: 'すき' },
    },
    {
        type: 'phrase',
        en: 'To like',
        pl: 'Lubić',
        jp: { text: 'すきです' },
    },
    {
        type: 'phrase',
        en: "Don't like",
        pl: 'Nie lubić',
        jp: { text: 'すきじゃないです' },
    },
    {
        type: 'noun',
        en: 'Wine',
        pl: 'Wino',
        jp: { text: 'ワイン' },
    },
    {
        type: 'noun',
        en: 'Beer',
        pl: 'Piwo',
        jp: { text: 'ビール' },
    },
    {
        type: 'noun',
        en: 'Soup',
        pl: 'Zupa',
        jp: { text: 'スープ' },
    },
    {
        type: 'noun',
        en: 'Ice cream',
        pl: 'Lody',
        jp: { text: 'アイスクリーム' },
    },
    {
        type: 'noun',
        en: 'Cake',
        pl: 'Ciasto',
        jp: { text: 'ケーキ' },
    },
    {
        type: 'noun',
        en: 'Sauce',
        pl: 'Sos',
        jp: { text: 'ソース' },
    },
    {
        type: 'noun',
        en: 'Potato chips',
        pl: 'Chipsy',
        jp: { text: 'チップス' },
    },
    {
        type: 'noun',
        en: 'Sushi',
        pl: 'Sushi',
        jp: { text: 'すし' },
    },
    {
        type: 'noun',
        en: 'Dumplings (polish)',
        pl: 'Pierogi',
        jp: { text: 'ピエロギ' },
    },
    {
        type: 'phrase',
        en: 'No, thank you.',
        pl: 'Nie, dziękuję.',
        jp: { text: 'いいえ、けっこうです。' },
    },
    {
        type: 'noun',
        en: 'Restaurant',
        pl: 'Restauracja',
        jp: { text: 'レストラン' },
    },
];
