import type { JapaneseWord } from '../../../types';

export const sakura_1_10: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Breakfast',
        pl: 'Śniadanie',
        jp: 'あさごはん',
    },
    {
        type: 'noun',
        en: 'Lunch',
        pl: 'Obiad',
        jp: 'ひるごはん',
    },
    {
        type: 'noun',
        en: 'Dinner',
        pl: 'Kolacja',
        jp: 'ばんごはん',
    },
    {
        type: 'noun',
        en: 'Picture / Drawing',
        pl: 'Obrazek / Rysunek',
        jp: 'え',
    },
    {
        type: 'noun',
        en: 'Music',
        pl: 'Muzyka',
        jp: 'おんがく',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Listen',
        pl: 'Słuchać',
        jp: 'きく',
        masu_form: 'ききます',
        masen_form: 'ききません',
    },
    {
        type: 'noun',
        en: 'Radio',
        pl: 'Radio',
        jp: 'ラジオ',
    },
    {
        type: 'noun',
        en: 'News',
        pl: 'Wiadomości',
        jp: 'ニュース',
    },
    {
        type: 'noun',
        en: 'Hiragana',
        pl: 'Hiragana',
        jp: 'ひらがな',
    },
    {
        type: 'noun',
        en: 'Katakana',
        pl: 'Katakana',
        jp: 'カタカナ',
    },
    {
        type: 'noun',
        en: 'Kanji',
        pl: 'Kanji',
        jp: 'かんじ',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Draw',
        pl: 'Rysować',
        jp: 'かく',
        masu_form: 'かきます',
        masen_form: 'かきません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Write',
        pl: 'Pisać',
        jp: 'かく',
        masu_form: 'かきます',
        masen_form: 'かきません',
    },
    {
        type: 'verb',
        verb_type: 'godan',
        en: 'Buy',
        pl: 'Kupować',
        jp: 'かう',
        masu_form: 'かいます',
        masen_form: 'かいません',
    },
    {
        type: 'noun',
        en: 'Smartphone',
        pl: 'Smartfon',
        jp: 'スマホ',
    },
    {
        type: 'verb',
        verb_type: 'irregular',
        en: 'Do / Play',
        pl: 'Robić / Grać',
        jp: 'する',
        masu_form: 'します',
        masen_form: 'しません',
    },
    {
        type: 'phrase',
        en: 'Learn',
        pl: 'Uczyć się',
        jp: 'べんきょうをする',
    },
    {
        type: 'phrase',
        en: 'Do judo',
        pl: 'Uprawiać judo',
        jp: 'じゅうどうをする',
    },
    {
        type: 'phrase',
        en: 'Play games',
        pl: 'Grać w gry',
        jp: 'ゲームをする',
    },
    {
        type: 'phrase',
        en: 'Do shopping',
        pl: 'Robić zakupy',
        jp: 'かいものをする',
    },
    {
        type: 'phrase',
        en: 'Do homework',
        pl: 'Robić pracę domową',
        jp: 'しゅくだいをする',
    },
    {
        type: 'noun',
        en: 'Email',
        pl: 'Email',
        jp: 'メール',
    },
];
