import type { JapaneseWord } from '../../../types';

export const sakura_1_8_fruitsAndVegetables: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Strawberry',
        pl: 'Truskawka',
        jp: 'いちご',
    },
    {
        type: 'noun',
        en: 'Apple',
        pl: 'Jabłko',
        jp: 'りんご',
    },
    {
        type: 'noun',
        en: 'Orange',
        pl: 'Pomarańcza',
        jp: 'オレンジ',
    },
    {
        type: 'noun',
        en: 'Peach',
        pl: 'Brzoskwinia',
        jp: 'もも',
    },
    {
        type: 'noun',
        en: 'Grape',
        pl: 'Winogrono',
        jp: 'ぶどう',
    },
    {
        type: 'noun',
        en: 'Watermelon',
        pl: 'Arbuz',
        jp: 'すいか',
    },
    {
        type: 'noun',
        en: 'Kaki fruit',
        pl: 'Owoc kaki',
        jp: 'かき',
    },
    {
        type: 'noun',
        en: 'Pear',
        pl: 'Gruszka',
        jp: 'なし',
    },
    {
        type: 'noun',
        en: 'Cherry',
        pl: 'Wiśnia',
        jp: 'さくらんぼ',
    },
    {
        type: 'noun',
        en: 'Plum',
        pl: 'Śliwka',
        jp: 'すもも',
    },
    {
        type: 'noun',
        en: 'Lemon',
        pl: 'Cytryna',
        jp: 'レモン',
    },
    {
        type: 'noun',
        en: 'Banana',
        pl: 'Banan',
        jp: 'バナナ',
    },
    {
        type: 'noun',
        en: 'Kiwi',
        pl: 'Kiwi',
        jp: 'キウイ',
    },
    {
        type: 'noun',
        en: 'Pineapple',
        pl: 'Ananas',
        jp: 'パイナップル',
    },
    {
        type: 'noun',
        en: 'Melon',
        pl: 'Melon',
        jp: 'メロン',
    },
    {
        type: 'noun',
        en: 'Blueberry',
        pl: 'Jagoda',
        jp: 'ブルーベリー',
    },
    {
        type: 'noun',
        en: 'Raspberry',
        pl: 'Malina',
        jp: 'ラズベリー',
    },
    {
        type: 'noun',
        en: 'Mango',
        pl: 'Mango',
        jp: 'マンゴー',
    },
    {
        type: 'noun',
        en: 'White radish',
        pl: 'Biała rzodkiew',
        jp: 'だいこん',
    },
    {
        type: 'noun',
        en: 'Radish',
        pl: 'Rzodkiewka',
        jp: 'ラディッシュ',
    },
    {
        type: 'noun',
        en: 'Edamame',
        pl: 'Edamame',
        jp: 'えだまめ',
    },
    {
        type: 'noun',
        en: 'Cucumber',
        pl: 'Ogórek',
        jp: 'きゅうり',
    },
    {
        type: 'noun',
        en: 'Leek',
        pl: 'Por',
        jp: 'ねぎ',
    },
    {
        type: 'noun',
        en: 'Onion',
        pl: 'Cebula',
        jp: 'たまねぎ',
    },
    {
        type: 'noun',
        en: 'Lettuce',
        pl: 'Sałata',
        jp: 'レタス',
    },
    {
        type: 'noun',
        en: 'Cabbage',
        pl: 'Kapusta',
        jp: 'キャベツ',
    },
    {
        type: 'noun',
        en: 'Chinese cabbage',
        pl: 'Kapusta pekińska',
        jp: 'はくさい',
    },
    {
        type: 'noun',
        en: 'Pumpkin',
        pl: 'Dynia',
        jp: 'かぼちゃ',
    },
    {
        type: 'noun',
        en: 'Mushroom',
        pl: 'Grzyb',
        jp: 'きのこ',
    },
    {
        type: 'noun',
        en: 'Carrot',
        pl: 'Marchewka',
        jp: 'にんじん',
    },
    {
        type: 'noun',
        en: 'Paprika',
        pl: 'Papryka',
        jp: 'パプリカ',
    },
    {
        type: 'noun',
        en: 'Potato',
        pl: 'Ziemniak',
        jp: 'じゃがいも',
    },
    {
        type: 'noun',
        en: 'Sweet potato',
        pl: 'Słodki ziemniak',
        jp: 'さつまいも',
    },
    {
        type: 'noun',
        en: 'Beetroot',
        pl: 'Burak',
        jp: 'ビーツ',
    },
    {
        type: 'noun',
        en: 'Broccoli',
        pl: 'Brokuł',
        jp: 'ブロッコリー',
    },
    {
        type: 'noun',
        en: 'Eggplant',
        pl: 'Bakłażan',
        jp: 'なす',
    },
    {
        type: 'noun',
        en: 'Corn',
        pl: 'Kukurydza',
        jp: 'とうもろこし',
    },
    {
        type: 'noun',
        en: 'Garlic',
        pl: 'Czosnek',
        jp: 'にんにく',
    },
    {
        type: 'noun',
        en: 'Zucchini',
        pl: 'Cukinia',
        jp: 'ズッキーニ',
    },
    {
        type: 'noun',
        en: 'Spinach',
        pl: 'Szpinak',
        jp: 'ほうれんそう',
    },
    {
        type: 'noun',
        en: 'Tomato',
        pl: 'Pomidor',
        jp: 'トマト',
    },
    {
        type: 'noun',
        en: 'Asparagus',
        pl: 'Szparagi',
        jp: 'アスパラガス',
    },
];
