import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_1_12: TranslatedJapaneseText[] = [
    {
        id: '64a85c3e-3ac5-4e8b-a6fc-1f430164cd58',
        type: 'phrase',
        en: 'Friends will come to my house.',
        pl: 'Przyjaciele przyjdą do mojego domu.',
        jp: { text: '友達が私の家に来ます。', pronunciation: 'ともだちがわたしのうちにきます。' },
    },
    {
        id: '0c214fbd-eadb-474f-b9d4-730234d44d42',
        type: 'pronoun',
        en: 'When',
        pl: 'Kiedy',
        jp: { text: 'いつ' },
    },
    {
        id: '251bf442-dd05-4bde-879a-50cefbfbcbee',
        type: 'verb',
        verb_type: 'godan',
        en: 'Use',
        pl: 'Używać',
        jp: { text: '使う', pronunciation: 'つかう' },
    },
    {
        id: '988b6ee6-fe98-4974-95ee-6f821431264b',
        type: 'verb',
        verb_type: 'godan',
        en: 'Meet',
        pl: 'Spotykać',
        jp: { text: '会う', pronunciation: 'あう' },
    },
    {
        id: '815da87d-0687-42d6-bdee-e70b444277f6',
        type: 'phrase',
        en: 'With whom do you meet?',
        pl: 'Z kim się spotykasz?',
        jp: { text: 'だれと会いますか。', pronunciation: 'だれとあいますか。' },
    },
    {
        id: 'c5ec38f5-89bf-444c-9873-44e2a50ef5a9',
        type: 'verb',
        verb_type: 'godan',
        en: 'Make / Create',
        pl: 'Robić / Tworzyć',
        jp: { text: '作る', pronunciation: 'つくる' },
    },
    {
        id: '612eeb27-b913-418c-b733-10cf2ff4fca4',
        type: 'phrase',
        en: 'I use a phone.',
        pl: 'Używam telefonu.',
        jp: { text: '電話を使います。', pronunciation: 'でんわをつかいます。' },
    },
    {
        id: '8ea0455a-539f-4dd0-8113-7f925792d20a',
        type: 'verb',
        verb_type: 'godan',
        en: 'Take (an object or picture)',
        pl: 'Brać (przedmiot) lub robić (zdjęcie)',
        jp: { text: '撮る', pronunciation: 'とる' },
    },
    {
        id: '9fd3b602-1575-42c9-a3f9-045f72e45ace',
        type: 'phrase',
        en: 'Take pictures',
        pl: 'Robić zdjęcia',
        jp: { text: '写真を撮る', pronunciation: 'しゃしんをとる' },
    },
    {
        id: 'df4183ff-1fd2-4377-a0fd-e1c9cdae3e8b',
        type: 'verb',
        verb_type: 'godan',
        en: 'Send',
        pl: 'Wysyłać',
        jp: { text: '送る', pronunciation: 'おくる' },
    },
    {
        id: '8858ac46-8fbf-453c-b6a0-53bc3d60d6ca',
        type: 'phrase',
        en: 'Send a letter',
        pl: 'Wysyłać list',
        jp: { text: '手紙を送る', pronunciation: 'てがみをおくる' },
    },
    {
        id: '5b2459f5-207b-49c0-8cbd-6613d85e685b',
        type: 'noun',
        en: 'Package',
        pl: 'Paczka',
        jp: { text: '荷物', pronunciation: 'にもつ' },
    },
    {
        id: 'fd7ed2a2-3d16-4564-8eb1-f76be703a15d',
        type: 'phrase',
        en: 'Play by yourself',
        pl: 'Bawić się sam',
        jp: { text: '一人で遊ぶ', pronunciation: 'ひとりであそぶ' },
    },
    {
        id: '76199ba7-2cda-4c33-a176-5a4811bd605d',
        type: 'verb',
        verb_type: 'godan',
        en: 'Play / Have fun / Hang out',
        pl: 'Bawić się / Miło spędzać czas',
        jp: { text: '遊ぶ', pronunciation: 'あそぶ' },
    },
    {
        id: '9cc47543-c74f-46cd-962e-d67c3a475ada',
        type: 'noun',
        en: 'Musical instrument',
        pl: 'Instrument muzyczny',
        jp: { text: '楽器', pronunciation: 'がっき' },
    },
    {
        id: '6c41053a-f0b7-41f6-a1bd-9dc196e177d6',
        type: 'verb',
        verb_type: 'godan',
        en: 'Play (a musical instrument)',
        pl: 'Grać (na instrumencie muzycznym)',
        jp: { text: '弾く', pronunciation: 'ひく' },
    },
    {
        id: '00173d0b-bda4-45bd-866a-6a4645b6d3a7',
        type: 'phrase',
        en: 'Play an instrument',
        pl: 'Grać na instrumencie',
        jp: { text: '楽器を弾く', pronunciation: 'がっきをひく' },
    },
    {
        id: '89e17e20-fec4-4e3b-8625-ab2aae5ea166',
        type: 'verb',
        verb_type: 'godan',
        en: 'Rest',
        pl: 'Odpoczywać',
        jp: { text: '休む', pronunciation: 'やすむ' },
    },
    {
        id: 'f7db90e3-e5ed-4a44-b1bd-a27571822823',
        type: 'verb',
        verb_type: 'godan',
        en: 'Swim',
        pl: 'Pływać',
        jp: { text: '泳ぐ', pronunciation: 'およぐ' },
    },
    {
        id: 'b285b276-7df3-44f7-b761-9cc71c1169a9',
        type: 'verb',
        verb_type: 'godan',
        en: 'Talk',
        pl: 'Rozmawiać',
        jp: { text: '話す', pronunciation: 'はなす' },
    },
    {
        id: 'a3f8ae6a-b88d-4957-8107-fb27f96ffc65',
        type: 'phrase',
        en: 'Who are you talking with?',
        pl: 'Z kim rozmawiasz?',
        jp: { text: 'だれと話しますか。', pronunciation: 'だれとはなしますか。' },
    },
    {
        id: '4febbdcc-824f-4ccf-a941-82675312c0d7',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Teach',
        pl: 'Uczyć (kogoś)',
        jp: { text: '教える', pronunciation: 'おしえる' },
    },
    {
        id: '123c5221-ab8d-4461-ae69-96672b9bcf5a',
        type: 'phrase',
        en: 'I teach my children math.',
        pl: 'Uczę moje dzieci matematyki.',
        jp: { text: '私は子供に数学を教えます。', pronunciation: 'わたしはこどもにすうがくをおしえます。' },
    },
    {
        id: '438b0076-de9a-4ce2-8c47-a7faae340280',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Put on (clothes above your waist)',
        pl: 'Zakładać (ubrania powyżej pasa)',
        jp: { text: '着る', pronunciation: 'きる' },
    },
    {
        id: 'd6734b02-18f8-413f-8bdc-49ca1c9ef286',
        type: 'phrase',
        en: 'Put on a jacket',
        pl: 'Zakładać kurtkę',
        jp: { text: 'ジャケットを着る', pronunciation: 'ジャケットをきる' },
    },
    {
        id: '522e9228-4749-4615-95ce-d6a71524d33f',
        type: 'phrase',
        en: 'All day',
        pl: 'Cały dzień',
        jp: { text: '一日中', pronunciation: 'いちにちじゅう' },
    },
    {
        id: '4f642d19-5515-47f5-958f-da07163fea45',
        type: 'verb',
        verb_type: 'suru',
        en: 'Cook',
        pl: 'Gotować',
        jp: { text: '料理をする', pronunciation: 'りょうりをする' },
    },
    {
        id: '6feb73e4-a5f4-412e-9ca8-2eb455666963',
        type: 'verb',
        verb_type: 'suru',
        en: 'Do sports',
        pl: 'Uprawiać sport',
        jp: { text: 'スポーツをする' },
    },
    {
        id: 'ce9367f4-c68f-4be0-81c9-c356cfc10e64',
        type: 'phrase',
        en: 'I shop twice every week.',
        pl: 'Robię zakupy dwa razy w tygodniu.',
        jp: { text: '毎週二回、買い物をします。', pronunciation: 'まいしゅうにかい、かいものをします。' },
    },
    {
        id: 'a5d17100-94d4-441e-add2-8045707cb527',
        type: 'phrase',
        en: 'Cook pierogi',
        pl: 'Gotować pierogi',
        jp: { text: 'ピエロギを作る', pronunciation: 'ピエロギをつくる' },
    },
    {
        id: '8648be4b-5677-436e-ba21-44341f83323b',
        type: 'phrase',
        en: 'Cook Japanese food',
        pl: 'Gotować japońskie jedzenie',
        jp: { text: '日本料理を作る', pronunciation: 'にほんりょうりをつくる' },
        description:
            'Technically, this should be "にほんのりょうりをつくる", but the particle "の" is often omitted in casual speech.',
    },
    {
        id: '01303ebd-938c-477b-91ce-5f20898fb01a',
        type: 'noun',
        en: 'Copy',
        pl: 'Kopia',
        jp: { text: 'コピー' },
    },
    {
        id: 'e97b142d-41b2-40ce-b70b-1d3049b18d48',
        type: 'verb',
        verb_type: 'suru',
        en: 'Make a copy',
        pl: 'Robić kopię',
        jp: { text: 'コピーをする' },
    },
    {
        id: '3625fb24-c8dd-4f74-badb-c793e09f192d',
        type: 'noun',
        en: 'Piano',
        pl: 'Pianino',
        jp: { text: 'ピアノ' },
    },
    {
        id: '7e7824a1-1fbd-4942-bcc4-e6e509428a0e',
        type: 'noun',
        en: 'Guitar',
        pl: 'Gitara',
        jp: { text: 'ギター' },
    },
    {
        id: 'd38c2fb9-2708-43db-9516-6007d8821fdf',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Yellow',
        pl: 'Żółty',
        jp: { text: '黄色い', pronunciation: 'きいろい' },
    },
    {
        id: 'b3a3a71c-6d10-4cd0-b9be-47440a7efd81',
        type: 'noun',
        en: 'Street',
        pl: 'Ulica',
        jp: { text: '通り', pronunciation: 'とおり' },
    },
    {
        id: '950e1371-92c6-44a0-8ead-3b38d3f41f53',
        type: 'noun',
        en: 'Air',
        pl: 'Powietrze',
        jp: { text: '空気', pronunciation: 'くうき' },
    },
    {
        id: 'cd8692b3-28c3-48f1-bb8f-8fcfaa36f80a',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Big',
        pl: 'Duży',
        jp: { text: '大きい', pronunciation: 'おおきい' },
    },
    {
        id: 'f39aa583-aea1-4c43-b4e0-063d2270c037',
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: { text: '狼', pronunciation: 'おおかみ' },
    },
    {
        id: '36d4d1ca-c347-4768-9b2a-09a99a205e2e',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Small',
        pl: 'Mały',
        jp: { text: '小さい', pronunciation: 'ちいさい' },
    },
    {
        id: '7ab9e903-8079-489a-81b1-9470799d37f6',
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Far',
        pl: 'Daleko',
        jp: { text: '遠い', pronunciation: 'とおい' },
    },
    {
        id: 'abaf5430-13a3-4875-96a3-9b171dc0c339',
        type: 'noun',
        en: 'Fridge',
        pl: 'Lodówka',
        jp: { text: '冷蔵庫', pronunciation: 'れいぞうこ' },
    },
    {
        id: 'c2408328-8593-44ba-9004-36fb7fb71bf0',
        type: 'verb',
        verb_type: 'suru',
        en: 'Play football',
        pl: 'Grać w piłkę nożną',
        jp: { text: 'サッカーをする' },
    },
];

export const sakura1_12Bag: WordBag = {
    id: '0dd511ac-1108-49ff-96f9-dc4a91c964c6',
    name: 'Sakura #1.12',
    words: sakura_1_12,
};
