import type { JapaneseWord } from '../../../types';

export const sakura_1_8_animals: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Dog',
        pl: 'Pies',
        jp: 'いぬ',
    },
    {
        type: 'noun',
        en: 'Cat',
        pl: 'Kot',
        jp: 'ねこ',
    },
    {
        type: 'noun',
        en: 'Lion',
        pl: 'Lew',
        jp: 'ライオン',
    },
    {
        type: 'noun',
        en: 'Elephant',
        pl: 'Słoń',
        jp: 'ぞう',
    },
    {
        type: 'noun',
        en: 'Horse',
        pl: 'Koń',
        jp: 'うま',
    },
    {
        type: 'noun',
        en: 'Cow',
        pl: 'Krowa',
        jp: 'うし',
    },
    {
        type: 'noun',
        en: 'Monkey',
        pl: 'Małpa',
        jp: 'さる',
    },
    {
        type: 'noun',
        en: 'Rabbit',
        pl: 'Królik',
        jp: 'うさぎ',
    },
    {
        type: 'noun',
        en: 'Giraffe',
        pl: 'Żyrafa',
        jp: 'きりん',
    },
    {
        type: 'noun',
        en: 'Bear',
        pl: 'Niedźwiedź',
        jp: 'くま',
    },
    {
        type: 'noun',
        en: 'Fox',
        pl: 'Lis',
        jp: 'きつね',
    },
    {
        type: 'noun',
        en: 'Squirrel',
        pl: 'Wiewiórka',
        jp: 'りす',
    },
    {
        type: 'noun',
        en: 'Tiger',
        pl: 'Tygrys',
        jp: 'とら',
    },
    {
        type: 'noun',
        en: 'Gorilla',
        pl: 'Goryl',
        jp: 'ゴリラ',
    },
    {
        type: 'noun',
        en: 'Kangaroo',
        pl: 'Kangur',
        jp: 'カンガルー',
    },
    {
        type: 'noun',
        en: 'Hippopotamus',
        pl: 'Hipopotam',
        jp: 'かば',
    },
    {
        type: 'noun',
        en: 'Zebra',
        pl: 'Zebra',
        jp: 'しまうま',
    },
    {
        type: 'noun',
        en: 'Deer',
        pl: 'Jeleń',
        jp: 'しか',
    },
    {
        type: 'noun',
        en: 'Panda',
        pl: 'Panda',
        jp: 'パンダ',
    },
    {
        type: 'noun',
        en: 'Pig',
        pl: 'Świnia',
        jp: 'ぶた',
    },
    {
        type: 'noun',
        en: 'Goat',
        pl: 'Koza',
        jp: 'やぎ',
    },
    {
        type: 'noun',
        en: 'Sheep',
        pl: 'Owca',
        jp: 'ひつじ',
    },
    {
        type: 'noun',
        en: 'Alpaca',
        pl: 'Alpaka',
        jp: 'アルパカ',
    },
    {
        type: 'noun',
        en: 'Raccoon',
        pl: 'Szop pracz',
        jp: 'あらいぐま',
    },
    {
        type: 'noun',
        en: 'Raccoon Dog (Tanuki)',
        pl: 'Jenot',
        jp: 'たぬき',
    },
    {
        type: 'noun',
        en: 'Koala',
        pl: 'Koala',
        jp: 'コアラ',
    },
    {
        type: 'noun',
        en: 'Rhinoceros',
        pl: 'Nosorożec',
        jp: 'さい',
    },
    {
        type: 'noun',
        en: 'Wild Boar',
        pl: 'Dzik',
        jp: 'いのしし',
    },
    {
        type: 'noun',
        en: 'Donkey',
        pl: 'Osioł',
        jp: 'ろば',
    },
    {
        type: 'noun',
        en: 'Camel',
        pl: 'Wielbłąd',
        jp: 'らくだ',
    },
    {
        type: 'noun',
        en: 'Wolf',
        pl: 'Wilk',
        jp: 'おおかみ',
    },
    {
        type: 'noun',
        en: 'Sloth',
        pl: 'Leniwiec',
        jp: 'なまけもの',
    },
    {
        type: 'noun',
        en: 'Chicken',
        pl: 'Kurczak',
        jp: 'にわとり',
    },
    {
        type: 'noun',
        en: 'Hamster',
        pl: 'Chomik',
        jp: 'ハムスター',
    },
    {
        type: 'noun',
        en: 'Mouse',
        pl: 'Mysz',
        jp: 'ねずみ',
    },
    {
        type: 'noun',
        en: 'Hedgehog',
        pl: 'Jeż',
        jp: 'はりねずみ',
    },
    {
        type: 'noun',
        en: 'Guinea pig',
        pl: 'Świnka morska',
        jp: 'モルモット',
    },
    {
        type: 'noun',
        en: 'Mole',
        pl: 'Kret',
        jp: 'もぐら',
    },
    {
        type: 'noun',
        en: 'Pigeon',
        pl: 'Gołąb',
        jp: 'はと',
    },
    {
        type: 'noun',
        en: 'Snake',
        pl: 'Wąż',
        jp: 'へび',
    },
];
