import type { TranslatedJapaneseText } from '../../../types';

export const sakura_1_8_fruitsAndVegetables: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Strawberry',
        pl: 'Truskawka',
        jp: { text: 'いちご' },
    },
    {
        type: 'noun',
        en: 'Apple',
        pl: 'Jabłko',
        jp: { text: 'りんご' },
    },
    {
        type: 'noun',
        en: 'Orange',
        pl: 'Pomarańcza',
        jp: { text: 'オレンジ' },
    },
    {
        type: 'noun',
        en: 'Peach',
        pl: 'Brzoskwinia',
        jp: { text: 'もも' },
    },
    {
        type: 'noun',
        en: 'Grape',
        pl: 'Winogrono',
        jp: { text: 'ぶどう' },
    },
    {
        type: 'noun',
        en: 'Watermelon',
        pl: 'Arbuz',
        jp: { text: 'すいか' },
    },
    {
        type: 'noun',
        en: 'Kaki fruit',
        pl: 'Owoc kaki',
        jp: { text: 'かき' },
    },
    {
        type: 'noun',
        en: 'Pear',
        pl: 'Gruszka',
        jp: { text: 'なし' },
    },
    {
        type: 'noun',
        en: 'Cherry',
        pl: 'Wiśnia',
        jp: { text: 'さくらんぼ' },
    },
    {
        type: 'noun',
        en: 'Plum',
        pl: 'Śliwka',
        jp: { text: 'すもも' },
    },
    {
        type: 'noun',
        en: 'Lemon',
        pl: 'Cytryna',
        jp: { text: 'レモン' },
    },
    {
        type: 'noun',
        en: 'Banana',
        pl: 'Banan',
        jp: { text: 'バナナ' },
    },
    {
        type: 'noun',
        en: 'Kiwi',
        pl: 'Kiwi',
        jp: { text: 'キウイ' },
    },
    {
        type: 'noun',
        en: 'Pineapple',
        pl: 'Ananas',
        jp: { text: 'パイナップル' },
    },
    {
        type: 'noun',
        en: 'Melon',
        pl: 'Melon',
        jp: { text: 'メロン' },
    },
    {
        type: 'noun',
        en: 'Blueberry',
        pl: 'Jagoda',
        jp: { text: 'ブルーベリー' },
    },
    {
        type: 'noun',
        en: 'Raspberry',
        pl: 'Malina',
        jp: { text: 'ラズベリー' },
    },
    {
        type: 'noun',
        en: 'Mango',
        pl: 'Mango',
        jp: { text: 'マンゴー' },
    },
    {
        type: 'noun',
        en: 'White radish',
        pl: 'Biała rzodkiew',
        jp: { text: 'だいこん' },
    },
    {
        type: 'noun',
        en: 'Radish',
        pl: 'Rzodkiewka',
        jp: { text: 'ラディッシュ' },
    },
    {
        type: 'noun',
        en: 'Edamame',
        pl: 'Edamame',
        jp: { text: 'えだまめ' },
    },
    {
        type: 'noun',
        en: 'Cucumber',
        pl: 'Ogórek',
        jp: { text: 'きゅうり' },
    },
    {
        type: 'noun',
        en: 'Leek',
        pl: 'Por',
        jp: { text: 'ねぎ' },
    },
    {
        type: 'noun',
        en: 'Onion',
        pl: 'Cebula',
        jp: { text: 'たまねぎ' },
    },
    {
        type: 'noun',
        en: 'Lettuce',
        pl: 'Sałata',
        jp: { text: 'レタス' },
    },
    {
        type: 'noun',
        en: 'Cabbage',
        pl: 'Kapusta',
        jp: { text: 'キャベツ' },
    },
    {
        type: 'noun',
        en: 'Chinese cabbage',
        pl: 'Kapusta pekińska',
        jp: { text: 'はくさい' },
    },
    {
        type: 'noun',
        en: 'Pumpkin',
        pl: 'Dynia',
        jp: { text: 'かぼちゃ' },
    },
    {
        type: 'noun',
        en: 'Mushroom',
        pl: 'Grzyb',
        jp: { text: 'きのこ' },
    },
    {
        type: 'noun',
        en: 'Carrot',
        pl: 'Marchewka',
        jp: { text: 'にんじん' },
    },
    {
        type: 'noun',
        en: 'Paprika',
        pl: 'Papryka',
        jp: { text: 'パプリカ' },
    },
    {
        type: 'noun',
        en: 'Potato',
        pl: 'Ziemniak',
        jp: { text: 'じゃがいも' },
    },
    {
        type: 'noun',
        en: 'Sweet potato',
        pl: 'Słodki ziemniak',
        jp: { text: 'さつまいも' },
    },
    {
        type: 'noun',
        en: 'Beetroot',
        pl: 'Burak',
        jp: { text: 'ビーツ' },
    },
    {
        type: 'noun',
        en: 'Broccoli',
        pl: 'Brokuł',
        jp: { text: 'ブロッコリー' },
    },
    {
        type: 'noun',
        en: 'Eggplant',
        pl: 'Bakłażan',
        jp: { text: 'なす' },
    },
    {
        type: 'noun',
        en: 'Corn',
        pl: 'Kukurydza',
        jp: { text: 'とうもろこし' },
    },
    {
        type: 'noun',
        en: 'Garlic',
        pl: 'Czosnek',
        jp: { text: 'にんにく' },
    },
    {
        type: 'noun',
        en: 'Zucchini',
        pl: 'Cukinia',
        jp: { text: 'ズッキーニ' },
    },
    {
        type: 'noun',
        en: 'Spinach',
        pl: 'Szpinak',
        jp: { text: 'ほうれんそう' },
    },
    {
        type: 'noun',
        en: 'Tomato',
        pl: 'Pomidor',
        jp: { text: 'トマト' },
    },
    {
        type: 'noun',
        en: 'Asparagus',
        pl: 'Szparagi',
        jp: { text: 'アスパラガス' },
    },
];
