import type { JapaneseWord } from '../../../types';

export const sakura_1_8: JapaneseWord[] = [
    {
        type: 'numeral',
        en: '4 things',
        pl: 'Cztery rzeczy',
        jp: 'よっつ',
    },
    {
        type: 'noun',
        en: 'Stamp',
        pl: 'Znaczek',
        jp: 'きって',
    },
    {
        type: 'noun',
        en: 'Magazine',
        pl: 'Czasopismo',
        jp: 'ざっし',
    },
    {
        type: 'numeral',
        en: 'Eight thousand',
        pl: 'Osiem tysięcy',
        jp: 'はっせん',
    },
    {
        type: 'numeral',
        en: 'Three things',
        pl: 'Trzy rzeczy',
        jp: 'みっつ',
    },
    {
        type: 'noun',
        en: 'One long object',
        pl: 'Jeden długi przedmiot',
        jp: 'いっぽん',
    },
    {
        type: 'noun',
        en: 'Ticket',
        pl: 'Bilet',
        jp: 'きっぷ',
    },
    {
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Liked / Favorite',
        pl: 'Lubiany / Ulubiony',
        jp: 'すき',
    },
    {
        type: 'phrase',
        en: 'To like',
        pl: 'Lubić',
        jp: 'すきです',
    },
    {
        type: 'phrase',
        en: "Don't like",
        pl: 'Nie lubić',
        jp: 'すきじゃないです',
    },
    {
        type: 'noun',
        en: 'Wine',
        pl: 'Wino',
        jp: 'ワイン',
    },
    {
        type: 'noun',
        en: 'Beer',
        pl: 'Piwo',
        jp: 'ビール',
    },
    {
        type: 'noun',
        en: 'Soup',
        pl: 'Zupa',
        jp: 'スープ',
    },
    {
        type: 'noun',
        en: 'Ice cream',
        pl: 'Lody',
        jp: 'アイスクリーム',
    },
    {
        type: 'noun',
        en: 'Cake',
        pl: 'Ciasto',
        jp: 'ケーキ',
    },
    {
        type: 'noun',
        en: 'Sauce',
        pl: 'Sos',
        jp: 'ソース',
    },
    {
        type: 'noun',
        en: 'Potato chips',
        pl: 'Chipsy',
        jp: 'チップス',
    },
    {
        type: 'noun',
        en: 'Sushi',
        pl: 'Sushi',
        jp: 'すし',
    },
    {
        type: 'noun',
        en: 'Dumplings (polish)',
        pl: 'Pierogi',
        jp: 'ピエロギ',
    },
    {
        type: 'phrase',
        en: 'No, thank you.',
        pl: 'Nie, dziękuję.',
        jp: 'いいえ、けっこうです。',
    },
    {
        type: 'noun',
        en: 'Restaurant',
        pl: 'Restauracja',
        jp: 'レストラン',
    },
];
