import type { JapaneseWord } from '../../../types';

export const sakura_1_5: JapaneseWord[] = [
    {
        type: 'pronoun',
        en: 'Who',
        pl: 'Kto',
        jp: { word: 'だれ' },
    },
    {
        type: 'phrase',
        en: 'Whose bike is this?',
        pl: 'Czyj to rower?',
        jp: { word: 'これはだれのじてんしゃですか。' },
    },
    {
        type: 'noun',
        en: 'Cherry / Cherry blossom',
        pl: 'Wiśnia / Kwiat wiśni',
        jp: { word: 'さくら' },
    },
    {
        type: 'noun',
        en: 'Medicine / Drug',
        pl: 'Lekarstwo / Lek',
        jp: { word: 'くすり' },
    },
    {
        type: 'noun',
        en: 'Car',
        pl: 'Samochód',
        jp: { word: 'くるま' },
    },
    {
        type: 'noun',
        en: 'History',
        pl: 'Historia',
        jp: { word: 'れきし' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'White',
        pl: 'Biały',
        jp: { word: 'しろい' },
    },
    {
        type: 'adjective',
        adjective_type: 'i-adjective',
        en: 'Black',
        pl: 'Czarny',
        jp: { word: 'くろい' },
    },
    {
        type: 'noun',
        en: 'River',
        pl: 'Rzeka',
        jp: { word: 'かわ' },
    },
    {
        type: 'noun',
        en: 'Mandarin',
        pl: 'Mandarynka',
        jp: { word: 'みかん' },
    },
    {
        type: 'phrase',
        en: 'How old are you? (informal)',
        pl: 'Ile masz lat? (nieformalnie)',
        jp: { word: 'なんさいですか。' },
    },
    {
        type: 'phrase',
        en: 'How old are you? (formal)',
        pl: 'Ile ma pan/pani lat? (formalnie)',
        jp: { word: 'おいくつですか。' },
    },
    {
        type: 'phrase',
        en: 'How old is your mother? (formal)',
        pl: 'Ile lat ma twoja mama? (formalnie)',
        jp: { word: 'おかあさんはおいくつですか。' },
    },
    {
        type: 'phrase',
        en: "I don't have an older sister.",
        pl: 'Nie mam starszej siostry.',
        jp: { word: 'あねはいません。' },
    },
    {
        type: 'noun',
        en: 'Phone number',
        pl: 'Numer telefonu',
        jp: { word: 'でんわばんごう' },
    },
    {
        type: 'noun',
        en: 'One year old',
        pl: 'Jeden rok (wiek)',
        jp: { word: 'いっさい' },
    },
    {
        type: 'noun',
        en: 'Two years old',
        pl: 'Dwa lata (wiek)',
        jp: { word: 'にさい' },
    },
    {
        type: 'noun',
        en: 'Three years old',
        pl: 'Trzy lata (wiek)',
        jp: { word: 'さんさい' },
    },
    {
        type: 'noun',
        en: 'Four years old',
        pl: 'Cztery lata (wiek)',
        jp: { word: 'よんさい' },
    },
    {
        type: 'noun',
        en: 'Five years old',
        pl: 'Pięć lat (wiek)',
        jp: { word: 'ごさい' },
    },
    {
        type: 'noun',
        en: 'Six years old',
        pl: 'Sześć lat (wiek)',
        jp: { word: 'ろくさい' },
    },
    {
        type: 'noun',
        en: 'Seven years old',
        pl: 'Siedem lat (wiek)',
        jp: { word: 'ななさい' },
    },
    {
        type: 'noun',
        en: 'Eight years old',
        pl: 'Osiem lat (wiek)',
        jp: { word: 'はっさい' },
    },
    {
        type: 'noun',
        en: 'Nine years old',
        pl: 'Dziewięć lat (wiek)',
        jp: { word: 'きゅうさい' },
    },
    {
        type: 'noun',
        en: 'Ten years old',
        pl: 'Dziesięć lat (wiek)',
        jp: { word: 'じゅっさい' },
    },
    {
        type: 'noun',
        en: 'Eleven years old',
        pl: 'Jedenaście lat (wiek)',
        jp: { word: 'じゅういっさい' },
    },
    {
        type: 'noun',
        en: 'Seventeen years old',
        pl: 'Siedemnaście lat (wiek)',
        jp: { word: 'じゅうななさい' },
    },
    {
        type: 'noun',
        en: 'Nineteen years old',
        pl: 'Dziewiętnaście lat (wiek)',
        jp: { word: 'じゅうきゅうさい' },
    },
    {
        type: 'noun',
        en: 'Twenty years old',
        pl: 'Dwadzieścia lat (wiek)',
        jp: { word: 'はたち' },
    },
    {
        type: 'noun',
        en: 'Twenty eight years old',
        pl: 'Dwadzieścia osiem lat (wiek)',
        jp: { word: 'にじゅうはっさい' },
    },
    {
        type: 'noun',
        en: 'Thirty years old',
        pl: 'Trzydzieści lat (wiek)',
        jp: { word: 'さんじゅっさい' },
    },
    {
        type: 'noun',
        en: 'One person',
        pl: 'Jedna osoba',
        jp: { word: 'ひとり' },
    },
    {
        type: 'noun',
        en: 'Two people',
        pl: 'Dwie osoby',
        jp: { word: 'ふたり' },
    },
    {
        type: 'noun',
        en: 'Three people',
        pl: 'Trzy osoby',
        jp: { word: 'さんにん' },
    },
    {
        type: 'noun',
        en: 'Four people',
        pl: 'Cztery osoby',
        jp: { word: 'よにん' },
    },
    {
        type: 'noun',
        en: 'Five people',
        pl: 'Pięć osób',
        jp: { word: 'ごにん' },
    },
    {
        type: 'noun',
        en: 'Six people',
        pl: 'Sześć osób',
        jp: { word: 'ろくにん' },
    },
    {
        type: 'noun',
        en: 'Seven people',
        pl: 'Siedem osób',
        jp: { word: 'ななにん' },
    },
    {
        type: 'noun',
        en: 'Eight people',
        pl: 'Osiem osób',
        jp: { word: 'はちにん' },
    },
    {
        type: 'noun',
        en: 'Nine people',
        pl: 'Dziewięć osób',
        jp: { word: 'きゅうにん' },
    },
    {
        type: 'noun',
        en: 'Ten people',
        pl: 'Dziesięć osób',
        jp: { word: 'じゅうにん' },
    },
    {
        type: 'noun',
        en: 'Eleven people',
        pl: 'Jedenaście osób',
        jp: { word: 'じゅういちにん' },
    },
    {
        type: 'noun',
        en: 'Twelve people',
        pl: 'Dwanaście osób',
        jp: { word: 'じゅうににん' },
    },
    {
        type: 'phrase',
        en: 'How many people are in your family?',
        pl: 'Ile osób jest w twojej rodzinie?',
        jp: { word: 'かぞくはなんにんですか。' },
    },
    {
        type: 'phrase',
        en: 'My family has four people.',
        pl: 'Moja rodzina liczy cztery osoby.',
        jp: { word: 'かぞくはよにんです。' },
    },
    {
        type: 'phrase',
        en: 'I have two older sisters.',
        pl: 'Mam dwie starsze siostry.',
        jp: { word: 'あねがふたりいます。' },
    },
];
