import type { TranslatedJapaneseText, WordBag } from '../../../types';
import dakuten from './sakura1Assets/dakuten.jpg';
import handakuten from './sakura1Assets/handakuten.jpg';

const sakura_3_1: TranslatedJapaneseText[] = [
    {
        id: '4d3bc4e8-8b7b-4869-964d-2eb8b512a3ad',
        type: 'noun',
        en: 'Place / Location',
        pl: 'Miejsce',
        jp: { text: '場所', pronunciation: 'ばしょ' },
    },
    {
        id: '9d2bed33-1fbb-4e96-a83c-1dcf4c409b7c',
        type: 'noun',
        en: '"Dots" diacritic',
        pl: 'Diakrytyk "kropki"',
        image_url: dakuten,
        jp: { text: '濁点', pronunciation: 'だくてん' },
    },
    {
        id: 'bdc5c7b2-9a28-4734-8224-0476162d24ff',
        type: 'noun',
        en: '"Circle" diacritic',
        pl: 'Diakrytyk "kółko"',
        image_url: handakuten,
        jp: { text: '半濁点', pronunciation: 'はんだくてん' },
    },
    {
        id: '78064d4b-fca7-448a-88cc-06deb4b20274',
        type: 'noun',
        en: 'Bossa Nova',
        pl: 'Bossa Nova',
        jp: { text: 'ボサノバ' },
    },
    {
        id: '95eb338a-60fd-4a63-bc5b-9b21bfb3febd',
        type: 'noun',
        en: 'Canoe',
        pl: 'Kanu',
        jp: { text: 'カヌー' },
    },
    {
        id: '58f4a4ed-fc27-4c8e-8f6a-2a3681a920d7',
        type: 'noun',
        en: 'Herb',
        pl: 'Zioło',
        jp: { text: 'ハーブ' },
    },
    {
        id: '9d03f013-1663-4467-806f-8629fb710dc9',
        type: 'noun',
        en: 'Bikini',
        pl: 'Bikini',
        jp: { text: 'ビキニ' },
    },
    {
        id: 'a7f09841-d275-4659-8bf5-187c2a29f9b0',
        type: 'noun',
        en: 'Nuts',
        pl: 'Orzechy',
        jp: { text: 'ナッツ' },
    },
    {
        id: '319c6766-2c0c-4ce9-8f08-1cd97591a4ed',
        type: 'noun',
        en: 'Pet',
        pl: 'Zwierzę domowe',
        jp: { text: 'ペット' },
    },
    {
        id: 'e9f01b33-1055-489b-8962-413b8b38dcf0',
        type: 'noun',
        en: 'Connection / Pull',
        pl: 'Znajomość',
        jp: { text: 'コネ' },
    },
    {
        id: '2991fc03-984c-44f1-864f-f73b4b0fa1c8',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Happy',
        pl: 'Szczęśliwy',
        jp: { text: 'ハッピー' },
    },
    {
        id: '5cb2e77a-a9be-489c-b11a-3d56b0ab2e31',
        type: 'noun',
        en: 'Necktie',
        pl: 'Krawat',
        jp: { text: 'ネクタイ' },
    },
    {
        id: '901142cc-763b-42e6-adcf-f18aa413fd6c',
        type: 'noun',
        en: 'Notebook',
        pl: 'Zeszyt',
        jp: { text: 'ノート' },
    },
    {
        id: '91004ea2-bc0d-454c-9c30-310a140e1e76',
        type: 'noun',
        en: 'Class / Lesson',
        pl: 'Lekcja / Zajęcia',
        jp: { text: '授業', pronunciation: 'じゅぎょう' },
    },
    {
        id: '54abca7d-972d-4a80-ab1f-a509e866bfb7',
        type: 'noun',
        en: 'Sofa',
        pl: 'Kanapa',
        jp: { text: 'ソファ' },
    },
    {
        id: '01800b5b-e845-4363-a519-561d8359058b',
        type: 'phrase',
        en: "It's big and dirty.",
        pl: 'To jest duże i brudne.',
        jp: { text: '大きくて汚いです。', pronunciation: 'おおきくてきたないです。' },
    },
    {
        id: '3c6747b2-102c-4d7c-bbbb-fef6b512aa43',
        type: 'phrase',
        en: "It's good and dark.",
        pl: 'To jest dobre i ciemne.',
        jp: { text: 'よくて暗いです。', pronunciation: 'よくてくらいです。' },
    },
    {
        id: '1a85c526-4a1b-4ca4-ab50-cdeff2e29232',
        type: 'phrase',
        en: "He's skilled and kind.",
        pl: 'On jest zdolny i miły.',
        jp: { text: '上手で親切です。', pronunciation: 'じょうずでしんせつです。' },
    },
    {
        id: '6e49acb5-257c-4a63-8f7a-d825db792d66',
        type: 'phrase',
        en: "It's tough and expensive.",
        pl: 'To jest ciężkie i drogie.',
        jp: { text: '大変で高いです。', pronunciation: 'たいへんでたかいです。' },
    },
    {
        id: 'da54df2d-d9b8-4ae2-8022-3da62ee2a53e',
        type: 'phrase',
        en: "It's not big and it's weird.",
        pl: 'To nie jest duże i jest dziwne.',
        jp: { text: '大きくなくて変です。', pronunciation: 'おおきくなくてへんです。' },
    },
    {
        id: '9cddcc09-a966-4c91-acd5-7da759f1867e',
        type: 'phrase',
        en: "I'm not skilled and I'm short.",
        pl: 'Nie jestem zdolny i jestem niski.',
        jp: { text: '得意じゃなくて背が低いです。', pronunciation: 'とくいじゃなくてせがひくいです。' },
    },
];

export const sakura3_1Bag: WordBag = {
    id: '1c8429d9-bbc6-4127-b688-4b19b43694ca',
    name: 'Sakura #3.1',
    category: 'sakura',
    words: sakura_3_1,
};
