import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_3_9: TranslatedJapaneseText[] = [
    {
        id: '0aa4f401-19a1-4653-8806-9afe1dff722e',
        type: 'verb',
        verb_type: 'godan',
        en: 'Ride / Board',
        pl: 'Jechać / Wsiadać',
        jp: { text: '乗る', pronunciation: 'のる' },
    },
    {
        id: '6d01421c-7459-4f7e-b05f-ee9d13e7f483',
        type: 'phrase',
        en: 'I ride a bike every day.',
        pl: 'Jeżdżę na rowerze codziennie.',
        jp: { text: '毎日自転車に乗ります。', pronunciation: 'まいにちじてんしゃにのります。' },
    },
    {
        id: '67996680-45e1-44dc-8eb5-6e7b24b26279',
        type: 'noun',
        en: 'Example',
        pl: 'Przykład',
        jp: { text: '例', pronunciation: 'れい' },
    },
    {
        id: '04e3d548-6e6c-466f-9a5a-1a25e6d2d825',
        type: 'noun',
        en: 'Tree',
        pl: 'Drzewo',
        jp: { text: '木', pronunciation: 'き' },
    },
    {
        id: 'b43b29e7-e5e5-49fa-bdef-9ca1173dd2f9',
        type: 'noun',
        en: 'Crossword',
        pl: 'Krzyżówka',
        jp: { text: 'クロスワード' },
    },
    {
        id: 'c9f941df-598a-4e65-8630-50550502f197',
        type: 'noun',
        en: 'Locker',
        pl: 'Szafka (w szkole, na siłowni itp.)',
        jp: { text: 'ロッカー' },
    },
    {
        id: '286808bb-d17f-4844-ab5a-bebddc3b7ddf',
        type: 'noun',
        en: 'Pamphlet / Brochure',
        pl: 'Ulotka / Broszura',
        jp: { text: 'パンフレット' },
    },
    {
        id: 'cada4844-c10a-4db2-b1a1-2122b1d9ca4d',
        type: 'noun',
        en: 'Slippers',
        pl: 'Kapcie',
        jp: { text: 'スリッパ' },
    },
    {
        id: 'f9491c49-a16f-4d4e-99b8-de83bce3b489',
        type: 'noun',
        en: 'Athlete (loan word)',
        pl: 'Sportowiec (zapożyczone słowo)',
        jp: { text: 'アスリート' },
    },
    {
        id: '5f16dde8-1357-4bee-bfac-31d07a5113d4',
        type: 'noun',
        en: 'Athlete (native Japanese word)',
        pl: 'Sportowiec (rodzime japońskie słowo)',
        jp: { text: '選手', pronunciation: 'せんしゅ' },
    },
    {
        id: 'c69a4ff8-401e-4a2f-9714-6b3a71123f5d',
        type: 'noun',
        en: 'Pineapple',
        pl: 'Ananas',
        jp: { text: 'パイナップル' },
    },
    {
        id: 'ac8c8a86-ce6f-4ff5-a0c2-eca1afc121ea',
        type: 'noun',
        en: 'Airport',
        pl: 'Lotnisko',
        jp: { text: '空港', pronunciation: 'くうこう' },
    },
    {
        id: '9b5401f4-4775-46ea-a07b-5d771864ae75',
        type: 'noun',
        en: 'Bus terminal / Bus station',
        pl: 'Pętla autobusowa / Dworzec autobusowy',
        jp: { text: 'バス乗り場', pronunciation: 'バスのりば' },
    },
    {
        id: '115cb25b-f49d-4bb3-936a-7121cf3f6826',
        type: 'noun',
        en: 'Taxi stand',
        pl: 'Postój taksówek',
        jp: { text: 'タクシー乗り場', pronunciation: 'タクシーのりば' },
    },
    {
        id: '75399f69-0875-4511-856a-513e1bf94197',
        type: 'phrase',
        en: 'How / In what way / By what means',
        pl: 'Jak / W jaki sposób / Jakim środkiem',
        jp: { text: 'どうやって' },
    },
    {
        id: '1b9e873c-639b-4387-9508-65d91e5f4aad',
        type: 'phrase',
        en: 'How do you get to the station?',
        pl: 'Jak dostajesz się na stację?',
        jp: { text: 'どうやって駅に行きますか。', pronunciation: 'どうやってえきにいきますか。' },
    },
    {
        id: 'eb04c59e-af6e-45c0-82f8-0ee972101869',
        type: 'noun',
        en: 'Kilometer',
        pl: 'Kilometr',
        jp: { text: 'キロメートル' },
    },
    {
        id: 'd4fb3857-a406-4e9a-bcab-4b7c5b81e60b',
        type: 'adjective',
        adjective_type: 'na-adjective',
        en: 'Comfortable / Easy / Simple',
        pl: 'Wygodny / Swobodny / Prosty',
        jp: { text: '楽', pronunciation: 'らく' },
    },
    {
        id: '5adb4ac5-b156-4e85-a87f-30d0a7878ffe',
        type: 'verb',
        verb_type: 'ichidan',
        en: 'Get tired / Become exhausted',
        pl: 'Zmęczyć się / Stać się wyczerpanym',
        jp: { text: '疲れる', pronunciation: 'つかれる' },
    },
    {
        id: 'aeae7704-30e8-4481-9a7c-97d618eb21eb',
        type: 'noun',
        en: 'Camera',
        pl: 'Aparat fotograficzny',
        jp: { text: 'カメラ' },
    },
];

export const sakura3_9Bag: WordBag = {
    id: '05ef5d8c-856a-4956-94fc-d29bcb014286',
    name: 'Sakura #3.9',
    words: sakura_3_9,
};
