import type { TranslatedJapaneseText, WordBag } from '../../../types';

const sakura_3_8: TranslatedJapaneseText[] = [
    {
        id: 'ab22dc98-d27e-4596-99ec-09325d97a6e7',
        type: 'noun',
        en: 'Worry / Concern',
        pl: 'Zmartwienie / Troska',
        jp: { text: '心配', pronunciation: 'しんぱい' },
    },
    {
        id: '503b6fe5-5e0a-4ceb-9e9f-67373e5a49b8',
        type: 'phrase',
        en: "Please don't worry.",
        pl: 'Proszę się nie martwić.',
        jp: { text: '心配しないでください。', pronunciation: 'しんぱいしないでください。' },
    },
    {
        id: 'b5fccbc6-f78d-4340-9e20-f7a2bfc79490',
        type: 'noun',
        en: 'Failure / Mistake',
        pl: 'Porażka / Błąd',
        jp: { text: '失敗', pronunciation: 'しっぱい' },
    },
    {
        id: '97f81037-d2e1-4532-8a52-70467c360630',
        type: 'noun',
        en: 'Subway',
        pl: 'Metro',
        jp: { text: '地下鉄', pronunciation: 'ちかてつ' },
    },
    {
        id: 'ca0cc4a7-37ca-4e8a-a5f6-462adba9058e',
        type: 'noun',
        en: 'Vehicle / Transportation',
        pl: 'Pojazd / Transport',
        jp: { text: '乗り物', pronunciation: 'のりもの' },
    },
    {
        id: '197daba7-7eca-4506-9767-cc7d1e1c069b',
        type: 'noun',
        en: 'Taxi',
        pl: 'Taksówka',
        jp: { text: 'タクシー' },
    },
    {
        id: '8ea03a75-1790-4751-9563-8a42f006e40b',
        type: 'noun',
        en: 'Shinkansen',
        pl: 'Shinkansen',
        jp: { text: '新幹線', pronunciation: 'しんかんせん' },
    },
    {
        id: 'c060ea8d-45e0-41d2-8c2f-3033ada12ee7',
        type: 'noun',
        en: 'Motorcycle',
        pl: 'Motocykl',
        jp: { text: 'バイク' },
    },
    {
        id: 'f9975f6b-4ebe-4d8a-bbfa-8428425b045b',
        type: 'noun',
        en: 'Tram',
        pl: 'Tramwaj',
        jp: { text: '路面電車', pronunciation: 'ろめんでんしゃ' },
    },
    {
        id: 'ca107c15-f2e3-47b2-a005-0a1da9269ef9',
        type: 'noun',
        en: 'Adjective',
        pl: 'Przymiotnik',
        jp: { text: '形容詞', pronunciation: 'けいようし' },
    },
    {
        id: '32c50014-f766-46fb-9028-80773dfee5cf',
        type: 'noun',
        en: 'Noun',
        pl: 'Rzeczownik',
        jp: { text: '名詞', pronunciation: 'めいし' },
    },
    {
        id: '98f235fd-826a-426d-a4a4-ac8daeede47c',
        type: 'noun',
        en: 'Cathedral',
        pl: 'Katedra',
        jp: { text: '大聖堂', pronunciation: 'だいせいどう' },
    },
    {
        id: '848b88c0-b2f1-42a2-b85d-9d4cb4c99c88',
        type: 'noun',
        en: 'Pencil',
        pl: 'Ołówek',
        jp: { text: '鉛筆', pronunciation: 'えんぴつ' },
    },
    {
        id: '28a515fb-c4c7-42ae-b0a5-b76ddf67e2ca',
        type: 'noun',
        en: 'Tennis racket',
        pl: 'Rakieta tenisowa',
        jp: { text: 'ラケット' },
    },
    {
        id: '1a53f90f-5363-4fe8-bd49-02807dce66e9',
        type: 'noun',
        en: 'Door',
        pl: 'Drzwi',
        jp: { text: 'ドア' },
    },
    {
        id: '1b393adb-95a1-42e0-9398-36110eb75a39',
        type: 'noun',
        en: 'Wall',
        pl: 'Ściana',
        jp: { text: '壁', pronunciation: 'かべ' },
    },
    {
        id: '9b25a6b5-c5da-4d03-aa45-83ea93417aae',
        type: 'phrase',
        en: 'The painting is on the wall.',
        pl: 'Obraz jest na ścianie.',
        jp: { text: '壁に絵があります。', pronunciation: 'かべにえがあります。' },
    },
    {
        id: 'ebc7e3b2-669b-40f1-bf9b-a9de6faf6e65',
        type: 'noun',
        en: 'Post office',
        pl: 'Poczta',
        jp: { text: '郵便局', pronunciation: 'ゆうびんきょく' },
    },
    {
        id: '9228b84d-f2da-436a-a188-4398b42d74eb',
        type: 'noun',
        en: 'Church',
        pl: 'Kościół',
        jp: { text: '教会', pronunciation: 'きょうかい' },
    },
    {
        id: '195c87c0-5a18-4d45-b54c-4af314d8c587',
        type: 'phrase',
        en: "Q: Are you at home? A: I'm not at home.",
        pl: 'P: Czy jesteś w domu? O: Nie jestem w domu.',
        jp: {
            text: '家にいますか。いいえ、家にはいません。',
            pronunciation: 'いえにいますか。いいえ、いえにはいません。',
        },
        description: 'Pay attention to は particle used after に.',
    },
];

export const sakura3_8Bag: WordBag = {
    id: '7f29d60e-21ab-4262-8da4-f25f9a63e607',
    name: 'Sakura #3.8',
    words: sakura_3_8,
};
