import type { TranslatedJapaneseText, WordBag } from '../types';

const directions: TranslatedJapaneseText[] = [
    {
        id: '96215ac3-f229-4347-9f56-302a1cc42511',
        type: 'noun',
        en: 'Right',
        pl: 'Prawo',
        jp: { text: '右', pronunciation: 'みぎ' },
    },
    {
        id: '13d28589-c462-43f8-91f9-77bc8898471e',
        type: 'noun',
        en: 'Left',
        pl: 'Lewo',
        jp: { text: '左', pronunciation: 'ひだり' },
    },
    {
        id: '734aed9c-b93a-4747-88c2-67518d0bc90a',
        type: 'noun',
        en: 'Front',
        pl: 'Przód',
        jp: { text: '前', pronunciation: 'まえ' },
    },
    {
        id: '4f948994-fcde-4666-9841-d204a1423eb8',
        type: 'noun',
        en: 'Back / Rear',
        pl: 'Tył / Tylna część',
        jp: { text: '後ろ', pronunciation: 'うしろ' },
    },
    {
        id: '2f01ca25-377a-40c0-a037-5cfff8b8e0f5',
        type: 'noun',
        en: 'Inside',
        pl: 'Wewnątrz',
        jp: { text: '中', pronunciation: 'なか' },
    },
    {
        id: '6aeadd22-ef1d-43a6-a9be-26df845309dc',
        type: 'noun',
        en: 'On top of / Above',
        pl: 'Na / Nad',
        jp: { text: '上', pronunciation: 'うえ' },
    },
    {
        id: '59b41a57-2efb-404b-848b-05b586a31b27',
        type: 'noun',
        en: 'Under / Below',
        pl: 'Pod / Poniżej',
        jp: { text: '下', pronunciation: 'した' },
    },
    {
        id: '197ae887-8b25-4be5-900d-ce8f1ac75461',
        type: 'noun',
        en: 'Near / Close to',
        pl: 'Blisko',
        jp: { text: '近く', pronunciation: 'ちかく' },
    },
    {
        id: '3cb82585-200f-4fed-9eb8-6664b334bdd4',
        type: 'noun',
        en: 'Next to / Beside (same type / nothing in between)',
        pl: 'Obok (ten sam typ / nic pomiędzy)',
        jp: { text: '隣', pronunciation: 'となり' },
    },
    {
        id: '7a501b77-3d53-44d2-b711-e5fe8b599aa1',
        type: 'noun',
        en: 'Next to / Beside (can be of different type / something in between)',
        pl: 'Obok (może być inny typ / coś pomiędzy)',
        jp: { text: '横', pronunciation: 'よこ' },
    },
    {
        id: '3dfeca2e-a50c-485a-a575-6f128c7b5d58',
        type: 'noun',
        en: 'Between',
        pl: 'Pomiędzy',
        jp: { text: '間', pronunciation: 'あいだ' },
    },
    {
        id: 'd853a86a-4e4c-4a7f-8c6d-4e82eccc6d10',
        type: 'noun',
        en: 'Around / Surrounding',
        pl: 'Wokół / Otoczenie',
        jp: { text: '周り', pronunciation: 'まわり' },
    },
    {
        id: '74f25db6-d8e0-469f-89ca-58e509c19400',
        type: 'phrase',
        en: "It's between the bank and the post office.",
        pl: 'To jest pomiędzy bankiem a pocztą.',
        jp: { text: '銀行と郵便局の間です。', pronunciation: 'ぎんこうとゆうびんきょくのあいだです。' },
    },
    {
        id: 'eb22fa40-ca6f-496f-850d-5ab5c93fed6e',
        type: 'phrase',
        en: "I'm next to the supermarket.",
        pl: 'Jestem obok supermarketu.',
        jp: { text: 'スーパーの横にいます。', pronunciation: 'スーパーのよこにいます。' },
    },
    {
        id: 'a018c8c5-4c94-435e-9389-2f99805c6ae2',
        type: 'phrase',
        en: "It's to the right of the station.",
        pl: 'To jest po prawej stronie dworca.',
        jp: { text: '駅の右です。', pronunciation: 'えきのみぎです。' },
    },
    {
        id: '18b42d5c-c147-4391-bbf6-818f1e4d32a0',
        type: 'phrase',
        en: "It's in front of the hotel.",
        pl: 'To jest przed hotelem.',
        jp: { text: 'ホテルの前です。', pronunciation: 'ホテルのまえです。' },
    },
    {
        id: 'd9268df4-aae6-44fb-b387-935147dc3b01',
        type: 'phrase',
        en: "It's near the supermarket.",
        pl: 'To jest blisko supermarketu.',
        jp: { text: 'スーパーの近くです。', pronunciation: 'スーパーのちかくです。' },
    },
];

export const directionsBag: WordBag = {
    id: '3a3f535c-4618-47bc-9f4c-d519964637fb',
    name: 'Directions',
    words: directions,
};
