import type { JapaneseWord } from '../types';

export const direction: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Right',
        pl: 'Prawo',
        jp: '右',
        jp_pronunciation: 'みぎ',
    },
    {
        type: 'noun',
        en: 'Left',
        pl: 'Lewo',
        jp: '左',
        jp_pronunciation: 'ひだり',
    },
    {
        type: 'noun',
        en: 'Front',
        pl: 'Przód',
        jp: '前',
        jp_pronunciation: 'まえ',
    },
    {
        type: 'noun',
        en: 'Back / Rear',
        pl: 'Tył / Tylna część',
        jp: '後ろ',
        jp_pronunciation: 'うしろ',
    },
    {
        type: 'noun',
        en: 'Inside',
        pl: 'Wewnątrz',
        jp: '中',
        jp_pronunciation: 'なか',
    },
    {
        type: 'noun',
        en: 'On top of / Above',
        pl: 'Na / Nad',
        jp: '上',
        jp_pronunciation: 'うえ',
    },
    {
        type: 'noun',
        en: 'Under / Below',
        pl: 'Pod / Poniżej',
        jp: '下',
        jp_pronunciation: 'した',
    },
    {
        type: 'noun',
        en: 'Near / Close to',
        pl: 'Blisko',
        jp: '近く',
        jp_pronunciation: 'ちかく',
    },
    {
        type: 'noun',
        en: 'Next to / Beside',
        pl: 'Obok',
        jp: '隣',
        jp_pronunciation: 'となり',
    },
    {
        type: 'noun',
        en: 'Between',
        pl: 'Pomiędzy',
        jp: '間',
        jp_pronunciation: 'あいだ',
    },
    {
        type: 'phrase',
        en: "It's between the bank and the post office.",
        pl: 'To jest pomiędzy bankiem a pocztą.',
        jp: '銀行と郵便局の間です。',
        jp_pronunciation: 'ぎんこうとゆうびんきょくのあいだです。',
    },
    {
        type: 'phrase',
        en: "It's to the right of the station.",
        pl: 'To jest po prawej stronie dworca.',
        jp: '駅の右です。',
        jp_pronunciation: 'えきのみぎです。',
    },
    {
        type: 'phrase',
        en: "It's in front of the hotel.",
        pl: 'To jest przed hotelem.',
        jp: 'ホテルの前です。',
        jp_pronunciation: 'ホテルのまえです。',
    },
];
