import { type TranslatedJapaneseText, type WordBag } from '../types';

const family: TranslatedJapaneseText[] = [
    {
        id: '6493cb13-5af0-4089-b150-2bff4163d0ec',
        type: 'noun',
        en: 'Mom (honorific / direct)',
        pl: 'Mama (forma honoryfikatywna / bezpośrednia)',
        jp: { text: 'お母さん', pronunciation: 'おかあさん' },
    },
    {
        id: '9386457e-6d06-4546-9e8f-200516d1ee26',
        type: 'noun',
        en: 'Mom (humble)',
        pl: 'Mama (forma skromna)',
        jp: { text: '母', pronunciation: 'はは' },
    },
    {
        id: 'd9920737-0d04-4936-93d8-a619095d6408',
        type: 'noun',
        en: 'Dad (honorific / direct)',
        pl: 'Tata (forma honoryfikatywna / bezpośrednia)',
        jp: { text: 'お父さん', pronunciation: 'おとうさん' },
    },
    {
        id: '034730a8-b2af-41be-b08f-d6b54fb0a88e',
        type: 'noun',
        en: 'Dad (humble)',
        pl: 'Tata (forma skromna)',
        jp: { text: '父', pronunciation: 'ちち' },
    },
    {
        id: '6bb55648-4ba3-45e5-993f-47bc6e3cecd1',
        type: 'noun',
        en: 'Younger sister (honorific)',
        pl: 'Młodsza siostra (forma honoryfikatywna)',
        jp: { text: '妹さん', pronunciation: 'いもうとさん' },
    },
    {
        id: 'abf40077-c6e5-43b7-8b30-6bc0f9451da1',
        type: 'noun',
        en: 'Younger sister (humble)',
        pl: 'Młodsza siostra (forma skromna)',
        jp: { text: '妹', pronunciation: 'いもうと' },
    },
    {
        id: '979e79d9-c5d7-4439-af9b-711843393816',
        type: 'phrase',
        en: 'Younger sister (direct)',
        pl: 'Młodsza siostra (forma bezpośrednia)',
        jp: { text: 'Her name 😊' },
    },
    {
        id: 'bf1751bb-6c86-4bab-927b-06b0f19fe10a',
        type: 'noun',
        en: 'Younger brother (honorific)',
        pl: 'Młodszy brat (forma honoryfikatywna)',
        jp: { text: '弟さん', pronunciation: 'おとうとさん' },
    },
    {
        id: 'fbe55f2a-982e-41bd-bea3-cfe52e61bd53',
        type: 'noun',
        en: 'Younger brother (humble)',
        pl: 'Młodszy brat (forma skromna)',
        jp: { text: '弟', pronunciation: 'おとうと' },
    },
    {
        id: '4dbae313-16ae-4873-962c-0de1162299c0',
        type: 'noun',
        en: 'Younger brother (direct)',
        pl: 'Młodszy brat (forma bezpośrednia)',
        jp: { text: 'His name 😊' },
    },
    {
        id: '3705f61b-1855-431d-9c5a-163862a732bb',
        type: 'noun',
        en: 'Older sister (honorific)',
        pl: 'Starsza siostra (forma honoryfikatywna)',
        jp: { text: 'お姉さん', pronunciation: 'おねえさん' },
    },
    {
        id: '05739fe7-46ff-4795-81c9-a40d5050131d',
        type: 'noun',
        en: 'Older sister (humble)',
        pl: 'Starsza siostra (forma skromna)',
        jp: { text: '姉', pronunciation: 'あね' },
    },
    {
        id: 'd067311d-efb6-4ca6-a87d-11cd328f3008',
        type: 'noun',
        en: 'Older sister (direct)',
        pl: 'Starsza siostra (forma bezpośrednia)',
        jp: { text: 'お姉ちゃん', pronunciation: 'おねえちゃん' },
    },
    {
        id: '16cba31d-279f-4f3a-84d8-22e20e2fe6c5',
        type: 'noun',
        en: 'Older brother (honorific)',
        pl: 'Starszy brat (forma honoryfikatywna)',
        jp: { text: 'お兄さん', pronunciation: 'おにいさん' },
    },
    {
        id: 'aacdbe8c-e0d8-4104-a780-5dd1a26b91a6',
        type: 'noun',
        en: 'Older brother (humble)',
        pl: 'Starszy brat (forma skromna)',
        jp: { text: '兄', pronunciation: 'あに' },
    },
    {
        id: '6f3d5d40-0f66-4af8-865f-e8e7b3e86879',
        type: 'noun',
        en: 'Older brother (direct)',
        pl: 'Starszy brat (forma bezpośrednia)',
        jp: { text: 'お兄ちゃん', pronunciation: 'おにいちゃん' },
    },
    {
        id: '019615a4-f98a-4576-8cdb-8d425baee2f4',
        type: 'noun',
        en: 'Grandma (honorific)',
        pl: 'Babcia (forma honoryfikatywna)',
        jp: { text: 'おばあさん' },
    },
    {
        id: 'ab2f6401-113a-4c8f-93f3-33f7f45899c4',
        type: 'noun',
        en: 'Grandma (humble)',
        pl: 'Babcia (forma skromna)',
        jp: { text: '祖母', pronunciation: 'そぼ' },
    },
    {
        id: '965a795e-6b78-49bd-bc52-15242f9644bb',
        type: 'noun',
        en: 'Grandma (direct)',
        pl: 'Babcia (forma bezpośrednia)',
        jp: { text: 'おばあちゃん' },
    },
    {
        id: '2a025585-35e3-40e5-b3f4-8f31f93fcbf1',
        type: 'noun',
        en: 'Grandpa (honorific)',
        pl: 'Dziadek (forma honoryfikatywna)',
        jp: { text: 'おじいさん' },
    },
    {
        id: 'a94af82f-ea7c-4613-95b7-90a0be021d13',
        type: 'noun',
        en: 'Grandpa (humble)',
        pl: 'Dziadek (forma skromna)',
        jp: { text: '祖父', pronunciation: 'そふ' },
    },
    {
        id: '52a5b3c9-5e3d-4f05-8d0b-805122128f89',
        type: 'noun',
        en: 'Grandpa (direct)',
        pl: 'Dziadek (forma bezpośrednia)',
        jp: { text: 'おじいちゃん' },
    },
    {
        id: 'b394f2dc-c171-4940-8185-3122272f3d0c',
        type: 'noun',
        en: 'Husband (honorific)',
        pl: 'Mąż (forma honoryfikatywna)',
        jp: { text: 'ご主人', pronunciation: 'ごしゅじん' },
    },
    {
        id: '2b926d05-b6f6-4977-b267-992798aee0f0',
        type: 'noun',
        en: 'Husband (humble)',
        pl: 'Mąż (forma skromna)',
        jp: { text: '夫', pronunciation: 'おっと' },
    },
    {
        id: '0ee94ed4-c5d2-4809-89c4-bd4b54d16a81',
        type: 'noun',
        en: 'Wife (honorific)',
        pl: 'Żona (forma honoryfikatywna)',
        jp: { text: '奥さん', pronunciation: 'おくさん' },
    },
    {
        id: '3014ede6-6c68-4c1e-afe4-da54a65f2b3b',
        type: 'noun',
        en: 'Wife (humble)',
        pl: 'Żona (forma skromna)',
        jp: { text: '妻', pronunciation: 'つま' },
    },
    {
        id: 'a2a1c491-bd1d-495e-851a-aebd2a9ca0b1',
        type: 'noun',
        en: 'Son (humble)',
        pl: 'Syn (forma skromna)',
        jp: { text: '息子', pronunciation: 'むすこ' },
    },
    {
        id: '5888e1fb-dce1-49a8-9193-62105a840be3',
        type: 'noun',
        en: 'Son (honorific)',
        pl: 'Syn (forma honoryfikatywna)',
        jp: { text: '息子さん', pronunciation: 'むすこさん' },
    },
    {
        id: 'a1c323bf-08f9-4579-abf7-1a62f6dbd455',
        type: 'noun',
        en: 'Daughter (humble)',
        pl: 'Córka (forma skromna)',
        jp: { text: '娘', pronunciation: 'むすめ' },
    },
    {
        id: 'fda4816e-510c-4776-9092-a78ccd52834b',
        type: 'noun',
        en: 'Daughter (honorific)',
        pl: 'Córka (forma honoryfikatywna)',
        jp: { text: '娘さん', pronunciation: 'むすめさん' },
    },
    {
        id: '4be125b1-147e-4e52-a9bc-f85fa2424f64',
        type: 'noun',
        en: 'Child (humble)',
        pl: 'Dziecko (forma skromna)',
        jp: { text: '子供', pronunciation: 'こども' },
    },
    {
        id: '973db874-e1de-4bc0-aed5-ab033854a0ba',
        type: 'noun',
        en: 'Child (honorific)',
        pl: 'Dziecko (forma honoryfikatywna)',
        jp: { text: 'お子さん', pronunciation: 'おこさん' },
    },
    {
        id: 'f2421853-e0fb-4fe2-888d-492a6c45d483',
        type: 'noun',
        en: 'Aunt (honorific)',
        pl: 'Ciocia (forma honoryfikatywna)',
        jp: { text: '叔母さん', pronunciation: 'おばさん' },
    },
    {
        id: '68ea4404-6567-4d91-b8ee-fa9e258539a6',
        type: 'noun',
        en: 'Aunt (humble)',
        pl: 'Ciocia (forma skromna)',
        jp: { text: '叔母', pronunciation: 'おば' },
    },
    {
        id: 'cbd12409-6a03-488d-967f-34c7686ae661',
        type: 'noun',
        en: 'Uncle (honorific)',
        pl: 'Wujek (forma honoryfikatywna)',
        jp: { text: '叔父さん', pronunciation: 'おじさん' },
    },
    {
        id: '09d9f5e7-e870-4315-b806-5c6575db1714',
        type: 'noun',
        en: 'Uncle (humble)',
        pl: 'Wujek (forma skromna)',
        jp: { text: '叔父', pronunciation: 'おじ' },
    },
    {
        id: '544c2c99-1d89-464a-a33b-f22590e0e7a2',
        type: 'noun',
        en: 'Parents (both) (humble)',
        pl: 'Rodzice (dwoje) (forma skromna)',
        jp: { text: '両親', pronunciation: 'りょうしん' },
    },
    {
        id: '41c97dff-1f46-4155-a02e-de00deeed5f7',
        type: 'noun',
        en: 'Parents (both) (honorific)',
        pl: 'Rodzice (dwoje) (forma honoryfikatywna)',
        jp: { text: 'ご両親', pronunciation: 'ごりょうしん' },
    },
    {
        id: '119ed9b9-1508-4870-9874-5b71ad99b8f6',
        type: 'noun',
        en: 'Parent (one) (humble)',
        pl: 'Rodzic (jeden) (forma skromna)',
        jp: { text: '親', pronunciation: 'おや' },
    },
    {
        id: 'bfe49e0b-2d18-4a5d-abfc-0565685ad757',
        type: 'noun',
        en: 'Parent (one) (honorific)',
        pl: 'Rodzic (jeden) (forma honoryfikatywna)',
        jp: { text: '親御さん', pronunciation: 'おやごさん' },
    },
    {
        id: '2adc727a-6048-4eb5-8640-6b931930e5ad',
        type: 'noun',
        en: 'Siblings / Brothers (humble)',
        pl: 'Rodzeństwo / Bracia (forma skromna)',
        jp: { text: '兄弟', pronunciation: 'きょうだい' },
    },
    {
        id: '403d8eff-bf26-46d8-a0a7-71db5956332f',
        type: 'noun',
        en: 'Siblings / Brothers (honorific)',
        pl: 'Rodzeństwo / Bracia (forma honoryfikatywna)',
        jp: { text: 'ご兄弟', pronunciation: 'ごきょうだい' },
    },
    {
        id: '545e12db-5df9-4dec-8ab9-95f8d8e63f4f',
        type: 'noun',
        en: 'Sisters (humble)',
        pl: 'Siostry (forma skromna)',
        jp: { text: '姉妹', pronunciation: 'しまい' },
    },
    {
        id: '3afc957a-2f50-4584-8197-4aada9d7d8ec',
        type: 'noun',
        en: 'Sisters (honorific)',
        pl: 'Siostry (forma honoryfikatywna)',
        jp: { text: 'ご姉妹', pronunciation: 'ごしまい' },
    },
    {
        id: '1fcd093f-abca-4ae5-b96e-b27a8643cd6e',
        type: 'noun',
        en: 'Cousin (humble)',
        pl: 'Kuzyn / Kuzynka (forma skromna)',
        jp: { text: 'いとこ' },
    },
    {
        id: '444e3c76-ee58-4198-b230-63f433ec39e4',
        type: 'noun',
        en: 'Cousin (honorific)',
        pl: 'Kuzyn / Kuzynka (forma honoryfikatywna)',
        jp: { text: 'いとこさん' },
    },
    {
        id: 'a135be66-89f5-49ca-9d27-92cedb9aac12',
        type: 'noun',
        en: 'Niece (humble)',
        pl: 'Bratanica / Siostrzenica (forma skromna)',
        jp: { text: '姪', pronunciation: 'めい' },
    },
    {
        id: '7f7673f5-d94f-4312-ad2e-ecb96d1e7839',
        type: 'noun',
        en: 'Niece (honorific)',
        pl: 'Bratanica / Siostrzenica (forma honoryfikatywna)',
        jp: { text: '姪御さん', pronunciation: 'めいごさん' },
    },
    {
        id: 'aea44875-2e08-4e9a-997e-36586aecd701',
        type: 'noun',
        en: 'Nephew (humble)',
        pl: 'Bratanek / Siostrzeniec (forma skromna)',
        jp: { text: '甥', pronunciation: 'おい' },
    },
    {
        id: '76780ba8-849a-457b-9f08-91a49a8fadcb',
        type: 'noun',
        en: 'Nephew (honorific)',
        pl: 'Bratanek / Siostrzeniec (forma honoryfikatywna)',
        jp: { text: '甥御さん', pronunciation: 'おいごさん' },
    },
    {
        id: 'bfd16d2c-3fed-40a0-b5f1-294f6e7f5f08',
        type: 'noun',
        en: 'Grandparents (humble)',
        pl: 'Dziadkowie (forma skromna)',
        jp: { text: '祖父母', pronunciation: 'そふぼ' },
    },
    {
        id: '034b5d7d-7aa1-4bba-9449-ef0ae25c0b94',
        type: 'phrase',
        en: 'Grandparents (honorific)',
        pl: 'Dziadkowie (forma honoryfikatywna)',
        jp: { text: 'お祖父さんとお祖母さん', pronunciation: 'おじいさんとおばあさん' },
    },
];

export const familyBag: WordBag = {
    id: '83be35f1-ba1d-4a71-86df-1a52fc4b51ce',
    name: 'Family',
    category: 'essentials',
    words: family,
};
