import { type TranslatedJapaneseText, type WordBag } from '../types';

const family: TranslatedJapaneseText[] = [
    {
        type: 'noun',
        en: 'Mom (honorific / direct)',
        pl: 'Mama (forma honoryfikatywna / bezpośrednia)',
        jp: { text: 'お母さん', pronunciation: 'おかあさん' },
    },
    {
        type: 'noun',
        en: 'Mom (humble)',
        pl: 'Mama (forma skromna)',
        jp: { text: '母', pronunciation: 'はは' },
    },
    {
        type: 'noun',
        en: 'Dad (honorific / direct)',
        pl: 'Tata (forma honoryfikatywna / bezpośrednia)',
        jp: { text: 'お父さん', pronunciation: 'おとうさん' },
    },
    {
        type: 'noun',
        en: 'Dad (humble)',
        pl: 'Tata (forma skromna)',
        jp: { text: '父', pronunciation: 'ちち' },
    },
    {
        type: 'noun',
        en: 'Younger sister (honorific)',
        pl: 'Młodsza siostra (forma honoryfikatywna)',
        jp: { text: '妹さん', pronunciation: 'いもうとさん' },
    },
    {
        type: 'noun',
        en: 'Younger sister (humble)',
        pl: 'Młodsza siostra (forma skromna)',
        jp: { text: '妹', pronunciation: 'いもうと' },
    },
    {
        type: 'phrase',
        en: 'Younger sister (direct)',
        pl: 'Młodsza siostra (forma bezpośrednia)',
        jp: { text: 'Her name 😊' },
    },
    {
        type: 'noun',
        en: 'Younger brother (honorific)',
        pl: 'Młodszy brat (forma honoryfikatywna)',
        jp: { text: '弟さん', pronunciation: 'おとうとさん' },
    },
    {
        type: 'noun',
        en: 'Younger brother (humble)',
        pl: 'Młodszy brat (forma skromna)',
        jp: { text: '弟', pronunciation: 'おとうと' },
    },
    {
        type: 'noun',
        en: 'Younger brother (direct)',
        pl: 'Młodszy brat (forma bezpośrednia)',
        jp: { text: 'His name 😊' },
    },
    {
        type: 'noun',
        en: 'Older sister (honorific)',
        pl: 'Starsza siostra (forma honoryfikatywna)',
        jp: { text: 'お姉さん', pronunciation: 'おねえさん' },
    },
    {
        type: 'noun',
        en: 'Older sister (humble)',
        pl: 'Starsza siostra (forma skromna)',
        jp: { text: '姉', pronunciation: 'あね' },
    },
    {
        type: 'noun',
        en: 'Older sister (direct)',
        pl: 'Starsza siostra (forma bezpośrednia)',
        jp: { text: 'お姉ちゃん', pronunciation: 'おねえちゃん' },
    },
    {
        type: 'noun',
        en: 'Older brother (honorific)',
        pl: 'Starszy brat (forma honoryfikatywna)',
        jp: { text: 'お兄さん', pronunciation: 'おにいさん' },
    },
    {
        type: 'noun',
        en: 'Older brother (humble)',
        pl: 'Starszy brat (forma skromna)',
        jp: { text: '兄', pronunciation: 'あに' },
    },
    {
        type: 'noun',
        en: 'Older brother (direct)',
        pl: 'Starszy brat (forma bezpośrednia)',
        jp: { text: 'お兄ちゃん', pronunciation: 'おにいちゃん' },
    },
    {
        type: 'noun',
        en: 'Grandma (honorific)',
        pl: 'Babcia (forma honoryfikatywna)',
        jp: { text: 'おばあさん' },
    },
    {
        type: 'noun',
        en: 'Grandma (humble)',
        pl: 'Babcia (forma skromna)',
        jp: { text: '祖母', pronunciation: 'そぼ' },
    },
    {
        type: 'noun',
        en: 'Grandma (direct)',
        pl: 'Babcia (forma bezpośrednia)',
        jp: { text: 'おばあちゃん' },
    },
    {
        type: 'noun',
        en: 'Grandpa (honorific)',
        pl: 'Dziadek (forma honoryfikatywna)',
        jp: { text: 'おじいさん' },
    },
    {
        type: 'noun',
        en: 'Grandpa (humble)',
        pl: 'Dziadek (forma skromna)',
        jp: { text: '祖父', pronunciation: 'そふ' },
    },
    {
        type: 'noun',
        en: 'Grandpa (direct)',
        pl: 'Dziadek (forma bezpośrednia)',
        jp: { text: 'おじいちゃん' },
    },
    {
        type: 'noun',
        en: 'Husband (honorific)',
        pl: 'Mąż (forma honoryfikatywna)',
        jp: { text: 'ご主人', pronunciation: 'ごしゅじん' },
    },
    {
        type: 'noun',
        en: 'Husband (humble)',
        pl: 'Mąż (forma skromna)',
        jp: { text: '夫', pronunciation: 'おっと' },
    },
    {
        type: 'noun',
        en: 'Wife (honorific)',
        pl: 'Żona (forma honoryfikatywna)',
        jp: { text: '奥さん', pronunciation: 'おくさん' },
    },
    {
        type: 'noun',
        en: 'Wife (humble)',
        pl: 'Żona (forma skromna)',
        jp: { text: '妻', pronunciation: 'つま' },
    },
    {
        type: 'noun',
        en: 'Son (humble)',
        pl: 'Syn (forma skromna)',
        jp: { text: '息子', pronunciation: 'むすこ' },
    },
    {
        type: 'noun',
        en: 'Son (honorific)',
        pl: 'Syn (forma honoryfikatywna)',
        jp: { text: '息子さん', pronunciation: 'むすこさん' },
    },
    {
        type: 'noun',
        en: 'Daughter (humble)',
        pl: 'Córka (forma skromna)',
        jp: { text: '娘', pronunciation: 'むすめ' },
    },
    {
        type: 'noun',
        en: 'Daughter (honorific)',
        pl: 'Córka (forma honoryfikatywna)',
        jp: { text: '娘さん', pronunciation: 'むすめさん' },
    },
    {
        type: 'noun',
        en: 'Child (humble)',
        pl: 'Dziecko (forma skromna)',
        jp: { text: '子供', pronunciation: 'こども' },
    },
    {
        type: 'noun',
        en: 'Child (honorific)',
        pl: 'Dziecko (forma honoryfikatywna)',
        jp: { text: 'お子さん', pronunciation: 'おこさん' },
    },
    {
        type: 'noun',
        en: 'Aunt (honorific)',
        pl: 'Ciocia (forma honoryfikatywna)',
        jp: { text: '叔母さん', pronunciation: 'おばさん' },
    },
    {
        type: 'noun',
        en: 'Aunt (humble)',
        pl: 'Ciocia (forma skromna)',
        jp: { text: '叔母', pronunciation: 'おば' },
    },
    {
        type: 'noun',
        en: 'Uncle (honorific)',
        pl: 'Wujek (forma honoryfikatywna)',
        jp: { text: '叔父さん', pronunciation: 'おじさん' },
    },
    {
        type: 'noun',
        en: 'Uncle (humble)',
        pl: 'Wujek (forma skromna)',
        jp: { text: '叔父', pronunciation: 'おじ' },
    },
    {
        type: 'noun',
        en: 'Parents (both) (humble)',
        pl: 'Rodzice (dwoje) (forma skromna)',
        jp: { text: '両親', pronunciation: 'りょうしん' },
    },
    {
        type: 'noun',
        en: 'Parents (both) (honorific)',
        pl: 'Rodzice (dwoje) (forma honoryfikatywna)',
        jp: { text: 'ご両親', pronunciation: 'ごりょうしん' },
    },
    {
        type: 'noun',
        en: 'Parent (one) (humble)',
        pl: 'Rodzic (jeden) (forma skromna)',
        jp: { text: '親', pronunciation: 'おや' },
    },
    {
        type: 'noun',
        en: 'Parent (one) (honorific)',
        pl: 'Rodzic (jeden) (forma honoryfikatywna)',
        jp: { text: '親御さん', pronunciation: 'おやごさん' },
    },
    {
        type: 'noun',
        en: 'Sibling(s) (humble)',
        pl: 'Rodzeństwo (forma skromna)',
        jp: { text: '兄弟', pronunciation: 'きょうだい' },
    },
    {
        type: 'noun',
        en: 'Sibling(s) (honorific)',
        pl: 'Rodzeństwo (forma honoryfikatywna)',
        jp: { text: 'ご兄弟', pronunciation: 'ごきょうだい' },
    },
];

export const familyBag: WordBag = {
    id: '83be35f1-ba1d-4a71-86df-1a52fc4b51ce',
    name: 'Family',
    words: family,
};
