import { type JapaneseWord } from '../types.ts';

export const family: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Mom (honorific / direct)',
        pl: 'Mama (forma honoryfikatywna / bezpośrednia)',
        jp: 'お母さん',
        jp_pronunciation: 'おかあさん',
    },
    {
        type: 'noun',
        en: 'Mom (humble)',
        pl: 'Mama (forma skromna)',
        jp: '母',
        jp_pronunciation: 'はは',
    },
    {
        type: 'noun',
        en: 'Dad (honorific / direct)',
        pl: 'Tata (forma honoryfikatywna / bezpośrednia)',
        jp: 'お父さん',
        jp_pronunciation: 'おとうさん',
    },
    {
        type: 'noun',
        en: 'Dad (humble)',
        pl: 'Tata (forma skromna)',
        jp: '父',
        jp_pronunciation: 'ちち',
    },
    {
        type: 'noun',
        en: 'Younger sister (honorific)',
        pl: 'Młodsza siostra (forma honoryfikatywna)',
        jp: '妹さん',
        jp_pronunciation: 'いもうとさん',
    },
    {
        type: 'noun',
        en: 'Younger sister (humble)',
        pl: 'Młodsza siostra (forma skromna)',
        jp: '妹',
        jp_pronunciation: 'いもうと',
    },
    {
        type: 'phrase',
        en: 'Younger sister (direct)',
        pl: 'Młodsza siostra (forma bezpośrednia)',
        jp: 'Her name 😊',
    },
    {
        type: 'noun',
        en: 'Younger brother (honorific)',
        pl: 'Młodszy brat (forma honoryfikatywna)',
        jp: '弟さん',
        jp_pronunciation: 'おとうとさん',
    },
    {
        type: 'noun',
        en: 'Younger brother (humble)',
        pl: 'Młodszy brat (forma skromna)',
        jp: '弟',
        jp_pronunciation: 'おとうと',
    },
    {
        type: 'noun',
        en: 'Younger brother (direct)',
        pl: 'Młodszy brat (forma bezpośrednia)',
        jp: 'His name 😊',
    },
    {
        type: 'noun',
        en: 'Older sister (honorific)',
        pl: 'Starsza siostra (forma honoryfikatywna)',
        jp: 'お姉さん',
        jp_pronunciation: 'おねえさん',
    },
    {
        type: 'noun',
        en: 'Older sister (humble)',
        pl: 'Starsza siostra (forma skromna)',
        jp: '姉',
        jp_pronunciation: 'あね',
    },
    {
        type: 'noun',
        en: 'Older sister (direct)',
        pl: 'Starsza siostra (forma bezpośrednia)',
        jp: 'お姉ちゃん',
        jp_pronunciation: 'おねえちゃん',
    },
    {
        type: 'noun',
        en: 'Older brother (honorific)',
        pl: 'Starszy brat (forma honoryfikatywna)',
        jp: 'お兄さん',
        jp_pronunciation: 'おにいさん',
    },
    {
        type: 'noun',
        en: 'Older brother (humble)',
        pl: 'Starszy brat (forma skromna)',
        jp: '兄',
        jp_pronunciation: 'あに',
    },
    {
        type: 'noun',
        en: 'Older brother (direct)',
        pl: 'Starszy brat (forma bezpośrednia)',
        jp: 'お兄ちゃん',
        jp_pronunciation: 'おにいちゃん',
    },
    {
        type: 'noun',
        en: 'Grandma (honorific)',
        pl: 'Babcia (forma honoryfikatywna)',
        jp: 'おばあさん',
    },
    {
        type: 'noun',
        en: 'Grandma (humble)',
        pl: 'Babcia (forma skromna)',
        jp: '祖母',
        jp_pronunciation: 'そぼ',
    },
    {
        type: 'noun',
        en: 'Grandma (direct)',
        pl: 'Babcia (forma bezpośrednia)',
        jp: 'おばあちゃん',
    },
    {
        type: 'noun',
        en: 'Grandpa (honorific)',
        pl: 'Dziadek (forma honoryfikatywna)',
        jp: 'おじいさん',
    },
    {
        type: 'noun',
        en: 'Grandpa (humble)',
        pl: 'Dziadek (forma skromna)',
        jp: '祖父',
        jp_pronunciation: 'そふ',
    },
    {
        type: 'noun',
        en: 'Grandpa (direct)',
        pl: 'Dziadek (forma bezpośrednia)',
        jp: 'おじいちゃん',
    },
    {
        type: 'noun',
        en: 'Husband (honorific)',
        pl: 'Mąż (forma honoryfikatywna)',
        jp: 'ご主人',
        jp_pronunciation: 'ごしゅじん',
    },
    {
        type: 'noun',
        en: 'Husband (humble)',
        pl: 'Mąż (forma skromna)',
        jp: '夫',
        jp_pronunciation: 'おっと',
    },
    {
        type: 'noun',
        en: 'Wife (honorific)',
        pl: 'Żona (forma honoryfikatywna)',
        jp: '奥さん',
        jp_pronunciation: 'おくさん',
    },
    {
        type: 'noun',
        en: 'Wife (humble)',
        pl: 'Żona (forma skromna)',
        jp: '妻',
        jp_pronunciation: 'つま',
    },
    {
        type: 'noun',
        en: 'Son (humble)',
        pl: 'Syn (forma skromna)',
        jp: '息子',
        jp_pronunciation: 'むすこ',
    },
    {
        type: 'noun',
        en: 'Son (honorific)',
        pl: 'Syn (forma honoryfikatywna)',
        jp: '息子さん',
        jp_pronunciation: 'むすこさん',
    },
    {
        type: 'noun',
        en: 'Daughter (humble)',
        pl: 'Córka (forma skromna)',
        jp: '娘',
        jp_pronunciation: 'むすめ',
    },
    {
        type: 'noun',
        en: 'Daughter (honorific)',
        pl: 'Córka (forma honoryfikatywna)',
        jp: '娘さん',
        jp_pronunciation: 'むすめさん',
    },
    {
        type: 'noun',
        en: 'Child (humble)',
        pl: 'Dziecko (forma skromna)',
        jp: '子供',
        jp_pronunciation: 'こども',
    },
    {
        type: 'noun',
        en: 'Child (honorific)',
        pl: 'Dziecko (forma honoryfikatywna)',
        jp: 'お子さん',
        jp_pronunciation: 'おこさん',
    },
    {
        type: 'noun',
        en: 'Aunt (honorific)',
        pl: 'Ciocia (forma honoryfikatywna)',
        jp: '叔母さん',
        jp_pronunciation: 'おばさん',
    },
    {
        type: 'noun',
        en: 'Aunt (humble)',
        pl: 'Ciocia (forma skromna)',
        jp: '叔母',
        jp_pronunciation: 'おば',
    },
    {
        type: 'noun',
        en: 'Uncle (honorific)',
        pl: 'Wujek (forma honoryfikatywna)',
        jp: '叔父さん',
        jp_pronunciation: 'おじさん',
    },
    {
        type: 'noun',
        en: 'Uncle (humble)',
        pl: 'Wujek (forma skromna)',
        jp: '叔父',
        jp_pronunciation: 'おじ',
    },
    {
        type: 'noun',
        en: 'Parents (both) (humble)',
        pl: 'Rodzice (dwoje) (forma skromna)',
        jp: '両親',
        jp_pronunciation: 'りょうしん',
    },
    {
        type: 'noun',
        en: 'Parents (both) (honorific)',
        pl: 'Rodzice (dwoje) (forma honoryfikatywna)',
        jp: 'ご両親',
        jp_pronunciation: 'ごりょうしん',
    },
    {
        type: 'noun',
        en: 'Parent (one) (humble)',
        pl: 'Rodzic (jeden) (forma skromna)',
        jp: '親',
        jp_pronunciation: 'おや',
    },
    {
        type: 'noun',
        en: 'Parent (one) (honorific)',
        pl: 'Rodzic (jeden) (forma honoryfikatywna)',
        jp: '親御さん',
        jp_pronunciation: 'おやごさん',
    },
    {
        type: 'noun',
        en: 'Sibling(s) (humble)',
        pl: 'Rodzeństwo (forma skromna)',
        jp: '兄弟',
        jp_pronunciation: 'きょうだい',
    },
    {
        type: 'noun',
        en: 'Sibling(s) (honorific)',
        pl: 'Rodzeństwo (forma honoryfikatywna)',
        jp: 'ご兄弟',
        jp_pronunciation: 'ごきょうだい',
    },
];
