import type { JapaneseWord } from '../types.ts';

export const months: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'January',
        pl: 'Styczeń',
        jp: '一月',
        jp_pronunciation: 'いちがつ',
    },
    {
        type: 'noun',
        en: 'February',
        pl: 'Luty',
        jp: '二月',
        jp_pronunciation: 'にがつ',
    },
    {
        type: 'noun',
        en: 'March',
        pl: 'Marzec',
        jp: '三月',
        jp_pronunciation: 'さんがつ',
    },
    {
        type: 'noun',
        en: 'April',
        pl: 'Kwiecień',
        jp: '四月',
        jp_pronunciation: 'しがつ',
    },
    {
        type: 'noun',
        en: 'May',
        pl: 'Maj',
        jp: '五月',
        jp_pronunciation: 'ごがつ',
    },
    {
        type: 'noun',
        en: 'June',
        pl: 'Czerwiec',
        jp: '六月',
        jp_pronunciation: 'ろくがつ',
    },
    {
        type: 'noun',
        en: 'July',
        pl: 'Lipiec',
        jp: '七月',
        jp_pronunciation: 'しちがつ',
    },
    {
        type: 'noun',
        en: 'August',
        pl: 'Sierpień',
        jp: '八月',
        jp_pronunciation: 'はちがつ',
    },
    {
        type: 'noun',
        en: 'September',
        pl: 'Wrzesień',
        jp: '九月',
        jp_pronunciation: 'くがつ',
    },
    {
        type: 'noun',
        en: 'October',
        pl: 'Październik',
        jp: '十月',
        jp_pronunciation: 'じゅうがつ',
    },
    {
        type: 'noun',
        en: 'November',
        pl: 'Listopad',
        jp: '十一月',
        jp_pronunciation: 'じゅういちがつ',
    },
    {
        type: 'noun',
        en: 'December',
        pl: 'Grudzień',
        jp: '十二月',
        jp_pronunciation: 'じゅうにがつ',
    },
];
