import type { TranslatedJapaneseText } from '../types';

export const numbers: TranslatedJapaneseText[] = [
    {
        type: 'numeral',
        en: 'One',
        pl: 'Jeden',
        jp: { text: '一', pronunciation: 'いち' },
    },
    {
        type: 'numeral',
        en: 'Two',
        pl: 'Dwa',
        jp: { text: '二', pronunciation: 'に' },
    },
    {
        type: 'numeral',
        en: 'Three',
        pl: 'Trzy',
        jp: { text: '三', pronunciation: 'さん' },
    },
    {
        type: 'numeral',
        en: 'Four',
        pl: 'Cztery',
        jp: { text: '四', pronunciation: 'よん' },
    },
    {
        type: 'numeral',
        en: 'Five',
        pl: 'Pięć',
        jp: { text: '五', pronunciation: 'ご' },
    },
    {
        type: 'numeral',
        en: 'Six',
        pl: 'Sześć',
        jp: { text: '六', pronunciation: 'ろく' },
    },
    {
        type: 'numeral',
        en: 'Seven',
        pl: 'Siedem',
        jp: { text: '七', pronunciation: 'なな' },
    },
    {
        type: 'numeral',
        en: 'Eight',
        pl: 'Osiem',
        jp: { text: '八', pronunciation: 'はち' },
    },
    {
        type: 'numeral',
        en: 'Nine',
        pl: 'Dziewięć',
        jp: { text: '九', pronunciation: 'きゅう' },
    },
    {
        type: 'numeral',
        en: 'Ten',
        pl: 'Dziesięć',
        jp: { text: '十', pronunciation: 'じゅう' },
    },
    {
        type: 'numeral',
        en: 'Eleven',
        pl: 'Jedenaście',
        jp: { text: '十一', pronunciation: 'じゅういち' },
    },
    {
        type: 'numeral',
        en: 'Twelve',
        pl: 'Dwanaście',
        jp: { text: '十二', pronunciation: 'じゅうに' },
    },
    {
        type: 'numeral',
        en: 'Thirteen',
        pl: 'Trzynaście',
        jp: { text: '十三', pronunciation: 'じゅうさん' },
    },
    {
        type: 'numeral',
        en: 'Fourteen',
        pl: 'Czternaście',
        jp: { text: '十四', pronunciation: 'じゅうよん' },
    },
    {
        type: 'numeral',
        en: 'Fifteen',
        pl: 'Piętnaście',
        jp: { text: '十五', pronunciation: 'じゅうご' },
    },
    {
        type: 'numeral',
        en: 'Sixteen',
        pl: 'Szesnaście',
        jp: { text: '十六', pronunciation: 'じゅうろく' },
    },
    {
        type: 'numeral',
        en: 'Seventeen',
        pl: 'Siedemnaście',
        jp: { text: '十七', pronunciation: 'じゅうなな' },
    },
    {
        type: 'numeral',
        en: 'Eighteen',
        pl: 'Osiemnaście',
        jp: { text: '十八', pronunciation: 'じゅうはち' },
    },
    {
        type: 'numeral',
        en: 'Nineteen',
        pl: 'Dziewiętnaście',
        jp: { text: '十九', pronunciation: 'じゅうきゅう' },
    },
    {
        type: 'numeral',
        en: 'Twenty',
        pl: 'Dwadzieścia',
        jp: { text: '二十', pronunciation: 'にじゅう' },
    },
    {
        type: 'numeral',
        en: 'Thirty',
        pl: 'Trzydzieści',
        jp: { text: '三十', pronunciation: 'さんじゅう' },
    },
    {
        type: 'numeral',
        en: 'One hundred',
        pl: 'Sto',
        jp: { text: '百', pronunciation: 'ひゃく' },
    },
    {
        type: 'numeral',
        en: 'Two hundred',
        pl: 'Dwieście',
        jp: { text: '二百', pronunciation: 'にひゃく' },
    },
    {
        type: 'numeral',
        en: 'Three hundred',
        pl: 'Trzysta',
        jp: { text: '三百', pronunciation: 'さんびゃく' },
    },
    {
        type: 'numeral',
        en: 'Four hundred',
        pl: 'Czterysta',
        jp: { text: '四百', pronunciation: 'よんひゃく' },
    },
    {
        type: 'numeral',
        en: 'Five hundred',
        pl: 'Pięćset',
        jp: { text: '五百', pronunciation: 'ごひゃく' },
    },
    {
        type: 'numeral',
        en: 'Six hundred',
        pl: 'Sześćset',
        jp: { text: '六百', pronunciation: 'ろっぴゃく' },
    },
    {
        type: 'numeral',
        en: 'Seven hundred',
        pl: 'Siedemset',
        jp: { text: '七百', pronunciation: 'ななひゃく' },
    },
    {
        type: 'numeral',
        en: 'Eight hundred',
        pl: 'Osiemset',
        jp: { text: '八百', pronunciation: 'はっぴゃく' },
    },
    {
        type: 'numeral',
        en: 'Nine hundred',
        pl: 'Dziewięćset',
        jp: { text: '九百', pronunciation: 'きゅうひゃく' },
    },
    {
        type: 'numeral',
        en: 'One thousand',
        pl: 'Tysiąc',
        jp: { text: '千', pronunciation: 'せん' },
    },
    {
        type: 'numeral',
        en: 'Two thousand',
        pl: 'Dwa tysiące',
        jp: { text: '二千', pronunciation: 'にせん' },
    },
    {
        type: 'numeral',
        en: 'Three thousand',
        pl: 'Trzy tysiące',
        jp: { text: '三千', pronunciation: 'さんぜん' },
    },
    {
        type: 'numeral',
        en: 'Four thousand',
        pl: 'Cztery tysiące',
        jp: { text: '四千', pronunciation: 'よんせん' },
    },
    {
        type: 'numeral',
        en: 'Five thousand',
        pl: 'Pięć tysięcy',
        jp: { text: '五千', pronunciation: 'ごせん' },
    },
    {
        type: 'numeral',
        en: 'Six thousand',
        pl: 'Sześć tysięcy',
        jp: { text: '六千', pronunciation: 'ろくせん' },
    },
    {
        type: 'numeral',
        en: 'Seven thousand',
        pl: 'Siedem tysięcy',
        jp: { text: '七千', pronunciation: 'ななせん' },
    },
    {
        type: 'numeral',
        en: 'Eight thousand',
        pl: 'Osiem tysięcy',
        jp: { text: '八千', pronunciation: 'はっせん' },
    },
    {
        type: 'numeral',
        en: 'Nine thousand',
        pl: 'Dziewięć tysięcy',
        jp: { text: '九千', pronunciation: 'きゅうせん' },
    },
    {
        type: 'numeral',
        en: 'Ten thousand',
        pl: 'Dziesięć tysięcy',
        jp: { text: '万', pronunciation: 'いちまん' },
    },
    {
        type: 'numeral',
        en: 'Twenty thousand',
        pl: 'Dwadzieścia tysięcy',
        jp: { text: '二万', pronunciation: 'にまん' },
    },
    {
        type: 'numeral',
        en: 'Thirty thousand',
        pl: 'Trzydzieści tysięcy',
        jp: { text: '三万', pronunciation: 'さんまん' },
    },
    {
        type: 'numeral',
        en: 'Forty thousand',
        pl: 'Czterdzieści tysięcy',
        jp: { text: '四万', pronunciation: 'よんまん' },
    },
    {
        type: 'numeral',
        en: 'Fifty thousand',
        pl: 'Pięćdziesiąt tysięcy',
        jp: { text: '五万', pronunciation: 'ごまん' },
    },
    {
        type: 'numeral',
        en: 'Sixty thousand',
        pl: 'Sześćdziesiąt tysięcy',
        jp: { text: '六万', pronunciation: 'ろくまん' },
    },
    {
        type: 'numeral',
        en: 'Seventy thousand',
        pl: 'Siedemdziesiąt tysięcy',
        jp: { text: '七万', pronunciation: 'ななまん' },
    },
    {
        type: 'numeral',
        en: 'Eighty thousand',
        pl: 'Osiemdziesiąt tysięcy',
        jp: { text: '八万', pronunciation: 'はちまん' },
    },
    {
        type: 'numeral',
        en: 'Ninety thousand',
        pl: 'Dziewięćdziesiąt tysięcy',
        jp: { text: '九万', pronunciation: 'きゅうまん' },
    },
];
