import type { JapaneseWord } from '../types';

const numbers: JapaneseWord[] = [
    {
        en: "One",
        pl: "Jeden",
        jp: "一",
        jp_pronunciation: "いち",
    },
    {
        en: "Two",
        pl: "Dwa",
        jp: "二",
        jp_pronunciation: "に",
    },
    {
        en: "Three",
        pl: "Trzy",
        jp: "三",
        jp_pronunciation: "さん",
    },
    {
        en: "Four",
        pl: "Cztery",
        jp: "四",
        jp_pronunciation: "よん",
    },
    {
        en: "Five",
        pl: "Pięć",
        jp: "五",
        jp_pronunciation: "ご",
    },
    {
        en: "Six",
        pl: "Sześć",
        jp: "六",
        jp_pronunciation: "ろく",
    },
    {
        en: "Seven",
        pl: "Siedem",
        jp: "七",
        jp_pronunciation: "なな",
    },
    {
        en: "Eight",
        pl: "Osiem",
        jp: "八",
        jp_pronunciation: "はち",
    },
    {
        en: "Nine",
        pl: "Dziewięć",
        jp: "九",
        jp_pronunciation: "きゅう",
    },
    {
        en: "Ten",
        pl: "Dziesięć",
        jp: "十",
        jp_pronunciation: "じゅう",
    },
    {
        en: "Eleven",
        pl: "Jedenaście",
        jp: "十一",
        jp_pronunciation: "じゅういち",
    },
    {
        en: "Twelve",
        pl: "Dwanaście",
        jp: "十二",
        jp_pronunciation: "じゅうに",
    },
    {
        en: "Thirteen",
        pl: "Trzynaście",
        jp: "十三",
        jp_pronunciation: "じゅうさん",
    },
    {
        en: "Fourteen",
        pl: "Czternaście",
        jp: "十四",
        jp_pronunciation: "じゅうよん",
    },
    {
        en: "Fifteen",
        pl: "Piętnaście",
        jp: "十五",
        jp_pronunciation: "じゅうご",
    },
    {
        en: "Sixteen",
        pl: "Szesnaście",
        jp: "十六",
        jp_pronunciation: "じゅうろく",
    },
    {
        en: "Seventeen",
        pl: "Siedemnaście",
        jp: "十七",
        jp_pronunciation: "じゅうなな",
    },
    {
        en: "Eighteen",
        pl: "Osiemnaście",
        jp: "十八",
        jp_pronunciation: "じゅうはち",
    },
    {
        en: "Nineteen",
        pl: "Dziewiętnaście",
        jp: "十九",
        jp_pronunciation: "じゅうきゅう",
    },
    {
        en: "Twenty",
        pl: "Dwadzieścia",
        jp: "二十",
        jp_pronunciation: "にじゅう",
    },
    {
        en: "Thirty",
        pl: "Trzydzieści",
        jp: "三十",
        jp_pronunciation: "さんじゅう",
    },
    {
        en: "One hundred",
        pl: "Sto",
        jp: "百",
        jp_pronunciation: "ひゃく",
    },
    {
        en: "Two hundred",
        pl: "Dwieście",
        jp: "二百",
        jp_pronunciation: "にひゃく",
    },
    {
        en: "Three hundred",
        pl: "Trzysta",
        jp: "三百",
        jp_pronunciation: "さんびゃく",
    },
    {
        en: "Four hundred",
        pl: "Czterysta",
        jp: "四百",
        jp_pronunciation: "よんひゃく",
    },
    {
        en: "Five hundred",
        pl: "Pięćset",
        jp: "五百",
        jp_pronunciation: "ごひゃく",
    },
    {
        en: "Six hundred",
        pl: "Sześćset",
        jp: "六百",
        jp_pronunciation: "ろっぴゃく",
    },
    {
        en: "Seven hundred",
        pl: "Siedemset",
        jp: "七百",
        jp_pronunciation: "ななひゃく",
    },
    {
        en: "Eight hundred",
        pl: "Osiemset",
        jp: "八百",
        jp_pronunciation: "はっぴゃく",
    },
    {
        en: "Nine hundred",
        pl: "Dziewięćset",
        jp: "九百",
        jp_pronunciation: "きゅうひゃく",
    },
    {
        en: "One thousand",
        pl: "Tysiąc",
        jp: "千",
        jp_pronunciation: "せん",
    },
    {
        en: "Two thousand",
        pl: "Dwa tysiące",
        jp: "二千",
        jp_pronunciation: "にせん",
    },
    {
        en: "Three thousand",
        pl: "Trzy tysiące",
        jp: "三千",
        jp_pronunciation: "さんぜん",
    },
    {
        en: "Four thousand",
        pl: "Cztery tysiące",
        jp: "四千",
        jp_pronunciation: "よんせん",
    },
    {
        en: "Five thousand",
        pl: "Pięć tysięcy",
        jp: "五千",
        jp_pronunciation: "ごせん",
    },
    {
        en: "Six thousand",
        pl: "Sześć tysięcy",
        jp: "六千",
        jp_pronunciation: "ろくせん",
    },
    {
        en: "Seven thousand",
        pl: "Siedem tysięcy",
        jp: "七千",
        jp_pronunciation: "ななせん",
    },
    {
        en: "Eight thousand",
        pl: "Osiem tysięcy",
        jp: "八千",
        jp_pronunciation: "はっせん",
    },
    {
        en: "Nine thousand",
        pl: "Dziewięć tysięcy",
        jp: "九千",
        jp_pronunciation: "きゅうせん",
    },
    {
        en: "Ten thousand",
        pl: "Dziesięć tysięcy",
        jp: "万",
        jp_pronunciation: "いちまん",
    },
    {
        en: "Twenty thousand",
        pl: "Dwadzieścia tysięcy",
        jp: "二万",
        jp_pronunciation: "にまん",
    },
    {
        en: "Thirty thousand",
        pl: "Trzydzieści tysięcy",
        jp: "三万",
        jp_pronunciation: "さんまん",
    },
    {
        en: "Fourty thousand",
        pl: "Czterdzieści tysięcy",
        jp: "四万",
        jp_pronunciation: "よんまん",
    },
    {
        en: "Fifty thousand",
        pl: "Pięćdziesiąt tysięcy",
        jp: "五万",
        jp_pronunciation: "ごまん",
    },
    {
        en: "Sixty thousand",
        pl: "Sześćdziesiąt tysięcy",
        jp: "六万",
        jp_pronunciation: "ろくまん",
    },
    {
        en: "Seventy thousand",
        pl: "Siedemdziesiąt tysięcy",
        jp: "七万",
        jp_pronunciation: "ななまん",
    },
    {
        en: "Eighty thousand",
        pl: "Osiemdziesiąt tysięcy",
        jp: "八万",
        jp_pronunciation: "はちまん",
    },
    {
        en: "Ninety thousand",
        pl: "Dziewięćdziesiąt tysięcy",
        jp: "九万",
        jp_pronunciation: "きゅうまん",
    },
];

export { numbers };
