import type { JapaneseWord } from '../types';

export const time: JapaneseWord[] = [
    {
        type: 'noun',
        en: "1 o'clock",
        pl: 'Pierwsza godzina',
        jp: '一時',
        jp_pronunciation: 'いちじ',
    },
    {
        type: 'noun',
        en: "2 o'clock",
        pl: 'Druga godzina',
        jp: '二時',
        jp_pronunciation: 'にじ',
    },
    {
        type: 'noun',
        en: "3 o'clock",
        pl: 'Trzecia godzina',
        jp: '三時',
        jp_pronunciation: 'さんじ',
    },
    {
        type: 'noun',
        en: "4 o'clock",
        pl: 'Czwarta godzina',
        jp: '四時',
        jp_pronunciation: 'よじ',
    },
    {
        type: 'noun',
        en: "5 o'clock",
        pl: 'Piąta godzina',
        jp: '五時',
        jp_pronunciation: 'ごじ',
    },
    {
        type: 'noun',
        en: "6 o'clock",
        pl: 'Szósta godzina',
        jp: '六時',
        jp_pronunciation: 'ろくじ',
    },
    {
        type: 'noun',
        en: "7 o'clock",
        pl: 'Siódma godzina',
        jp: '七時',
        jp_pronunciation: 'しちじ',
    },
    {
        type: 'noun',
        en: "8 o'clock",
        pl: 'Ósma godzina',
        jp: '八時',
        jp_pronunciation: 'はちじ',
    },
    {
        type: 'noun',
        en: "9 o'clock",
        pl: 'Dziewiąta godzina',
        jp: '九時',
        jp_pronunciation: 'くじ',
    },
    {
        type: 'noun',
        en: "10 o'clock",
        pl: 'Dziesiąta godzina',
        jp: '十時',
        jp_pronunciation: 'じゅうじ',
    },
    {
        type: 'noun',
        en: "11 o'clock",
        pl: 'Jedenasta godzina',
        jp: '十一時',
        jp_pronunciation: 'じゅういちじ',
    },
    {
        type: 'noun',
        en: "12 o'clock",
        pl: 'Dwunasta godzina',
        jp: '十二時',
        jp_pronunciation: 'じゅうにじ',
    },
    {
        type: 'noun',
        en: 'One minute',
        pl: 'Jedna minuta',
        jp: '一分',
        jp_pronunciation: 'いっぷん',
    },
    {
        type: 'noun',
        en: 'Two minutes',
        pl: 'Dwie minuty',
        jp: '二分',
        jp_pronunciation: 'にふん',
    },
    {
        type: 'noun',
        en: 'Three minutes',
        pl: 'Trzy minuty',
        jp: '三分',
        jp_pronunciation: 'さんぷん',
    },
    {
        type: 'noun',
        en: 'Four minutes',
        pl: 'Cztery minuty',
        jp: '四分',
        jp_pronunciation: 'よんぷん',
    },
    {
        type: 'noun',
        en: 'Five minutes',
        pl: 'Pięć minut',
        jp: '五分',
        jp_pronunciation: 'ごふん',
    },
    {
        type: 'noun',
        en: 'Six minutes',
        pl: 'Sześć minut',
        jp: '六分',
        jp_pronunciation: 'ろっぷん',
    },
    {
        type: 'noun',
        en: 'Seven minutes',
        pl: 'Siedem minut',
        jp: '七分',
        jp_pronunciation: 'ななふん',
    },
    {
        type: 'noun',
        en: 'Eight minutes',
        pl: 'Osiem minut',
        jp: '八分',
        jp_pronunciation: 'はっぷん',
    },
    {
        type: 'noun',
        en: 'Nine minutes',
        pl: 'Dziewięć minut',
        jp: '九分',
        jp_pronunciation: 'きゅうふん',
    },
    {
        type: 'noun',
        en: 'Ten minutes',
        pl: 'Dziesięć minut',
        jp: '十分',
        jp_pronunciation: 'じゅっぷん',
    },
    {
        type: 'noun',
        en: 'Eleven minutes',
        pl: 'Jedenaście minut',
        jp: '十一分',
        jp_pronunciation: 'じゅういっぷん',
    },
    {
        type: 'noun',
        en: 'Twelve minutes',
        pl: 'Dwanaście minut',
        jp: '十二分',
        jp_pronunciation: 'じゅうにふん',
    },
    {
        type: 'noun',
        en: 'Thirteen minutes',
        pl: 'Trzynaście minut',
        jp: '十三分',
        jp_pronunciation: 'じゅうさんぷん',
    },
    {
        type: 'noun',
        en: 'Half past',
        pl: '30 minut po',
        jp: '半',
        jp_pronunciation: 'はん',
    },
    {
        type: 'noun',
        en: 'Minute',
        pl: 'Minuta',
        jp: '分',
        jp_pronunciation: 'ふん',
    },
    {
        type: 'suffix',
        en: 'Hour',
        pl: 'Godzina',
        jp: '時',
        jp_pronunciation: 'じ',
    },
];
