import type { JapaneseWord } from '../types.ts';

export const week: JapaneseWord[] = [
    {
        type: 'noun',
        en: 'Monday',
        pl: 'Poniedziałek',
        jp: '月曜日',
        jp_pronunciation: 'げつようび',
    },
    {
        type: 'noun',
        en: 'Tuesday',
        pl: 'Wtorek',
        jp: '火曜日',
        jp_pronunciation: 'かようび',
    },
    {
        type: 'noun',
        en: 'Wednesday',
        pl: 'Środa',
        jp: '水曜日',
        jp_pronunciation: 'すいようび',
    },
    {
        type: 'noun',
        en: 'Thursday',
        pl: 'Czwartek',
        jp: '木曜日',
        jp_pronunciation: 'もくようび',
    },
    {
        type: 'noun',
        en: 'Friday',
        pl: 'Piątek',
        jp: '金曜日',
        jp_pronunciation: 'きんようび',
    },
    {
        type: 'noun',
        en: 'Saturday',
        pl: 'Sobota',
        jp: '土曜日',
        jp_pronunciation: 'どようび',
    },
    {
        type: 'noun',
        en: 'Sunday',
        pl: 'Niedziela',
        jp: '日曜日',
        jp_pronunciation: 'にちようび',
    },
    {
        type: 'noun',
        en: 'Week',
        pl: 'Tydzień',
        jp: '週',
        jp_pronunciation: 'しゅう',
    },
    {
        type: 'noun',
        en: 'Weekend',
        pl: 'Weekend',
        jp: '週末',
        jp_pronunciation: 'しゅうまつ',
    },
    {
        type: 'noun',
        en: 'This week',
        pl: 'Ten tydzień',
        jp: '今週',
        jp_pronunciation: 'こんしゅう',
    },
    {
        type: 'noun',
        en: 'Last week',
        pl: 'Poprzedni tydzień',
        jp: '先週',
        jp_pronunciation: 'せんしゅう',
    },
    {
        type: 'noun',
        en: 'Next week',
        pl: 'Przyszły tydzień',
        jp: '来週',
        jp_pronunciation: 'らいしゅう',
    },
    {
        type: 'noun',
        en: 'Today',
        pl: 'Dzisiaj',
        jp: '今日',
        jp_pronunciation: 'きょう',
    },
    {
        type: 'noun',
        en: 'Tomorrow',
        pl: 'Jutro',
        jp: '明日',
        jp_pronunciation: 'あした',
    },
    {
        type: 'noun',
        en: 'Yesterday',
        pl: 'Wczoraj',
        jp: '昨日',
        jp_pronunciation: 'きのう',
    },
    {
        type: 'noun',
        en: 'Day',
        pl: 'Dzień',
        jp: '日',
        jp_pronunciation: 'ひ',
    },
    {
        type: 'noun',
        en: 'This year',
        pl: 'W tym roku',
        jp: '今年',
        jp_pronunciation: 'ことし',
    },
];
